In [1]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, text, DateTime
from sqlalchemy.orm import Session
import psycopg
import time

In [2]:
from multiprocessing import Pool

In [3]:
import dask.dataframe as dd
import dask.array as da
import dask.bag as db

In [4]:
import warnings
warnings.filterwarnings("ignore", 'This pattern has match groups')

In [5]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [6]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [7]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [8]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [9]:
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

plantslist = list(set(seem['plantid'].to_list()))
plantslist.sort()

/tmp/ipykernel_908441/3027777900.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [10]:
"06-08-2948214" in plantslist

False

In [11]:
#plantslist

In [12]:
#plantslist.remove('661-94')
#plantslist.remove('661-10')

#plantslist.remove('07-05-8290552')
#plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [13]:
#refpl = "03-01-01241117210.csv"

In [14]:
#df = pd.read_csv("./combined/" + refpl)

In [15]:
#df

In [16]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [17]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [18]:
testdf = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv")

In [19]:
nd = "01.01.2023 00:00"

In [20]:
datetime.strptime(nd, "%d.%m.%Y %H:%M")

datetime.datetime(2023, 1, 1, 0, 0)

In [21]:
arr = [nd, "2022-12-31 23:15:00", "2021-12-24 08:00:00", '29.04.2023 12:00', '01.01.2023 00:00']

In [22]:
list(map(lambda x: fix_date(x), arr))

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2022, 12, 31, 23, 15),
 datetime.datetime(2021, 12, 24, 8, 0),
 datetime.datetime(2023, 4, 29, 12, 0),
 datetime.datetime(2023, 1, 1, 0, 0)]

In [23]:
fix_date(nd)

datetime.datetime(2023, 1, 1, 0, 0)

In [24]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [25]:
#engine = create_engine('sqlite://', echo=False)

In [26]:
#2023-12-31 19:00:00.000000

In [27]:
#melt.dtypes

In [28]:
#testdf.iloc[70128]

In [29]:
#testdf['produced_at'] = testdf['produced_at'].map(return_date)

In [30]:
#testdf['produced_at'] = pd.to_datetime(testdf['produced_at'])

In [31]:
#df.dtypes

In [32]:
#df.iloc[70128]

In [33]:
#connection = engine2.connect()
#with engine2.begin() as connection:
plant = "06-05-100-0853075"

df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])
df.drop_duplicates(subset='produced_at', inplace=True)
#melt = df.melt(id_vars='produced_at')
#melt.drop('index', axis=1, inplace=True)
#res = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

In [34]:
#res

In [35]:
#melt

In [36]:
#melt.dtypes

In [37]:
with Session(engine2) as sess:
    sess.execute(text("TRUNCATE TABLE power9"))
    sess.commit()

In [38]:
from datetime import datetime

In [39]:
lpdid = "SN80011277"

In [40]:
lpd = pd.read_csv("./combined/" + lpdid + ".csv", delimiter=",", engine='c')
lpd2 = lpd[lpd.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]

/tmp/ipykernel_908441/1832200049.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  lpd2 = lpd[lpd.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]

In [41]:
#lpd.loc[~(lpd.produced_at == '0')]
#lpd = lpd.loc[~(lpd.produced_at == '03.05.2')]

In [42]:
#lpd2

In [43]:
#lpd2['produced_at'] = lpd2['produced_at'].map(fix_date)
lpd2['produced_at'] = pd.to_datetime(lpd2['produced_at'], format='mixed')

In [44]:
len(lpd) - len(lpd2)

0

In [45]:
starttime = datetime.now()

In [46]:
def df_to_db(plant):
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        engine3 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')
        try: #, format='%d.%m.%Y %H:%M'
            #df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df2['produced_at'] = df2['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df2['produced_at'] = df2['produced_at'].map(return_date)
            df2 = df
        except ValueError:
            print(plant + "\nfaulty")
            try:
                df2 = df[df.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
                df2['produced_at'] = df2['produced_at'].map(fix_date)
                #df2['produced_at'] = df2['produced_at'].map(fix_date)
                df2['produced_at'] = pd.to_datetime(df2['produced_at'])
                df2.drop_duplicates(subset='produced_at', inplace=True)
            except ValueError:
                print(plant + "\nfaulty beyond repair")
                return
            #df2['produced_at'] = df2['produced_at'].map(fix_date)
            #df2['produced_at'] = pd.to_datetime(df2['produced_at'])
            #print(df2)
            #pass
        melt = df2.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power9', con=engine3, if_exists='append', index=False, dtype={'produced_at': DateTime})
        engine3.dispose()
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        #print(df.shape)
    except FileNotFoundError:
        pass

In [47]:
if __name__ == '__main__':
    with Pool(os.cpu_count()) as pool: 
        pool.map(df_to_db, plantslist)

NW100-0081105
faulty

/tmp/ipykernel_908441/2279507993.py:17: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = df[df.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_908441/2279507993.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_908441/2279507993.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_908441/2279507993.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)

SD661-94
faulty

/tmp/ipykernel_908441/2279507993.py:17: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = df[df.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_908441/2279507993.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_908441/2279507993.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_908441/2279507993.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)

In [48]:
'''
counter = 0
for plant in plantslist:
    #if plant == '06-05-300-9046030':
    #    continue
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        try: #, format='%d.%m.%Y %H:%M'
            #df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df2['produced_at'] = df2['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df2['produced_at'] = df2['produced_at'].map(return_date)
            df2 = df
        except ValueError:
            print(plant + "\nfaulty")
            try:
                df2 = df[df.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
                df2['produced_at'] = df2['produced_at'].map(fix_date)
                #df2['produced_at'] = df2['produced_at'].map(fix_date)
                df2['produced_at'] = pd.to_datetime(df2['produced_at'])
                df2.drop_duplicates(subset='produced_at', inplace=True)
            except ValueError:
                print(plant + "\nfaulty beyond repair")
            #df2['produced_at'] = df2['produced_at'].map(fix_date)
            #df2['produced_at'] = pd.to_datetime(df2['produced_at'])
            #print(df2)
                continue
            #pass
        melt = df2.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power9', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)
'''

'\ncounter = 0\nfor plant in plantslist:\n    #if plant == \'06-05-300-9046030\':\n    #    continue\n    #print(plant)\n    try:\n        #print(plant)\n        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine=\'c\')\n        try: #, format=\'%d.%m.%Y %H:%M\'\n            #df2 = df[df.produced_at.str.contains(\'([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)\', regex=True)]\n            df[\'produced_at\'] = df[\'produced_at\'].map(fix_date)\n            #df2[\'produced_at\'] = df2[\'produced_at\'].map(fix_date)\n            df[\'produced_at\'] = pd.to_datetime(df[\'produced_at\'])\n            df.drop_duplicates(subset=\'produced_at\', inplace=True)\n            #df2[\'produced_at\'] = df2[\'produced_at\'].map(return_date)\n            df2 = df\n        except ValueError:\n            print(plant + "\nfaulty")\n            try:\n                df2 = df[df.produced_at.str.contains(\'(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)\', regex=True)]\n                df2[\'produced_at\'] = df2[\'produced_at\'].map(fix_date)\n                #df2[\'produced_at\'] = df2[\'produced_at\'].map(fix_date)\n                df2[\'produced_at\'] = pd.to_datetime(df2[\'produced_at\'])\n                df2.drop_duplicates(subset=\'produced_at\', inplace=True)\n            except ValueError:\n                print(plant + "\nfaulty beyond repair")\n            #df2[\'produced_at\'] = df2[\'produced_at\'].map(fix_date)\n            #df2[\'produced_at\'] = pd.to_datetime(df2[\'produced_at\'])\n            #print(df2)\n                continue\n            #pass\n        melt = df2.melt(id_vars=\'produced_at\')\n        melt.to_csv("./melt/" + plant + ".csv", index=False)\n        #melt.drop(\'index\', axis=1, inplace=True)\n        result = melt.to_sql(\'power9\', con=engine2, if_exists=\'append\', index=False, dtype={\'produced_at\': DateTime})\n        #time.sleep(1)\n        #if result == -1:\n            #print(plant + "\nfaulty2")\n        counter += 1\n        #print(df.shape)\n    except FileNotFoundError:\n        pass\nprint(counter)\n'

In [49]:
endtime = datetime.now()
duration = endtime - starttime

In [50]:
duration

datetime.timedelta(seconds=189, microseconds=821370)

In [115]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [51]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26301 rows x 3 columns]

In [52]:
df = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])

In [53]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [54]:
#columns_table = (inspect(engine).get_columns('power'))

In [55]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [56]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [57]:
starttime2 = datetime.now()

In [58]:
CDF = pd.read_sql_table('power9', engine2)

In [59]:
endtime2 = datetime.now()
duration2 = endtime2 - starttime2

In [60]:
duration2

datetime.timedelta(seconds=264, microseconds=479533)

In [61]:
CDF.sort_values(by=["produced_at", "variable"], ascending=True)

                 produced_at         variable  value
32430121 2015-01-01 00:00:00          BNA0199    0.0
11568001 2015-01-01 00:00:00          BNA0215    0.0
26501848 2015-01-01 00:00:00         BNA0221c    0.0
4181224  2015-01-01 00:00:00          BNA0302    0.0
3490413  2015-01-01 00:00:00          BNA0303    0.0
...                      ...              ...    ...
24020517 2025-12-31 23:45:00  SEE995943794058   24.0
15219197 2025-12-31 23:45:00  SEE996720450723    5.0
24851674 2025-12-31 23:45:00  SEE998199911088    0.0
30394314 2025-12-31 23:45:00  SEE998383491525    0.0
42758609 2025-12-31 23:45:00       Unnamed: 3    0.0

[43529978 rows x 3 columns]

In [62]:
#CDF.drop_duplicates(subset=['produced_at', 'variable'])

In [63]:
CDF.shape

(43529978, 3)

In [64]:
CDF.duplicated(subset=['produced_at', 'variable'])

0           False
1           False
2           False
3           False
4           False
            ...
43529973    False
43529974    False
43529975    False
43529976    False
43529977    False
Length: 43529978, dtype: bool

In [65]:
CDF[CDF.duplicated(subset=['produced_at', 'variable'], keep=False)]

Empty DataFrame
Columns: [produced_at, variable, value]
Index: []

In [66]:
CDF.drop_duplicates(subset=['produced_at', 'variable'], inplace=True)

In [67]:
CDF.to_csv("CDF-v2.csv", index=False)

In [68]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [69]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [70]:
CDF9.sort_values(by="produced_at")

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE997719859992    0.0
16629672 2015-01-01 00:00:00  SEE985577062814    0.0
757232   2015-01-01 00:00:00  SEE987197130805    0.0
19545    2015-01-01 00:00:00  SEE913896693631    0.0
31597150 2015-01-01 00:00:00  SEE991817093418    0.0
...                      ...              ...    ...
42758609 2025-12-31 23:45:00       Unnamed: 3    0.0
22385596 2025-12-31 23:45:00          BNA0187    0.0
33841949 2025-12-31 23:45:00  SEE919134316447    0.0
22842754 2025-12-31 23:45:00  SEE921905907730  144.0
43529977 2025-12-31 23:45:00  SEE968136280119    0.0

[43529978 rows x 3 columns]

In [71]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [72]:
CDF9.iloc[70128]

produced_at    2016-03-17 15:00:00
variable           SEE913896693631
value                         52.0
Name: 70128, dtype: object

In [73]:
CDF9.loc[CDF.variable=='SEE998199911088'].sort_values('produced_at')

                 produced_at         variable  value
20778861 2015-01-01 00:00:00  SEE998199911088    0.0
20778862 2015-01-01 00:15:00  SEE998199911088    0.0
20778863 2015-01-01 00:30:00  SEE998199911088    0.0
20778864 2015-01-01 00:45:00  SEE998199911088    0.0
20778865 2015-01-01 01:00:00  SEE998199911088    0.0
...                      ...              ...    ...
24851670 2025-12-31 22:45:00  SEE998199911088    0.0
24851671 2025-12-31 23:00:00  SEE998199911088    0.0
24851672 2025-12-31 23:15:00  SEE998199911088    0.0
24851673 2025-12-31 23:30:00  SEE998199911088    0.0
24851674 2025-12-31 23:45:00  SEE998199911088    0.0

[385684 rows x 3 columns]

In [74]:
CDF9.shape

(43529978, 3)

In [75]:
#CDF9.iloc[15219136]

In [76]:
#CDF9.iloc[929304]

In [77]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [78]:
CDF9[CDF9.isnull().any(axis=1)].shape

(70072, 3)

In [79]:
CDF9b = CDF9.fillna(0)

In [80]:
#CDF10 = CDF9.dropna()

In [81]:
CDF9b["value"] = CDF9b["value"].astype(int)

In [82]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [83]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [84]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE997719859992    0.0
1        2015-01-01 01:00:00  SEE997719859992    0.0
2        2015-01-01 02:00:00  SEE997719859992    0.0
3        2015-01-01 03:00:00  SEE997719859992    0.0
4        2015-01-01 04:00:00  SEE997719859992    0.0
...                      ...              ...    ...
43529973 2025-12-31 22:45:00  SEE968136280119    0.0
43529974 2025-12-31 23:00:00  SEE968136280119    0.0
43529975 2025-12-31 23:15:00  SEE968136280119    0.0
43529976 2025-12-31 23:30:00  SEE968136280119    0.0
43529977 2025-12-31 23:45:00  SEE968136280119    0.0

[43529978 rows x 3 columns]

In [85]:
#CDF_new = CDF.reset_index(drop=False)

In [86]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [87]:
#CDF_new[CDF_new.produced_at.isnull()]

In [88]:
#CDF_new

In [89]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [90]:
#CDF

In [91]:
#CDF99.set_index('produced_at')

In [92]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [93]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [94]:
#subC1

In [95]:
CDF10 = CDF9b.copy()

In [96]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [97]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE997719859992      0
1        2015-01-01 01:00:00  SEE997719859992      0
2        2015-01-01 02:00:00  SEE997719859992      0
3        2015-01-01 03:00:00  SEE997719859992      0
4        2015-01-01 04:00:00  SEE997719859992      0
...                      ...              ...    ...
43529973 2025-12-31 22:45:00  SEE968136280119      0
43529974 2025-12-31 23:00:00  SEE968136280119      0
43529975 2025-12-31 23:15:00  SEE968136280119      0
43529976 2025-12-31 23:30:00  SEE968136280119      0
43529977 2025-12-31 23:45:00  SEE968136280119      0

[43529978 rows x 3 columns]

In [98]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

/tmp/ipykernel_908441/675855814.py:1: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

In [99]:
#CDF2

In [100]:
CDF3 = CDF2.drop(columns="variable")

In [101]:
#CDF3

In [102]:
CDF3

                        value
variable   produced_at
BNA0187    2017-01-31       0
           2017-02-28       0
           2017-03-31       0
           2017-04-30       0
           2017-05-31       0
...                       ...
Unnamed: 3 2025-08-31       0
           2025-09-30       0
           2025-10-31       0
           2025-11-30       0
           2025-12-31       0

[24180 rows x 1 columns]

In [103]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [104]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [105]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [106]:
#gm2

In [107]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [108]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [109]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [110]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [111]:
gm8.loc[gm8.blockid == "SEE998199911088"]

       year  month          blockid   power
204    2015      1  SEE998199911088  347848
413    2015      2  SEE998199911088  495932
622    2015      3  SEE998199911088  427360
831    2015      4  SEE998199911088  339184
1040   2015      5  SEE998199911088  583308
...     ...    ...              ...     ...
23805  2025      8  SEE998199911088  194648
23898  2025      9  SEE998199911088  260424
23991  2025     10  SEE998199911088  255496
24084  2025     11  SEE998199911088  394972
24177  2025     12  SEE998199911088   48584

[132 rows x 4 columns]

In [112]:
gm7

       year  month          blockid  power
324    2015      1          BNA0199      0
456    2015      1          BNA0215      0
576    2015      1         BNA0221c      0
708    2015      1          BNA0302      0
744    2015      1          BNA0303      0
...     ...    ...              ...    ...
23291  2025     12  SEE995943794058  69120
23423  2025     12  SEE996720450723  65740
23675  2025     12  SEE998199911088  48584
23927  2025     12  SEE998383491525      0
24179  2025     12       Unnamed: 3      0

[24180 rows x 4 columns]

In [113]:
gm7

       year  month          blockid  power
324    2015      1          BNA0199      0
456    2015      1          BNA0215      0
576    2015      1         BNA0221c      0
708    2015      1          BNA0302      0
744    2015      1          BNA0303      0
...     ...    ...              ...    ...
23291  2025     12  SEE995943794058  69120
23423  2025     12  SEE996720450723  65740
23675  2025     12  SEE998199911088  48584
23927  2025     12  SEE998383491525      0
24179  2025     12       Unnamed: 3      0

[24180 rows x 4 columns]

In [114]:
bpm = seem.copy()

In [115]:
bpm

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [116]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [117]:
pm2

       year  month          blockid  power                    plantid
0      2015      1          BNA0199      0              NW300-9002708
1      2015      1          BNA0215      0              NW100-0365906
2      2015      1         BNA0221c      0              NW100-0167182
3      2015      1          BNA0302      0              NW100-0081105
4      2015      1          BNA0303      0              NW100-0081105
...     ...    ...              ...    ...                        ...
23455  2025     12  SEE992973663477      0  BWpf-450-1195689-00000000
23456  2025     12  SEE995943794058  69120                 BB23020490
23457  2025     12  SEE996720450723  65740                   BYS00044
23458  2025     12  SEE998199911088  48584                 SN80011277
23459  2025     12  SEE998383491525      0  BWpf-450-1195689-00000000

[23460 rows x 5 columns]

In [118]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [119]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [120]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [121]:
ym1.loc[ym1.plantid == "SN80011277"]

       year  month     plantid  plantpower  yearpower
144    2015      1  SN80011277      832996   10794404
346    2015      2  SN80011277     1021732   10794404
548    2015      3  SN80011277      943700   10794404
750    2015      4  SN80011277      889312   10794404
952    2015      5  SN80011277      583308   10794404
...     ...    ...         ...         ...        ...
23073  2025      8  SN80011277      471512    7583580
23162  2025      9  SN80011277      645588    7583580
23251  2025     10  SN80011277      677312    7583580
23340  2025     11  SN80011277      780492    7583580
23429  2025     12  SN80011277      459556    7583580

[132 rows x 5 columns]

In [122]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [123]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [124]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)
gm8.to_csv("monthly.csv", header=False)

In [125]:
#invCDF = CDF.pivot(columns='variable')

In [126]:
gm8

       year  month          blockid  power
0      2015      1          BNA0199      0
1      2015      1          BNA0215      0
2      2015      1         BNA0221c      0
3      2015      1          BNA0302      0
4      2015      1          BNA0303      0
...     ...    ...              ...    ...
24175  2025     12  SEE995943794058  69120
24176  2025     12  SEE996720450723  65740
24177  2025     12  SEE998199911088  48584
24178  2025     12  SEE998383491525      0
24179  2025     12       Unnamed: 3      0

[24180 rows x 4 columns]

In [127]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [128]:
pm2

       year  month          blockid  power                    plantid
0      2015      1          BNA0199      0              NW300-9002708
1      2015      1          BNA0215      0              NW100-0365906
2      2015      1         BNA0221c      0              NW100-0167182
3      2015      1          BNA0302      0              NW100-0081105
4      2015      1          BNA0303      0              NW100-0081105
...     ...    ...              ...    ...                        ...
23455  2025     12  SEE992973663477      0  BWpf-450-1195689-00000000
23456  2025     12  SEE995943794058  69120                 BB23020490
23457  2025     12  SEE996720450723  65740                   BYS00044
23458  2025     12  SEE998199911088  48584                 SN80011277
23459  2025     12  SEE998383491525      0  BWpf-450-1195689-00000000

[23460 rows x 5 columns]

In [129]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [130]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [131]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [132]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [133]:
ym4.loc[ym4.plantid == "NW100-0248923"]

     year        plantid  yearpower
27   2015  NW100-0248923   18262795
98   2016  NW100-0248923   25468598
170  2017  NW100-0248923   27112376
239  2018  NW100-0248923   29463725
306  2019  NW100-0248923   20841356
369  2020  NW100-0248923   17221819
431  2021  NW100-0248923   20015332
493  2022  NW100-0248923   22326897
553  2023  NW100-0248923   15021992
613  2024  NW100-0248923   12629202

In [134]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [135]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [136]:
#invCDF = CDF.pivot(columns='variable')

In [137]:
gm8

       year  month          blockid  power
0      2015      1          BNA0199      0
1      2015      1          BNA0215      0
2      2015      1         BNA0221c      0
3      2015      1          BNA0302      0
4      2015      1          BNA0303      0
...     ...    ...              ...    ...
24175  2025     12  SEE995943794058  69120
24176  2025     12  SEE996720450723  65740
24177  2025     12  SEE998199911088  48584
24178  2025     12  SEE998383491525      0
24179  2025     12       Unnamed: 3      0

[24180 rows x 4 columns]

In [138]:
bpm

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [139]:
endtime3 = datetime.now()
duration3 = endtime3 - starttime2

In [140]:
duration3

datetime.timedelta(seconds=372, microseconds=626541)