In [1]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, text, DateTime
from sqlalchemy.orm import Session
import psycopg
import time

In [2]:
import warnings
warnings.filterwarnings("ignore", 'This pattern has match groups')

In [3]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [4]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [5]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [6]:
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

plantslist = list(set(seem['plantid'].to_list()))
plantslist.sort()

/tmp/ipykernel_8345/3027777900.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [7]:
"06-08-2948214" in plantslist

False

In [8]:
#plantslist

In [9]:
#plantslist.remove('661-94')
#plantslist.remove('661-10')

#plantslist.remove('07-05-8290552')
#plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [10]:
#refpl = "03-01-01241117210.csv"

In [11]:
#df = pd.read_csv("./combined/" + refpl)

In [12]:
#df

In [13]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [14]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [15]:
testdf = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv")

In [16]:
nd = "01.01.2023 00:00"

In [17]:
datetime.strptime(nd, "%d.%m.%Y %H:%M")

datetime.datetime(2023, 1, 1, 0, 0)

In [18]:
arr = [nd, "2022-12-31 23:15:00", "2021-12-24 08:00:00", '29.04.2023 12:00', '01.01.2023 00:00']

In [19]:
list(map(lambda x: fix_date(x), arr))

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2022, 12, 31, 23, 15),
 datetime.datetime(2021, 12, 24, 8, 0),
 datetime.datetime(2023, 4, 29, 12, 0),
 datetime.datetime(2023, 1, 1, 0, 0)]

In [20]:
fix_date(nd)

datetime.datetime(2023, 1, 1, 0, 0)

In [21]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [22]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [23]:
#engine = create_engine('sqlite://', echo=False)

In [24]:
#2023-12-31 19:00:00.000000

In [25]:
#melt.dtypes

In [26]:
#testdf.iloc[70128]

In [27]:
#testdf['produced_at'] = testdf['produced_at'].map(return_date)

In [28]:
#testdf['produced_at'] = pd.to_datetime(testdf['produced_at'])

In [29]:
#df.dtypes

In [30]:
#df.iloc[70128]

In [31]:
#connection = engine2.connect()
#with engine2.begin() as connection:
plant = "06-05-100-0853075"

df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])
df.drop_duplicates(subset='produced_at', inplace=True)
#melt = df.melt(id_vars='produced_at')
#melt.drop('index', axis=1, inplace=True)
#res = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

In [32]:
#res

In [33]:
#melt

In [34]:
#melt.dtypes

In [35]:
with Session(engine2) as sess:
    sess.execute(text("TRUNCATE TABLE power2"))
    sess.commit()

In [36]:
from datetime import datetime

In [55]:
lpdid = "NW900-9141660"

In [60]:
lpd = pd.read_csv("./combined/" + lpdid + ".csv", delimiter=",", engine='c')
lpd2 = lpd[lpd.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]

/tmp/ipykernel_8345/1832200049.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  lpd2 = lpd[lpd.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]

In [61]:
#lpd.loc[~(lpd.produced_at == '0')]
#lpd = lpd.loc[~(lpd.produced_at == '03.05.2')]

In [62]:
#lpd2

In [63]:
#lpd2['produced_at'] = lpd2['produced_at'].map(fix_date)
lpd2['produced_at'] = pd.to_datetime(lpd2['produced_at'], format='mixed')

/tmp/ipykernel_8345/2102960277.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lpd2['produced_at'] = pd.to_datetime(lpd2['produced_at'], format='mixed')

In [66]:
len(lpd) - len(lpd2)

8

In [64]:
starttime = datetime.now()

In [46]:
counter = 0
for plant in plantslist:
    #if plant == '06-05-300-9046030':
    #    continue
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        try: #, format='%d.%m.%Y %H:%M'
            #df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df2['produced_at'] = df2['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df2['produced_at'] = df2['produced_at'].map(return_date)
            df2 = df
        except ValueError:
            print(plant + "\nfaulty")
            try:
                df2 = df[df.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
                df2['produced_at'] = df2['produced_at'].map(fix_date)
                #df2['produced_at'] = df2['produced_at'].map(fix_date)
                df2['produced_at'] = pd.to_datetime(df2['produced_at'])
                df2.drop_duplicates(subset='produced_at', inplace=True)
            except ValueError:
                print(plant + "\nfaulty beyond repair")
            #df2['produced_at'] = df2['produced_at'].map(fix_date)
            #df2['produced_at'] = pd.to_datetime(df2['produced_at'])
            #print(df2)
            continue
            #pass
        melt = df2.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power2', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

NW100-0081105
faulty

/tmp/ipykernel_8345/2985682516.py:20: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_8345/2985682516.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_8345/2985682516.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_8345/2985682516.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)

NW900-9141660
faulty

/tmp/ipykernel_8345/2985682516.py:20: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]

NW900-9141660
faulty byond repair
SD661-94
faulty

/tmp/ipykernel_8345/2985682516.py:20: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_8345/2985682516.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_8345/2985682516.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_8345/2985682516.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)

SN80011277
faulty

/tmp/ipykernel_8345/2985682516.py:20: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = df[df.produced_at.str.contains('([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|([0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_8345/2985682516.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_8345/2985682516.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_8345/2985682516.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)

69

In [53]:
endtime = datetime.now()
duration = endtime - starttime

In [67]:
duration

datetime.timedelta(seconds=767, microseconds=652614)

In [68]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [69]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [70]:
df = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])

In [71]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [72]:
#columns_table = (inspect(engine).get_columns('power'))

In [73]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [74]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [ ]:
starttime2 = datetime.now()

In [75]:
CDF = pd.read_sql_table('power2', engine2)

In [ ]:
endtime2 = datetime.now()
duration2 = endtime2 - starttime2

In [ ]:
duration2

In [76]:
CDF.sort_values(by=["produced_at", "variable"], ascending=True)

                 produced_at         variable  value
31433558 2015-01-01 00:00:00          BNA0199    0.0
68310415 2015-01-01 00:00:00          BNA0199    0.0
25753406 2015-01-01 00:00:00          BNA0215    0.0
62630263 2015-01-01 00:00:00          BNA0215    0.0
24491102 2015-01-01 00:00:00         BNA0221c    0.0
...                      ...              ...    ...
54706054 2025-12-31 23:45:00  SEE996720450723    0.0
8677937  2025-12-31 23:45:00  SEE998383491525    0.0
45554794 2025-12-31 23:45:00  SEE998383491525    0.0
15234565 2025-12-31 23:45:00       Unnamed: 3    0.0
52111422 2025-12-31 23:45:00       Unnamed: 3    0.0

[78820208 rows x 3 columns]

In [77]:
#CDF.drop_duplicates(subset=['produced_at', 'variable'])

In [78]:
CDF.shape

(78820208, 3)

In [79]:
CDF.to_csv("CDF.csv", index=False)

In [80]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [81]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [82]:
CDF9.sort_values(by="produced_at")

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631    0.0
24105418 2015-01-01 00:00:00  SEE975361659900    0.0
24491102 2015-01-01 00:00:00         BNA0221c    0.0
24876786 2015-01-01 00:00:00  SEE922855765289    0.0
24964448 2015-01-01 00:00:00  SEE964745752825    0.0
...                      ...              ...    ...
43205630 2025-12-31 23:45:00  SEE948541471333    0.0
71641186 2025-12-31 23:45:00          BNA0189    0.0
24105417 2025-12-31 23:45:00  SEE972458947407    0.0
64348322 2025-12-31 23:45:00  SEE957229968300    0.0
78820207 2025-12-31 23:45:00  SEE960652233358    0.0

[78820208 rows x 3 columns]

In [83]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [84]:
CDF9.iloc[70128]

produced_at    2023-01-01 08:00:00
variable           SEE913896693631
value                          0.0
Name: 70128, dtype: object

In [85]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

                 produced_at         variable  value
16146174 2015-01-01 00:00:00  SEE949509046600    0.0
53023031 2015-01-01 00:00:00  SEE949509046600    0.0
53023032 2015-01-01 01:00:00  SEE949509046600    0.0
16146175 2015-01-01 01:00:00  SEE949509046600    0.0
16146176 2015-01-01 02:00:00  SEE949509046600    0.0
...                      ...              ...    ...
16233833 2024-12-31 21:00:00  SEE949509046600    0.0
53110691 2024-12-31 22:00:00  SEE949509046600    0.0
16233834 2024-12-31 22:00:00  SEE949509046600    0.0
16233835 2024-12-31 23:00:00  SEE949509046600    0.0
53110692 2024-12-31 23:00:00  SEE949509046600    0.0

[175324 rows x 3 columns]

In [86]:
CDF9.shape

(78820208, 3)

In [87]:
#CDF9.iloc[15219136]

In [88]:
#CDF9.iloc[929304]

In [89]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [90]:
CDF9[CDF9.isnull().any(axis=1)].shape

(140144, 3)

In [91]:
CDF9b = CDF9.fillna(0)

In [92]:
#CDF10 = CDF9.dropna()

In [93]:
CDF9b["value"] = CDF9b["value"].astype(int)

In [94]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [95]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [96]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631    0.0
1        2015-01-01 01:00:00  SEE913896693631    0.0
2        2015-01-01 02:00:00  SEE913896693631    0.0
3        2015-01-01 03:00:00  SEE913896693631    0.0
4        2015-01-01 04:00:00  SEE913896693631    0.0
...                      ...              ...    ...
78820203 2025-12-31 22:45:00  SEE960652233358    0.0
78820204 2025-12-31 23:00:00  SEE960652233358    0.0
78820205 2025-12-31 23:15:00  SEE960652233358    0.0
78820206 2025-12-31 23:30:00  SEE960652233358    0.0
78820207 2025-12-31 23:45:00  SEE960652233358    0.0

[78820208 rows x 3 columns]

In [97]:
#CDF_new = CDF.reset_index(drop=False)

In [98]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [99]:
#CDF_new[CDF_new.produced_at.isnull()]

In [100]:
#CDF_new

In [101]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [102]:
#CDF

In [103]:
#CDF99.set_index('produced_at')

In [104]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [105]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [106]:
#subC1

In [107]:
CDF10 = CDF9b.copy()

In [108]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [109]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
78820203 2025-12-31 22:45:00  SEE960652233358      0
78820204 2025-12-31 23:00:00  SEE960652233358      0
78820205 2025-12-31 23:15:00  SEE960652233358      0
78820206 2025-12-31 23:30:00  SEE960652233358      0
78820207 2025-12-31 23:45:00  SEE960652233358      0

[78820208 rows x 3 columns]

In [110]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

/tmp/ipykernel_8345/675855814.py:1: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

In [151]:
#CDF2

In [112]:
CDF3 = CDF2.drop(columns="variable")

In [152]:
#CDF3

In [ ]:
CDF3

In [114]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [115]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [116]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [117]:
#gm2

In [118]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [119]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [120]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [121]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [122]:
gm8

       year  month          blockid  power
0      2015      1          BNA0199      0
1      2015      1          BNA0215      0
2      2015      1         BNA0221c      0
3      2015      1          BNA0333      0
4      2015      1          BNA0334      0
...     ...    ...              ...    ...
23191  2025     12  SEE992973663477      0
23192  2025     12  SEE995943794058  73728
23193  2025     12  SEE996720450723  64496
23194  2025     12  SEE998383491525      0
23195  2025     12       Unnamed: 3      0

[23196 rows x 4 columns]

In [123]:
gm7

       year  month          blockid  power
324    2015      1          BNA0199      0
456    2015      1          BNA0215      0
576    2015      1         BNA0221c      0
708    2015      1          BNA0333      0
828    2015      1          BNA0334      0
...     ...    ...              ...    ...
21947  2025     12  SEE992973663477      0
22439  2025     12  SEE995943794058  73728
22571  2025     12  SEE996720450723  64496
22943  2025     12  SEE998383491525      0
23195  2025     12       Unnamed: 3      0

[23196 rows x 4 columns]

In [124]:
bpm = seem.copy()

In [125]:
bpm

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [126]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [127]:
pm2

       year  month          blockid  power                    plantid
0      2015      1          BNA0199      0              NW300-9002708
1      2015      1          BNA0215      0              NW100-0365906
2      2015      1         BNA0221c      0              NW100-0167182
3      2015      1          BNA0333      0              NW500-0342658
4      2015      1          BNA0334      0              NW500-0342658
...     ...    ...              ...    ...                        ...
22543  2025     12  SEE992187994404      0                   BE172654
22544  2025     12  SEE992973663477      0  BWpf-450-1195689-00000000
22545  2025     12  SEE995943794058  73728                 BB23020490
22546  2025     12  SEE996720450723  64496                   BYS00044
22547  2025     12  SEE998383491525      0  BWpf-450-1195689-00000000

[22548 rows x 5 columns]

In [128]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [129]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [130]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [131]:
ym4

     year                    plantid  yearpower
0    2015              NW300-9002708    2748912
1    2015              NW100-0365906    4940446
2    2015              NW100-0167182     182888
3    2015              NW500-0342658    4612586
4    2015                 HE30001045    5057154
..    ...                        ...        ...
634  2025              NI06060316030    1802152
635  2025  BWpf-450-2797933-00000000    6823240
636  2025                 MV30000226    3635904
637  2025                   BE166928    1805536
638  2025                   BYS00044    2298504

[639 rows x 3 columns]

In [132]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [133]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [134]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [135]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [136]:
#invCDF = CDF.pivot(columns='variable')

In [137]:
gm8

       year  month          blockid  power
0      2015      1          BNA0199      0
1      2015      1          BNA0215      0
2      2015      1         BNA0221c      0
3      2015      1          BNA0333      0
4      2015      1          BNA0334      0
...     ...    ...              ...    ...
23191  2025     12  SEE992973663477      0
23192  2025     12  SEE995943794058  73728
23193  2025     12  SEE996720450723  64496
23194  2025     12  SEE998383491525      0
23195  2025     12       Unnamed: 3      0

[23196 rows x 4 columns]

In [138]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [139]:
pm2

       year  month          blockid  power                    plantid
0      2015      1          BNA0199      0              NW300-9002708
1      2015      1          BNA0215      0              NW100-0365906
2      2015      1         BNA0221c      0              NW100-0167182
3      2015      1          BNA0333      0              NW500-0342658
4      2015      1          BNA0334      0              NW500-0342658
...     ...    ...              ...    ...                        ...
22543  2025     12  SEE992187994404      0                   BE172654
22544  2025     12  SEE992973663477      0  BWpf-450-1195689-00000000
22545  2025     12  SEE995943794058  73728                 BB23020490
22546  2025     12  SEE996720450723  64496                   BYS00044
22547  2025     12  SEE998383491525      0  BWpf-450-1195689-00000000

[22548 rows x 5 columns]

In [140]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [141]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [142]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [143]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [144]:
ym4.loc[ym4.plantid == "NW100-0248923"]

     year        plantid  yearpower
26   2015  NW100-0248923   36525590
93   2016  NW100-0248923   50937196
161  2017  NW100-0248923   54224752
227  2018  NW100-0248923   58927450
291  2019  NW100-0248923   41682712
351  2020  NW100-0248923   34443638
410  2021  NW100-0248923   40030664
469  2022  NW100-0248923   44653794
526  2023  NW100-0248923   30043984
583  2024  NW100-0248923   25258404

In [145]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [146]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [147]:
#invCDF = CDF.pivot(columns='variable')

In [148]:
gm8

       year  month          blockid  power
0      2015      1          BNA0199      0
1      2015      1          BNA0215      0
2      2015      1         BNA0221c      0
3      2015      1          BNA0333      0
4      2015      1          BNA0334      0
...     ...    ...              ...    ...
23191  2025     12  SEE992973663477      0
23192  2025     12  SEE995943794058  73728
23193  2025     12  SEE996720450723  64496
23194  2025     12  SEE998383491525      0
23195  2025     12       Unnamed: 3      0

[23196 rows x 4 columns]

In [149]:
bpm

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]