In [1]:
import pandas as pd
from helpers import get_factor, get_price

In [2]:
CDF = pd.read_csv("../production/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

/tmp/ipykernel_1036702/3001582791.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [3]:
smard = pd.read_csv("Gro_handelspreise_202401010000_202501010000_Stunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

/tmp/ipykernel_1036702/2825335293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
/tmp/ipykernel_1036702/2825335293.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [4]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [5]:
CDF2 = CDF.loc[CDF.produced_at > "2023-12-31 23:50"].loc[CDF.produced_at < "2025-01-01 00:00"]

In [6]:
dataset = CDF2.merge(seem, left_on="variable", right_on="sseid")

In [7]:
magic = dataset.groupby(["produced_at", "plantid"]).sum()

In [8]:
magic2 = magic[["value"]]

In [9]:
#magic2.sort_values(["produced_at", "value"])

In [10]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [11]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")

In [12]:
merged["revenue"] = merged["value"] * merged["price"]
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [13]:
tmp1.reset_index(inplace=True)

In [14]:
revenue = tmp1[["plantid", "revenue"]]

In [15]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [16]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [17]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2023].loc[co2s.pollutant == "CO2"]

In [18]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [19]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [20]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [21]:
tmp2 = tmp1

In [22]:
#tmp2

In [23]:
coal_cost_per_t = 103.5 or 120
co2_cost = 80
#electricity_price = 78.50

In [24]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [25]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [26]:
co2s3.dtypes

plantid      object
amount_2    float64
dtype: object

In [27]:
tmp2.sort_values("profit")

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2,co2_cost,coal_cost,profit
1,BB45025564,7.982573e+08,Braunkohle,Kraftwerk Jänschwalde Block A,11960.0,3.25,18,14.134000,1129.763200,78.280615,-409.786491
26,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,16.485000,1318.559920,91.301538,-316.861528
12,BWpf-450-2948214-00000000,1.721634e+08,Steinkohle,GKM Block 6,92027.0,2.68,120,3.430000,267.037840,153.582090,-248.456500
0,BB23020490,1.093048e+08,Mineralölprodukte,1MKA,0.0,2.30,75,3.015000,241.200000,98.315217,-230.210395
34,NW500-0342658,2.653052e+07,Steinkohle,Scholven 1 DT,48161.0,2.68,120,1.993000,155.587120,89.238806,-218.295404
28,NW300-0326774,9.212323e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,13.311000,1062.796720,73.722462,-215.286920
2,BB45025611,6.055226e+08,Braunkohle,Kraftwerk Schwarze Pumpe Block A,207831.0,3.25,18,9.713000,760.413520,53.795077,-208.685953
35,NW500-0915123,1.619746e+08,Steinkohle,Datteln 4,631.0,2.68,120,2.945000,235.549520,131.865672,-205.440545
11,BWpf-450-2797933-00000000,2.106808e+08,Steinkohle,Rheinhafen- Dampfkraftwerk RDK 4S DT,0.0,2.68,120,3.185000,254.800000,142.611940,-186.731180
14,BYS00041,6.431633e+07,Erdgas,SWM HKW Nord 2 T20,0.0,1.50,40,2.090000,167.200000,55.733333,-158.617001
19,MV30000226,7.126096e+07,Steinkohle,Kraftwerk Rostock Block A,14468.0,2.68,120,1.728000,137.082560,77.373134,-143.194736
21,NI01241117210,3.552431e+07,Steinkohle,DT30 GuD Süd Wolfsburg,0.0,2.68,120,1.429000,114.320000,63.985075,-142.780761
27,NW100-0365906,3.694577e+07,Steinkohle,Walsum 10,16300.0,2.68,120,1.244000,98.216000,55.701493,-116.971719
36,NW700-0105516,1.775971e+07,Steinkohle,Heyden 4,0.0,2.68,120,1.046000,83.680000,46.835821,-112.756112
47,SN80011277,5.286458e+08,Braunkohle,Kraftwerk Lippendorf Block S,43457.0,3.25,18,7.443000,591.963440,41.222769,-104.540417
18,HE30001045,2.140724e+07,Steinkohle,Staudinger 4,0.0,2.68,120,0.967000,77.360000,43.298507,-99.251268
3,BE166928,9.494364e+07,Steinkohle,HKW Reuter West Dampfturbine D,63958.0,2.68,120,1.547000,118.643360,69.268657,-92.968376
39,NW900-0327252,1.109757e+07,Steinkohle,GuD Herne,0.0,2.68,120,0.763000,61.040000,34.164179,-84.106611
38,NW900-0205103,2.082932e+07,Steinkohle,Bergkamen A,474.0,2.68,120,0.808000,64.602080,36.179104,-79.951861
22,NI06060316030,8.229311e+07,Steinkohle,GKH 1,0.0,2.68,120,1.286000,102.880000,57.582090,-78.168977
42,SL0100999-G,2.155009e+07,Steinkohle,Bexbach,0.0,2.68,120,0.755000,60.400000,33.805970,-72.655876
44,SL0101003-G,1.084055e+07,Steinkohle,Weiher 3,0.0,2.68,120,0.653000,52.240000,29.238806,-70.638255
9,BWpf-450-1741292-00000000,4.850663e+07,Steinkohle,Heizkraftwerk Altbach/Deizisau HKW 1,17065.0,2.68,120,0.904000,70.954800,40.477612,-62.925778
17,BYS00114,1.151014e+07,Erdgas,Gasturbinenanlage 12,0.0,1.50,40,0.617000,49.360000,16.453333,-54.303189
46,SN70015796,1.065023e+09,Braunkohle,Boxberg Block N,6085.0,3.25,18,13.088000,1046.553200,72.487385,-54.018023
30,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,9.336000,745.902160,51.707077,-45.403904
13,BYS00009,1.027118e+08,Steinkohle,Kraftwerk Zolling,0.0,2.68,120,1.160000,92.800000,51.940299,-42.028450
8,BWpf-450-1195689-00000000,1.711508e+07,Steinkohle,Heizkraftwerk Stuttgart-Münster DT 12,0.0,2.68,120,0.448000,35.840000,20.059701,-38.784626
48,ST100125,3.009824e+08,Braunkohle,Schkopau A,15250.0,3.25,18,3.942000,314.140000,21.832615,-34.990241
20,NI01010098080,4.114252e+07,Steinkohle,KWM Block 3,0.0,2.68,120,0.579000,46.320000,25.925373,-31.102857
31,NW300-0923949,0.000000e+00,Braunkohle,Block 4 Merkenich RheinEnergie,0.0,3.25,18,0.280000,22.400000,1.550769,-23.950769
41,NW900-9141660,2.497194e+08,Steinkohle,Trianel Kohlekraftwerk Lünen,1662.0,2.68,120,2.146000,171.547040,96.089552,-17.917207
43,SL0101000-G,1.556536e+06,Steinkohle,Gasmotor 1 Mod.,0.0,2.68,120,0.132000,10.560000,5.910448,-14.913911
10,BWpf-450-2142201-00000000,3.174966e+06,Steinkohle,Kraftwerk Walheim Block 2,0.0,2.68,120,0.113000,9.040000,5.059701,-10.924735
4,BE169709,3.070577e+07,Erdgas,HKW Klingenberg Dampfturbine 1,82983.0,1.50,40,0.407000,25.921360,10.853333,-6.068926
45,SL0105352-G,1.230613e+07,Erdgas,Dampfturbinenanlage DT3,0.0,1.50,40,0.103000,8.240000,2.746667,1.319462
7,BWpf-450-1020129-00000000,5.957858e+07,Steinkohle,Heizkraftwerk Heilbronn FHT 1,0.0,2.68,120,0.425000,34.000000,19.029851,6.548729
25,NW100-0229264,3.269475e+07,Erdgas,HKW III Block A,0.0,1.50,40,0.201637,16.130960,5.376987,11.186803
6,BE172656,8.590997e+07,Erdgas,GuD Marzahn Dampfturbine,22820.0,1.50,40,0.584000,44.894400,15.573333,25.442232
5,BE172654,1.153207e+08,Erdgas,HKW Mitte Dampfturbine,79075.0,1.50,40,0.696000,49.354000,18.560000,47.406734
32,NW300-9002708,1.312524e+08,Erdgas,Dormagen DT,0.0,1.50,40,0.702474,56.197936,18.732645,56.321779
15,BYS00044,9.903749e+07,Erdgas,SWM HKW Sued GuD1 GT2,0.0,1.50,40,0.387000,30.960000,10.320000,57.757495
37,NW900-0125939,8.414225e+07,Erdgas,Cuno Heizkraftwerk Herdecke BHKW1,0.0,1.50,40,0.241000,19.280000,6.426667,58.435587
33,NW300-9046030,1.241809e+08,Erdgas,Knapsack I - Dampfturbine - DT 10,0.0,1.50,40,0.377000,30.160000,10.053333,83.967573
29,NW300-0370387,1.942240e+08,Erdgas,DT Niehl 2 RheinEnergie,0.0,1.50,40,1.023000,81.840000,27.280000,85.103969
40,NW900-9140178,1.370171e+08,Erdgas,Trianel Gaskraftwerk Hamm Block 10,0.0,1.50,40,0.344000,27.520000,9.173333,100.323734
23,NI10257673950,2.827623e+08,Erdgas,Emsland B DT,43608.0,1.50,40,1.436000,111.391360,38.293333,133.077615
24,NW100-0167182,2.446624e+08,Erdgas,SWD KWF GTKW,0.0,1.50,40,0.897000,71.760000,23.920000,148.982389
16,BYS00048,3.586528e+08,Erdgas,Irsching 5 DT,0.0,1.50,40,1.130000,90.400000,30.133333,238.119507

In [28]:
#tmp2["profit_adj"] = (tmp2["revenue"] * 1.10) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [29]:
tmp2.sort_values("profit")

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2,co2_cost,coal_cost,profit
1,BB45025564,7.982573e+08,Braunkohle,Kraftwerk Jänschwalde Block A,11960.0,3.25,18,14.134000,1129.763200,78.280615,-409.786491
26,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,16.485000,1318.559920,91.301538,-316.861528
12,BWpf-450-2948214-00000000,1.721634e+08,Steinkohle,GKM Block 6,92027.0,2.68,120,3.430000,267.037840,153.582090,-248.456500
0,BB23020490,1.093048e+08,Mineralölprodukte,1MKA,0.0,2.30,75,3.015000,241.200000,98.315217,-230.210395
34,NW500-0342658,2.653052e+07,Steinkohle,Scholven 1 DT,48161.0,2.68,120,1.993000,155.587120,89.238806,-218.295404
28,NW300-0326774,9.212323e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,13.311000,1062.796720,73.722462,-215.286920
2,BB45025611,6.055226e+08,Braunkohle,Kraftwerk Schwarze Pumpe Block A,207831.0,3.25,18,9.713000,760.413520,53.795077,-208.685953
35,NW500-0915123,1.619746e+08,Steinkohle,Datteln 4,631.0,2.68,120,2.945000,235.549520,131.865672,-205.440545
11,BWpf-450-2797933-00000000,2.106808e+08,Steinkohle,Rheinhafen- Dampfkraftwerk RDK 4S DT,0.0,2.68,120,3.185000,254.800000,142.611940,-186.731180
14,BYS00041,6.431633e+07,Erdgas,SWM HKW Nord 2 T20,0.0,1.50,40,2.090000,167.200000,55.733333,-158.617001
19,MV30000226,7.126096e+07,Steinkohle,Kraftwerk Rostock Block A,14468.0,2.68,120,1.728000,137.082560,77.373134,-143.194736
21,NI01241117210,3.552431e+07,Steinkohle,DT30 GuD Süd Wolfsburg,0.0,2.68,120,1.429000,114.320000,63.985075,-142.780761
27,NW100-0365906,3.694577e+07,Steinkohle,Walsum 10,16300.0,2.68,120,1.244000,98.216000,55.701493,-116.971719
36,NW700-0105516,1.775971e+07,Steinkohle,Heyden 4,0.0,2.68,120,1.046000,83.680000,46.835821,-112.756112
47,SN80011277,5.286458e+08,Braunkohle,Kraftwerk Lippendorf Block S,43457.0,3.25,18,7.443000,591.963440,41.222769,-104.540417
18,HE30001045,2.140724e+07,Steinkohle,Staudinger 4,0.0,2.68,120,0.967000,77.360000,43.298507,-99.251268
3,BE166928,9.494364e+07,Steinkohle,HKW Reuter West Dampfturbine D,63958.0,2.68,120,1.547000,118.643360,69.268657,-92.968376
39,NW900-0327252,1.109757e+07,Steinkohle,GuD Herne,0.0,2.68,120,0.763000,61.040000,34.164179,-84.106611
38,NW900-0205103,2.082932e+07,Steinkohle,Bergkamen A,474.0,2.68,120,0.808000,64.602080,36.179104,-79.951861
22,NI06060316030,8.229311e+07,Steinkohle,GKH 1,0.0,2.68,120,1.286000,102.880000,57.582090,-78.168977
42,SL0100999-G,2.155009e+07,Steinkohle,Bexbach,0.0,2.68,120,0.755000,60.400000,33.805970,-72.655876
44,SL0101003-G,1.084055e+07,Steinkohle,Weiher 3,0.0,2.68,120,0.653000,52.240000,29.238806,-70.638255
9,BWpf-450-1741292-00000000,4.850663e+07,Steinkohle,Heizkraftwerk Altbach/Deizisau HKW 1,17065.0,2.68,120,0.904000,70.954800,40.477612,-62.925778
17,BYS00114,1.151014e+07,Erdgas,Gasturbinenanlage 12,0.0,1.50,40,0.617000,49.360000,16.453333,-54.303189
46,SN70015796,1.065023e+09,Braunkohle,Boxberg Block N,6085.0,3.25,18,13.088000,1046.553200,72.487385,-54.018023
30,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,9.336000,745.902160,51.707077,-45.403904
13,BYS00009,1.027118e+08,Steinkohle,Kraftwerk Zolling,0.0,2.68,120,1.160000,92.800000,51.940299,-42.028450
8,BWpf-450-1195689-00000000,1.711508e+07,Steinkohle,Heizkraftwerk Stuttgart-Münster DT 12,0.0,2.68,120,0.448000,35.840000,20.059701,-38.784626
48,ST100125,3.009824e+08,Braunkohle,Schkopau A,15250.0,3.25,18,3.942000,314.140000,21.832615,-34.990241
20,NI01010098080,4.114252e+07,Steinkohle,KWM Block 3,0.0,2.68,120,0.579000,46.320000,25.925373,-31.102857
31,NW300-0923949,0.000000e+00,Braunkohle,Block 4 Merkenich RheinEnergie,0.0,3.25,18,0.280000,22.400000,1.550769,-23.950769
41,NW900-9141660,2.497194e+08,Steinkohle,Trianel Kohlekraftwerk Lünen,1662.0,2.68,120,2.146000,171.547040,96.089552,-17.917207
43,SL0101000-G,1.556536e+06,Steinkohle,Gasmotor 1 Mod.,0.0,2.68,120,0.132000,10.560000,5.910448,-14.913911
10,BWpf-450-2142201-00000000,3.174966e+06,Steinkohle,Kraftwerk Walheim Block 2,0.0,2.68,120,0.113000,9.040000,5.059701,-10.924735
4,BE169709,3.070577e+07,Erdgas,HKW Klingenberg Dampfturbine 1,82983.0,1.50,40,0.407000,25.921360,10.853333,-6.068926
45,SL0105352-G,1.230613e+07,Erdgas,Dampfturbinenanlage DT3,0.0,1.50,40,0.103000,8.240000,2.746667,1.319462
7,BWpf-450-1020129-00000000,5.957858e+07,Steinkohle,Heizkraftwerk Heilbronn FHT 1,0.0,2.68,120,0.425000,34.000000,19.029851,6.548729
25,NW100-0229264,3.269475e+07,Erdgas,HKW III Block A,0.0,1.50,40,0.201637,16.130960,5.376987,11.186803
6,BE172656,8.590997e+07,Erdgas,GuD Marzahn Dampfturbine,22820.0,1.50,40,0.584000,44.894400,15.573333,25.442232
5,BE172654,1.153207e+08,Erdgas,HKW Mitte Dampfturbine,79075.0,1.50,40,0.696000,49.354000,18.560000,47.406734
32,NW300-9002708,1.312524e+08,Erdgas,Dormagen DT,0.0,1.50,40,0.702474,56.197936,18.732645,56.321779
15,BYS00044,9.903749e+07,Erdgas,SWM HKW Sued GuD1 GT2,0.0,1.50,40,0.387000,30.960000,10.320000,57.757495
37,NW900-0125939,8.414225e+07,Erdgas,Cuno Heizkraftwerk Herdecke BHKW1,0.0,1.50,40,0.241000,19.280000,6.426667,58.435587
33,NW300-9046030,1.241809e+08,Erdgas,Knapsack I - Dampfturbine - DT 10,0.0,1.50,40,0.377000,30.160000,10.053333,83.967573
29,NW300-0370387,1.942240e+08,Erdgas,DT Niehl 2 RheinEnergie,0.0,1.50,40,1.023000,81.840000,27.280000,85.103969
40,NW900-9140178,1.370171e+08,Erdgas,Trianel Gaskraftwerk Hamm Block 10,0.0,1.50,40,0.344000,27.520000,9.173333,100.323734
23,NI10257673950,2.827623e+08,Erdgas,Emsland B DT,43608.0,1.50,40,1.436000,111.391360,38.293333,133.077615
24,NW100-0167182,2.446624e+08,Erdgas,SWD KWF GTKW,0.0,1.50,40,0.897000,71.760000,23.920000,148.982389
16,BYS00048,3.586528e+08,Erdgas,Irsching 5 DT,0.0,1.50,40,1.130000,90.400000,30.133333,238.119507