In [1]:
import pandas as pd
from helpers import get_factor, get_price
pd.options.mode.chained_assignment = None

In [2]:
CDF = pd.read_csv("../production-v2/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [3]:
#CDF.sort_values(by=["produced_at", "variable"])

In [4]:
smard = pd.read_csv("Gro_handelspreise_202501010000_202601010000_Viertelstunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [5]:
smardlog['timestamp'] = smardlog['timestamp'] + pd.offsets.DateOffset(years=-1)

In [6]:
smardlog.dtypes

timestamp    datetime64[ns]
price               float64
dtype: object

In [7]:
smardlog_2024 = pd.read_excel("GHP_2023.xlsx")[['timestamp', 'price']]

In [8]:
smardlog.to_excel("GHP_2025.xlsx", index=False)

In [9]:
smardlog.describe()

                           timestamp         price
count                          35040  35040.000000
mean   2024-07-02 08:34:15.205479424     89.321723
min              2024-01-01 00:00:00   -250.320000
25%              2024-04-02 06:56:15     70.570000
50%              2024-07-02 12:52:30     92.325000
75%              2024-10-01 18:48:45    114.160000
max              2024-12-31 23:45:00    583.400000
std                              NaN     52.475480

In [10]:
smardlog_2024.describe()

                           timestamp         price
count                          35136  35136.000000
mean   2024-07-02 00:26:55.573770496     78.512033
min              2024-01-01 00:00:00   -135.450000
25%              2024-04-01 12:56:15     55.560000
50%              2024-07-02 00:52:30     79.585000
75%              2024-10-01 12:48:45    101.340000
max              2024-12-31 23:45:00    936.280000
std                              NaN     52.724158

In [11]:
smardlog.sort_values('price')

                timestamp   price
12529 2024-11-05 13:15:00 -250.32
12530 2024-11-05 13:30:00 -250.32
12528 2024-11-05 13:00:00 -250.32
12531 2024-11-05 13:45:00 -250.32
12535 2024-11-05 14:45:00 -230.98
...                   ...     ...
27527 2024-10-14 18:45:00  508.38
1893  2024-01-20 17:15:00  583.40
1894  2024-01-20 17:30:00  583.40
1895  2024-01-20 17:45:00  583.40
1892  2024-01-20 17:00:00  583.40

[35040 rows x 2 columns]

In [12]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [13]:
#co2s['year'] = co2s['year'] + 1

In [14]:
#co2s

In [15]:
CDF2 = CDF.loc[CDF.produced_at > "2023-12-31 23:50"].loc[CDF.produced_at < "2025-01-01 00:00"]

In [16]:
CDF2['produced_at'] = pd.to_datetime(CDF2['produced_at'])

In [17]:
CDF2

                 produced_at         variable  value
78879    2024-01-01 00:00:00  SEE913896693631    0.0
78880    2024-01-01 01:00:00  SEE913896693631    0.0
78881    2024-01-01 02:00:00  SEE913896693631    0.0
78882    2024-01-01 03:00:00  SEE913896693631    0.0
78883    2024-01-01 04:00:00  SEE913896693631    0.0
...                      ...              ...    ...
43493831 2024-12-31 22:45:00  SEE960652233358    0.0
43493832 2024-12-31 23:00:00  SEE960652233358    0.0
43493833 2024-12-31 23:15:00  SEE960652233358    0.0
43493834 2024-12-31 23:30:00  SEE960652233358    0.0
43493835 2024-12-31 23:45:00  SEE960652233358    0.0

[3899652 rows x 3 columns]

In [18]:
CDF2a = CDF2.copy()#loc[~(CDF2.variable.str.contains("Unnamed"))]

In [19]:
#CDF2b = CDF2a.groupby('variable').resample('1h', on='produced_at').mean()

In [20]:
CDF3 = CDF2a

In [21]:
#CDF3 = CDF2.dropna()

In [22]:
len(CDF2) - len(CDF3)

0

In [23]:
len(CDF2.groupby('produced_at').sum())

35132

In [24]:
dataset = CDF3.merge(seem, left_on="variable", right_on="sseid", how="inner")

In [25]:
dataset2 = dataset.drop_duplicates(subset=['produced_at', 'variable'])

In [26]:
len(dataset)

3750341

In [27]:
dataset

,produced_at,variable,value,plantid,sseid
0,2024-01-01 00:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
1,2024-01-01 01:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
2,2024-01-01 02:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
3,2024-01-01 03:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
4,2024-01-01 04:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
...,...,...,...,...,...
3750336,2024-12-31 22:45:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750337,2024-12-31 23:00:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750338,2024-12-31 23:15:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750339,2024-12-31 23:30:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750340,2024-12-31 23:45:00,SEE960652233358,0.0,ST100125,SEE960652233358

In [28]:
magic = dataset2.groupby(["produced_at", "plantid"]).sum()

In [29]:
#magic

In [30]:
magic2 = magic[["value"]]

In [31]:
#magic2.sort_values(["produced_at", "value"])

In [32]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [33]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")
merged["revenue"] = merged["value"] * merged["price"]

In [34]:
merged_mytmp = merged[['produced_at', 'plantid', 'value', 'price', 'revenue']]

In [35]:
merged_mytmp.loc[merged_mytmp.plantid == "BB45025564"].sort_values('revenue').resample('1YE', on='produced_at').sum()

,plantid,value,price,revenue
produced_at,,,,
2024-12-31,BB45025564BB45025564BB45025564BB45025564BB4502...,9513820.0,3129575.52,9.021745e+08

In [36]:
#merged1a = merged.groupby('plantid').resample('1h', on='produced_at').mean().reset_index()

In [37]:
#merged1a.sort_values('revenue')

In [38]:
#merged

In [39]:
#production.sort_values(by=["plantid", "produced_at"])

In [40]:
#merged1a

In [41]:

#merged_tmp = merged.drop(columns=["timestamp"])
#merged1a = merged_tmp.set_index("produced_at", drop=True)

In [42]:
#merged1a = merged_tmp.set_index(['plantid']).sort_values(['plantid', 'produced_at'])

In [43]:
#merged2 = merged1a.resample("1h", on="produced_at").agg({'value':'sum', 'price':'sum', 'revenue': 'sum' })

In [44]:
#merged1a

In [45]:
#tmp1 = merged2.copy()
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [46]:
tmp1.reset_index(inplace=True)

In [47]:
revenue = tmp1[["plantid", "revenue"]]

In [48]:
#tmp1

In [49]:
#dataset.sort_values(["plantid", "produced_at"])

In [50]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [51]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [52]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2024].loc[co2s.pollutant == "CO2"]

In [53]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [54]:
#co2s2

In [55]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [56]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [57]:
tmp2 = pd.merge(tmp1, production, on="plantid")

In [58]:
tmp2 = tmp1

In [67]:
coal_cost_per_t = 103.5# or 120
co2_cost = 74 # https://www.umweltbundesamt.de/presse/pressemitteilungen/emissionshandel-21-milliarden-euro-fliessen-in-den
# https://icapcarbonaction.com/system/files/ets_pdfs/icap-etsmap-factsheet-43.pdf
#electricity_price = 78.50

In [68]:
#tmp2

In [69]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [70]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [71]:
#tmp2

In [72]:
#tmp2.sort_values(by="free_co2s", ascending=False)

In [73]:
profit = tmp2[["plantid", "plantname", "revenue", "profit"]]
profit["revenue"] = profit["revenue"].apply(lambda x: x / 10**6)

In [74]:
profit.sort_values("profit", ascending=False)

,plantid,plantname,revenue,profit
15,BYS00048,Irsching 5 DT,357.246201,227.386201
22,NI10257673950,Emsland B DT,301.656254,186.096580
23,NW100-0167182,SWD KWF GTKW,263.085984,164.130651
25,NW100-0248923,Neurath F,1187.301991,123.378988
46,SN80011277,Kraftwerk Lippendorf Block S,565.427126,112.808021
28,NW300-0370387,DT Niehl 2 RheinEnergie,219.186454,103.218454
39,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,132.185978,84.570645
31,NW300-9002708,Dormagen DT,135.061712,67.313045
5,BE172654,HKW Mitte Dampfturbine,127.173536,65.377086
32,NW300-9046030,Knapsack I - Dampfturbine - DT 10,112.465133,64.145133
14,BYS00044,SWM HKW Sued GuD1 GT2,106.869396,55.630063
36,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,80.676611,48.060611
45,SN70015796,Boxberg Block N,1146.480136,46.436272
27,NW300-0326774,Niederaußem G,981.344994,43.047874
6,BE172656,GuD Marzahn Dampfturbine,92.553058,41.693738
2,BB45025611,Kraftwerk Schwarze Pumpe Block A,655.785999,28.393789
24,NW100-0229264,HKW III Block A,34.128614,14.901281
19,NI01010098080,KWM Block 3,54.529096,5.118231
44,SL0105352-G,Dampfturbinenanlage DT3,14.071483,3.702816
4,BE169709,HKW Klingenberg Dampfturbine 1,35.805329,-0.937929
37,NW900-0205103,Bergkamen A,27.209600,-1.261593
18,MV30000226,Kraftwerk Rostock Block A,60.178252,-3.246548
34,NW500-0915123,Datteln 4,198.825520,-4.234950
12,BYS00009,Kraftwerk Zolling,100.357407,-5.590891
43,SL0101003-G,Weiher 3,16.047329,-7.114014
40,NW900-9141660,Trianel Kohlekraftwerk Lünen,246.058102,-9.900224
38,NW900-0327252,GuD Herne,16.097425,-9.914546
42,SL0100999-G,Bexbach,24.768377,-10.389354
35,NW700-0105516,Heyden 4,23.699739,-17.040470
30,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-23.782000
8,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,19.474931,-31.004919
47,ST100125,Schkopau A,310.619842,-31.062427
17,HE30001045,Staudinger 4,32.219021,-33.345397
7,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,54.604057,-37.209883
9,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,48.974416,-40.745282
21,NI06060316030,GKH 1,88.594929,-41.583698
10,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,191.278702,-43.066582
16,BYS00114,Gasturbinenanlage 12,13.139349,-45.045985
29,NW300-0877384,Weisweiler F,782.163416,-49.938390
3,BE166928,HKW Reuter West Dampfturbine D,113.278756,-53.738620
1,BB45025564,Kraftwerk Jänschwalde Block A,902.174453,-71.843430
33,NW500-0342658,Scholven 1 DT,32.964248,-71.914435
13,BYS00041,SWM HKW Nord 2 T20,75.012671,-71.960662
20,NI01241117210,DT30 GuD Süd Wolfsburg,43.984333,-72.653816
26,NW100-0365906,Walsum 10,36.958857,-119.688406
11,BWpf-450-2948214-00000000,GKM Block 6,189.545224,-177.195674
0,BB23020490,1MKA,122.240428,-227.116268
41,RP5000671,GuD Mitte DT10,173.697326,-341.716007

In [80]:
profit.sort_values("profit", ascending=False)

,plantid,plantname,revenue,profit
14,BYS00048,Irsching 5 DT,357.246201,226.096201
21,NI10257673950,Emsland B DT,301.656254,184.960188
22,NW100-0167182,SWD KWF GTKW,263.085984,163.147651
24,NW100-0248923,Neurath F,1187.301991,110.002989
45,SN80011277,Kraftwerk Lippendorf Block S,565.427126,107.120478
27,NW300-0370387,DT Niehl 2 RheinEnergie,219.186454,102.066454
38,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,132.185978,84.097645
30,NW300-9002708,Dormagen DT,135.061712,66.640045
4,BE172654,HKW Mitte Dampfturbine,127.173536,64.784161
31,NW300-9046030,Knapsack I - Dampfturbine - DT 10,112.465133,63.665133
13,BYS00044,SWM HKW Sued GuD1 GT2,106.869396,55.121063
35,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,80.676611,47.736611
5,BE172656,GuD Marzahn Dampfturbine,92.553058,41.194558
44,SN70015796,Boxberg Block N,1146.480136,32.606357
26,NW300-0326774,Niederaußem G,981.344994,31.252915
23,NW100-0229264,HKW III Block A,34.128614,14.710281
18,NI01010098080,KWM Block 3,54.529096,4.702231
43,SL0105352-G,Dampfturbinenanlage DT3,14.071483,3.599816
3,BE169709,HKW Klingenberg Dampfturbine 1,35.805329,-1.280946
36,NW900-0205103,Bergkamen A,27.209600,-1.501119
17,MV30000226,Kraftwerk Rostock Block A,60.178252,-3.775080
33,NW500-0915123,Datteln 4,198.825520,-5.944319
11,BYS00009,Kraftwerk Zolling,100.357407,-6.482891
42,SL0101003-G,Weiher 3,16.047329,-7.309014
37,NW900-0327252,GuD Herne,16.097425,-10.133546
41,SL0100999-G,Bexbach,24.768377,-10.685354
39,NW900-9141660,Trianel Kohlekraftwerk Lünen,246.058102,-12.054562
34,NW700-0105516,Heyden 4,23.699739,-17.383470
29,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-24.081000
7,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,19.474931,-31.429919
16,HE30001045,Staudinger 4,32.219021,-33.897397
46,ST100125,Schkopau A,310.619842,-35.357177
6,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,54.604057,-37.982883
8,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,48.974416,-41.494217
20,NI06060316030,GKH 1,88.594929,-42.679698
9,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,191.278702,-45.039582
15,BYS00114,Gasturbinenanlage 12,13.139349,-45.623985
2,BE166928,HKW Reuter West Dampfturbine D,113.278756,-55.120662
28,NW300-0877384,Weisweiler F,782.163416,-60.399167
32,NW500-0342658,Scholven 1 DT,32.964248,-72.779274
12,BYS00041,SWM HKW Nord 2 T20,75.012671,-73.420662
19,NI01241117210,DT30 GuD Süd Wolfsburg,43.984333,-73.635816
1,BB45025564,Kraftwerk Jänschwalde Block A,902.174453,-84.088470
25,NW100-0365906,Walsum 10,36.958857,-121.001106
10,BWpf-450-2948214-00000000,GKM Block 6,189.545224,-180.248647
0,BB23020490,1MKA,122.240428,-230.393268
40,RP5000671,GuD Mitte DT10,173.697326,-346.836007

In [81]:
profit_combined = pd.concat([profit, profit2])

NameError: name 'profit2' is not defined

In [ ]:
profit_final = profit_combined.drop_duplicates(subset="plantid", keep="first").sort_values('profit')

In [ ]:
#profit.to_csv("profit.csv", index=False)

In [ ]:
pd.concat([profit2, profit, profit]).drop_duplicates(keep=False)

In [ ]:
#profit_final.reset_index()

In [ ]:
pd.concat([profit, profit2, profit2]).drop_duplicates(keep=False).sort_values('profit', ascending=False)

In [ ]:
#profit2 = profit

In [ ]:
profit2.sort_values("profit", ascending=False)