In [1]:
import pandas as pd
from helpers import get_factor, get_price
pd.options.mode.chained_assignment = None

In [2]:
CDF = pd.read_csv("../production-v2/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [3]:
#CDF.sort_values(by=["produced_at", "variable"])

In [4]:
smard = pd.read_csv("Gro_handelspreise_202401010000_202501010000_Viertelstunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [5]:
smardlog.dtypes

timestamp    datetime64[us]
price               float64
dtype: object

In [6]:
#smardlog.to_excel("GHP_2023.xlsx")

In [7]:
smardlog.describe()

                           timestamp         price
count                          35136  35136.000000
mean   2024-07-02 00:26:55.573770496     78.512033
min              2024-01-01 00:00:00   -135.450000
25%              2024-04-01 12:56:15     55.560000
50%              2024-07-02 00:52:30     79.585000
75%              2024-10-01 12:48:45    101.340000
max              2024-12-31 23:45:00    936.280000
std                              NaN     52.724158

In [8]:
smardlog.sort_values('price')

                timestamp   price
12721 2024-12-05 13:15:00 -135.45
12722 2024-12-05 13:30:00 -135.45
12723 2024-12-05 13:45:00 -135.45
12720 2024-12-05 13:00:00 -135.45
12725 2024-12-05 14:15:00 -132.85
...                   ...     ...
29831 2024-06-11 17:45:00  820.11
33287 2024-12-12 17:45:00  936.28
33286 2024-12-12 17:30:00  936.28
33285 2024-12-12 17:15:00  936.28
33284 2024-12-12 17:00:00  936.28

[35136 rows x 2 columns]

In [9]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [10]:
#co2s['year'] = co2s['year'] + 1

In [11]:
#co2s

In [12]:
CDF2 = CDF.loc[CDF.produced_at > "2023-12-31 23:50"].loc[CDF.produced_at < "2025-01-01 00:00"]

In [13]:
CDF2['produced_at'] = pd.to_datetime(CDF2['produced_at'])

In [14]:
CDF2

                 produced_at         variable  value
78879    2024-01-01 00:00:00  SEE913896693631    0.0
78880    2024-01-01 01:00:00  SEE913896693631    0.0
78881    2024-01-01 02:00:00  SEE913896693631    0.0
78882    2024-01-01 03:00:00  SEE913896693631    0.0
78883    2024-01-01 04:00:00  SEE913896693631    0.0
...                      ...              ...    ...
43493831 2024-12-31 22:45:00  SEE960652233358    0.0
43493832 2024-12-31 23:00:00  SEE960652233358    0.0
43493833 2024-12-31 23:15:00  SEE960652233358    0.0
43493834 2024-12-31 23:30:00  SEE960652233358    0.0
43493835 2024-12-31 23:45:00  SEE960652233358    0.0

[3899652 rows x 3 columns]

In [15]:
CDF2a = CDF2.copy()#loc[~(CDF2.variable.str.contains("Unnamed"))]

In [16]:
#CDF2b = CDF2a.groupby('variable').resample('1h', on='produced_at').mean()

In [17]:
CDF3 = CDF2a

In [18]:
#CDF3 = CDF2.dropna()

In [19]:
len(CDF2) - len(CDF3)

0

In [20]:
len(CDF2.groupby('produced_at').sum())

35132

In [21]:
dataset = CDF3.merge(seem, left_on="variable", right_on="sseid", how="inner")

In [22]:
dataset2 = dataset.drop_duplicates(subset=['produced_at', 'variable'])

In [23]:
len(dataset)

3750341

In [72]:
dataset.sort_values('value', ascending=False)

,produced_at,variable,value,plantid,sseid
2251051,2024-04-18 12:00:00,SEE925599434282,1203.0,NW100-0248923,SEE925599434282
2256884,2024-12-17 13:00:00,SEE925599434282,1080.0,NW100-0248923,SEE925599434282
2256767,2024-12-12 16:00:00,SEE925599434282,1075.0,NW100-0248923,SEE925599434282
2256802,2024-12-14 03:00:00,SEE925599434282,1074.0,NW100-0248923,SEE925599434282
2256769,2024-12-12 18:00:00,SEE925599434282,1073.0,NW100-0248923,SEE925599434282
...,...,...,...,...,...
1426599,2024-06-05 10:00:00,SEE952372080091,0.0,BYS00041,SEE952372080091
1426600,2024-06-05 11:00:00,SEE952372080091,0.0,BYS00041,SEE952372080091
1426601,2024-06-05 12:00:00,SEE952372080091,0.0,BYS00041,SEE952372080091
1426602,2024-06-05 13:00:00,SEE952372080091,0.0,BYS00041,SEE952372080091
1426590,2024-06-05 01:00:00,SEE952372080091,0.0,BYS00041,SEE952372080091

In [25]:
magic = dataset2.groupby(["produced_at", "plantid"]).sum()

In [26]:
#magic

In [27]:
magic2 = magic[["value"]]

In [28]:
#magic2.sort_values(["produced_at", "value"])

In [29]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [30]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")
merged["revenue"] = merged["value"] * merged["price"]

In [31]:
merged_mytmp = merged[['produced_at', 'plantid', 'value', 'price', 'revenue']]

In [32]:
merged_mytmp.loc[merged_mytmp.plantid == "BB45025564"].sort_values('revenue').resample('1YE', on='produced_at').sum()

,plantid,value,price,revenue
produced_at,,,,
2024-12-31,BB45025564BB45025564BB45025564BB45025564BB4502...,9559700.0,2758598.8,8.005455e+08

In [33]:
#merged1a = merged.groupby('plantid').resample('1h', on='produced_at').mean().reset_index()

In [34]:
#merged1a.sort_values('revenue')

In [35]:
#merged

In [36]:
#production.sort_values(by=["plantid", "produced_at"])

In [37]:
#merged1a

In [38]:

#merged_tmp = merged.drop(columns=["timestamp"])
#merged1a = merged_tmp.set_index("produced_at", drop=True)

In [39]:
#merged1a = merged_tmp.set_index(['plantid']).sort_values(['plantid', 'produced_at'])

In [40]:
#merged2 = merged1a.resample("1h", on="produced_at").agg({'value':'sum', 'price':'sum', 'revenue': 'sum' })

In [41]:
#merged1a

In [42]:
#tmp1 = merged2.copy()
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [43]:
tmp1.reset_index(inplace=True)

In [44]:
revenue = tmp1[["plantid", "revenue"]]

In [45]:
tmp1

                      plantid       value      price       revenue
0            06-02-B10117A007    637346.0   689649.7  5.288343e+07
1                  BB23020490   1376356.0  2758598.8  1.086602e+08
2                  BB45025564   9559700.0  2758598.8  8.005455e+08
3                  BB45025611   7007511.0   689649.7  6.055226e+08
4                    BE166928   1171476.0  2758598.8  9.504822e+07
5                    BE169709    362015.0   689649.7  3.070577e+07
6                    BE172654   1297508.0  2758598.8  1.158482e+08
7                    BE172656    962853.0   689649.7  8.590997e+07
8   BWpf-450-1020129-00000000    593836.0  2758598.8  6.110538e+07
9   BWpf-450-1195689-00000000    205400.0  2758598.8  1.626545e+07
10  BWpf-450-1741292-00000000    487424.0  2758598.8  4.878585e+07
11  BWpf-450-2142201-00000000     20988.0  2758598.8  3.107986e+06
12  BWpf-450-2797933-00000000   2077640.0  2758598.8  1.949110e+08
13  BWpf-450-2948214-00000000   1927636.0   689649.7  1.721634e+08
14                   BYS00009    996180.0   689649.7  1.027118e+08
15                   BYS00041    758068.0   689649.7  6.431633e+07
16                   BYS00044   1075856.0  2758598.8  9.900856e+07
17                   BYS00048   3458496.0  2758598.8  3.595232e+08
18                   BYS00114    141668.0   689649.7  1.151014e+07
19                   BYS00727    154566.0   689649.7  2.284722e+07
20                 HE30001045    291623.0   689649.7  2.140724e+07
21                 MV30000226    641708.0  2758598.8  7.165928e+07
22              NI01010098080    498280.0   689649.7  4.114252e+07
23              NI01241117210    467977.0   689649.7  3.552431e+07
24              NI06060316030    934480.0  2758598.8  8.169654e+07
25              NI10257673950   2981610.0   689649.7  2.827623e+08
26              NW100-0167182   2640068.0  2758598.8  2.456223e+08
27              NW100-0229264    336060.0   689649.7  3.269475e+07
28              NW100-0248923  12631284.0   689649.7  1.093000e+09
29              NW100-0365906    392952.0   689649.7  3.694577e+07
30              NW300-0326774  10407704.0  2758598.8  9.262812e+08
31              NW300-0370387   2247607.0   689649.7  1.942240e+08
32              NW300-0877384   8193258.0   689649.7  7.522053e+08
33              NW300-0923949         0.0  2758598.8  0.000000e+00
34              NW300-9002708   1401460.0  2758598.8  1.310311e+08
35              NW300-9046030   1136896.0   689649.7  1.241809e+08
36              NW500-0342658    353192.0   689649.7  2.653052e+07
37              NW500-0915123   1999908.0  2758598.8  1.615442e+08
38              NW700-0105516    212496.0   689649.7  1.775971e+07
39              NW900-0125939    782046.0   689649.7  8.414225e+07
40              NW900-0205103    232316.0   689649.7  2.082932e+07
41              NW900-0327252    143684.0   689649.7  1.109757e+07
42              NW900-0865327      8569.0   689649.7  1.338652e+06
43              NW900-9140178   1287514.0   689649.7  1.370171e+08
44              NW900-9141660   2557468.0  2758598.8  2.492269e+08
45                  RP5000671   1868048.0  2758598.8  1.576855e+08
46                   SD661-06     16012.0   689649.7  2.357491e+06
47                   SD661-18    300566.0   689649.7  2.398127e+07
48                   SD661-94    864190.0   689649.7  7.387270e+07
49                SL0100999-G    262692.0   689649.7  2.155009e+07
50                SL0101000-G     17196.0   689649.7  1.556536e+06
51                SL0101003-G    160123.0   689649.7  1.084055e+07
52                SL0105352-G    137404.0   689649.7  1.230613e+07
53                 SN70015796  12664788.0  2758598.8  1.069532e+09
54                 SN80011277   5887548.0  2758598.8  5.327062e+08
55                   ST100125   3309276.0  2758598.8  3.006925e+08

In [46]:
#dataset.sort_values(["plantid", "produced_at"])

In [47]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [48]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [49]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2024].loc[co2s.pollutant == "CO2"]

In [50]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [51]:
co2s2

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
55,2024,BB16018798,CO2,Air,2.330000e+08,9,Mio. t,0.233,CO2 [Mio. t]
88,2024,BB23020389,CO2,Air,3.250000e+08,9,Mio. t,0.325,CO2 [Mio. t]
171,2024,BB23020490,CO2,Air,3.277000e+09,9,Mio. t,3.277,CO2 [Mio. t]
387,2024,BB23022811,CO2,Air,1.210000e+08,9,Mio. t,0.121,CO2 [Mio. t]
430,2024,BB45025564,CO2,Air,1.225700e+10,9,Mio. t,12.257,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...
15994,2024,ST18046,CO2,Air,2.210000e+08,9,Mio. t,0.221,CO2 [Mio. t]
16127,2024,TH30013152,CO2,Air,2.540000e+08,9,Mio. t,0.254,CO2 [Mio. t]
16160,2024,TH62013494,CO2,Air,1.270000e+08,9,Mio. t,0.127,CO2 [Mio. t]
16238,2024,TH72012874,CO2,Air,1.850000e+08,9,Mio. t,0.185,CO2 [Mio. t]
16273,2024,TH86012942,CO2,Air,1.070000e+08,9,Mio. t,0.107,CO2 [Mio. t]

In [52]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [53]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [54]:
tmp2 = pd.merge(tmp1, production, on="plantid")

In [55]:
tmp2 = tmp1

In [56]:
coal_cost_per_t = 103.5# or 120
co2_cost = 69 # see below
#co2_cost = 65 # alternative https://icapcarbonaction.com/system/files/ets_pdfs/icap-etsmap-factsheet-43.pdf
#electricity_price = 78.50

#https://www.unternehmensregister.de/de/publication?payload=LXxXcfbIejd_v2Be0PSDkD7vo76lhpnrWMKzXGRjUoEPqWlxLhTxwRcC1GfbHMjobv880NLL8BOogW39iTMtoYMTf3C7JceYGttc9xoAHNkSjhhA1vTajd5nW7vWDfQzL-X9mmnDwZsSkqYbE4IM92VMRa8KT7k6axrG8WFJALfV90eno0kl1qqDGUmTftPZBku3uRcZu-UGVw

In [57]:
tmp2

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2
0,BB23020490,1.086602e+08,Mineralölprodukte,1MKA,0.0,2.30,75,3.277000
1,BB45025564,8.005455e+08,Braunkohle,Kraftwerk Jänschwalde Block A,11960.0,3.25,18,12.257000
2,BB45025611,6.055226e+08,Braunkohle,Kraftwerk Schwarze Pumpe Block A,207831.0,3.25,18,8.081269
3,BE166928,9.504822e+07,Steinkohle,HKW Reuter West Dampfturbine D,63958.0,2.68,120,1.446000
4,BE169709,3.070577e+07,Erdgas,HKW Klingenberg Dampfturbine 1,82983.0,1.50,40,0.426000
5,BE172654,1.158482e+08,Erdgas,HKW Mitte Dampfturbine,79075.0,1.50,40,0.672000
6,BE172656,8.590997e+07,Erdgas,GuD Marzahn Dampfturbine,22820.0,1.50,40,0.522000
7,BWpf-450-1020129-00000000,6.110538e+07,Steinkohle,Heizkraftwerk Heilbronn FHT 1,0.0,2.68,120,0.773000
8,BWpf-450-1195689-00000000,1.626545e+07,Steinkohle,Heizkraftwerk Stuttgart-Münster DT 12,0.0,2.68,120,0.425000
9,BWpf-450-1741292-00000000,4.878585e+07,Steinkohle,Heizkraftwerk Altbach/Deizisau HKW 1,17065.0,2.68,120,0.766000
10,BWpf-450-2797933-00000000,1.949110e+08,Steinkohle,Rheinhafen- Dampfkraftwerk RDK 4S DT,0.0,2.68,120,1.973000
11,BWpf-450-2948214-00000000,1.721634e+08,Steinkohle,GKM Block 6,92027.0,2.68,120,3.145000
12,BYS00009,1.027118e+08,Steinkohle,Kraftwerk Zolling,0.0,2.68,120,0.892000
13,BYS00041,6.431633e+07,Erdgas,SWM HKW Nord 2 T20,0.0,1.50,40,1.460000
14,BYS00044,9.900856e+07,Erdgas,SWM HKW Sued GuD1 GT2,0.0,1.50,40,0.509000
15,BYS00048,3.595232e+08,Erdgas,Irsching 5 DT,0.0,1.50,40,1.290000
16,BYS00114,1.151014e+07,Erdgas,Gasturbinenanlage 12,0.0,1.50,40,0.578000
17,HE30001045,2.140724e+07,Steinkohle,Staudinger 4,0.0,2.68,120,0.552000
18,MV30000226,7.165928e+07,Steinkohle,Kraftwerk Rostock Block A,14468.0,2.68,120,0.543000
19,NI01010098080,4.114252e+07,Steinkohle,KWM Block 3,0.0,2.68,120,0.416000
20,NI01241117210,3.552431e+07,Steinkohle,DT30 GuD Süd Wolfsburg,0.0,2.68,120,0.982000
21,NI06060316030,8.169654e+07,Steinkohle,GKH 1,0.0,2.68,120,1.096000
22,NI10257673950,2.827623e+08,Erdgas,Emsland B DT,43608.0,1.50,40,1.180000
23,NW100-0167182,2.456223e+08,Erdgas,SWD KWF GTKW,0.0,1.50,40,0.983000
24,NW100-0229264,3.269475e+07,Erdgas,HKW III Block A,0.0,1.50,40,0.191000
25,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,13.379000
26,NW100-0365906,3.694577e+07,Steinkohle,Walsum 10,16300.0,2.68,120,1.329000
27,NW300-0326774,9.262812e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,11.821000
28,NW300-0370387,1.942240e+08,Erdgas,DT Niehl 2 RheinEnergie,0.0,1.50,40,1.152000
29,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,10.473000
30,NW300-0923949,0.000000e+00,Braunkohle,Block 4 Merkenich RheinEnergie,0.0,3.25,18,0.299000
31,NW300-9002708,1.310311e+08,Erdgas,Dormagen DT,0.0,1.50,40,0.673000
32,NW300-9046030,1.241809e+08,Erdgas,Knapsack I - Dampfturbine - DT 10,0.0,1.50,40,0.480000
33,NW500-0342658,2.653052e+07,Steinkohle,Scholven 1 DT,48161.0,2.68,120,0.913000
34,NW500-0915123,1.615442e+08,Steinkohle,Datteln 4,631.0,2.68,120,1.710000
35,NW700-0105516,1.775971e+07,Steinkohle,Heyden 4,0.0,2.68,120,0.343000
36,NW900-0125939,8.414225e+07,Erdgas,Cuno Heizkraftwerk Herdecke BHKW1,0.0,1.50,40,0.324000
37,NW900-0205103,2.082932e+07,Steinkohle,Bergkamen A,474.0,2.68,120,0.240000
38,NW900-0327252,1.109757e+07,Steinkohle,GuD Herne,0.0,2.68,120,0.219000
39,NW900-9140178,1.370171e+08,Erdgas,Trianel Gaskraftwerk Hamm Block 10,0.0,1.50,40,0.473000
40,NW900-9141660,2.492269e+08,Steinkohle,Trianel Kohlekraftwerk Lünen,1662.0,2.68,120,2.156000
41,RP5000671,1.576855e+08,Erdgas,GuD Mitte DT10,0.0,1.50,40,5.120000
42,SL0100999-G,2.155009e+07,Steinkohle,Bexbach,0.0,2.68,120,0.296000
43,SL0101003-G,1.084055e+07,Steinkohle,Weiher 3,0.0,2.68,120,0.195000
44,SL0105352-G,1.230613e+07,Erdgas,Dampfturbinenanlage DT3,0.0,1.50,40,0.103000
45,SN70015796,1.069532e+09,Braunkohle,Boxberg Block N,6085.0,3.25,18,13.836000
46,SN80011277,5.327062e+08,Braunkohle,Kraftwerk Lippendorf Block S,43457.0,3.25,18,5.731000
47,ST100125,3.006925e+08,Braunkohle,Schkopau A,15250.0,3.25,18,4.310000

In [58]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [59]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [70]:
analysis = tmp2[(tmp2.plantname == "Neurath F") | (tmp2.plantname == "Weisweiler F") | (tmp2.plantname == "Niederaußem G")]

In [71]:
analysis

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2,co2_cost,coal_cost,profit
25,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,13.379,922.943931,74.099077,95.956922
27,NW300-0326774,9.262812e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,11.821,813.852171,65.470154,46.958842
29,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,10.473,721.793613,58.004308,-27.592588

In [65]:
tmp2.sort_values('coal_cost', ascending=False)

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2,co2_cost,coal_cost,profit
11,BWpf-450-2948214-00000000,1.721634e+08,Steinkohle,GKM Block 6,92027.0,2.68,120,3.145000,210.655137,140.820896,-179.312603
41,RP5000671,1.576855e+08,Erdgas,GuD Mitte DT10,0.0,1.50,40,5.120000,353.280000,136.533333,-332.127784
0,BB23020490,1.086602e+08,Mineralölprodukte,1MKA,0.0,2.30,75,3.277000,226.113000,106.858696,-224.311473
40,NW900-9141660,2.492269e+08,Steinkohle,Trianel Kohlekraftwerk Lünen,1662.0,2.68,120,2.156000,148.649322,96.537313,4.040292
10,BWpf-450-2797933-00000000,1.949110e+08,Steinkohle,Rheinhafen- Dampfkraftwerk RDK 4S DT,0.0,2.68,120,1.973000,136.137000,88.343284,-29.569291
45,SN70015796,1.069532e+09,Braunkohle,Boxberg Block N,6085.0,3.25,18,13.836000,954.264135,76.630154,38.638132
34,NW500-0915123,1.615442e+08,Steinkohle,Datteln 4,631.0,2.68,120,1.710000,117.946461,76.567164,-32.969410
25,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,13.379000,922.943931,74.099077,95.956922
1,BB45025564,8.005455e+08,Braunkohle,Kraftwerk Jänschwalde Block A,11960.0,3.25,18,12.257000,844.907760,67.884923,-112.247154
27,NW300-0326774,9.262812e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,11.821000,813.852171,65.470154,46.958842
3,BE166928,9.504822e+07,Steinkohle,HKW Reuter West Dampfturbine D,63958.0,2.68,120,1.446000,95.360898,64.746269,-65.058945
26,NW100-0365906,3.694577e+07,Steinkohle,Walsum 10,16300.0,2.68,120,1.329000,90.576300,59.507463,-113.137990
29,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,10.473000,721.793613,58.004308,-27.592588
21,NI06060316030,8.169654e+07,Steinkohle,GKH 1,0.0,2.68,120,1.096000,75.624000,49.074627,-43.002088
2,BB45025611,6.055226e+08,Braunkohle,Kraftwerk Schwarze Pumpe Block A,207831.0,3.25,18,8.081269,543.267222,44.757798,17.497624
20,NI01241117210,3.552431e+07,Steinkohle,DT30 GuD Süd Wolfsburg,0.0,2.68,120,0.982000,67.758000,43.970149,-76.203836
33,NW500-0342658,2.653052e+07,Steinkohle,Scholven 1 DT,48161.0,2.68,120,0.913000,59.673891,40.880597,-74.023966
12,BYS00009,1.027118e+08,Steinkohle,Kraftwerk Zolling,0.0,2.68,120,0.892000,61.548000,39.940299,1.223550
13,BYS00041,6.431633e+07,Erdgas,SWM HKW Nord 2 T20,0.0,1.50,40,1.460000,100.740000,38.933333,-75.357001
7,BWpf-450-1020129-00000000,6.110538e+07,Steinkohle,Heizkraftwerk Heilbronn FHT 1,0.0,2.68,120,0.773000,53.337000,34.611940,-26.843562
15,BYS00048,3.595232e+08,Erdgas,Irsching 5 DT,0.0,1.50,40,1.290000,89.010000,34.400000,236.113220
9,BWpf-450-1741292-00000000,4.878585e+07,Steinkohle,Heizkraftwerk Altbach/Deizisau HKW 1,17065.0,2.68,120,0.766000,51.676515,34.298507,-37.189168
46,SN80011277,5.327062e+08,Braunkohle,Kraftwerk Lippendorf Block S,43457.0,3.25,18,5.731000,392.440467,31.740923,108.524848
22,NI10257673950,2.827623e+08,Erdgas,Emsland B DT,43608.0,1.50,40,1.180000,78.411048,31.466667,172.884594
28,NW300-0370387,1.942240e+08,Erdgas,DT Niehl 2 RheinEnergie,0.0,1.50,40,1.152000,79.488000,30.720000,84.015969
23,NW100-0167182,2.456223e+08,Erdgas,SWD KWF GTKW,0.0,1.50,40,0.983000,67.827000,26.213333,151.581937
17,HE30001045,2.140724e+07,Steinkohle,Staudinger 4,0.0,2.68,120,0.552000,38.088000,24.716418,-41.397178
18,MV30000226,7.165928e+07,Steinkohle,Kraftwerk Rostock Block A,14468.0,2.68,120,0.543000,36.468708,24.313433,10.877141
47,ST100125,3.006925e+08,Braunkohle,Schkopau A,15250.0,3.25,18,4.310000,296.337750,23.870769,-19.516065
8,BWpf-450-1195689-00000000,1.626545e+07,Steinkohle,Heizkraftwerk Stuttgart-Münster DT 12,0.0,2.68,120,0.425000,29.325000,19.029851,-32.089402
19,NI01010098080,4.114252e+07,Steinkohle,KWM Block 3,0.0,2.68,120,0.416000,28.704000,18.626866,-6.188350
31,NW300-9002708,1.310311e+08,Erdgas,Dormagen DT,0.0,1.50,40,0.673000,46.437000,17.946667,66.647441
5,BE172654,1.158482e+08,Erdgas,HKW Mitte Dampfturbine,79075.0,1.50,40,0.672000,40.911825,17.920000,57.016360
16,BYS00114,1.151014e+07,Erdgas,Gasturbinenanlage 12,0.0,1.50,40,0.578000,39.882000,15.413333,-43.785189
35,NW700-0105516,1.775971e+07,Steinkohle,Heyden 4,0.0,2.68,120,0.343000,23.667000,15.358209,-21.265500
6,BE172656,8.590997e+07,Erdgas,GuD Marzahn Dampfturbine,22820.0,1.50,40,0.522000,34.443420,13.920000,37.546545
14,BYS00044,9.900856e+07,Erdgas,SWM HKW Sued GuD1 GT2,0.0,1.50,40,0.509000,35.121000,13.573333,50.314222
42,SL0100999-G,2.155009e+07,Steinkohle,Bexbach,0.0,2.68,120,0.296000,20.424000,13.253731,-12.127637
32,NW300-9046030,1.241809e+08,Erdgas,Knapsack I - Dampfturbine - DT 10,0.0,1.50,40,0.480000,33.120000,12.800000,78.260906
39,NW900-9140178,1.370171e+08,Erdgas,Trianel Gaskraftwerk Hamm Block 10,0.0,1.50,40,0.473000,32.637000,12.613333,91.766734
4,BE169709,3.070577e+07,Erdgas,HKW Klingenberg Dampfturbine 1,82983.0,1.50,40,0.426000,23.668173,11.360000,-4.322406
37,NW900-0205103,2.082932e+07,Steinkohle,Bergkamen A,474.0,2.68,120,0.240000,16.527294,10.746269,-6.444239
38,NW900-0327252,1.109757e+07,Steinkohle,GuD Herne,0.0,2.68,120,0.219000,15.111000,9.805970,-13.819402
43,SL0101003-G,1.084055e+07,Steinkohle,Weiher 3,0.0,2.68,120,0.195000,13.455000,8.731343,-11.345793
36,NW900-0125939,8.414225e+07,Erdgas,Cuno Heizkraftwerk Herdecke BHKW1,0.0,1.50,40,0.324000,22.356000,8.640000,53.146254
24,NW100-0229264,3.269475e+07,Erdgas,HKW III Block A,0.0,1.50,40,0.191000,13.179000,5.093333,14.422416
44,SL0105352-G,1.230613e+07,Erdgas,Dampfturbinenanlage DT3,0.0,1.50,40,0.103000,7.107000,2.746667,2.452462
30,NW300-0923949,0.000000e+00,Braunkohle,Block 4 Merkenich RheinEnergie,0.0,3.25,18,0.299000,20.631000,1.656000,-22.287000

In [61]:
#tmp2.sort_values(by="free_co2s", ascending=False)

In [62]:
profit = tmp2[["plantid", "plantname", "revenue", "profit"]]
profit["revenue"] = profit["revenue"].apply(lambda x: x / 10**6)

In [63]:
profit.sort_values("profit", ascending=False)

,plantid,plantname,revenue,profit
15,BYS00048,Irsching 5 DT,359.523220,236.113220
22,NI10257673950,Emsland B DT,282.762309,172.884594
23,NW100-0167182,SWD KWF GTKW,245.622271,151.581937
46,SN80011277,Kraftwerk Lippendorf Block S,532.706238,108.524848
25,NW100-0248923,Neurath F,1092.999930,95.956922
39,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,137.017067,91.766734
28,NW300-0370387,DT Niehl 2 RheinEnergie,194.223969,84.015969
32,NW300-9046030,Knapsack I - Dampfturbine - DT 10,124.180906,78.260906
31,NW300-9002708,Dormagen DT,131.031108,66.647441
5,BE172654,HKW Mitte Dampfturbine,115.848185,57.016360
36,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,84.142254,53.146254
14,BYS00044,SWM HKW Sued GuD1 GT2,99.008555,50.314222
27,NW300-0326774,Niederaußem G,926.281167,46.958842
45,SN70015796,Boxberg Block N,1069.532421,38.638132
6,BE172656,GuD Marzahn Dampfturbine,85.909965,37.546545
2,BB45025611,Kraftwerk Schwarze Pumpe Block A,605.522644,17.497624
24,NW100-0229264,HKW III Block A,32.694750,14.422416
18,MV30000226,Kraftwerk Rostock Block A,71.659282,10.877141
40,NW900-9141660,Trianel Kohlekraftwerk Lünen,249.226927,4.040292
44,SL0105352-G,Dampfturbinenanlage DT3,12.306129,2.452462
12,BYS00009,Kraftwerk Zolling,102.711849,1.223550
4,BE169709,HKW Klingenberg Dampfturbine 1,30.705767,-4.322406
19,NI01010098080,KWM Block 3,41.142516,-6.188350
37,NW900-0205103,Bergkamen A,20.829323,-6.444239
43,SL0101003-G,Weiher 3,10.840551,-11.345793
42,SL0100999-G,Bexbach,21.550094,-12.127637
38,NW900-0327252,GuD Herne,11.097568,-13.819402
47,ST100125,Schkopau A,300.692454,-19.516065
35,NW700-0105516,Heyden 4,17.759709,-21.265500
30,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-22.287000
7,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,61.105379,-26.843562
29,NW300-0877384,Weisweiler F,752.205333,-27.592588
10,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,194.910993,-29.569291
8,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,16.265449,-32.089402
34,NW500-0915123,Datteln 4,161.544215,-32.969410
9,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,48.785854,-37.189168
17,HE30001045,Staudinger 4,21.407240,-41.397178
21,NI06060316030,GKH 1,81.696539,-43.002088
16,BYS00114,Gasturbinenanlage 12,11.510145,-43.785189
3,BE166928,HKW Reuter West Dampfturbine D,95.048222,-65.058945
33,NW500-0342658,Scholven 1 DT,26.530522,-74.023966
13,BYS00041,SWM HKW Nord 2 T20,64.316332,-75.357001
20,NI01241117210,DT30 GuD Süd Wolfsburg,35.524314,-76.203836
1,BB45025564,Kraftwerk Jänschwalde Block A,800.545529,-112.247154
26,NW100-0365906,Walsum 10,36.945773,-113.137990
11,BWpf-450-2948214-00000000,GKM Block 6,172.163429,-179.312603
0,BB23020490,1MKA,108.660223,-224.311473
41,RP5000671,GuD Mitte DT10,157.685550,-332.127784

In [64]:
profit.sort_values("profit", ascending=False)

,plantid,plantname,revenue,profit
15,BYS00048,Irsching 5 DT,359.523220,241.273220
22,NI10257673950,Emsland B DT,282.762309,177.430162
23,NW100-0167182,SWD KWF GTKW,245.622271,155.513937
25,NW100-0248923,Neurath F,1092.999930,149.460918
46,SN80011277,Kraftwerk Lippendorf Block S,532.706238,131.275020
27,NW300-0326774,Niederaußem G,926.281167,94.138678
45,SN70015796,Boxberg Block N,1069.532421,93.957792
39,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,137.017067,93.658734
28,NW300-0370387,DT Niehl 2 RheinEnergie,194.223969,88.623969
32,NW300-9046030,Knapsack I - Dampfturbine - DT 10,124.180906,80.180906
31,NW300-9002708,Dormagen DT,131.031108,69.339441
5,BE172654,HKW Mitte Dampfturbine,115.848185,59.388060
36,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,84.142254,54.442254
14,BYS00044,SWM HKW Sued GuD1 GT2,99.008555,52.350222
2,BB45025611,Kraftwerk Schwarze Pumpe Block A,605.522644,48.991376
6,BE172656,GuD Marzahn Dampfturbine,85.909965,39.543265
24,NW100-0229264,HKW III Block A,32.694750,15.186416
29,NW300-0877384,Weisweiler F,752.205333,14.250520
18,MV30000226,Kraftwerk Rostock Block A,71.659282,12.991269
40,NW900-9141660,Trianel Kohlekraftwerk Lünen,249.226927,12.657644
12,BYS00009,Kraftwerk Zolling,102.711849,4.791550
44,SL0105352-G,Dampfturbinenanlage DT3,12.306129,2.864462
47,ST100125,Schkopau A,300.692454,-2.337065
4,BE169709,HKW Klingenberg Dampfturbine 1,30.705767,-2.950338
19,NI01010098080,KWM Block 3,41.142516,-4.524350
37,NW900-0205103,Bergkamen A,20.829323,-5.486135
43,SL0101003-G,Weiher 3,10.840551,-10.565793
42,SL0100999-G,Bexbach,21.550094,-10.943637
38,NW900-0327252,GuD Herne,11.097568,-12.943402
35,NW700-0105516,Heyden 4,17.759709,-19.893500
30,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-21.091000
10,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,194.910993,-21.677291
7,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,61.105379,-23.751562
34,NW500-0915123,Datteln 4,161.544215,-26.131934
8,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,16.265449,-30.389402
9,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,48.785854,-34.193428
21,NI06060316030,GKH 1,81.696539,-38.618088
17,HE30001045,Staudinger 4,21.407240,-39.189178
16,BYS00114,Gasturbinenanlage 12,11.510145,-41.473189
3,BE166928,HKW Reuter West Dampfturbine D,95.048222,-59.530777
1,BB45025564,Kraftwerk Jänschwalde Block A,800.545529,-63.266994
13,BYS00041,SWM HKW Nord 2 T20,64.316332,-69.517001
33,NW500-0342658,Scholven 1 DT,26.530522,-70.564610
20,NI01241117210,DT30 GuD Süd Wolfsburg,35.524314,-72.275836
26,NW100-0365906,Walsum 10,36.945773,-107.887190
11,BWpf-450-2948214-00000000,GKM Block 6,172.163429,-167.100711
0,BB23020490,1MKA,108.660223,-211.203473
41,RP5000671,GuD Mitte DT10,157.685550,-311.647784

In [66]:
#profit_combined = pd.concat([profit, profit2])

In [67]:
#profit_final = profit_combined.drop_duplicates(subset="plantid", keep="first").sort_values('profit')

In [68]:
profit.to_csv("profit.csv", index=False)

In [ ]:
pd.concat([profit2, profit, profit]).drop_duplicates(keep=False)

In [ ]:
#profit_final.reset_index()

In [ ]:
pd.concat([profit, profit2, profit2]).drop_duplicates(keep=False).sort_values('profit', ascending=False)

In [ ]:
#profit2 = profit

In [ ]:
profit2.sort_values("profit", ascending=False)