In [1]:
import pandas as pd
from helpers import get_factor, get_price

In [2]:
CDF = pd.read_csv("../production/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

/tmp/ipykernel_1385580/3001582791.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [3]:
smard = pd.read_csv("Gro_handelspreise_202401010000_202501010000_Stunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

/tmp/ipykernel_1385580/2825335293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
/tmp/ipykernel_1385580/2825335293.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [4]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [5]:
CDF2 = CDF.loc[CDF.produced_at > "2023-12-31 23:50"].loc[CDF.produced_at < "2025-01-01 00:00"]

In [6]:
dataset = CDF2.merge(seem, left_on="variable", right_on="sseid")

In [7]:
magic = dataset.groupby(["produced_at", "plantid"]).sum()

In [8]:
magic2 = magic[["value"]]

In [9]:
#magic2.sort_values(["produced_at", "value"])

In [10]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [11]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")

In [12]:
merged["revenue"] = merged["value"] * merged["price"]
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [13]:
tmp1.reset_index(inplace=True)

In [14]:
revenue = tmp1[["plantid", "revenue"]]

In [17]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [18]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [19]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2023].loc[co2s.pollutant == "CO2"]

In [20]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [21]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [22]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [25]:
tmp2 = tmp1

In [26]:
#tmp2

In [27]:
coal_cost_per_t = 103.5 or 120
co2_cost = 70
#electricity_price = 78.50

In [28]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [29]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [30]:
co2s3.dtypes

plantid      object
amount_2    float64
dtype: object

In [31]:
tmp2.sort_values("profit")

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2,co2_cost,coal_cost,profit
1,BB45025564,7.982573e+08,Braunkohle,Kraftwerk Jänschwalde Block A,11960.0,3.25,18,14.134000,988.542800,78.280615,-268.566091
12,BWpf-450-2948214-00000000,1.721634e+08,Steinkohle,GKM Block 6,92027.0,2.68,120,3.430000,233.658110,153.582090,-215.076770
0,BB23020490,1.093048e+08,Mineralölprodukte,1MKA,0.0,2.30,75,3.015000,211.050000,98.315217,-200.060395
32,NW500-0342658,2.653052e+07,Steinkohle,Scholven 1 DT,48161.0,2.68,120,1.993000,136.138730,89.238806,-198.847014
33,NW500-0915123,1.619746e+08,Steinkohle,Datteln 4,631.0,2.68,120,2.945000,206.105830,131.865672,-175.996855
11,BWpf-450-2797933-00000000,1.932364e+08,Steinkohle,Rheinhafen- Dampfkraftwerk RDK 4S DT,0.0,2.68,120,3.185000,222.950000,142.611940,-172.325495
24,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,16.485000,1153.739930,91.301538,-152.041538
19,NI01241117210,3.552431e+07,Steinkohle,DT30 GuD Süd Wolfsburg,0.0,2.68,120,1.429000,100.030000,63.985075,-128.490761
17,MV30000226,7.126096e+07,Steinkohle,Kraftwerk Rostock Block A,14468.0,2.68,120,1.728000,119.947240,77.373134,-126.059416
2,BB45025611,6.055226e+08,Braunkohle,Kraftwerk Schwarze Pumpe Block A,207831.0,3.25,18,9.713000,665.361830,53.795077,-113.634263
25,NW100-0365906,3.694577e+07,Steinkohle,Walsum 10,16300.0,2.68,120,1.244000,85.939000,55.701493,-104.694719
34,NW700-0105516,1.775971e+07,Steinkohle,Heyden 4,0.0,2.68,120,1.046000,73.220000,46.835821,-102.296112
16,HE30001045,2.140724e+07,Steinkohle,Staudinger 4,0.0,2.68,120,0.967000,67.690000,43.298507,-89.581268
26,NW300-0326774,9.212323e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,13.311000,929.947130,73.722462,-82.437330
3,BE166928,9.494364e+07,Steinkohle,HKW Reuter West Dampfturbine D,63958.0,2.68,120,1.547000,103.812940,69.268657,-78.137956
37,NW900-0327252,1.109757e+07,Steinkohle,GuD Herne,0.0,2.68,120,0.763000,53.410000,34.164179,-76.476611
36,NW900-0205103,2.082932e+07,Steinkohle,Bergkamen A,474.0,2.68,120,0.808000,56.526820,36.179104,-71.876601
20,NI06060316030,8.229311e+07,Steinkohle,GKH 1,0.0,2.68,120,1.286000,90.020000,57.582090,-65.308977
40,SL0100999-G,2.155009e+07,Steinkohle,Bexbach,0.0,2.68,120,0.755000,52.850000,33.805970,-65.105876
42,SL0101003-G,1.084055e+07,Steinkohle,Weiher 3,0.0,2.68,120,0.653000,45.710000,29.238806,-64.108255
9,BWpf-450-1741292-00000000,4.850663e+07,Steinkohle,Heizkraftwerk Altbach/Deizisau HKW 1,17065.0,2.68,120,0.904000,62.085450,40.477612,-54.056428
15,BYS00114,1.151014e+07,Erdgas,Gasturbinenanlage 12,0.0,1.50,40,0.617000,43.190000,16.453333,-48.133189
8,BWpf-450-1195689-00000000,1.711508e+07,Steinkohle,Heizkraftwerk Stuttgart-Münster DT 12,0.0,2.68,120,0.448000,31.360000,20.059701,-34.304626
45,SN80011277,5.286458e+08,Braunkohle,Kraftwerk Lippendorf Block S,43457.0,3.25,18,7.443000,517.968010,41.222769,-30.544987
18,NI01010098080,4.114252e+07,Steinkohle,KWM Block 3,0.0,2.68,120,0.579000,40.530000,25.925373,-25.312857
29,NW300-0923949,0.000000e+00,Braunkohle,Block 4 Merkenich RheinEnergie,0.0,3.25,18,0.280000,19.600000,1.550769,-21.150769
41,SL0101000-G,1.556536e+06,Steinkohle,Gasmotor 1 Mod.,0.0,2.68,120,0.132000,9.240000,5.910448,-13.593911
10,BWpf-450-2142201-00000000,3.174966e+06,Steinkohle,Kraftwerk Walheim Block 2,0.0,2.68,120,0.113000,7.910000,5.059701,-9.794735
4,BE169709,3.070577e+07,Erdgas,HKW Klingenberg Dampfturbine 1,82983.0,1.50,40,0.407000,22.681190,10.853333,-2.828756
43,SL0105352-G,1.230613e+07,Erdgas,Dampfturbinenanlage DT3,0.0,1.50,40,0.103000,7.210000,2.746667,2.349462
39,NW900-9141660,2.497194e+08,Steinkohle,Trianel Kohlekraftwerk Lünen,1662.0,2.68,120,2.146000,150.103660,96.089552,3.526173
46,ST100125,3.009824e+08,Braunkohle,Schkopau A,15250.0,3.25,18,3.942000,274.872500,21.832615,4.277259
7,BWpf-450-1020129-00000000,5.957858e+07,Steinkohle,Heizkraftwerk Heilbronn FHT 1,0.0,2.68,120,0.425000,29.750000,19.029851,10.798729
23,NW100-0229264,3.269475e+07,Erdgas,HKW III Block A,0.0,1.50,40,0.201637,14.114590,5.376987,13.203173
6,BE172656,8.590997e+07,Erdgas,GuD Marzahn Dampfturbine,22820.0,1.50,40,0.584000,39.282600,15.573333,31.054032
28,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,9.336000,652.664390,51.707077,47.833866
5,BE172654,1.153207e+08,Erdgas,HKW Mitte Dampfturbine,79075.0,1.50,40,0.696000,43.184750,18.560000,53.575984
35,NW900-0125939,8.414225e+07,Erdgas,Cuno Heizkraftwerk Herdecke BHKW1,0.0,1.50,40,0.241000,16.870000,6.426667,60.845587
13,BYS00044,9.903749e+07,Erdgas,SWM HKW Sued GuD1 GT2,0.0,1.50,40,0.387000,27.090000,10.320000,61.627495
30,NW300-9002708,1.312524e+08,Erdgas,Dormagen DT,0.0,1.50,40,0.702474,49.173194,18.732645,63.346521
44,SN70015796,1.065023e+09,Braunkohle,Boxberg Block N,6085.0,3.25,18,13.088000,915.734050,72.487385,76.801127
27,NW300-0370387,1.942240e+08,Erdgas,DT Niehl 2 RheinEnergie,0.0,1.50,40,1.023000,71.610000,27.280000,95.333969
38,NW900-9140178,1.370171e+08,Erdgas,Trianel Gaskraftwerk Hamm Block 10,0.0,1.50,40,0.344000,24.080000,9.173333,103.763734
21,NI10257673950,2.827623e+08,Erdgas,Emsland B DT,43608.0,1.50,40,1.436000,97.467440,38.293333,147.001535
22,NW100-0167182,2.446624e+08,Erdgas,SWD KWF GTKW,0.0,1.50,40,0.897000,62.790000,23.920000,157.952389
31,NW300-9046030,2.138355e+08,Erdgas,Knapsack I - Dampfturbine - DT 10,0.0,1.50,40,0.377000,26.390000,10.053333,177.392174
14,BYS00048,3.586528e+08,Erdgas,Irsching 5 DT,0.0,1.50,40,1.130000,79.100000,30.133333,249.419507

In [32]:
#tmp2["profit_adj"] = (tmp2["revenue"] * 1.10) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [33]:
tmp2.sort_values("profit")

,plantid,revenue,energysource,plantname,free_co2s,factor,fuel_price,amount_2,co2_cost,coal_cost,profit
1,BB45025564,7.982573e+08,Braunkohle,Kraftwerk Jänschwalde Block A,11960.0,3.25,18,14.134000,988.542800,78.280615,-268.566091
12,BWpf-450-2948214-00000000,1.721634e+08,Steinkohle,GKM Block 6,92027.0,2.68,120,3.430000,233.658110,153.582090,-215.076770
0,BB23020490,1.093048e+08,Mineralölprodukte,1MKA,0.0,2.30,75,3.015000,211.050000,98.315217,-200.060395
32,NW500-0342658,2.653052e+07,Steinkohle,Scholven 1 DT,48161.0,2.68,120,1.993000,136.138730,89.238806,-198.847014
33,NW500-0915123,1.619746e+08,Steinkohle,Datteln 4,631.0,2.68,120,2.945000,206.105830,131.865672,-175.996855
11,BWpf-450-2797933-00000000,1.932364e+08,Steinkohle,Rheinhafen- Dampfkraftwerk RDK 4S DT,0.0,2.68,120,3.185000,222.950000,142.611940,-172.325495
24,NW100-0248923,1.093000e+09,Braunkohle,Neurath F,3001.0,3.25,18,16.485000,1153.739930,91.301538,-152.041538
19,NI01241117210,3.552431e+07,Steinkohle,DT30 GuD Süd Wolfsburg,0.0,2.68,120,1.429000,100.030000,63.985075,-128.490761
17,MV30000226,7.126096e+07,Steinkohle,Kraftwerk Rostock Block A,14468.0,2.68,120,1.728000,119.947240,77.373134,-126.059416
2,BB45025611,6.055226e+08,Braunkohle,Kraftwerk Schwarze Pumpe Block A,207831.0,3.25,18,9.713000,665.361830,53.795077,-113.634263
25,NW100-0365906,3.694577e+07,Steinkohle,Walsum 10,16300.0,2.68,120,1.244000,85.939000,55.701493,-104.694719
34,NW700-0105516,1.775971e+07,Steinkohle,Heyden 4,0.0,2.68,120,1.046000,73.220000,46.835821,-102.296112
16,HE30001045,2.140724e+07,Steinkohle,Staudinger 4,0.0,2.68,120,0.967000,67.690000,43.298507,-89.581268
26,NW300-0326774,9.212323e+08,Braunkohle,Niederaußem G,26041.0,3.25,18,13.311000,929.947130,73.722462,-82.437330
3,BE166928,9.494364e+07,Steinkohle,HKW Reuter West Dampfturbine D,63958.0,2.68,120,1.547000,103.812940,69.268657,-78.137956
37,NW900-0327252,1.109757e+07,Steinkohle,GuD Herne,0.0,2.68,120,0.763000,53.410000,34.164179,-76.476611
36,NW900-0205103,2.082932e+07,Steinkohle,Bergkamen A,474.0,2.68,120,0.808000,56.526820,36.179104,-71.876601
20,NI06060316030,8.229311e+07,Steinkohle,GKH 1,0.0,2.68,120,1.286000,90.020000,57.582090,-65.308977
40,SL0100999-G,2.155009e+07,Steinkohle,Bexbach,0.0,2.68,120,0.755000,52.850000,33.805970,-65.105876
42,SL0101003-G,1.084055e+07,Steinkohle,Weiher 3,0.0,2.68,120,0.653000,45.710000,29.238806,-64.108255
9,BWpf-450-1741292-00000000,4.850663e+07,Steinkohle,Heizkraftwerk Altbach/Deizisau HKW 1,17065.0,2.68,120,0.904000,62.085450,40.477612,-54.056428
15,BYS00114,1.151014e+07,Erdgas,Gasturbinenanlage 12,0.0,1.50,40,0.617000,43.190000,16.453333,-48.133189
8,BWpf-450-1195689-00000000,1.711508e+07,Steinkohle,Heizkraftwerk Stuttgart-Münster DT 12,0.0,2.68,120,0.448000,31.360000,20.059701,-34.304626
45,SN80011277,5.286458e+08,Braunkohle,Kraftwerk Lippendorf Block S,43457.0,3.25,18,7.443000,517.968010,41.222769,-30.544987
18,NI01010098080,4.114252e+07,Steinkohle,KWM Block 3,0.0,2.68,120,0.579000,40.530000,25.925373,-25.312857
29,NW300-0923949,0.000000e+00,Braunkohle,Block 4 Merkenich RheinEnergie,0.0,3.25,18,0.280000,19.600000,1.550769,-21.150769
41,SL0101000-G,1.556536e+06,Steinkohle,Gasmotor 1 Mod.,0.0,2.68,120,0.132000,9.240000,5.910448,-13.593911
10,BWpf-450-2142201-00000000,3.174966e+06,Steinkohle,Kraftwerk Walheim Block 2,0.0,2.68,120,0.113000,7.910000,5.059701,-9.794735
4,BE169709,3.070577e+07,Erdgas,HKW Klingenberg Dampfturbine 1,82983.0,1.50,40,0.407000,22.681190,10.853333,-2.828756
43,SL0105352-G,1.230613e+07,Erdgas,Dampfturbinenanlage DT3,0.0,1.50,40,0.103000,7.210000,2.746667,2.349462
39,NW900-9141660,2.497194e+08,Steinkohle,Trianel Kohlekraftwerk Lünen,1662.0,2.68,120,2.146000,150.103660,96.089552,3.526173
46,ST100125,3.009824e+08,Braunkohle,Schkopau A,15250.0,3.25,18,3.942000,274.872500,21.832615,4.277259
7,BWpf-450-1020129-00000000,5.957858e+07,Steinkohle,Heizkraftwerk Heilbronn FHT 1,0.0,2.68,120,0.425000,29.750000,19.029851,10.798729
23,NW100-0229264,3.269475e+07,Erdgas,HKW III Block A,0.0,1.50,40,0.201637,14.114590,5.376987,13.203173
6,BE172656,8.590997e+07,Erdgas,GuD Marzahn Dampfturbine,22820.0,1.50,40,0.584000,39.282600,15.573333,31.054032
28,NW300-0877384,7.522053e+08,Braunkohle,Weisweiler F,12223.0,3.25,18,9.336000,652.664390,51.707077,47.833866
5,BE172654,1.153207e+08,Erdgas,HKW Mitte Dampfturbine,79075.0,1.50,40,0.696000,43.184750,18.560000,53.575984
35,NW900-0125939,8.414225e+07,Erdgas,Cuno Heizkraftwerk Herdecke BHKW1,0.0,1.50,40,0.241000,16.870000,6.426667,60.845587
13,BYS00044,9.903749e+07,Erdgas,SWM HKW Sued GuD1 GT2,0.0,1.50,40,0.387000,27.090000,10.320000,61.627495
30,NW300-9002708,1.312524e+08,Erdgas,Dormagen DT,0.0,1.50,40,0.702474,49.173194,18.732645,63.346521
44,SN70015796,1.065023e+09,Braunkohle,Boxberg Block N,6085.0,3.25,18,13.088000,915.734050,72.487385,76.801127
27,NW300-0370387,1.942240e+08,Erdgas,DT Niehl 2 RheinEnergie,0.0,1.50,40,1.023000,71.610000,27.280000,95.333969
38,NW900-9140178,1.370171e+08,Erdgas,Trianel Gaskraftwerk Hamm Block 10,0.0,1.50,40,0.344000,24.080000,9.173333,103.763734
21,NI10257673950,2.827623e+08,Erdgas,Emsland B DT,43608.0,1.50,40,1.436000,97.467440,38.293333,147.001535
22,NW100-0167182,2.446624e+08,Erdgas,SWD KWF GTKW,0.0,1.50,40,0.897000,62.790000,23.920000,157.952389
31,NW300-9046030,2.138355e+08,Erdgas,Knapsack I - Dampfturbine - DT 10,0.0,1.50,40,0.377000,26.390000,10.053333,177.392174
14,BYS00048,3.586528e+08,Erdgas,Irsching 5 DT,0.0,1.50,40,1.130000,79.100000,30.133333,249.419507