In [143]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, DateTime
import psycopg
import time

In [144]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [145]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [146]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [147]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
plantslist = list(set(bpm['plantid'].to_list()))
plantslist.sort()

In [148]:
"06-08-2948214" in plantslist

True

In [149]:
#plantslist

In [150]:
#plantslist.remove('661-94')
#plantslist.remove('661-10')

#plantslist.remove('07-05-8290552')
#plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [151]:
#refpl = "03-01-01241117210.csv"

In [152]:
#df = pd.read_csv("./combined/" + refpl)

In [153]:
#df

In [154]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [155]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [156]:
testdf = pd.read_csv("./combined/" + "06-09-100-0003-0003" + ".csv")

In [157]:
nd = "01.01.2023 00:00"

In [158]:
datetime.strptime(nd, "%d.%m.%Y %H:%M")

datetime.datetime(2023, 1, 1, 0, 0)

In [159]:
arr = [nd, "2022-12-31 23:15:00", "2021-12-24 08:00:00", '29.04.2023 12:00', '01.01.2023 00:00']

In [160]:
list(map(lambda x: fix_date(x), arr))

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2022, 12, 31, 23, 15),
 datetime.datetime(2021, 12, 24, 8, 0),
 datetime.datetime(2023, 4, 29, 12, 0),
 datetime.datetime(2023, 1, 1, 0, 0)]

In [161]:
fix_date(nd)

datetime.datetime(2023, 1, 1, 0, 0)

In [162]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [163]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [164]:
#engine = create_engine('sqlite://', echo=False)

In [165]:
#2023-12-31 19:00:00.000000

In [166]:
#melt.dtypes

In [167]:
testdf.iloc[70128]

produced_at        01.01.2023 00:00
SEE949509046600                   0
SEE918648599230                   0
SEE958847865460                   0
Name: 70128, dtype: object

In [168]:
#testdf['produced_at'] = testdf['produced_at'].map(return_date)

In [169]:
#testdf['produced_at'] = pd.to_datetime(testdf['produced_at'])

In [170]:
#df.dtypes

In [171]:
#df.iloc[70128]

In [177]:
#connection = engine2.connect()
#with engine2.begin() as connection:
plant = "06-05-300-9046030"

df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])
df.drop_duplicates(subset='produced_at', inplace=True)
#melt = df.melt(id_vars='produced_at')
#melt.drop('index', axis=1, inplace=True)
#res = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

In [178]:
#res

In [179]:
melt

               produced_at         variable  value
0      2015-01-01 00:00:00  SEE950675787617      0
1      2015-01-01 01:00:00  SEE950675787617      0
2      2015-01-01 02:00:00  SEE950675787617      0
3      2015-01-01 03:00:00  SEE950675787617      0
4      2015-01-01 04:00:00  SEE950675787617      0
...                    ...              ...    ...
122717 2021-12-31 19:00:00  SEE983645175053      0
122718 2021-12-31 20:00:00  SEE983645175053      0
122719 2021-12-31 21:00:00  SEE983645175053      0
122720 2021-12-31 22:00:00  SEE983645175053      0
122721 2021-12-31 23:00:00  SEE983645175053      0

[122722 rows x 3 columns]

In [180]:
melt.dtypes

produced_at    datetime64[ns]
variable               object
value                   int64
dtype: object

In [182]:
counter = 0
for plant in plantslist:
    #if plant == '06-05-300-9046030':
    #    continue
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        try: #, format='%d.%m.%Y %H:%M'
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = df['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df['produced_at'] = df['produced_at'].map(return_date)
        except ValueError:
            print(plant + "\nfaulty")
            #df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = pd.to_datetime(df['produced_at'])
            #print(df)
            continue
            #pass
        melt = df.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

06-05-100-0081105
faulty
06-05-900-0125939
faulty
06-08-2142201
faulty
06-09-100-0003-0003
faulty
07-05-8290552
faulty
661-18
faulty
661-94
faulty
66

In [183]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [189]:
df

,produced_at,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972
0,2015-01-01 00:00:00,0,0,0,0,0
1,2015-01-01 01:00:00,0,0,0,0,0
2,2015-01-01 02:00:00,0,0,0,0,0
3,2015-01-01 03:00:00,0,0,0,0,0
4,2015-01-01 04:00:00,0,0,0,0,0
...,...,...,...,...,...,...
87668,2024-12-31 19:00:00,0,0,0,0,0
87669,2024-12-31 20:00:00,0,0,0,0,0
87670,2024-12-31 21:00:00,0,0,0,0,0
87671,2024-12-31 22:00:00,0,0,0,0,0
87672,2024-12-31 23:00:00,0,0,0,0,0

In [190]:
df = pd.read_csv("./combined/" + "06-05-500-0342658" + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])

In [191]:
df

,produced_at,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972
0,2015-01-01 00:00:00,0,0,0,0,0
1,2015-01-01 01:00:00,0,0,0,0,0
2,2015-01-01 02:00:00,0,0,0,0,0
3,2015-01-01 03:00:00,0,0,0,0,0
4,2015-01-01 04:00:00,0,0,0,0,0
...,...,...,...,...,...,...
87668,2024-12-31 19:00:00,0,0,0,0,0
87669,2024-12-31 20:00:00,0,0,0,0,0
87670,2024-12-31 21:00:00,0,0,0,0,0
87671,2024-12-31 22:00:00,0,0,0,0,0
87672,2024-12-31 23:00:00,0,0,0,0,0

In [192]:
#columns_table = (inspect(engine).get_columns('power'))

In [193]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [194]:
df

,produced_at,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972
0,2015-01-01 00:00:00,0,0,0,0,0
1,2015-01-01 01:00:00,0,0,0,0,0
2,2015-01-01 02:00:00,0,0,0,0,0
3,2015-01-01 03:00:00,0,0,0,0,0
4,2015-01-01 04:00:00,0,0,0,0,0
...,...,...,...,...,...,...
87668,2024-12-31 19:00:00,0,0,0,0,0
87669,2024-12-31 20:00:00,0,0,0,0,0
87670,2024-12-31 21:00:00,0,0,0,0,0
87671,2024-12-31 22:00:00,0,0,0,0,0
87672,2024-12-31 23:00:00,0,0,0,0,0

In [195]:
CDF = pd.read_sql_table('power', engine2)

In [196]:
CDF.shape

(14640627, 3)

In [197]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [198]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [199]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0526      0
1        2015-01-01 01:00:00          BNA0526      0
2        2015-01-01 02:00:00          BNA0526      0
3        2015-01-01 03:00:00          BNA0526      0
4        2015-01-01 04:00:00          BNA0526      0
...                      ...              ...    ...
14640622 2021-12-31 19:00:00  SEE983645175053      0
14640623 2021-12-31 20:00:00  SEE983645175053      0
14640624 2021-12-31 21:00:00  SEE983645175053      0
14640625 2021-12-31 22:00:00  SEE983645175053      0
14640626 2021-12-31 23:00:00  SEE983645175053      0

[14640627 rows x 3 columns]

In [200]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [201]:
CDF9.iloc[70128]

produced_at    2018-01-01 08:00:00
variable           SEE904194792843
value                            0
Name: 70128, dtype: object

In [202]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

Empty DataFrame
Columns: [produced_at, variable, value]
Index: []

In [203]:
CDF9.shape

(14640627, 3)

In [204]:
#CDF9.iloc[15219136]

In [205]:
CDF9.iloc[929304]

produced_at    2016-01-05 10:00:00
variable           SEE994418588468
value                          135
Name: 929304, dtype: object

In [206]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [207]:
CDF9[CDF9.isnull().any(axis=1)].shape

(0, 3)

In [208]:
#CDF10 = CDF9.dropna()

In [209]:
CDF9["value"] = CDF9["value"].astype(int)

In [210]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [211]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [212]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0526      0
1        2015-01-01 01:00:00          BNA0526      0
2        2015-01-01 02:00:00          BNA0526      0
3        2015-01-01 03:00:00          BNA0526      0
4        2015-01-01 04:00:00          BNA0526      0
...                      ...              ...    ...
14640622 2021-12-31 19:00:00  SEE983645175053      0
14640623 2021-12-31 20:00:00  SEE983645175053      0
14640624 2021-12-31 21:00:00  SEE983645175053      0
14640625 2021-12-31 22:00:00  SEE983645175053      0
14640626 2021-12-31 23:00:00  SEE983645175053      0

[14640627 rows x 3 columns]

In [213]:
#CDF_new = CDF.reset_index(drop=False)

In [214]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [215]:
#CDF_new[CDF_new.produced_at.isnull()]

In [216]:
#CDF_new

In [217]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [218]:
#CDF

In [219]:
#CDF99.set_index('produced_at')

In [220]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [221]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [222]:
#subC1

In [223]:
CDF10 = CDF9.copy()

In [224]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [225]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0526      0
1        2015-01-01 01:00:00          BNA0526      0
2        2015-01-01 02:00:00          BNA0526      0
3        2015-01-01 03:00:00          BNA0526      0
4        2015-01-01 04:00:00          BNA0526      0
...                      ...              ...    ...
14640622 2021-12-31 19:00:00  SEE983645175053      0
14640623 2021-12-31 20:00:00  SEE983645175053      0
14640624 2021-12-31 21:00:00  SEE983645175053      0
14640625 2021-12-31 22:00:00  SEE983645175053      0
14640626 2021-12-31 23:00:00  SEE983645175053      0

[14640627 rows x 3 columns]

In [226]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

In [227]:
CDF2

                                                                      variable  \
variable        produced_at
BNA0140         2015-01-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-02-28   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-03-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-04-30   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-05-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
...                                                                        ...
SEE999117793854 2024-08-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-09-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-10-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-11-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-12-31   SEE999117793854SEE999117793854SEE999117793854S...

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[20160 rows x 2 columns]

In [228]:
CDF3 = CDF2.drop(columns="variable")

In [229]:
CDF3

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[20160 rows x 1 columns]

In [230]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [231]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [232]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [233]:
#gm2

In [234]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [235]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [236]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [237]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [238]:
gm8

In [ ]:
gm7

In [ ]:
bpm

In [ ]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [214]:
pm2

      year  month          blockid   power              plantid  plantpower
0     2015      1          BNA0333       0    06-05-500-0342658      171025
1     2015      1          BNA0334       0    06-05-500-0342658      171025
2     2015      1          BNA0335       0    06-05-500-0342658      171025
3     2015      1  SEE911613995433    2383        06-08-2142201        2383
4     2015      1  SEE913556136355       0               661-18           0
...    ...    ...              ...     ...                  ...         ...
1675  2024     12  SEE952352206145       0    06-05-500-0342658           0
1676  2024     12  SEE958847865460   92161  06-09-100-0003-0003       92161
1677  2024     12  SEE964114029633       0        06-08-2142201        3027
1678  2024     12  SEE966331411864  443247    14-80-00009560000      618104
1679  2024     12  SEE998199911088  174857    14-80-00009560000      618104

[1680 rows x 6 columns]

In [215]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [216]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [217]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [218]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [219]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [220]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [221]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [222]:
#invCDF = CDF.pivot(columns='variable')

In [223]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
20155  2024     12  SEE996720450723   51349
20156  2024     12  SEE997719859992   60650
20157  2024     12  SEE998199911088  174857
20158  2024     12  SEE998383491525       0
20159  2024     12  SEE999117793854   14587

[20160 rows x 4 columns]

In [239]:
gm7

       year  month          blockid   power
0      2015      1          BNA0140       0
120    2015      1          BNA0143       0
240    2015      1          BNA0145       0
324    2015      1          BNA0146  129164
696    2015      1          BNA0215       0
...     ...    ...              ...     ...
19679  2024     12  SEE996720450723   51349
19799  2024     12  SEE997719859992   60650
19919  2024     12  SEE998199911088  174857
20039  2024     12  SEE998383491525       0
20159  2024     12  SEE999117793854   14587

[20160 rows x 4 columns]

In [240]:
bpm

                plantid            sseid
0        12-30532000000  SEE969511682320
1     06-05-900-0327252  SEE948351715917
2     14-80-55047380000  SEE986249505394
3     14-80-55047380000  SEE955310827123
4        12-30532000000  SEE939848582457
...                 ...              ...
1002  14-60-48821410003  SEE928331694449
1003  14-60-48821410003  SEE974236609859
1004  14-60-48821410003  SEE909466066615
1005  14-70-52316707024  SEE963438570067
1006      06-08-3042693  SEE976252866650

[1007 rows x 2 columns]

In [241]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [242]:
pm2

       year  month          blockid   power               plantid
0      2015      1          BNA0140       0  06-04-11_2001178_8_0
1      2015      1          BNA0145       0  06-04-11_2001178_8_1
2      2015      1          BNA0146  129164  06-04-11_2001178_8_1
3      2015      1          BNA0215       0     06-05-100-0365906
4      2015      1         BNA0221c   15020     06-05-100-0167182
...     ...    ...              ...     ...                   ...
18991  2024     12  SEE996720450723   51349   06-09-100-0088-0005
18992  2024     12  SEE997719859992   60650      06-11-01-1105501
18993  2024     12  SEE998199911088  174857     14-80-00009560000
18994  2024     12  SEE998383491525       0         06-08-1195689
18995  2024     12  SEE999117793854   14587     06-05-300-0877384

[18996 rows x 5 columns]

In [243]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [244]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [245]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [246]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

     year            plantid  yearpower
37   2015  06-05-100-0248923   15386816
102  2016  06-05-100-0248923   21812847
168  2017  06-05-100-0248923   22611486
232  2018  06-05-100-0248923   25507220
294  2019  06-05-100-0248923   17881538
352  2020  06-05-100-0248923   14625468
409  2021  06-05-100-0248923   16554636
463  2022  06-05-100-0248923   21857955
516  2023  06-05-100-0248923   15021992
569  2024  06-05-100-0248923   12629202

In [247]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

     year              plantid  yearpower
50   2015  06-09-100-0001-0002     560921
115  2016  06-09-100-0001-0002     204765
181  2017  06-09-100-0001-0002     133508
245  2018  06-09-100-0001-0002      24090
307  2019  06-09-100-0001-0002      37682
365  2020  06-09-100-0001-0002    1734818
422  2021  06-09-100-0001-0002    4187402
476  2022  06-09-100-0001-0002    2498555
529  2023  06-09-100-0001-0002    2856627
579  2024  06-09-100-0001-0002    3445690

In [248]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [249]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [250]:
#invCDF = CDF.pivot(columns='variable')

In [251]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
20155  2024     12  SEE996720450723   51349
20156  2024     12  SEE997719859992   60650
20157  2024     12  SEE998199911088  174857
20158  2024     12  SEE998383491525       0
20159  2024     12  SEE999117793854   14587

[20160 rows x 4 columns]

In [252]:
bpm

                plantid            sseid
0        12-30532000000  SEE969511682320
1     06-05-900-0327252  SEE948351715917
2     14-80-55047380000  SEE986249505394
3     14-80-55047380000  SEE955310827123
4        12-30532000000  SEE939848582457
...                 ...              ...
1002  14-60-48821410003  SEE928331694449
1003  14-60-48821410003  SEE974236609859
1004  14-60-48821410003  SEE909466066615
1005  14-70-52316707024  SEE963438570067
1006      06-08-3042693  SEE976252866650

[1007 rows x 2 columns]