In [206]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, text, DateTime
from sqlalchemy.orm import Session
import psycopg
import time

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [4]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [5]:
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

plantslist = list(set(seem['plantid'].to_list()))
plantslist.sort()

/tmp/ipykernel_89420/3027777900.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [6]:
"06-08-2948214" in plantslist

False

In [7]:
#plantslist

In [8]:
#plantslist.remove('661-94')
#plantslist.remove('661-10')

#plantslist.remove('07-05-8290552')
#plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [9]:
#refpl = "03-01-01241117210.csv"

In [10]:
#df = pd.read_csv("./combined/" + refpl)

In [11]:
#df

In [12]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [13]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [14]:
testdf = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv")

In [15]:
nd = "01.01.2023 00:00"

In [16]:
datetime.strptime(nd, "%d.%m.%Y %H:%M")

datetime.datetime(2023, 1, 1, 0, 0)

In [17]:
arr = [nd, "2022-12-31 23:15:00", "2021-12-24 08:00:00", '29.04.2023 12:00', '01.01.2023 00:00']

In [18]:
list(map(lambda x: fix_date(x), arr))

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2022, 12, 31, 23, 15),
 datetime.datetime(2021, 12, 24, 8, 0),
 datetime.datetime(2023, 4, 29, 12, 0),
 datetime.datetime(2023, 1, 1, 0, 0)]

In [19]:
fix_date(nd)

datetime.datetime(2023, 1, 1, 0, 0)

In [20]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [21]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [22]:
#engine = create_engine('sqlite://', echo=False)

In [23]:
#2023-12-31 19:00:00.000000

In [24]:
#melt.dtypes

In [25]:
#testdf.iloc[70128]

In [26]:
#testdf['produced_at'] = testdf['produced_at'].map(return_date)

In [27]:
#testdf['produced_at'] = pd.to_datetime(testdf['produced_at'])

In [28]:
#df.dtypes

In [29]:
#df.iloc[70128]

In [30]:
#connection = engine2.connect()
#with engine2.begin() as connection:
plant = "06-05-100-0853075"

df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])
df.drop_duplicates(subset='produced_at', inplace=True)
#melt = df.melt(id_vars='produced_at')
#melt.drop('index', axis=1, inplace=True)
#res = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

In [31]:
#res

In [32]:
#melt

In [33]:
#melt.dtypes

In [207]:
with Session(engine2) as sess:
    sess.execute(text("TRUNCATE TABLE power"))
    sess.commit()

In [116]:
from datetime import datetime

In [117]:
starttime = datetime.now()

In [35]:
counter = 0
for plant in plantslist:
    #if plant == '06-05-300-9046030':
    #    continue
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        try: #, format='%d.%m.%Y %H:%M'
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = df['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df['produced_at'] = df['produced_at'].map(return_date)
        except ValueError:
            print(plant + "\nfaulty")
            #df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = pd.to_datetime(df['produced_at'])
            #print(df)
            continue
            #pass
        melt = df.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

NW100-0081105
faulty
RP5000671
faulty
SD661-94
faulty
70

In [118]:
endtime = datetime.now()
duration = endtime - starttime

In [199]:
duration

datetime.timedelta(microseconds=4316)

In [119]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [120]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [121]:
df = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])

In [122]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [123]:
#columns_table = (inspect(engine).get_columns('power'))

In [124]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [125]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [126]:
CDF = pd.read_sql_table('power', engine2)

In [127]:
#CDF.drop_duplicates(subset=['produced_at', 'variable'])

In [128]:
CDF.shape

(15068889, 3)

In [129]:
CDF.to_csv("CDF.csv", index=False)

In [130]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [131]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [132]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
15068884 2024-12-31 19:00:00  SEE947677200282      0
15068885 2024-12-31 20:00:00  SEE947677200282      0
15068886 2024-12-31 21:00:00  SEE947677200282      0
15068887 2024-12-31 22:00:00  SEE947677200282      0
15068888 2024-12-31 23:00:00  SEE947677200282      0

[15068889 rows x 3 columns]

In [133]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [134]:
CDF9.iloc[70128]

produced_at    2023-01-01 08:00:00
variable           SEE913896693631
value                            0
Name: 70128, dtype: object

In [135]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

                produced_at         variable  value
3786984 2015-01-01 00:00:00  SEE949509046600      0
3786985 2015-01-01 01:00:00  SEE949509046600      0
3786986 2015-01-01 02:00:00  SEE949509046600      0
3786987 2015-01-01 03:00:00  SEE949509046600      0
3786988 2015-01-01 04:00:00  SEE949509046600      0
...                     ...              ...    ...
3874641 2024-12-31 19:00:00  SEE949509046600      0
3874642 2024-12-31 20:00:00  SEE949509046600      0
3874643 2024-12-31 21:00:00  SEE949509046600      0
3874644 2024-12-31 22:00:00  SEE949509046600      0
3874645 2024-12-31 23:00:00  SEE949509046600      0

[87662 rows x 3 columns]

In [136]:
CDF9.shape

(15068889, 3)

In [137]:
#CDF9.iloc[15219136]

In [138]:
CDF9.iloc[929304]

produced_at    2019-01-04 10:00:00
variable           SEE989591633753
value                          469
Name: 929304, dtype: object

In [139]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [140]:
CDF9[CDF9.isnull().any(axis=1)].shape

(0, 3)

In [141]:
#CDF10 = CDF9.dropna()

In [142]:
CDF9["value"] = CDF9["value"].astype(int)

In [143]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [144]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [145]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
15068884 2024-12-31 19:00:00  SEE947677200282      0
15068885 2024-12-31 20:00:00  SEE947677200282      0
15068886 2024-12-31 21:00:00  SEE947677200282      0
15068887 2024-12-31 22:00:00  SEE947677200282      0
15068888 2024-12-31 23:00:00  SEE947677200282      0

[15068889 rows x 3 columns]

In [146]:
#CDF_new = CDF.reset_index(drop=False)

In [147]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [148]:
#CDF_new[CDF_new.produced_at.isnull()]

In [149]:
#CDF_new

In [150]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [151]:
#CDF

In [152]:
#CDF99.set_index('produced_at')

In [153]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [154]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [155]:
#subC1

In [156]:
CDF10 = CDF9.copy()

In [157]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [158]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
15068884 2024-12-31 19:00:00  SEE947677200282      0
15068885 2024-12-31 20:00:00  SEE947677200282      0
15068886 2024-12-31 21:00:00  SEE947677200282      0
15068887 2024-12-31 22:00:00  SEE947677200282      0
15068888 2024-12-31 23:00:00  SEE947677200282      0

[15068889 rows x 3 columns]

In [159]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

/tmp/ipykernel_89420/675855814.py:1: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

In [160]:
CDF2

                                                                      variable  \
variable        produced_at
BNA0187         2017-01-31   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-02-28   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-03-31   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-04-30   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-05-31   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
...                                                                        ...
SEE999117793854 2024-08-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-09-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-10-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-11-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-12-31   SEE999117793854SEE999117793854SEE999117793854S...

                             value
variable        produced_at
BNA0187         2017-01-31       0
                2017-02-28       0
                2017-03-31       0
                2017-04-30       0
                2017-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[20676 rows x 2 columns]

In [161]:
CDF3 = CDF2.drop(columns="variable")

In [162]:
CDF3

                             value
variable        produced_at
BNA0187         2017-01-31       0
                2017-02-28       0
                2017-03-31       0
                2017-04-30       0
                2017-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[20676 rows x 1 columns]

In [163]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [164]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [165]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [166]:
#gm2

In [167]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [168]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [169]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [170]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [171]:
gm8

       year  month          blockid   power
0      2015      1          BNA0215       0
1      2015      1         BNA0221c   15020
2      2015      1          BNA0333       0
3      2015      1          BNA0334       0
4      2015      1          BNA0335       0
...     ...    ...              ...     ...
20671  2024     12  SEE997719859992   60650
20672  2024     12  SEE998199911088  174857
20673  2024     12  SEE998278854237       0
20674  2024     12  SEE998383491525       0
20675  2024     12  SEE999117793854   14587

[20676 rows x 4 columns]

In [172]:
gm7

       year  month          blockid   power
288    2015      1          BNA0215       0
408    2015      1         BNA0221c   15020
528    2015      1          BNA0333       0
648    2015      1          BNA0334       0
768    2015      1          BNA0335       0
...     ...    ...              ...     ...
20195  2024     12  SEE997719859992   60650
20315  2024     12  SEE998199911088  174857
20435  2024     12  SEE998278854237       0
20555  2024     12  SEE998383491525       0
20675  2024     12  SEE999117793854   14587

[20676 rows x 4 columns]

In [173]:
bpm = seem.copy()

In [174]:
bpm

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [175]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [176]:
pm2

       year  month          blockid   power                    plantid
0      2015      1          BNA0215       0              NW100-0365906
1      2015      1         BNA0221c   15020              NW100-0167182
2      2015      1          BNA0333       0              NW500-0342658
3      2015      1          BNA0334       0              NW500-0342658
4      2015      1          BNA0335       0              NW500-0342658
...     ...    ...              ...     ...                        ...
20431  2024     12  SEE997719859992   60650                   BE169709
20432  2024     12  SEE998199911088  174857                 SN80011277
20433  2024     12  SEE998278854237       0                   BYS00041
20434  2024     12  SEE998383491525       0  BWpf-450-1195689-00000000
20435  2024     12  SEE999117793854   14587              NW300-0877384

[20436 rows x 5 columns]

In [177]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [178]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [179]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [180]:
ym4

     year        plantid  yearpower
0    2015  NW100-0365906    2470223
1    2015  NW100-0167182     115006
2    2015  NW500-0342658    2306293
3    2015     HE30001045    2528577
4    2015  NW900-0079017    2985155
..    ...            ...        ...
622  2024       BE166928    1171226
623  2024    SL0105352-G     137404
624  2024       BYS00044    1075551
625  2024  NW300-9002708    1403116
626  2024       BE169709     361995

[627 rows x 3 columns]

In [181]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [182]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [183]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [184]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [185]:
#invCDF = CDF.pivot(columns='variable')

In [186]:
gm8

       year  month          blockid   power
0      2015      1          BNA0215       0
1      2015      1         BNA0221c   15020
2      2015      1          BNA0333       0
3      2015      1          BNA0334       0
4      2015      1          BNA0335       0
...     ...    ...              ...     ...
20671  2024     12  SEE997719859992   60650
20672  2024     12  SEE998199911088  174857
20673  2024     12  SEE998278854237       0
20674  2024     12  SEE998383491525       0
20675  2024     12  SEE999117793854   14587

[20676 rows x 4 columns]

In [187]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [188]:
pm2

       year  month          blockid   power                    plantid
0      2015      1          BNA0215       0              NW100-0365906
1      2015      1         BNA0221c   15020              NW100-0167182
2      2015      1          BNA0333       0              NW500-0342658
3      2015      1          BNA0334       0              NW500-0342658
4      2015      1          BNA0335       0              NW500-0342658
...     ...    ...              ...     ...                        ...
20431  2024     12  SEE997719859992   60650                   BE169709
20432  2024     12  SEE998199911088  174857                 SN80011277
20433  2024     12  SEE998278854237       0                   BYS00041
20434  2024     12  SEE998383491525       0  BWpf-450-1195689-00000000
20435  2024     12  SEE999117793854   14587              NW300-0877384

[20436 rows x 5 columns]

In [189]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [190]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [191]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [192]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [193]:
ym4.loc[ym4.plantid == "NW100-0248923"]

     year        plantid  yearpower
24   2015  NW100-0248923   18262795
92   2016  NW100-0248923   25468598
161  2017  NW100-0248923   27112376
228  2018  NW100-0248923   29463725
293  2019  NW100-0248923   20841356
354  2020  NW100-0248923   17221819
414  2021  NW100-0248923   20015332
474  2022  NW100-0248923   22326897
532  2023  NW100-0248923   15021992
590  2024  NW100-0248923   12629202

In [194]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [195]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [196]:
#invCDF = CDF.pivot(columns='variable')

In [197]:
gm8

       year  month          blockid   power
0      2015      1          BNA0215       0
1      2015      1         BNA0221c   15020
2      2015      1          BNA0333       0
3      2015      1          BNA0334       0
4      2015      1          BNA0335       0
...     ...    ...              ...     ...
20671  2024     12  SEE997719859992   60650
20672  2024     12  SEE998199911088  174857
20673  2024     12  SEE998278854237       0
20674  2024     12  SEE998383491525       0
20675  2024     12  SEE999117793854   14587

[20676 rows x 4 columns]

In [198]:
bpm

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]