In [165]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, DateTime
import psycopg
import time

In [166]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [167]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [168]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [169]:
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

plantslist = list(set(seem['plantid'].to_list()))
plantslist.sort()

/tmp/ipykernel_1743672/3027777900.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [170]:
"06-08-2948214" in plantslist

False

In [171]:
#plantslist

In [172]:
#plantslist.remove('661-94')
#plantslist.remove('661-10')

#plantslist.remove('07-05-8290552')
#plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [173]:
#refpl = "03-01-01241117210.csv"

In [174]:
#df = pd.read_csv("./combined/" + refpl)

In [175]:
#df

In [176]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [177]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [178]:
testdf = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv")

In [179]:
nd = "01.01.2023 00:00"

In [180]:
datetime.strptime(nd, "%d.%m.%Y %H:%M")

datetime.datetime(2023, 1, 1, 0, 0)

In [181]:
arr = [nd, "2022-12-31 23:15:00", "2021-12-24 08:00:00", '29.04.2023 12:00', '01.01.2023 00:00']

In [182]:
list(map(lambda x: fix_date(x), arr))

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2022, 12, 31, 23, 15),
 datetime.datetime(2021, 12, 24, 8, 0),
 datetime.datetime(2023, 4, 29, 12, 0),
 datetime.datetime(2023, 1, 1, 0, 0)]

In [183]:
fix_date(nd)

datetime.datetime(2023, 1, 1, 0, 0)

In [184]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [185]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [186]:
#engine = create_engine('sqlite://', echo=False)

In [187]:
#2023-12-31 19:00:00.000000

In [188]:
#melt.dtypes

In [189]:
#testdf.iloc[70128]

In [190]:
#testdf['produced_at'] = testdf['produced_at'].map(return_date)

In [191]:
#testdf['produced_at'] = pd.to_datetime(testdf['produced_at'])

In [192]:
#df.dtypes

In [193]:
#df.iloc[70128]

In [194]:
#connection = engine2.connect()
#with engine2.begin() as connection:
plant = "06-05-100-0853075"

df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])
df.drop_duplicates(subset='produced_at', inplace=True)
#melt = df.melt(id_vars='produced_at')
#melt.drop('index', axis=1, inplace=True)
#res = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

In [195]:
#res

In [196]:
#melt

In [197]:
#melt.dtypes

In [198]:
counter = 0
for plant in plantslist:
    #if plant == '06-05-300-9046030':
    #    continue
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        try: #, format='%d.%m.%Y %H:%M'
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = df['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df['produced_at'] = df['produced_at'].map(return_date)
        except ValueError:
            print(plant + "\nfaulty")
            #df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = pd.to_datetime(df['produced_at'])
            #print(df)
            continue
            #pass
        melt = df.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

NW100-0081105
faulty
RP5000671
faulty
60

In [199]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [200]:
df

              produced_at  SEE960652233358  SEE947677200282
0     2015-01-01 00:00:00                0                0
1     2015-01-01 01:00:00                0                0
2     2015-01-01 02:00:00                0                0
3     2015-01-01 03:00:00                0                0
4     2015-01-01 04:00:00                0                0
...                   ...              ...              ...
87667 2024-12-31 19:00:00                0                0
87668 2024-12-31 20:00:00                0                0
87669 2024-12-31 21:00:00                0                0
87670 2024-12-31 22:00:00                0                0
87671 2024-12-31 23:00:00                0                0

[87662 rows x 3 columns]

In [201]:
df = pd.read_csv("./combined/" + "06-05-100-0853075" + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])

In [202]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [203]:
#columns_table = (inspect(engine).get_columns('power'))

In [204]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [205]:
df

              produced_at  BNA0990  BNA0989
0     2015-01-01 00:00:00        0        0
1     2015-01-01 01:00:00        0        0
2     2015-01-01 02:00:00        0        0
3     2015-01-01 03:00:00        0        0
4     2015-01-01 04:00:00        0        0
...                   ...      ...      ...
26299 2017-12-31 19:00:00        0        0
26300 2017-12-31 20:00:00        0        0
26301 2017-12-31 21:00:00        0        0
26302 2017-12-31 22:00:00        0        0
26303 2017-12-31 23:00:00        0        0

[26304 rows x 3 columns]

In [206]:
CDF = pd.read_sql_table('power', engine2)

In [207]:
CDF.shape

(13824175, 3)

In [208]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [209]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [210]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
13824170 2024-12-31 19:00:00  SEE947677200282      0
13824171 2024-12-31 20:00:00  SEE947677200282      0
13824172 2024-12-31 21:00:00  SEE947677200282      0
13824173 2024-12-31 22:00:00  SEE947677200282      0
13824174 2024-12-31 23:00:00  SEE947677200282      0

[13824175 rows x 3 columns]

In [211]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [212]:
CDF9.iloc[70128]

produced_at    2023-01-01 08:00:00
variable           SEE913896693631
value                            0
Name: 70128, dtype: object

In [213]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

Empty DataFrame
Columns: [produced_at, variable, value]
Index: []

In [214]:
CDF9.shape

(13824175, 3)

In [215]:
#CDF9.iloc[15219136]

In [216]:
CDF9.iloc[929304]

produced_at    2019-01-04 10:00:00
variable           SEE989591633753
value                          469
Name: 929304, dtype: object

In [217]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [218]:
CDF9[CDF9.isnull().any(axis=1)].shape

(0, 3)

In [219]:
#CDF10 = CDF9.dropna()

In [220]:
CDF9["value"] = CDF9["value"].astype(int)

In [221]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [222]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [223]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
13824170 2024-12-31 19:00:00  SEE947677200282      0
13824171 2024-12-31 20:00:00  SEE947677200282      0
13824172 2024-12-31 21:00:00  SEE947677200282      0
13824173 2024-12-31 22:00:00  SEE947677200282      0
13824174 2024-12-31 23:00:00  SEE947677200282      0

[13824175 rows x 3 columns]

In [224]:
#CDF_new = CDF.reset_index(drop=False)

In [225]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [226]:
#CDF_new[CDF_new.produced_at.isnull()]

In [227]:
#CDF_new

In [228]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [229]:
#CDF

In [230]:
#CDF99.set_index('produced_at')

In [231]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [232]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [233]:
#subC1

In [234]:
CDF10 = CDF9.copy()

In [235]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [236]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00  SEE913896693631      0
1        2015-01-01 01:00:00  SEE913896693631      0
2        2015-01-01 02:00:00  SEE913896693631      0
3        2015-01-01 03:00:00  SEE913896693631      0
4        2015-01-01 04:00:00  SEE913896693631      0
...                      ...              ...    ...
13824170 2024-12-31 19:00:00  SEE947677200282      0
13824171 2024-12-31 20:00:00  SEE947677200282      0
13824172 2024-12-31 21:00:00  SEE947677200282      0
13824173 2024-12-31 22:00:00  SEE947677200282      0
13824174 2024-12-31 23:00:00  SEE947677200282      0

[13824175 rows x 3 columns]

In [237]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

In [238]:
CDF2

                                                                      variable  \
variable        produced_at
BNA0187         2017-01-31   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-02-28   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-03-31   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-04-30   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
                2017-05-31   BNA0187BNA0187BNA0187BNA0187BNA0187BNA0187BNA0...
...                                                                        ...
SEE999117793854 2024-08-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-09-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-10-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-11-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-12-31   SEE999117793854SEE999117793854SEE999117793854S...

                             value
variable        produced_at
BNA0187         2017-01-31       0
                2017-02-28       0
                2017-03-31       0
                2017-04-30       0
                2017-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[18924 rows x 2 columns]

In [239]:
CDF3 = CDF2.drop(columns="variable")

In [240]:
CDF3

                             value
variable        produced_at
BNA0187         2017-01-31       0
                2017-02-28       0
                2017-03-31       0
                2017-04-30       0
                2017-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[18924 rows x 1 columns]

In [241]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [242]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [243]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [244]:
#gm2

In [245]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [246]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [247]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [248]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [249]:
gm8

       year  month          blockid   power
0      2015      1          BNA0215       0
1      2015      1         BNA0216a       0
2      2015      1         BNA0221c   15020
3      2015      1          BNA0333       0
4      2015      1          BNA0334       0
...     ...    ...              ...     ...
18919  2024     12  SEE996720450723   51349
18920  2024     12  SEE997719859992   60650
18921  2024     12  SEE998199911088  174857
18922  2024     12  SEE998383491525       0
18923  2024     12  SEE999117793854   14587

[18924 rows x 4 columns]

In [250]:
gm7

       year  month          blockid   power
288    2015      1          BNA0215       0
408    2015      1         BNA0216a       0
528    2015      1         BNA0221c   15020
648    2015      1          BNA0333       0
768    2015      1          BNA0334       0
...     ...    ...              ...     ...
18443  2024     12  SEE996720450723   51349
18563  2024     12  SEE997719859992   60650
18683  2024     12  SEE998199911088  174857
18803  2024     12  SEE998383491525       0
18923  2024     12  SEE999117793854   14587

[18924 rows x 4 columns]

In [251]:
bpm = seem.copy()

In [252]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [253]:
pm2

       year  month          blockid   power                    plantid
0      2015      1          BNA0215       0              NW100-0365906
1      2015      1         BNA0221c   15020              NW100-0167182
2      2015      1          BNA0333       0              NW500-0342658
3      2015      1          BNA0334       0              NW500-0342658
4      2015      1          BNA0335       0              NW500-0342658
...     ...    ...              ...     ...                        ...
17995  2024     12  SEE996720450723   51349                   BYS00044
17996  2024     12  SEE997719859992   60650                   BE169709
17997  2024     12  SEE998199911088  174857                 SN80011277
17998  2024     12  SEE998383491525       0  BWpf-450-1195689-00000000
17999  2024     12  SEE999117793854   14587              NW300-0877384

[18000 rows x 5 columns]

In [254]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [255]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [256]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [257]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [258]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [259]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [260]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [261]:
#invCDF = CDF.pivot(columns='variable')

In [262]:
gm8

       year  month          blockid   power
0      2015      1          BNA0215       0
1      2015      1         BNA0216a       0
2      2015      1         BNA0221c   15020
3      2015      1          BNA0333       0
4      2015      1          BNA0334       0
...     ...    ...              ...     ...
18919  2024     12  SEE996720450723   51349
18920  2024     12  SEE997719859992   60650
18921  2024     12  SEE998199911088  174857
18922  2024     12  SEE998383491525       0
18923  2024     12  SEE999117793854   14587

[18924 rows x 4 columns]

In [263]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [264]:
pm2

       year  month          blockid   power                    plantid
0      2015      1          BNA0215       0              NW100-0365906
1      2015      1         BNA0221c   15020              NW100-0167182
2      2015      1          BNA0333       0              NW500-0342658
3      2015      1          BNA0334       0              NW500-0342658
4      2015      1          BNA0335       0              NW500-0342658
...     ...    ...              ...     ...                        ...
17995  2024     12  SEE996720450723   51349                   BYS00044
17996  2024     12  SEE997719859992   60650                   BE169709
17997  2024     12  SEE998199911088  174857                 SN80011277
17998  2024     12  SEE998383491525       0  BWpf-450-1195689-00000000
17999  2024     12  SEE999117793854   14587              NW300-0877384

[18000 rows x 5 columns]

In [265]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [266]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [267]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [268]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [269]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [270]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [271]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [272]:
#invCDF = CDF.pivot(columns='variable')

In [273]:
gm8

       year  month          blockid   power
0      2015      1          BNA0215       0
1      2015      1         BNA0216a       0
2      2015      1         BNA0221c   15020
3      2015      1          BNA0333       0
4      2015      1          BNA0334       0
...     ...    ...              ...     ...
18919  2024     12  SEE996720450723   51349
18920  2024     12  SEE997719859992   60650
18921  2024     12  SEE998199911088  174857
18922  2024     12  SEE998383491525       0
18923  2024     12  SEE999117793854   14587

[18924 rows x 4 columns]

In [274]:
bpm

               plantid            sseid
0     06-02-B10117A007  SEE987197130805
1     06-02-B10117A007  SEE913896693631
2    06-05-100-0030723          BNA1084
3    06-05-100-0431554          BNA0992
4    06-05-100-0431554          BNA0991
..                 ...              ...
887         TH72012874  SEE912583238223
888         TH72012874  SEE969004747543
889         TH72012874  SEE951160693116
890         TH86012942  SEE925388069183
891         TH86012942  SEE962906846994

[892 rows x 2 columns]