In [1]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, DateTime
import psycopg
import time

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [4]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [5]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
plantslist = list(set(bpm['plantid'].to_list()))
plantslist.sort()

In [6]:
"06-08-2948214" in plantslist

True

In [7]:
#plantslist

In [8]:
#plantslist.remove('661-94')
#plantslist.remove('661-10')

#plantslist.remove('07-05-8290552')
#plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [9]:
#refpl = "03-01-01241117210.csv"

In [10]:
#df = pd.read_csv("./combined/" + refpl)

In [11]:
#df

In [12]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [13]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [14]:
testdf = pd.read_csv("./combined/" + "06-09-100-0003-0003" + ".csv")

In [15]:
nd = "01.01.2023 00:00"

In [16]:
datetime.strptime(nd, "%d.%m.%Y %H:%M")

datetime.datetime(2023, 1, 1, 0, 0)

In [17]:
arr = [nd, "2022-12-31 23:15:00", "2021-12-24 08:00:00", '29.04.2023 12:00', '01.01.2023 00:00']

In [18]:
list(map(lambda x: fix_date(x), arr))

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2022, 12, 31, 23, 15),
 datetime.datetime(2021, 12, 24, 8, 0),
 datetime.datetime(2023, 4, 29, 12, 0),
 datetime.datetime(2023, 1, 1, 0, 0)]

In [19]:
fix_date(nd)

datetime.datetime(2023, 1, 1, 0, 0)

In [20]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [21]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [22]:
#engine = create_engine('sqlite://', echo=False)

In [23]:
#2023-12-31 19:00:00.000000

In [24]:
#melt.dtypes

In [25]:
testdf.iloc[70128]

produced_at        01.01.2023 00:00
SEE949509046600                   0
SEE918648599230                   0
SEE958847865460                   0
Name: 70128, dtype: object

In [26]:
#testdf['produced_at'] = testdf['produced_at'].map(return_date)

In [27]:
#testdf['produced_at'] = pd.to_datetime(testdf['produced_at'])

In [28]:
#df.dtypes

In [29]:
#df.iloc[70128]

In [30]:
#connection = engine2.connect()
#with engine2.begin() as connection:
plant = "06-05-300-9046030"

df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])
df.drop_duplicates(subset='produced_at', inplace=True)
#melt = df.melt(id_vars='produced_at')
#melt.drop('index', axis=1, inplace=True)
#res = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

In [31]:
#res

In [32]:
#melt

In [33]:
#melt.dtypes

In [34]:
counter = 0
for plant in plantslist:
    #if plant == '06-05-300-9046030':
    #    continue
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv", delimiter=",", engine='c')
        try: #, format='%d.%m.%Y %H:%M'
            df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = df['produced_at'].map(fix_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df.drop_duplicates(subset='produced_at', inplace=True)
            #df['produced_at'] = df['produced_at'].map(return_date)
        except ValueError:
            print(plant + "\nfaulty")
            #df['produced_at'] = df['produced_at'].map(fix_date)
            #df['produced_at'] = pd.to_datetime(df['produced_at'])
            #print(df)
            continue
            #pass
        melt = df.melt(id_vars='produced_at')
        melt.to_csv("./melt/" + plant + ".csv", index=False)
        #melt.drop('index', axis=1, inplace=True)
        result = melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #time.sleep(1)
        #if result == -1:
            #print(plant + "\nfaulty2")
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

01-50-02000000309
faulty
06-05-100-0081105
faulty
06-09-100-0003-0003
faulty
07-05-8290552
faulty
661-94
faulty
72

In [35]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [36]:
df

              produced_at  SEE950675787617  SEE983645175053
0     2015-01-01 00:00:00                0                0
1     2015-01-01 01:00:00                0                0
2     2015-01-01 02:00:00                0                0
3     2015-01-01 03:00:00                0                0
4     2015-01-01 04:00:00                0                0
...                   ...              ...              ...
61363 2021-12-31 19:00:00                0                0
61364 2021-12-31 20:00:00                0                0
61365 2021-12-31 21:00:00                0                0
61366 2021-12-31 22:00:00                0                0
61367 2021-12-31 23:00:00                0                0

[61361 rows x 3 columns]

In [37]:
df = pd.read_csv("./combined/" + "06-05-500-0342658" + ".csv", delimiter=",", engine='c')
df['produced_at'] = df['produced_at'].map(fix_date)
df['produced_at'] = pd.to_datetime(df['produced_at'])

In [38]:
df

,produced_at,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972
0,2015-01-01 00:00:00,0,0,0,0,0
1,2015-01-01 01:00:00,0,0,0,0,0
2,2015-01-01 02:00:00,0,0,0,0,0
3,2015-01-01 03:00:00,0,0,0,0,0
4,2015-01-01 04:00:00,0,0,0,0,0
...,...,...,...,...,...,...
87667,2024-12-31 19:00:00,0,0,0,0,0
87668,2024-12-31 20:00:00,0,0,0,0,0
87669,2024-12-31 21:00:00,0,0,0,0,0
87670,2024-12-31 22:00:00,0,0,0,0,0
87671,2024-12-31 23:00:00,0,0,0,0,0

In [39]:
#columns_table = (inspect(engine).get_columns('power'))

In [40]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [41]:
df

,produced_at,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972
0,2015-01-01 00:00:00,0,0,0,0,0
1,2015-01-01 01:00:00,0,0,0,0,0
2,2015-01-01 02:00:00,0,0,0,0,0
3,2015-01-01 03:00:00,0,0,0,0,0
4,2015-01-01 04:00:00,0,0,0,0,0
...,...,...,...,...,...,...
87667,2024-12-31 19:00:00,0,0,0,0,0
87668,2024-12-31 20:00:00,0,0,0,0,0
87669,2024-12-31 21:00:00,0,0,0,0,0
87670,2024-12-31 22:00:00,0,0,0,0,0
87671,2024-12-31 23:00:00,0,0,0,0,0

In [42]:
CDF = pd.read_sql_table('power', engine2)

In [43]:
CDF.shape

(15252972, 3)

In [44]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [45]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [46]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0526      0
1        2015-01-01 01:00:00          BNA0526      0
2        2015-01-01 02:00:00          BNA0526      0
3        2015-01-01 03:00:00          BNA0526      0
4        2015-01-01 04:00:00          BNA0526      0
...                      ...              ...    ...
15252967 2021-12-31 19:00:00  SEE983645175053      0
15252968 2021-12-31 20:00:00  SEE983645175053      0
15252969 2021-12-31 21:00:00  SEE983645175053      0
15252970 2021-12-31 22:00:00  SEE983645175053      0
15252971 2021-12-31 23:00:00  SEE983645175053      0

[15252972 rows x 3 columns]

In [47]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [48]:
CDF9.iloc[70128]

produced_at    2018-01-01 08:00:00
variable           SEE904194792843
value                            0
Name: 70128, dtype: object

In [49]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

Empty DataFrame
Columns: [produced_at, variable, value]
Index: []

In [50]:
CDF9.shape

(15252972, 3)

In [51]:
#CDF9.iloc[15219136]

In [52]:
CDF9.iloc[929304]

produced_at    2016-01-05 10:00:00
variable           SEE994418588468
value                          135
Name: 929304, dtype: object

In [53]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [54]:
CDF9[CDF9.isnull().any(axis=1)].shape

(0, 3)

In [55]:
#CDF10 = CDF9.dropna()

In [56]:
CDF9["value"] = CDF9["value"].astype(int)

In [57]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [58]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [59]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0526      0
1        2015-01-01 01:00:00          BNA0526      0
2        2015-01-01 02:00:00          BNA0526      0
3        2015-01-01 03:00:00          BNA0526      0
4        2015-01-01 04:00:00          BNA0526      0
...                      ...              ...    ...
15252967 2021-12-31 19:00:00  SEE983645175053      0
15252968 2021-12-31 20:00:00  SEE983645175053      0
15252969 2021-12-31 21:00:00  SEE983645175053      0
15252970 2021-12-31 22:00:00  SEE983645175053      0
15252971 2021-12-31 23:00:00  SEE983645175053      0

[15252972 rows x 3 columns]

In [60]:
#CDF_new = CDF.reset_index(drop=False)

In [61]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [62]:
#CDF_new[CDF_new.produced_at.isnull()]

In [63]:
#CDF_new

In [64]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [65]:
#CDF

In [66]:
#CDF99.set_index('produced_at')

In [67]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [68]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [69]:
#subC1

In [70]:
CDF10 = CDF9.copy()

In [71]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [72]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0526      0
1        2015-01-01 01:00:00          BNA0526      0
2        2015-01-01 02:00:00          BNA0526      0
3        2015-01-01 03:00:00          BNA0526      0
4        2015-01-01 04:00:00          BNA0526      0
...                      ...              ...    ...
15252967 2021-12-31 19:00:00  SEE983645175053      0
15252968 2021-12-31 20:00:00  SEE983645175053      0
15252969 2021-12-31 21:00:00  SEE983645175053      0
15252970 2021-12-31 22:00:00  SEE983645175053      0
15252971 2021-12-31 23:00:00  SEE983645175053      0

[15252972 rows x 3 columns]

In [73]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

In [74]:
CDF2

                                                                      variable  \
variable        produced_at
BNA0140         2015-01-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-02-28   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-03-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-04-30   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-05-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
...                                                                        ...
SEE999117793854 2024-08-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-09-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-10-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-11-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-12-31   SEE999117793854SEE999117793854SEE999117793854S...

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[20928 rows x 2 columns]

In [75]:
CDF3 = CDF2.drop(columns="variable")

In [76]:
CDF3

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[20928 rows x 1 columns]

In [77]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [78]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [79]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [80]:
#gm2

In [81]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [82]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [83]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [84]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [85]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
20923  2024     12  SEE996720450723   51349
20924  2024     12  SEE997719859992   60650
20925  2024     12  SEE998199911088  174857
20926  2024     12  SEE998383491525       0
20927  2024     12  SEE999117793854   14587

[20928 rows x 4 columns]

In [86]:
gm7

       year  month          blockid   power
0      2015      1          BNA0140       0
120    2015      1          BNA0143       0
240    2015      1          BNA0145       0
324    2015      1          BNA0146  129164
696    2015      1          BNA0215       0
...     ...    ...              ...     ...
20447  2024     12  SEE996720450723   51349
20567  2024     12  SEE997719859992   60650
20687  2024     12  SEE998199911088  174857
20807  2024     12  SEE998383491525       0
20927  2024     12  SEE999117793854   14587

[20928 rows x 4 columns]

In [87]:
bpm

                plantid            sseid
0        12-30532000000  SEE969511682320
1     06-05-900-0327252  SEE948351715917
2     14-80-55047380000  SEE986249505394
3     14-80-55047380000  SEE955310827123
4        12-30532000000  SEE939848582457
...                 ...              ...
1127  03-10-10101531850  SEE908658611688
1128  03-10-10285139970  SEE940780197517
1129  06-05-300-0215443  SEE924053403383
1130  06-05-300-0215443  SEE990523934756
1131  06-05-300-0914998  SEE972128015696

[1132 rows x 2 columns]

In [88]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [89]:
pm2

       year  month          blockid   power               plantid
0      2015      1          BNA0140       0  06-04-11_2001178_8_0
1      2015      1          BNA0145       0  06-04-11_2001178_8_1
2      2015      1          BNA0146  129164  06-04-11_2001178_8_1
3      2015      1          BNA0215       0     06-05-100-0365906
4      2015      1         BNA0221c   15020     06-05-100-0167182
...     ...    ...              ...     ...                   ...
19759  2024     12  SEE996720450723   51349   06-09-100-0088-0005
19760  2024     12  SEE997719859992   60650      06-11-01-1105501
19761  2024     12  SEE998199911088  174857     14-80-00009560000
19762  2024     12  SEE998383491525       0         06-08-1195689
19763  2024     12  SEE999117793854   14587     06-05-300-0877384

[19764 rows x 5 columns]

In [90]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [91]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [92]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [93]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

     year            plantid  yearpower
41   2015  06-05-100-0248923   15386816
111  2016  06-05-100-0248923   21812847
182  2017  06-05-100-0248923   22611486
251  2018  06-05-100-0248923   25507220
318  2019  06-05-100-0248923   17881538
381  2020  06-05-100-0248923   14625468
443  2021  06-05-100-0248923   16554636
503  2022  06-05-100-0248923   21857955
562  2023  06-05-100-0248923   15021992
621  2024  06-05-100-0248923   12629202

In [94]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

     year              plantid  yearpower
55   2015  06-09-100-0001-0002     560921
125  2016  06-09-100-0001-0002     204765
196  2017  06-09-100-0001-0002     133508
265  2018  06-09-100-0001-0002      24090
332  2019  06-09-100-0001-0002      37682
395  2020  06-09-100-0001-0002    1734818
458  2021  06-09-100-0001-0002    4187402
518  2022  06-09-100-0001-0002    2498555
577  2023  06-09-100-0001-0002    2856627
633  2024  06-09-100-0001-0002    3445690

In [95]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [96]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [97]:
#invCDF = CDF.pivot(columns='variable')

In [98]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
20923  2024     12  SEE996720450723   51349
20924  2024     12  SEE997719859992   60650
20925  2024     12  SEE998199911088  174857
20926  2024     12  SEE998383491525       0
20927  2024     12  SEE999117793854   14587

[20928 rows x 4 columns]

In [99]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [100]:
pm2

       year  month          blockid   power               plantid
0      2015      1          BNA0140       0  06-04-11_2001178_8_0
1      2015      1          BNA0145       0  06-04-11_2001178_8_1
2      2015      1          BNA0146  129164  06-04-11_2001178_8_1
3      2015      1          BNA0215       0     06-05-100-0365906
4      2015      1         BNA0221c   15020     06-05-100-0167182
...     ...    ...              ...     ...                   ...
19759  2024     12  SEE996720450723   51349   06-09-100-0088-0005
19760  2024     12  SEE997719859992   60650      06-11-01-1105501
19761  2024     12  SEE998199911088  174857     14-80-00009560000
19762  2024     12  SEE998383491525       0         06-08-1195689
19763  2024     12  SEE999117793854   14587     06-05-300-0877384

[19764 rows x 5 columns]

In [101]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [102]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [103]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [104]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

     year            plantid  yearpower
41   2015  06-05-100-0248923   15386816
111  2016  06-05-100-0248923   21812847
182  2017  06-05-100-0248923   22611486
251  2018  06-05-100-0248923   25507220
318  2019  06-05-100-0248923   17881538
381  2020  06-05-100-0248923   14625468
443  2021  06-05-100-0248923   16554636
503  2022  06-05-100-0248923   21857955
562  2023  06-05-100-0248923   15021992
621  2024  06-05-100-0248923   12629202

In [105]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

     year              plantid  yearpower
55   2015  06-09-100-0001-0002     560921
125  2016  06-09-100-0001-0002     204765
196  2017  06-09-100-0001-0002     133508
265  2018  06-09-100-0001-0002      24090
332  2019  06-09-100-0001-0002      37682
395  2020  06-09-100-0001-0002    1734818
458  2021  06-09-100-0001-0002    4187402
518  2022  06-09-100-0001-0002    2498555
577  2023  06-09-100-0001-0002    2856627
633  2024  06-09-100-0001-0002    3445690

In [106]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [107]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [108]:
#invCDF = CDF.pivot(columns='variable')

In [109]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
20923  2024     12  SEE996720450723   51349
20924  2024     12  SEE997719859992   60650
20925  2024     12  SEE998199911088  174857
20926  2024     12  SEE998383491525       0
20927  2024     12  SEE999117793854   14587

[20928 rows x 4 columns]

In [110]:
bpm

                plantid            sseid
0        12-30532000000  SEE969511682320
1     06-05-900-0327252  SEE948351715917
2     14-80-55047380000  SEE986249505394
3     14-80-55047380000  SEE955310827123
4        12-30532000000  SEE939848582457
...                 ...              ...
1127  03-10-10101531850  SEE908658611688
1128  03-10-10285139970  SEE940780197517
1129  06-05-300-0215443  SEE924053403383
1130  06-05-300-0215443  SEE990523934756
1131  06-05-300-0914998  SEE972128015696

[1132 rows x 2 columns]