In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-4]
YEARS = ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [4]:
FOLDERS

['./2015',
 './2016',
 './2017',
 './2018',
 './2019',
 './2020',
 './2021',
 './2022',
 './2023',
 './2024']

In [5]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
#ssem = pd.read_csv("../basic/plant_sse_mapper.csv")
#ssem['plantid'] = ssem['plantid'].apply(lambda x: str(x).replace('/', '_'))

raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

plantslist = list(set(seem['plantid'].to_list()))

/tmp/ipykernel_889020/4204571207.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [6]:
seem

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [7]:
#plantslist

In [8]:
def save2combined(df, plantname):
    df.to_csv("./combined/" + plantname + ".csv", index=False, decimal=',')

In [9]:
def squash_production(plantslist):
    emptyplants = []
    for plant in plantslist:
        #print(plant)
        dflist = []
        for year in YEARS:
            try:
                df = pd.read_csv("./by_plantid/" + year + "/" + plant + ".csv")
                #df.fillna(0, inplace=True)
                df[df.columns[1:]] = df[df.columns[1:]].astype(int)
            except FileNotFoundError:
                print("./by_plantid/" + year + "/" + plant + ".csv")
                df = pd.DataFrame({'produced_at': []})
    
            testdf = df.dropna()
            if testdf.empty:
                emptyplants.append(plant)
            else:
                dflist.append(df)
                
        if len(dflist) > 0:
            newdf = pd.concat(dflist)
            save2combined(newdf, plant)

    return list(set(emptyplants))

In [10]:
a = squash_production(plantslist)

./by_plantid/2015/NI05050072350.csv
./by_plantid/2016/NI05050072350.csv
./by_plantid/2017/NI05050072350.csv
./by_plantid/2018/NI05050072350.csv
./by_plantid/2019/NI05050072350.csv
./by_plantid/2020/NI05050072350.csv
./by_plantid/2021/NI05050072350.csv
./by_plantid/2022/NI05050072350.csv
./by_plantid/2023/NI05050072350.csv
./by_plantid/2024/NI05050072350.csv
./by_plantid/2015/BWpf-450-34064722-00000000.csv
./by_plantid/2016/BWpf-450-34064722-00000000.csv
./by_plantid/2017/BWpf-450-34064722-00000000.csv
./by_plantid/2018/BWpf-450-34064722-00000000.csv
./by_plantid/2019/BWpf-450-34064722-00000000.csv
./by_plantid/2020/BWpf-450-34064722-00000000.csv
./by_plantid/2021/BWpf-450-34064722-00000000.csv
./by_plantid/2022/BWpf-450-34064722-00000000.csv
./by_plantid/2023/BWpf-450-34064722-00000000.csv
./by_plantid/2024/BWpf-450-34064722-00000000.csv
./by_plantid/2015/DE.EEA44708.csv
./by_plantid/2016/DE.EEA44708.csv
./by_plantid/2017/DE.EEA44708.csv
./by_plantid/2018/DE.EEA44708.csv
./by_plantid/2019/DE.EEA44708.csv
./by_plantid/2020/DE.EEA44708.csv
./by_plantid/2021/DE.EEA44708.csv
./by_plantid/2022/DE.EEA44708.csv
./by_plantid/2023/DE.EEA44708.csv
./by_plantid/2024/DE.EEA44708.csv
./by_plantid/2015/NW900-0021170.csv
./by_plantid/2016/NW900-0021170.csv
./by_plantid/2017/NW900-0021170.csv
./by_plantid/2018/NW900-0021170.csv
./by_plantid/2019/NW900-0021170.csv
./by_plantid/2020/NW900-0021170.csv
./by_plantid/2021/NW900-0021170.csv
./by_plantid/2022/NW900-0021170.csv
./by_plantid/2023/NW900-0021170.csv
./by_plantid/2024/NW900-0021170.csv
./by_plantid/2015/BWpf-450-1371304-00000000.csv
./by_plantid/2016/BWpf-450-1371304-00000000.csv
./by_plantid/2017/BWpf-450-1371304-00000000.csv
./by_plantid/2018/BWpf-450-1371304-00000000.csv
./by_plantid/2019/BWpf-450-1371304-00000000.csv
./by_plantid/2020/BWpf-450-1371304-00000000.csv
./by_plantid/2021/BWpf-450-1371304-00000000.csv
./by_plantid/2022/BWpf-450-1371304-00000000.csv
./by_plantid/2023/BWpf-450-1371304-00000000.csv
./by_plantid/2024/BWpf-450-1371304-00000000.csv
./by_plantid/2015/SH10000140.csv
./by_plantid/2016/SH10000140.csv
./by_plantid/2017/SH10000140.csv
./by_plantid/2018/SH10000140.csv
./by_plantid/2019/SH10000140.csv
./by_plantid/2020/SH10000140.csv
./by_plantid/2021/SH10000140.csv
./by_plantid/2022/SH10000140.csv
./by_plantid/2023/SH10000140.csv
./by_plantid/2024/SH10000140.csv
./by_plantid/2015/SD661-77.csv
./by_plantid/2016/SD661-77.csv
./by_plantid/2017/SD661-77.csv
./by_plantid/2018/SD661-77.csv
./by_plantid/2019/SD661-77.csv
./by_plantid/2020/SD661-77.csv
./by_plantid/2021/SD661-77.csv
./by_plantid/2022/SD661-77.csv
./by_plantid/2023/SD661-77.csv
./by_plantid/2024/SD661-77.csv
./by_plantid/2015/HE30000036.csv
./by_plantid/2016/HE30000036.csv
./by_plantid/2017/HE30000036.csv
./by_plantid/2018/HE30000036.csv
./by_plantid/2019/HE30000036.csv
./by_plantid/2020/HE30000036.csv
./by_plantid/2021/HE30000036.csv
./by_plantid/2022/HE30000036.csv
./by_plantid/2023/HE30000036.csv
./by_plantid/2024/HE30000036.csv
./by_plantid/2015/SD661-42.csv
./by_plantid/2016/SD661-42.csv
./by_plantid/2017/SD661-42.csv
./by_plantid/2018/SD661-42.csv
./by_plantid/2019/SD661-42.csv
./by_plantid/2020/SD661-42.csv
./by_plantid/2021/SD661-42.csv
./by_plantid/2022/SD661-42.csv
./by_plantid/2023/SD661-42.csv
./by_plantid/2024/SD661-42.csv
./by_plantid/2024/SD666-18.csv
./by_plantid/2015/NI01227041760.csv
./by_plantid/2016/NI01227041760.csv
./by_plantid/2017/NI01227041760.csv
./by_plantid/2018/NI01227041760.csv
./by_plantid/2019/NI01227041760.csv
./by_plantid/2020/NI01227041760.csv
./by_plantid/2021/NI01227041760.csv
./by_plantid/2022/NI01227041760.csv
./by_plantid/2023/NI01227041760.csv
./by_plantid/2024/NI01227041760.csv
./by_plantid/2015/SD662-28.csv
./by_plantid/2016/SD662-28.csv
./by_plantid/2017/SD662-28.csv
./by_plantid/2018/SD662-28.csv
./by_plantid/2019/SD662-28.csv
./by_plantid/2020/SD662-28.csv
./by_plantid/2021/SD662-28.csv
./by_plantid/2022/SD662-28.csv
./by_plantid/2023/SD662-28.csv
./by_plantid/2024/SD662-28.csv
./by_plantid/2015/BB16018798.csv
./by_plantid/2016/BB16018798.csv
./by_plantid/2017/BB16018798.csv
./by_plantid/2018/BB16018798.csv
./by_plantid/2019/BB16018798.csv
./by_plantid/2020/BB16018798.csv
./by_plantid/2021/BB16018798.csv
./by_plantid/2022/BB16018798.csv
./by_plantid/2023/BB16018798.csv
./by_plantid/2024/BB16018798.csv
./by_plantid/2015/NW700-9073508.csv
./by_plantid/2016/NW700-9073508.csv
./by_plantid/2017/NW700-9073508.csv
./by_plantid/2018/NW700-9073508.csv
./by_plantid/2019/NW700-9073508.csv
./by_plantid/2020/NW700-9073508.csv
./by_plantid/2021/NW700-9073508.csv
./by_plantid/2022/NW700-9073508.csv
./by_plantid/2023/NW700-9073508.csv
./by_plantid/2024/NW700-9073508.csv
./by_plantid/2015/NI07244141350.csv
./by_plantid/2016/NI07244141350.csv
./by_plantid/2017/NI07244141350.csv
./by_plantid/2018/NI07244141350.csv
./by_plantid/2019/NI07244141350.csv
./by_plantid/2020/NI07244141350.csv
./by_plantid/2021/NI07244141350.csv
./by_plantid/2022/NI07244141350.csv
./by_plantid/2023/NI07244141350.csv
./by_plantid/2024/NI07244141350.csv
./by_plantid/2015/NW700-0104479.csv
./by_plantid/2016/NW700-0104479.csv
./by_plantid/2017/NW700-0104479.csv
./by_plantid/2018/NW700-0104479.csv
./by_plantid/2019/NW700-0104479.csv
./by_plantid/2020/NW700-0104479.csv
./by_plantid/2021/NW700-0104479.csv
./by_plantid/2022/NW700-0104479.csv
./by_plantid/2023/NW700-0104479.csv
./by_plantid/2024/NW700-0104479.csv
./by_plantid/2019/NW900-0884101.csv
./by_plantid/2020/NW900-0884101.csv
./by_plantid/2021/NW900-0884101.csv
./by_plantid/2022/NW900-0884101.csv
./by_plantid/2023/NW900-0884101.csv
./by_plantid/2024/NW900-0884101.csv
./by_plantid/2015/SD661-102.csv
./by_plantid/2016/SD661-102.csv
./by_plantid/2017/SD661-102.csv
./by_plantid/2018/SD661-102.csv
./by_plantid/2019/SD661-102.csv
./by_plantid/2020/SD661-102.csv
./by_plantid/2021/SD661-102.csv
./by_plantid/2022/SD661-102.csv
./by_plantid/2023/SD661-102.csv
./by_plantid/2024/SD661-102.csv
./by_plantid/2015/SD661-108.csv
./by_plantid/2016/SD661-108.csv
./by_plantid/2017/SD661-108.csv
./by_plantid/2018/SD661-108.csv
./by_plantid/2019/SD661-108.csv
./by_plantid/2020/SD661-108.csv
./by_plantid/2021/SD661-108.csv
./by_plantid/2022/SD661-108.csv
./by_plantid/2023/SD661-108.csv
./by_plantid/2024/SD661-108.csv
./by_plantid/2015/BYS00904.csv
./by_plantid/2016/BYS00904.csv
./by_plantid/2017/BYS00904.csv
./by_plantid/2018/BYS00904.csv
./by_plantid/2019/BYS00904.csv
./by_plantid/2020/BYS00904.csv
./by_plantid/2021/BYS00904.csv
./by_plantid/2022/BYS00904.csv
./by_plantid/2023/BYS00904.csv
./by_plantid/2024/BYS00904.csv
./by_plantid/2015/NW100-0990908.csv
./by_plantid/2016/NW100-0990908.csv
./by_plantid/2017/NW100-0990908.csv
./by_plantid/2018/NW100-0990908.csv
./by_plantid/2019/NW100-0990908.csv
./by_plantid/2020/NW100-0990908.csv
./by_plantid/2021/NW100-0990908.csv
./by_plantid/2022/NW100-0990908.csv
./by_plantid/2023/NW100-0990908.csv
./by_plantid/2024/NW100-0990908.csv
./by_plantid/2015/NI10257401440.csv
./by_plantid/2016/NI10257401440.csv
./by_plantid/2017/NI10257401440.csv
./by_plantid/2018/NI10257401440.csv
./by_plantid/2019/NI10257401440.csv
./by_plantid/2020/NI10257401440.csv
./by_plantid/2021/NI10257401440.csv
./by_plantid/2022/NI10257401440.csv
./by_plantid/2023/NI10257401440.csv
./by_plantid/2024/NI10257401440.csv
./by_plantid/2015/SD661-19.csv
./by_plantid/2016/SD661-19.csv
./by_plantid/2017/SD661-19.csv
./by_plantid/2018/SD661-19.csv
./by_plantid/2019/SD661-19.csv
./by_plantid/2020/SD661-19.csv
./by_plantid/2021/SD661-19.csv
./by_plantid/2022/SD661-19.csv
./by_plantid/2023/SD661-19.csv
./by_plantid/2024/SD661-19.csv
./by_plantid/2015/NW700-9073419.csv
./by_plantid/2016/NW700-9073419.csv
./by_plantid/2017/NW700-9073419.csv
./by_plantid/2018/NW700-9073419.csv
./by_plantid/2019/NW700-9073419.csv
./by_plantid/2020/NW700-9073419.csv
./by_plantid/2021/NW700-9073419.csv
./by_plantid/2022/NW700-9073419.csv
./by_plantid/2023/NW700-9073419.csv
./by_plantid/2024/NW700-9073419.csv
./by_plantid/2015/SN60018636.csv
./by_plantid/2016/SN60018636.csv
./by_plantid/2017/SN60018636.csv
./by_plantid/2018/SN60018636.csv
./by_plantid/2019/SN60018636.csv
./by_plantid/2020/SN60018636.csv
./by_plantid/2021/SN60018636.csv
./by_plantid/2022/SN60018636.csv
./by_plantid/2023/SN60018636.csv
./by_plantid/2024/SN60018636.csv
./by_plantid/2015/RP5000656.csv
./by_plantid/2016/RP5000656.csv
./by_plantid/2017/RP5000656.csv
./by_plantid/2018/RP5000656.csv
./by_plantid/2019/RP5000656.csv
./by_plantid/2020/RP5000656.csv
./by_plantid/2021/RP5000656.csv
./by_plantid/2022/RP5000656.csv
./by_plantid/2023/RP5000656.csv
./by_plantid/2024/RP5000656.csv
./by_plantid/2015/SD662-10.csv
./by_plantid/2016/SD662-10.csv
./by_plantid/2017/SD662-10.csv
./by_plantid/2018/SD662-10.csv
./by_plantid/2019/SD662-10.csv
./by_plantid/2020/SD662-10.csv
./by_plantid/2021/SD662-10.csv
./by_plantid/2022/SD662-10.csv
./by_plantid/2023/SD662-10.csv
./by_plantid/2024/SD662-10.csv
./by_plantid/2015/ST101086.csv
./by_plantid/2016/ST101086.csv
./by_plantid/2017/ST101086.csv
./by_plantid/2018/ST101086.csv
./by_plantid/2019/ST101086.csv
./by_plantid/2020/ST101086.csv
./by_plantid/2021/ST101086.csv
./by_plantid/2022/ST101086.csv
./by_plantid/2023/ST101086.csv
./by_plantid/2024/ST101086.csv
./by_plantid/2015/ST100032.csv
./by_plantid/2016/ST100032.csv
./by_plantid/2017/ST100032.csv
./by_plantid/2018/ST100032.csv
./by_plantid/2019/ST100032.csv
./by_plantid/2020/ST100032.csv
./by_plantid/2021/ST100032.csv
./by_plantid/2022/ST100032.csv
./by_plantid/2023/ST100032.csv
./by_plantid/2024/ST100032.csv
./by_plantid/2015/NW500-9981505.csv
./by_plantid/2016/NW500-9981505.csv
./by_plantid/2017/NW500-9981505.csv
./by_plantid/2018/NW500-9981505.csv
./by_plantid/2019/NW500-9981505.csv
./by_plantid/2020/NW500-9981505.csv
./by_plantid/2021/NW500-9981505.csv
./by_plantid/2022/NW500-9981505.csv
./by_plantid/2023/NW500-9981505.csv
./by_plantid/2024/NW500-9981505.csv
./by_plantid/2015/NW500-0338944.csv
./by_plantid/2016/NW500-0338944.csv
./by_plantid/2017/NW500-0338944.csv
./by_plantid/2018/NW500-0338944.csv
./by_plantid/2019/NW500-0338944.csv
./by_plantid/2020/NW500-0338944.csv
./by_plantid/2021/NW500-0338944.csv
./by_plantid/2022/NW500-0338944.csv
./by_plantid/2023/NW500-0338944.csv
./by_plantid/2024/NW500-0338944.csv
./by_plantid/2015/ST100864.csv
./by_plantid/2016/ST100864.csv
./by_plantid/2017/ST100864.csv
./by_plantid/2018/ST100864.csv
./by_plantid/2019/ST100864.csv
./by_plantid/2020/ST100864.csv
./by_plantid/2021/ST100864.csv
./by_plantid/2022/ST100864.csv
./by_plantid/2023/ST100864.csv
./by_plantid/2024/ST100864.csv
./by_plantid/2015/TH72012874.csv
./by_plantid/2016/TH72012874.csv
./by_plantid/2017/TH72012874.csv
./by_plantid/2018/TH72012874.csv
./by_plantid/2019/TH72012874.csv
./by_plantid/2020/TH72012874.csv
./by_plantid/2021/TH72012874.csv
./by_plantid/2022/TH72012874.csv
./by_plantid/2023/TH72012874.csv
./by_plantid/2024/TH72012874.csv
./by_plantid/2015/NI09281566110.csv
./by_plantid/2016/NI09281566110.csv
./by_plantid/2017/NI09281566110.csv
./by_plantid/2018/NI09281566110.csv
./by_plantid/2019/NI09281566110.csv
./by_plantid/2020/NI09281566110.csv
./by_plantid/2021/NI09281566110.csv
./by_plantid/2022/NI09281566110.csv
./by_plantid/2023/NI09281566110.csv
./by_plantid/2024/NI09281566110.csv
./by_plantid/2015/BYS00235.csv
./by_plantid/2016/BYS00235.csv
./by_plantid/2017/BYS00235.csv
./by_plantid/2018/BYS00235.csv
./by_plantid/2019/BYS00235.csv
./by_plantid/2020/BYS00235.csv
./by_plantid/2021/BYS00235.csv
./by_plantid/2022/BYS00235.csv
./by_plantid/2023/BYS00235.csv
./by_plantid/2024/BYS00235.csv
./by_plantid/2015/SD661-36.csv
./by_plantid/2016/SD661-36.csv
./by_plantid/2017/SD661-36.csv
./by_plantid/2018/SD661-36.csv
./by_plantid/2019/SD661-36.csv
./by_plantid/2020/SD661-36.csv
./by_plantid/2021/SD661-36.csv
./by_plantid/2022/SD661-36.csv
./by_plantid/2023/SD661-36.csv
./by_plantid/2024/SD661-36.csv
./by_plantid/2015/SD661-97.csv
./by_plantid/2016/SD661-97.csv
./by_plantid/2017/SD661-97.csv
./by_plantid/2018/SD661-97.csv
./by_plantid/2019/SD661-97.csv
./by_plantid/2020/SD661-97.csv
./by_plantid/2021/SD661-97.csv
./by_plantid/2022/SD661-97.csv
./by_plantid/2023/SD661-97.csv
./by_plantid/2024/SD661-97.csv
./by_plantid/2015/SD661-12.csv
./by_plantid/2016/SD661-12.csv
./by_plantid/2017/SD661-12.csv
./by_plantid/2018/SD661-12.csv
./by_plantid/2019/SD661-12.csv
./by_plantid/2020/SD661-12.csv
./by_plantid/2021/SD661-12.csv
./by_plantid/2022/SD661-12.csv
./by_plantid/2023/SD661-12.csv
./by_plantid/2024/SD661-12.csv
./by_plantid/2015/SD661-111.csv
./by_plantid/2016/SD661-111.csv
./by_plantid/2017/SD661-111.csv
./by_plantid/2018/SD661-111.csv
./by_plantid/2019/SD661-111.csv
./by_plantid/2020/SD661-111.csv
./by_plantid/2021/SD661-111.csv
./by_plantid/2022/SD661-111.csv
./by_plantid/2023/SD661-111.csv
./by_plantid/2024/SD661-111.csv
./by_plantid/2015/SD661-78.csv
./by_plantid/2016/SD661-78.csv
./by_plantid/2017/SD661-78.csv
./by_plantid/2018/SD661-78.csv
./by_plantid/2019/SD661-78.csv
./by_plantid/2020/SD661-78.csv
./by_plantid/2021/SD661-78.csv
./by_plantid/2022/SD661-78.csv
./by_plantid/2023/SD661-78.csv
./by_plantid/2024/SD661-78.csv
./by_plantid/2015/DE.EEA46679.csv
./by_plantid/2016/DE.EEA46679.csv
./by_plantid/2017/DE.EEA46679.csv
./by_plantid/2018/DE.EEA46679.csv
./by_plantid/2019/DE.EEA46679.csv
./by_plantid/2020/DE.EEA46679.csv
./by_plantid/2021/DE.EEA46679.csv
./by_plantid/2022/DE.EEA46679.csv
./by_plantid/2023/DE.EEA46679.csv
./by_plantid/2024/DE.EEA46679.csv
./by_plantid/2015/BB23022811.csv
./by_plantid/2016/BB23022811.csv
./by_plantid/2017/BB23022811.csv
./by_plantid/2018/BB23022811.csv
./by_plantid/2019/BB23022811.csv
./by_plantid/2020/BB23022811.csv
./by_plantid/2021/BB23022811.csv
./by_plantid/2022/BB23022811.csv
./by_plantid/2023/BB23022811.csv
./by_plantid/2024/BB23022811.csv
./by_plantid/2015/ST18046.csv
./by_plantid/2016/ST18046.csv
./by_plantid/2017/ST18046.csv
./by_plantid/2018/ST18046.csv
./by_plantid/2019/ST18046.csv
./by_plantid/2020/ST18046.csv
./by_plantid/2021/ST18046.csv
./by_plantid/2022/ST18046.csv
./by_plantid/2023/ST18046.csv
./by_plantid/2024/ST18046.csv
./by_plantid/2015/NI10285139970.csv
./by_plantid/2016/NI10285139970.csv
./by_plantid/2017/NI10285139970.csv
./by_plantid/2018/NI10285139970.csv
./by_plantid/2019/NI10285139970.csv
./by_plantid/2020/NI10285139970.csv
./by_plantid/2021/NI10285139970.csv
./by_plantid/2022/NI10285139970.csv
./by_plantid/2023/NI10285139970.csv
./by_plantid/2024/NI10285139970.csv
./by_plantid/2015/SD661-86.csv
./by_plantid/2016/SD661-86.csv
./by_plantid/2017/SD661-86.csv
./by_plantid/2018/SD661-86.csv
./by_plantid/2019/SD661-86.csv
./by_plantid/2020/SD661-86.csv
./by_plantid/2021/SD661-86.csv
./by_plantid/2022/SD661-86.csv
./by_plantid/2023/SD661-86.csv
./by_plantid/2024/SD661-86.csv
./by_plantid/2015/BWpf-450-1383701-00000000.csv
./by_plantid/2016/BWpf-450-1383701-00000000.csv
./by_plantid/2017/BWpf-450-1383701-00000000.csv
./by_plantid/2018/BWpf-450-1383701-00000000.csv
./by_plantid/2019/BWpf-450-1383701-00000000.csv
./by_plantid/2020/BWpf-450-1383701-00000000.csv
./by_plantid/2021/BWpf-450-1383701-00000000.csv
./by_plantid/2022/BWpf-450-1383701-00000000.csv
./by_plantid/2023/BWpf-450-1383701-00000000.csv
./by_plantid/2024/BWpf-450-1383701-00000000.csv
./by_plantid/2015/SD661-103.csv
./by_plantid/2016/SD661-103.csv
./by_plantid/2017/SD661-103.csv
./by_plantid/2018/SD661-103.csv
./by_plantid/2019/SD661-103.csv
./by_plantid/2020/SD661-103.csv
./by_plantid/2021/SD661-103.csv
./by_plantid/2022/SD661-103.csv
./by_plantid/2023/SD661-103.csv
./by_plantid/2024/SD661-103.csv
./by_plantid/2015/BE166927.csv
./by_plantid/2016/BE166927.csv
./by_plantid/2017/BE166927.csv
./by_plantid/2018/BE166927.csv
./by_plantid/2019/BE166927.csv
./by_plantid/2020/BE166927.csv
./by_plantid/2021/BE166927.csv
./by_plantid/2022/BE166927.csv
./by_plantid/2023/BE166927.csv
./by_plantid/2024/BE166927.csv
./by_plantid/2015/SD662-17.csv
./by_plantid/2016/SD662-17.csv
./by_plantid/2017/SD662-17.csv
./by_plantid/2018/SD662-17.csv
./by_plantid/2019/SD662-17.csv
./by_plantid/2020/SD662-17.csv
./by_plantid/2021/SD662-17.csv
./by_plantid/2022/SD662-17.csv
./by_plantid/2023/SD662-17.csv
./by_plantid/2024/SD662-17.csv
./by_plantid/2015/RP4000041.csv
./by_plantid/2016/RP4000041.csv
./by_plantid/2017/RP4000041.csv
./by_plantid/2018/RP4000041.csv
./by_plantid/2019/RP4000041.csv
./by_plantid/2020/RP4000041.csv
./by_plantid/2021/RP4000041.csv
./by_plantid/2022/RP4000041.csv
./by_plantid/2023/RP4000041.csv
./by_plantid/2024/RP4000041.csv
./by_plantid/2015/BYS00135.csv
./by_plantid/2016/BYS00135.csv
./by_plantid/2017/BYS00135.csv
./by_plantid/2018/BYS00135.csv
./by_plantid/2019/BYS00135.csv
./by_plantid/2020/BYS00135.csv
./by_plantid/2021/BYS00135.csv
./by_plantid/2022/BYS00135.csv
./by_plantid/2023/BYS00135.csv
./by_plantid/2024/BYS00135.csv
./by_plantid/2022/SN80011256.csv
./by_plantid/2023/SN80011256.csv
./by_plantid/2024/SN80011256.csv
./by_plantid/2015/HH4383.csv
./by_plantid/2016/HH4383.csv
./by_plantid/2017/HH4383.csv
./by_plantid/2018/HH4383.csv
./by_plantid/2019/HH4383.csv
./by_plantid/2020/HH4383.csv
./by_plantid/2021/HH4383.csv
./by_plantid/2022/HH4383.csv
./by_plantid/2023/HH4383.csv
./by_plantid/2024/HH4383.csv
./by_plantid/2015/NW300-0838652.csv
./by_plantid/2016/NW300-0838652.csv
./by_plantid/2017/NW300-0838652.csv
./by_plantid/2018/NW300-0838652.csv
./by_plantid/2019/NW300-0838652.csv
./by_plantid/2020/NW300-0838652.csv
./by_plantid/2021/NW300-0838652.csv
./by_plantid/2022/NW300-0838652.csv
./by_plantid/2023/NW300-0838652.csv
./by_plantid/2024/NW300-0838652.csv
./by_plantid/2015/SN80011250.csv
./by_plantid/2016/SN80011250.csv
./by_plantid/2017/SN80011250.csv
./by_plantid/2018/SN80011250.csv
./by_plantid/2019/SN80011250.csv
./by_plantid/2020/SN80011250.csv
./by_plantid/2021/SN80011250.csv
./by_plantid/2022/SN80011250.csv
./by_plantid/2023/SN80011250.csv
./by_plantid/2024/SN80011250.csv
./by_plantid/2015/SD661-105.csv
./by_plantid/2016/SD661-105.csv
./by_plantid/2017/SD661-105.csv
./by_plantid/2018/SD661-105.csv
./by_plantid/2019/SD661-105.csv
./by_plantid/2020/SD661-105.csv
./by_plantid/2021/SD661-105.csv
./by_plantid/2022/SD661-105.csv
./by_plantid/2023/SD661-105.csv
./by_plantid/2024/SD661-105.csv
./by_plantid/2015/SD661-109.csv
./by_plantid/2016/SD661-109.csv
./by_plantid/2017/SD661-109.csv
./by_plantid/2018/SD661-109.csv
./by_plantid/2019/SD661-109.csv
./by_plantid/2020/SD661-109.csv
./by_plantid/2021/SD661-109.csv
./by_plantid/2022/SD661-109.csv
./by_plantid/2023/SD661-109.csv
./by_plantid/2024/SD661-109.csv
./by_plantid/2015/NI02221253020.csv
./by_plantid/2016/NI02221253020.csv
./by_plantid/2017/NI02221253020.csv
./by_plantid/2018/NI02221253020.csv
./by_plantid/2019/NI02221253020.csv
./by_plantid/2020/NI02221253020.csv
./by_plantid/2021/NI02221253020.csv
./by_plantid/2022/NI02221253020.csv
./by_plantid/2023/NI02221253020.csv
./by_plantid/2024/NI02221253020.csv
./by_plantid/2015/ST100498.csv
./by_plantid/2016/ST100498.csv
./by_plantid/2017/ST100498.csv
./by_plantid/2018/ST100498.csv
./by_plantid/2019/ST100498.csv
./by_plantid/2020/ST100498.csv
./by_plantid/2021/ST100498.csv
./by_plantid/2022/ST100498.csv
./by_plantid/2023/ST100498.csv
./by_plantid/2024/ST100498.csv
./by_plantid/2015/ST100850.csv
./by_plantid/2016/ST100850.csv
./by_plantid/2017/ST100850.csv
./by_plantid/2018/ST100850.csv
./by_plantid/2019/ST100850.csv
./by_plantid/2020/ST100850.csv
./by_plantid/2021/ST100850.csv
./by_plantid/2022/ST100850.csv
./by_plantid/2023/ST100850.csv
./by_plantid/2024/ST100850.csv
./by_plantid/2015/SH10039818.csv
./by_plantid/2016/SH10039818.csv
./by_plantid/2017/SH10039818.csv
./by_plantid/2018/SH10039818.csv
./by_plantid/2019/SH10039818.csv
./by_plantid/2020/SH10039818.csv
./by_plantid/2021/SH10039818.csv
./by_plantid/2022/SH10039818.csv
./by_plantid/2023/SH10039818.csv
./by_plantid/2024/SH10039818.csv
./by_plantid/2015/BWpf-450-1479296-00000000.csv
./by_plantid/2016/BWpf-450-1479296-00000000.csv

In [11]:
len(plantslist)

355

In [12]:
len(a)

301

In [13]:
errorset = []
for plant in plantslist:
    dflist = []
    for year in YEARS:
        df = pd.DataFrame()
        try:
            df = pd.read_csv("./by_plantid/" + year + "/" + plant + ".csv", na_values=['-'])
        except FileNotFoundError:
            if (plant not in errorset):
                errorset.append(plant)
            pass
        
        dflist.append(df)
    newdf = pd.concat(dflist)
    #print(newdf.shape)
print(errorset)

['NI05050072350', 'BWpf-450-34064722-00000000', 'DE.EEA44708', 'NW900-0021170', 'BWpf-450-1371304-00000000', 'SH10000140', 'SD661-77', 'HE30000036', 'SD661-42', 'SD666-18', 'NI01227041760', 'SD662-28', 'BB16018798', 'NW700-9073508', 'NI07244141350', 'NW700-0104479', 'NW900-0884101', 'SD661-102', 'SD661-108', 'BYS00904', 'NW100-0990908', 'NI10257401440', 'SD661-19', 'NW700-9073419', 'SN60018636', 'RP5000656', 'SD662-10', 'ST101086', 'ST100032', 'NW500-9981505', 'NW500-0338944', 'ST100864', 'TH72012874', 'NI09281566110', 'BYS00235', 'SD661-36', 'SD661-97', 'SD661-12', 'SD661-111', 'SD661-78', 'DE.EEA46679', 'BB23022811', 'ST18046', 'NI10285139970', 'SD661-86', 'BWpf-450-1383701-00000000', 'SD661-103', 'BE166927', 'SD662-17', 'RP4000041', 'BYS00135', 'SN80011256', 'HH4383', 'NW300-0838652', 'SN80011250', 'SD661-105', 'SD661-109', 'NI02221253020', 'ST100498', 'ST100850', 'SH10039818', 'BWpf-450-1479296-00000000', 'SD662-03', 'DE.EEA44322', 'HE30000963', 'BWpf-450-9840001-00000000', 'SD661-53', 'DE.EEA255737', 'SD661-81', 'SD661-113', 'SD661-101', 'SD661-93', 'NW800-0197054', 'SD661-66', 'BYS00925', 'BYS00045', 'NW100-0989137', '16-30-31400103005', 'ST100876', 'SD664-02', 'SD661-17', 'BE172368', 'NI04247180070', 'SN70015959', 'NI01010959490', 'NW100-0031758', 'NI06277201660', 'SD661-64', 'DE.EEA43436', 'SD661-43', 'SD662-14', 'BWpf-450-2951606-00000000', 'BYS00758', 'SD662-98', 'BYS00860', 'NI04224004080', 'MV50000071', 'SD661-29', 'NW700-0020290', 'SD661-38', 'TH86012942', 'HH11643', 'NW500-0875785', 'SD661-16', 'BYS00505', 'NW300-0054298', 'SD661-54', 'MV60004960', 'NI10101531850', 'SD662-06', 'SD661-96', 'NI05231382180', 'HE50000118', 'NW300-0890760', 'BYS00869', 'BB45026985', 'BYS00149', 'NI01211092310', 'SD662-12', 'ST100674', 'NW100-0036701', 'BWpf-450-4666496-00000000', 'SD661-63', 'BB16012651', 'BWpf-450-1574906-00000000', 'HE20000004', 'SD662-18', 'SD661-110', 'HE20000115', 'HE30000163', 'HE50002119', 'RP4000021', 'BYS00334', 'BYS00104', 'SD661-09', 'SD666-11', 'BE173145', 'BE132279', 'BYS00719', '06-05-100-0853075', 'MV60004935', 'SD661-39', 'HE80000333', 'NW100-0018507', 'NI08271405180', 'BWpf-450-3610519-00000000', 'NW100-0387357', 'NI10100029340', 'BYS00471', 'BYS00311', 'NI09000237910', 'SD661-90', 'NW300-0213768', 'SH50080412', 'SD662-99', 'SD661-106', 'NW100-0154540', 'BYS01153', 'SD661-11', 'MV40000004', 'NW300-0215443', 'SD666-12', 'DE.EEA44484', 'SH50080603', 'SD662-01', 'NI01010157480', 'SD661-79', 'NW300-0215520', 'SL0075248-G', 'SD661-15', 'TH30013152', 'SD666-17', 'NI03030273580', 'SD661-87', 'NW100-0042820', 'SD669-01', 'HE50001960', 'SD661-59', 'SD662-11', 'NW100-0888309', 'BYS00708', 'BYS00845', 'NW300-0079450', 'SD666-13', 'BB23020389', 'BYS00282', 'NW900-0079017', 'SD661-65', '06-05-100-0030723', 'NW900-0045033', 'SD661-67', 'NW500-0915123', 'SD661-115', 'NI07244473830', 'SD661-80', 'BB45025575', 'HE50002167', 'DE.EEA46609', 'SD661-89', 'BWpf-450-4124448-00000000', 'BE222276', 'SD664-07', 'HB06-04-11_2000122_0_0', 'SD666-14', 'SN70015917', 'SD661-44', 'SH50082038', 'BWpf-450-2948214-00000000', 'SD666-16', 'SD661-84', 'RP5000031', 'HE50002124', 'BYS00064', 'BE173097', 'BWpf-450-3042693-00000000', 'SN80011266', 'HE30000030', 'NW100-9020309', 'SD661-75', 'BYS00233', 'HE50000213', 'BYS00056', 'SD662-22', 'BYS00894', 'NI09281337040', 'SD661-83', 'NW900-0080266', 'NI02020049510', 'SD661-37', 'SD661-82', 'HE50002126', 'BYS00995', 'ST101071', 'SN70015792', 'BYS00998', 'DE.EEA2514', 'SD661-28', 'TH62013494', 'SD661-91', 'SD661-99', 'ST100419', 'NW100-0501870', 'NW300-0181417', 'SD661-107', 'BWpf-450-2719371-00000000', 'BYS00035', 'ST100344', 'NW900-0888950', 'SD662-20', 'NW900-0235121', 'DE.EEA255206', 'RP1000136', 'NI01244641360', 'SD666-15', 'BWpf-450-80920445-00000000', 'MV90031941', 'HH12275', 'NW300-0072412', 'NI03267770260', 'BE181711', 'SD661-100', 'SD661-14', 'BB45026224', 'NW100-9021016', '06-05-100-0431554', 'RP5000152', 'DE.EEA43267', 'RP4000050', 'NI06060116320', 'NW300-0907015', 'NW300-9046797', 'NW100-0030712', 'SD662-09', 'SD661-13', 'ST100609', 'NW900-0271161', 'SD661-92', 'NI01012110180', 'SD661-112', 'SD661-85', 'SD661-88', 'BYS00323', 'ST102622', 'BE172656', 'BYS00291', 'NI09261732970', 'MV30000298', 'DE.EEA46617', 'SD661-98', 'NI31000005008', 'SN60015149', 'SH50083712', 'NW700-0008683', 'HH12273', 'NW100-0046639', 'DE.EEA44408', 'RP5000221', 'NW900-0001413', 'SD661-95', 'DE.EEA46983', 'BYS00108']

In [14]:
newdf

Empty DataFrame
Columns: []
Index: []

In [15]:
True if '06-05-500-0915123' in errorset else False

False