In [91]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect

In [92]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [93]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [94]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [95]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
plantslist = list(set(bpm['plantid'].to_list()))

In [96]:
plantslist.remove('661-94')
plantslist.remove('661-10')

plantslist.remove('07-05-8290552')
plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [97]:
#refpl = "03-01-01241117210.csv"

In [98]:
#df = pd.read_csv("./combined/" + refpl)

In [99]:
#df

In [187]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [188]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [189]:
engine = create_engine('sqlite://', echo=False)

In [192]:
#2023-12-31 19:00:00.000000

In [191]:
counter = 0
for plant in plantslist:
    #print(plant)
    try:
        #print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv")
        try: #, format='%d.%m.%Y %H:%M'
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            df['produced_at'] = df['produced_at'].map(return_date)
        except ValueError:
            print(plant + "faulty")
            pass
        melt = df.melt(id_vars='produced_at')
        melt.to_sql('power', con=engine, if_exists='append')
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

661-103
06-05-900-0021170
661-53
03-10-10100029340
661-90
15397
661-39
06-09-100-0003-0003
06-09-100-0003-0003faulty
661-06
06-10-00100999
13-60-80407
06-08-2948214
06-04-11_2039669_2_0
661-18
661-18faulty
14326
03-06-06254353820
661-85
06-00176010435
14-70-46630660001
06-05-100-0990908
661-98
662-20
06-05-700-0105516
06-05-300-0072412
06-09-100-0088-0003
661-84
661-12
661-100
662-14
01-50-02000283604
13-50-138
06-11-01-1105608
661-80
06-08-3610519
06-05-900-0327252
07-05-8153238
661-108
661-78
661-95
14-20-48821410003
661-105
06-11-01-1105602
06-00464020412
06-09-271-0260-0001
661-16
06-05-100-0888309
06-05-100-9021016
06-10-00101003
06-09-500-0368-0001
06-08-1741292
06-05-100-0030712
13-30-2102110
06-05-500-0875741
03-04-04224004080
06-05-112-0458158
03-09-09000237910
11975
06-02-B2A100H003
661-14
666-18
06-05-100-0501870
666-17
06-09-600-0025-0001
06-05-300-0079450
06-05-100-0431554
16-62-09401231000
07-01-126351
661-66
661-03
661-63
06-00453010412
16-30-31400103005
661-17
06-08-1383701
06-05-300-0907015
666-11
661-54
661-99
06-00464010412
06-90032200632
661-13
03-05-05050072350
06-09-761-0026-0001
06-10-0075248
06-05-300-9046030
12-40710010000
03-10-10257673950
06-09-178-0722-0001
03-05-05231382180
03-31-31000005008
06-09-100-0001-0002
06-09-190-0036-0002
14-70-51322590000
12-40716440000
06-05-500-9981505
06-05-900-0125939
06-05-900-0125939faulty
06-05-300-0215520
06-08-1195689
06-02-B10117A007
18038
06-50940010414
06-05-100-0229264
18037
13-60-80624
661-115
03-07-07244141350
06-90031210632
06-05-900-0080266
664-02
661-93
06-09-600-0009-0001
16591
06-11-01-1105603
661-87
06-05-800-0197010
16874
662-17
06-05-100-0154540
06-05-300-0838652
06-05-100-9020309
06-05-500-0915123
14-80-55047380000
661-42
06-76400010631
06-05-100-0031758
14-60-48821410003
661-43
662-11
03-06-06060316030
06-05-900-0001413
03-07-07244473830
06-11-01-1105609
13-40-1300408
662-09
06-05-100-0248923
06-08-2951606
06-10-0020157
666-13
06-09-171-0009-0B01
01-50-56050192711
06-08-2719371
06-04-11_2001178_8_0
06-09-187-4048-0001
06-05-500-0342658
06-05-500-0342658faulty
06-05-300-0054298
06-10-00101000
06-08-4666496
661-92
03-09-09281337040
06-08-3042693
03-01-01012110180
06-08-4380932
661-65
06-05-900-9141660
03-01-01244641360
12-40669070000
661-36
661-101
661-91
03-09-09281566110
13-30-1010101
03-01-01010157480
661-77
662-28
06-05-500-0338944
06-09-564-0555-0001
14-80-00009560000
14-80-00009560000faulty
16873
661-07
16-30-30400102003
06-05-300-9046797
06-09-100-0020-0001
06-19200010636
03-10-10257401440
03-01-01241117210
661-107
661-59
661-110
662-12
14-30-56918040000
661-88
12-60510410000
06-02-B28903H003
03-01-01010098080
06-05-100-0018507
662-22
03-01-01010959490
662-10
03-09-09261732970
661-75
06-09-661-0020-0001
06-05-100-0989137
06-09-171-0002--C01
06-02-BERZ003800
03-02-02020049510
661-89
06-05-700-0008683
06-05-900-0884101
661-113
661-104
06-00059010413
18040
06-11-01-1105502
662-18
661-64
13770
06-05-900-0865327
661-19
06-05-300-0890760
12-40520430000
06-09-362-0100-0001
12-20730670000
12342
18042
06-05-900-9140178
06-04-11_2001178_8_1
661-96
03-01-01010356620
03-06-06060116320
662-06
661-81
06-05-900-0045033
666-12
06-09-674-2071-0001
06-05-300-0326774
06-05-300-0923949
669-01
06-05-900-0271161
01-50-01000004838
666-15
06-11-01-1105503
661-111
06-05-100-0365906
06-08-34064722
12110
661-37
661-83
03-02-02221253020
06-05-900-0205103
06-09-273-0310-0001
06-11-01-1105607
06-09-500-0354-0002
661-38
661-112
06-09-100-0088-0001
661-82
03-03-03267770260
06-09-671-0140-0001
07-04-6021280
06-04-11_2001178_8_2
06-05-900-0888950
06-05-300-0370387
06-05-300-0213768
06-11-01-1105501
662-03
03-03-03030273580
06-05-800-0203946
06-05-300-0181417
06-14600010611
06-09-187-4135-0001
06-05-900-0079017
06-05-700-9073419
06-05-700-0020290
661-29
664-07
06-05-800-0197054
14-20-60319980000
06-05-100-0167182
661-86
666-14
03-08-08271405180
06-05-300-9002708
06-08-1020129
06-05-100-0387357
06-05-100-0853075
661-15
06-00004310411
06-08-4124448
662-01
661-44
06-08-9840001
06-11-01-1105604
06-00000130433
07-05-8030815
06-08-2797933
06-26200010633
01-50-04000082392
12-50724070000
06-09-500-0112-0001
06-08-2142201
06-08-2142201faulty
06-09-162-0025-0001
06-09-676-2101-0002
661-97
06-05-100-0030723
14-70-52316700250
12-30532000000
661-11
06-08-1574906
661-109
12358
06-05-300-0877384
06-09-261-0007-0041
06-09-100-0088-0005
13-60-34101
661-09
06-05-700-0090319
661-67
12305
07-04-6048443
07-05-8779480
06-09-279-0013-0001
06-05-900-0235121
661-28
06-08-1479296
06-08-1371304
666-16
661-106
661-102
06-05-900-0320357
661-79
69

In [106]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [193]:
df

               produced_at  SEE943690268513
0      2015-01-01 00:00:00                0
1      2015-01-01 01:00:00                0
2      2015-01-01 02:00:00                0
3      2015-01-01 03:00:00                0
4      2015-01-01 04:00:00                0
...                    ...              ...
78883  2023-12-31 19:00:00                0
78884  2023-12-31 20:00:00                0
78885  2023-12-31 21:00:00                0
78886  2023-12-31 22:00:00                0
78887  2023-12-31 23:00:00                0

[78888 rows x 2 columns]

In [194]:
columns_table = (inspect(engine).get_columns('power'))

In [195]:
for c in columns_table :
    print(c['name'], c['type'])

index BIGINT
produced_at TEXT
variable TEXT
value BIGINT

In [196]:
df

               produced_at  SEE943690268513
0      2015-01-01 00:00:00                0
1      2015-01-01 01:00:00                0
2      2015-01-01 02:00:00                0
3      2015-01-01 03:00:00                0
4      2015-01-01 04:00:00                0
...                    ...              ...
78883  2023-12-31 19:00:00                0
78884  2023-12-31 20:00:00                0
78885  2023-12-31 21:00:00                0
78886  2023-12-31 22:00:00                0
78887  2023-12-31 23:00:00                0

[78888 rows x 2 columns]

In [197]:
CDF = pd.read_sql_table('power', engine)

In [198]:
CDF.shape

(15131470, 4)

In [115]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [199]:
CDF9 = CDF.drop(columns=['index'])

In [200]:
CDF9

                  produced_at         variable  value
0         2015-01-01 00:00:00  SEE949509046600      0
1         2015-01-01 01:00:00  SEE949509046600      0
2         2015-01-01 02:00:00  SEE949509046600      0
3         2015-01-01 03:00:00  SEE949509046600      0
4         2015-01-01 04:00:00  SEE949509046600      0
...                       ...              ...    ...
15131465  2023-12-31 19:00:00  SEE943690268513      0
15131466  2023-12-31 20:00:00  SEE943690268513      0
15131467  2023-12-31 21:00:00  SEE943690268513      0
15131468  2023-12-31 22:00:00  SEE943690268513      0
15131469  2023-12-31 23:00:00  SEE943690268513      0

[15131470 rows x 3 columns]

In [141]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [257]:
CDF9.iloc[70128]

produced_at                 01
variable       SEE949509046600
value                        0
Name: 70128, dtype: object

In [259]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

      produced_at         variable  value
74933          00  SEE949509046600      0
70128          01  SEE949509046600      0
73751          01  SEE949509046600      0
73030          01  SEE949509046600      0
73029          01  SEE949509046600      0
...           ...              ...    ...
75946          31  SEE949509046600      0
75947          31  SEE949509046600      0
75948          31  SEE949509046600      0
70848          31  SEE949509046600      0
78886          31  SEE949509046600      0

[87671 rows x 3 columns]

In [202]:
CDF9.shape

(15131470, 3)

In [204]:
#CDF9.iloc[15219136]

In [ ]:
CDF9.iloc[30262935]

In [145]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [146]:
CDF9[CDF9.isnull().any(axis=1)].shape

(0, 3)

In [147]:
#CDF10 = CDF9.dropna()

In [148]:
CDF9["value"] = CDF9["value"].astype(int)

In [248]:
CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [249]:
CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [250]:
CDF9

                  produced_at         variable  value
0         2015-01-01 00:00:00  SEE949509046600      0
1         2015-01-01 01:00:00  SEE949509046600      0
2         2015-01-01 02:00:00  SEE949509046600      0
3         2015-01-01 03:00:00  SEE949509046600      0
4         2015-01-01 04:00:00  SEE949509046600      0
...                       ...              ...    ...
15131465  2023-12-31 19:00:00  SEE943690268513      0
15131466  2023-12-31 20:00:00  SEE943690268513      0
15131467  2023-12-31 21:00:00  SEE943690268513      0
15131468  2023-12-31 22:00:00  SEE943690268513      0
15131469  2023-12-31 23:00:00  SEE943690268513      0

[15131470 rows x 3 columns]

In [231]:
#CDF_new = CDF.reset_index(drop=False)

In [232]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [233]:
#CDF_new[CDF_new.produced_at.isnull()]

In [234]:
#CDF_new

In [235]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [236]:
#CDF

In [237]:
#CDF99.set_index('produced_at')

In [238]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [239]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [240]:
#subC1

In [251]:
CDF10 = CDF9.copy()

In [256]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at'], format='mixed') #, errors='coerce'

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 01, at position 70128

In [254]:
CDF10

                  produced_at         variable  value
0         2015-01-01 00:00:00  SEE949509046600      0
1         2015-01-01 01:00:00  SEE949509046600      0
2         2015-01-01 02:00:00  SEE949509046600      0
3         2015-01-01 03:00:00  SEE949509046600      0
4         2015-01-01 04:00:00  SEE949509046600      0
...                       ...              ...    ...
15131465  2023-12-31 19:00:00  SEE943690268513      0
15131466  2023-12-31 20:00:00  SEE943690268513      0
15131467  2023-12-31 21:00:00  SEE943690268513      0
15131468  2023-12-31 22:00:00  SEE943690268513      0
15131469  2023-12-31 23:00:00  SEE943690268513      0

[15131470 rows x 3 columns]

In [255]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

In [ ]:
CDF2

In [ ]:
CDF3 = CDF2.drop(columns="variable")

In [ ]:
CDF3

In [ ]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [ ]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [ ]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [ ]:
#gm2

In [ ]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [ ]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [ ]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [ ]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [ ]:
gm8

In [ ]:
gm7

In [ ]:
bpm

In [ ]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [214]:
pm2

      year  month          blockid   power              plantid  plantpower
0     2015      1          BNA0333       0    06-05-500-0342658      171025
1     2015      1          BNA0334       0    06-05-500-0342658      171025
2     2015      1          BNA0335       0    06-05-500-0342658      171025
3     2015      1  SEE911613995433    2383        06-08-2142201        2383
4     2015      1  SEE913556136355       0               661-18           0
...    ...    ...              ...     ...                  ...         ...
1675  2024     12  SEE952352206145       0    06-05-500-0342658           0
1676  2024     12  SEE958847865460   92161  06-09-100-0003-0003       92161
1677  2024     12  SEE964114029633       0        06-08-2142201        3027
1678  2024     12  SEE966331411864  443247    14-80-00009560000      618104
1679  2024     12  SEE998199911088  174857    14-80-00009560000      618104

[1680 rows x 6 columns]

In [215]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [216]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [217]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [218]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [219]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [220]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [221]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [222]:
#invCDF = CDF.pivot(columns='variable')

In [223]:
gm8

      year  month          blockid   power
0     2015      1          BNA0333       0
1     2015      1          BNA0334       0
2     2015      1          BNA0335       0
3     2015      1  SEE911613995433    2383
4     2015      1  SEE913556136355       0
...    ...    ...              ...     ...
1795  2024     12  SEE952352206145       0
1796  2024     12  SEE958847865460   92161
1797  2024     12  SEE964114029633       0
1798  2024     12  SEE966331411864  443247
1799  2024     12  SEE998199911088  174857

[1800 rows x 4 columns]

In [224]:
bpm

                 plantid            sseid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
3      14-80-55047380000  SEE955310827123
4         12-30532000000  SEE939848582457
..                   ...              ...
936    06-05-300-9046797  SEE976489828827
937               664-07  SEE906830618081
938               664-02  SEE999977738880
939        07-05-8030815  SEE957723162266
940  06-09-661-0020-0001         BNA1337a

[941 rows x 2 columns]