In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [4]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [5]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
plantslist = list(set(bpm['plantid'].to_list()))

In [6]:
plantslist.remove('661-94')
plantslist.remove('661-10')

plantslist.remove('07-05-8290552')
plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [7]:
#refpl = "03-01-01241117210.csv"

In [8]:
#df = pd.read_csv("./combined/" + refpl)

In [9]:
#df

In [10]:
engine = create_engine('sqlite://', echo=False)

In [11]:
counter = 0
for plant in plantslist:
    #print(plant)
    try:
        print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv")
        try:
            df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')
        except ValueError:
            print(plant + "faulty")
        melt = df.melt(id_vars='produced_at')
        melt.to_sql('power', con=engine, if_exists='append')
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

13-60-80624
666-11
661-103
06-09-261-0007-0041
661-44
13-50-138
06-05-300-0877384
661-07
06-05-900-0327252
06-05-300-0838652
06-11-01-1105607
03-10-10257673950
662-06
14-70-51322590000
661-93
06-05-700-0090319
12-40520430000
661-107
03-06-06254353820
13-30-1010101
666-16
06-08-1741292
06-09-187-4048-0001
661-16
06-05-900-0865327
661-100
03-06-06060116320
661-82
661-77
07-05-8153238
03-02-02221253020
661-95
01-50-02000283604
06-10-00100999
13-60-80407
662-17
06-08-34064722
661-06
661-110
12-40710010000
06-05-500-0915123
06-05-900-0045033
06-05-100-0431554
06-08-2142201
661-86
661-11
06-09-171-0009-0B01
06-11-01-1105602
661-104
07-05-8779480
06-09-271-0260-0001
664-02
666-17
03-09-09281337040
662-20
666-13
662-10
662-14
12-50724070000
12110
06-05-900-0320357
06-11-01-1105604
06-09-187-4135-0001
661-80
661-113
03-01-01010098080
16-30-30400102003
661-115
06-19200010636
06-05-500-0875741
06-00000130433
12-60510410000
661-109
03-04-04224004080
16-30-31400103005
661-112
06-10-0020157
06-05-900-0080266
14-80-55047380000
661-67
06-08-1371304
03-03-03030273580
06-26200010633
06-14600010611
06-09-500-0368-0001
06-09-273-0310-0001
07-05-8030815
06-08-3610519
06-04-11_2001178_8_0
662-11
662-22
13-40-1300408
06-05-900-9141660
661-14
06-00004310411
06-10-00101003
06-05-900-0125939
07-04-6048443
661-102
06-09-500-0354-0002
06-05-100-0030723
06-05-700-9073419
661-105
06-09-600-0009-0001
14-70-52316700250
06-11-01-1105501
06-09-100-0003-0003
06-08-2797933
06-08-3042693
06-05-112-0458158
06-05-300-0370387
06-09-362-0100-0001
06-05-300-9046030
06-09-178-0722-0001
06-05-300-0054298
18037
661-36
06-00464010412
661-53
661-96
03-03-03267770260
03-10-10100029340
16874
06-04-11_2039669_2_0
661-101
03-01-01010157480
18040
661-85
06-10-0075248
06-05-300-0079450
661-12
03-05-05231382180
06-76400010631
14-30-56918040000
14-60-48821410003
06-08-4380932
06-05-900-0271161
06-05-900-9140178
661-98
03-31-31000005008
18042
03-06-06060316030
06-08-2951606
661-19
661-37
661-97
662-01
06-05-900-0021170
662-28
661-13
06-05-100-0030712
06-09-171-0002--C01
03-02-02020049510
01-50-01000004838
07-04-6021280
12-40716440000
06-05-700-0105516
06-05-100-9020309
12305
06-05-100-0387357
01-50-56050192711
03-01-01010356620
06-05-500-0342658
06-02-B28903H003
06-05-900-0205103
661-66
661-15
661-89
662-12
661-83
14-70-46630660001
06-08-1383701
06-05-900-0884101
11975
18038
06-09-100-0088-0003
06-08-1479296
06-11-01-1105608
661-92
06-00176010435
13-30-2102110
661-65
661-79
06-05-100-0154540
06-08-1574906
12-20730670000
13-60-34101
661-111
06-00464020412
661-75
666-14
06-05-300-0181417
06-04-11_2001178_8_2
06-05-500-0338944
06-09-564-0555-0001
01-50-04000082392
06-09-671-0140-0001
03-08-08271405180
03-01-01012110180
06-05-300-0326774
661-09
661-99
12342
06-05-100-0365906
661-29
06-05-300-9002708
661-108
06-08-4666496
06-04-11_2001178_8_1
06-11-01-1105502
06-50940010414
661-43
06-09-100-0001-0002
06-11-01-1105603
14326
06-09-100-0020-0001
06-05-500-9981505
06-05-900-0888950
06-09-674-2071-0001
661-17
03-07-07244141350
661-64
06-02-B2A100H003
06-09-190-0036-0002
661-81
12358
06-05-100-0248923
03-01-01244641360
16591
06-05-300-0215520
06-05-700-0008683
06-08-2948214
06-05-100-0989137
14-80-00009560000
06-08-4124448
14-20-48821410003
06-09-100-0088-0005
06-05-900-0001413
12-30532000000
03-10-10257401440
03-01-01010959490
03-09-09261732970
661-54
664-07
16-62-09401231000
06-11-01-1105609
662-18
13770
661-78
06-90032200632
16873
06-05-800-0197054
03-01-01241117210
06-90031210632
06-00453010412
662-09
12-40669070000
03-09-09281566110
662-03
07-01-126351
06-05-100-0018507
06-09-500-0112-0001
666-15
661-39
06-05-800-0197010
661-84
669-01
06-09-661-0020-0001
06-10-00101000
661-87
06-09-676-2101-0002
661-42
06-05-100-0888309
06-05-700-0020290
666-12
03-09-09000237910
06-09-279-0013-0001
03-05-05050072350
06-02-BERZ003800
06-05-300-0213768
06-08-1195689
06-05-100-0990908
661-63
06-05-300-0907015
14-20-60319980000
06-05-100-0501870
06-05-100-9021016
06-05-300-0923949
15397
661-38
661-88
06-00059010413
661-91
06-05-100-0031758
06-05-300-9046797
06-05-100-0853075
06-02-B10117A007
06-11-01-1105503
661-106
06-05-100-0167182
661-90
661-18
06-09-100-0088-0001
06-05-100-0229264
06-09-162-0025-0001
06-05-900-0079017
661-28
06-05-300-0072412
06-09-600-0025-0001
06-08-9840001
06-08-1020129
06-05-800-0203946
666-18
06-05-900-0235121
06-08-2719371
03-07-07244473830
661-59
661-03
06-05-300-0890760
06-09-761-0026-0001
69

In [12]:
CDF = pd.read_sql_table('power', engine)

In [13]:
CDF.shape

(13796760, 4)

In [14]:
CDF9 = CDF.drop(columns=['index'])

In [15]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA1022      0
1        2015-01-01 01:00:00          BNA1022      0
2        2015-01-01 02:00:00          BNA1022      0
3        2015-01-01 03:00:00          BNA1022      0
4        2015-01-01 04:00:00          BNA1022      0
...                      ...              ...    ...
13796755 2023-12-31 19:00:00  SEE985577062814      0
13796756 2023-12-31 20:00:00  SEE985577062814      0
13796757 2023-12-31 21:00:00  SEE985577062814      0
13796758 2023-12-31 22:00:00  SEE985577062814      0
13796759 2023-12-31 23:00:00  SEE985577062814      0

[13796760 rows x 3 columns]

In [16]:
CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M')
#CDF = CDF.set_index('produced_at')

In [17]:
CDF9["value"] = CDF9["value"].astype(int)

In [18]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA1022      0
1        2015-01-01 01:00:00          BNA1022      0
2        2015-01-01 02:00:00          BNA1022      0
3        2015-01-01 03:00:00          BNA1022      0
4        2015-01-01 04:00:00          BNA1022      0
...                      ...              ...    ...
13796755 2023-12-31 19:00:00  SEE985577062814      0
13796756 2023-12-31 20:00:00  SEE985577062814      0
13796757 2023-12-31 21:00:00  SEE985577062814      0
13796758 2023-12-31 22:00:00  SEE985577062814      0
13796759 2023-12-31 23:00:00  SEE985577062814      0

[13796760 rows x 3 columns]

In [19]:
#CDF_new = CDF.reset_index(drop=False)

In [20]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [21]:
#CDF_new[CDF_new.produced_at.isnull()]

In [22]:
#CDF_new

In [23]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [24]:
#CDF

In [25]:
#CDF99.set_index('produced_at')

In [26]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA1022      0
1        2015-01-01 01:00:00          BNA1022      0
2        2015-01-01 02:00:00          BNA1022      0
3        2015-01-01 03:00:00          BNA1022      0
4        2015-01-01 04:00:00          BNA1022      0
...                      ...              ...    ...
13796755 2023-12-31 19:00:00  SEE985577062814      0
13796756 2023-12-31 20:00:00  SEE985577062814      0
13796757 2023-12-31 21:00:00  SEE985577062814      0
13796758 2023-12-31 22:00:00  SEE985577062814      0
13796759 2023-12-31 23:00:00  SEE985577062814      0

[13796760 rows x 3 columns]

In [27]:
CDF2 = CDF9.groupby('variable').resample('1M', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

In [28]:
CDF2

                                                                      variable  \
variable        produced_at
BNA0140         2015-01-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-02-28   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-03-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-04-30   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-05-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
...                                                                        ...
SEE999117793854 2023-08-31   SEE999117793854SEE999117793854SEE999117793854S...
                2023-09-30   SEE999117793854SEE999117793854SEE999117793854S...
                2023-10-31   SEE999117793854SEE999117793854SEE999117793854S...
                2023-11-30   SEE999117793854SEE999117793854SEE999117793854S...
                2023-12-31   SEE999117793854SEE999117793854SEE999117793854S...

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2023-08-31    4618
                2023-09-30    7041
                2023-10-31    2242
                2023-11-30    1986
                2023-12-31    3814

[18888 rows x 2 columns]

In [29]:
CDF3 = CDF2.drop(columns="variable")

In [30]:
CDF3

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2023-08-31    4618
                2023-09-30    7041
                2023-10-31    2242
                2023-11-30    1986
                2023-12-31    3814

[18888 rows x 1 columns]

In [31]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [38]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [40]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [44]:
#gm2

In [46]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [48]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [50]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [52]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [54]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
18883  2023     12  SEE996720450723   37405
18884  2023     12  SEE997719859992   55523
18885  2023     12  SEE998199911088  252140
18886  2023     12  SEE998383491525       0
18887  2023     12  SEE999117793854    3814

[18888 rows x 4 columns]

In [56]:
gm7

       year  month          blockid   power
0      2015      1          BNA0140       0
108    2015      1          BNA0143       0
216    2015      1          BNA0145       0
300    2015      1          BNA0146  129164
636    2015      1          BNA0215       0
...     ...    ...              ...     ...
18455  2023     12  SEE996720450723   37405
18563  2023     12  SEE997719859992   55523
18671  2023     12  SEE998199911088  252140
18779  2023     12  SEE998383491525       0
18887  2023     12  SEE999117793854    3814

[18888 rows x 4 columns]

In [58]:
bpm

                 plantid            sseid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
3      14-80-55047380000  SEE955310827123
4         12-30532000000  SEE939848582457
..                   ...              ...
936    06-05-300-9046797  SEE976489828827
937               664-07  SEE906830618081
938               664-02  SEE999977738880
939        07-05-8030815  SEE957723162266
940  06-09-661-0020-0001         BNA1337a

[941 rows x 2 columns]

In [60]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [62]:
pm2

       year  month          blockid   power               plantid
0      2015      1          BNA0140       0  06-04-11_2001178_8_0
1      2015      2          BNA0140       0  06-04-11_2001178_8_0
2      2015      3          BNA0140       0  06-04-11_2001178_8_0
3      2015      4          BNA0140       0  06-04-11_2001178_8_0
4      2015      5          BNA0140       0  06-04-11_2001178_8_0
...     ...    ...              ...     ...                   ...
17719  2023      8  SEE913516809497  452032     06-05-500-0915123
17720  2023      9  SEE913516809497  223899     06-05-500-0915123
17721  2023     10  SEE913516809497  392955     06-05-500-0915123
17722  2023     11  SEE913516809497  418374     06-05-500-0915123
17723  2023     12  SEE913516809497  269507     06-05-500-0915123

[17724 rows x 5 columns]

In [64]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [66]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [68]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [70]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

     year            plantid  yearpower
303  2015  06-05-100-0248923   15389371
304  2016  06-05-100-0248923   21816032
305  2017  06-05-100-0248923   22612324
306  2018  06-05-100-0248923   25510420
307  2019  06-05-100-0248923   17882517
308  2020  06-05-100-0248923   14625943
309  2021  06-05-100-0248923   16556991
310  2022  06-05-100-0248923   21859813
311  2023  06-05-100-0248923   15022471

In [72]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

     year              plantid  yearpower
429  2015  06-09-100-0001-0002     560921
430  2016  06-09-100-0001-0002     204765
431  2017  06-09-100-0001-0002     133508
432  2018  06-09-100-0001-0002      24090
433  2019  06-09-100-0001-0002      37682
434  2020  06-09-100-0001-0002    1734818
435  2021  06-09-100-0001-0002    4187402
436  2022  06-09-100-0001-0002    2498555
437  2023  06-09-100-0001-0002    2856627

In [74]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [76]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [78]:
#invCDF = CDF.pivot(columns='variable')

In [80]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
18883  2023     12  SEE996720450723   37405
18884  2023     12  SEE997719859992   55523
18885  2023     12  SEE998199911088  252140
18886  2023     12  SEE998383491525       0
18887  2023     12  SEE999117793854    3814

[18888 rows x 4 columns]

In [39]:
bpm

               plantid            sseid
0    01-50-01000004838  SEE957285549260
1    01-50-01000004838  SEE990438768378
2    01-50-01000004838  SEE966920434281
3    01-50-01000004838  SEE999539592561
4    01-50-01000004838          BNA0273
..                 ...              ...
940     06-10-00101000  SEE943764365964
941  01-50-04000082392  SEE953266686481
942  01-50-04000082392  SEE934591835126
943  01-50-04000082392  SEE961021885321
944  01-50-04000082392  SEE923340224045

[945 rows x 2 columns]