In [28]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, DateTime
import psycopg

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [4]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-3]

In [5]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
plantslist = list(set(bpm['plantid'].to_list()))

In [6]:
plantslist.remove('661-94')
plantslist.remove('661-10')

plantslist.remove('07-05-8290552')
plantslist.remove('06-05-100-0081105')
#plantslist.remove(

In [7]:
#refpl = "03-01-01241117210.csv"

In [8]:
#df = pd.read_csv("./combined/" + refpl)

In [9]:
#df

In [10]:
def return_date(noDate):
    try:
        return str(noDate).split(".")[0]
    except IndexError:
        return noDate

In [11]:
return_date('2023-12-31 19:00:00')

'2023-12-31 19:00:00'

In [18]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [19]:
#engine = create_engine('sqlite://', echo=False)

In [20]:
#2023-12-31 19:00:00.000000

In [24]:
melt.dtypes

produced_at    object
variable       object
value           int64
dtype: object

In [31]:
counter = 0
for plant in plantslist:
    #print(plant)
    try:
        print(plant)
        df = pd.read_csv("./combined/" + plant + ".csv")
        try: #, format='%d.%m.%Y %H:%M'
            df['produced_at'] = df['produced_at'].map(return_date)
            df['produced_at'] = pd.to_datetime(df['produced_at'])
            #df['produced_at'] = df['produced_at'].map(return_date)
        except ValueError:
            print(plant + "faulty")
            print(df)
            continue
        melt = df.melt(id_vars='produced_at')
        #melt.drop('index', axis=1, inplace=True)
        melt.to_sql('power', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        counter += 1
        #print(df.shape)
    except FileNotFoundError:
        pass
print(counter)

661-44
661-95
06-09-261-0007-0041
03-07-07244473830
06-09-661-0020-0001
661-93
662-28
662-09
661-105
06-05-700-0090319
03-05-05050072350
03-01-01012110180
12-30532000000
06-09-171-0009-0B01
661-53
06-05-100-0431554
06-05-500-0342658
06-05-500-0342658faulty
               produced_at  BNA0335  BNA0334  BNA0333  SEE952352206145  \
0      2015-01-01 00:00:00        0        0        0                0
1      2015-01-01 01:00:00        0        0        0                0
2      2015-01-01 02:00:00        0        0        0                0
3      2015-01-01 03:00:00        0        0        0                0
4      2015-01-01 04:00:00        0        0        0                0
...                    ...      ...      ...      ...              ...
87669  2024-12-31 19:00:00        0        0        0                0
87670  2024-12-31 20:00:00        0        0        0                0
87671  2024-12-31 21:00:00        0        0        0                0
87672  2024-12-31 22:00:00        0        0        0                0
87673  2024-12-31 23:00:00        0        0        0                0

       SEE933236950972
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
87669                0
87670                0
87671                0
87672                0
87673                0

[87674 rows x 6 columns]
12-40710010000
03-03-03267770260
661-66
06-08-2951606
06-05-300-0213768
661-78
06-05-900-0001413
661-37
06-04-11_2001178_8_2
06-08-1574906
06-05-500-0338944
666-13
07-01-126351
06-05-900-0235121
662-18
06-76400010631
06-05-700-0105516
06-05-900-0205103
06-14600010611
662-01
12-20730670000
06-00004310411
661-88
666-15
06-05-100-0154540
662-14
06-08-3610519
661-84
06-08-1383701
06-08-3042693
06-05-300-0877384
06-05-100-9020309
06-05-900-9141660
666-17
661-90
14-60-48821410003
661-07
06-09-600-0009-0001
06-09-187-4048-0001
12-40669070000
18040
06-05-300-9046030
06-50940010414
03-03-03030273580
14-20-60319980000
661-87
06-09-500-0368-0001
06-08-1371304
03-09-09281337040
06-05-300-0215520
03-10-10100029340
06-05-900-0884101
16873
16-30-31400103005
662-03
662-12
06-11-01-1105602
661-110
03-06-06060316030
06-09-100-0088-0001
661-75
06-09-500-0354-0002
06-04-11_2001178_8_0
06-05-500-0915123
14-80-55047380000
06-09-674-2071-0001
661-16
661-111
661-103
06-08-2142201
06-08-2142201faulty
               produced_at  SEE911613995433  SEE937157344278  SEE964114029633
0      2015-01-01 00:00:00                0                0                0
1      2015-01-01 01:00:00                0                0                0
2      2015-01-01 02:00:00                0                0                0
3      2015-01-01 03:00:00                0                0                0
4      2015-01-01 04:00:00                0                0                0
...                    ...              ...              ...              ...
87575  2024-12-31 19:00:00                0                0                0
87576  2024-12-31 20:00:00                0                0                0
87577  2024-12-31 21:00:00                0                0                0
87578  2024-12-31 22:00:00                0                0                0
87579  2024-12-31 23:00:00                0                0                0

[87580 rows x 4 columns]
661-108
06-05-100-0031758
662-10
06-05-900-0271161
13-40-1300408
06-09-100-0003-0003
06-09-100-0003-0003faulty
               produced_at  SEE949509046600  SEE918648599230  SEE958847865460
0      2015-01-01 00:00:00                0                0                0
1      2015-01-01 01:00:00                0                0                0
2      2015-01-01 02:00:00                0                0                0
3      2015-01-01 03:00:00                0                0                0
4      2015-01-01 04:00:00                0                0                0
...                    ...              ...              ...              ...
87666  2024-12-31 19:00:00                0                0                0
87667  2024-12-31 20:00:00                0                0                0
87668  2024-12-31 21:00:00                0                0                0
87669  2024-12-31 22:00:00                0                0                0
87670  2024-12-31 23:00:00                0                0                0

[87671 rows x 4 columns]
03-06-06254353820
13-60-80624
661-17
03-01-01010157480
06-11-01-1105609
06-05-300-0072412
14-70-52316700250
13770
06-08-1020129
06-05-100-0989137
06-05-300-0079450
661-77
06-08-1195689
06-05-900-0125939
06-05-900-0125939faulty
               produced_at  SEE942982288260
0      2015-01-01 00:00:00                0
1      2015-01-01 01:00:00                0
2      2015-01-01 02:00:00                0
3      2015-01-01 03:00:00                0
4      2015-01-01 04:00:00                0
...                    ...              ...
87619  2024-12-31 19:00:00                0
87620  2024-12-31 20:00:00                0
87621  2024-12-31 21:00:00                0
87622  2024-12-31 22:00:00                0
87623  2024-12-31 23:00:00                0

[87624 rows x 2 columns]
06-10-0020157
06-00464010412
661-80
666-14
11975
15397
662-22
661-67
14-70-46630660001
12358
661-101
661-100
06-02-B28903H003
01-50-01000004838
06-09-187-4135-0001
661-59
06-05-100-0248923
06-09-100-0001-0002
06-08-2719371
03-09-09000237910
06-00000130433
06-19200010636
06-09-362-0100-0001
06-00176010435
06-04-11_2001178_8_1
661-18
661-18faulty
               produced_at  SEE913556136355
0      2015-01-01 00:00:00                0
1      2015-01-01 01:00:00                0
2      2015-01-01 02:00:00                0
3      2015-01-01 03:00:00                0
4      2015-01-01 04:00:00                0
...                    ...              ...
87571  2024-12-31 19:00:00                0
87572  2024-12-31 20:00:00                0
87573  2024-12-31 21:00:00                0
87574  2024-12-31 22:00:00                0
87575  2024-12-31 23:00:00                0

[87576 rows x 2 columns]
03-01-01010356620
06-08-9840001
661-06
03-04-04224004080
661-13
06-11-01-1105604
661-86
661-09
06-08-2797933
07-04-6021280
666-16
661-97
661-29
06-08-34064722
06-90032200632
06-08-1741292
664-02
06-05-100-0018507
06-09-271-0260-0001
661-03
06-09-273-0310-0001
06-05-900-0079017
13-60-34101
12-50724070000
13-60-80407
03-02-02020049510
06-05-500-9981505
06-05-700-9073419
661-81
661-64
06-05-800-0203946
06-08-4380932
13-30-1010101
03-10-10257401440
06-11-01-1105607
06-05-100-0229264
03-09-09281566110
06-05-700-0008683
661-79
06-09-279-0013-0001
16-30-30400102003
661-113
06-09-162-0025-0001
06-08-2948214
06-05-900-0865327
666-18
14-80-00009560000
14-80-00009560000faulty
               produced_at  SEE966331411864  SEE998199911088
0      2015-01-01 00:00:00                0                0
1      2015-01-01 01:00:00                0                0
2      2015-01-01 02:00:00                0                0
3      2015-01-01 03:00:00                0                0
4      2015-01-01 04:00:00                0                0
...                    ...              ...              ...
87682  2024-12-31 19:00:00                0                0
87683  2024-12-31 20:00:00                0                0
87684  2024-12-31 21:00:00                0                0
87685  2024-12-31 22:00:00                0                0
87686  2024-12-31 23:00:00                0                0

[87687 rows x 3 columns]
12-60510410000
06-05-100-0030712
14-70-51322590000
06-05-112-0458158
666-12
07-05-8153238
06-05-100-0365906
661-12
07-05-8030815
13-30-2102110
03-02-02221253020
06-05-300-0370387
03-05-05231382180
06-02-BERZ003800
06-11-01-1105603
06-09-100-0088-0005
06-08-1479296
06-05-800-0197010
661-104
661-63
661-107
661-82
06-05-100-0990908
06-10-00100999
662-17
661-39
06-08-4124448
06-05-300-0181417
661-99
07-05-8779480
06-05-100-0853075
06-05-900-0021170
06-09-600-0025-0001
661-102
669-01
661-11
06-00464020412
06-09-171-0002--C01
06-05-800-0197054
06-05-900-0320357
06-05-300-0907015
06-05-100-0501870
661-115
18037
01-50-02000283604
03-07-07244141350
06-10-0075248
06-11-01-1105501
661-112
03-31-31000005008
06-05-300-9046797
662-20
661-109
06-04-11_2039669_2_0
06-90031210632
03-06-06060116320
14-30-56918040000
06-05-300-0054298
661-98
12-40716440000
06-08-4666496
661-36
14326
03-01-01244641360
18038
06-05-300-0890760
14-20-48821410003
661-28
03-09-09261732970
06-11-01-1105503
06-05-300-0923949
06-05-100-9021016
06-05-700-0020290
06-05-100-0030723
06-09-100-0020-0001
661-85
06-05-100-0387357
06-02-B2A100H003
06-09-178-0722-0001
06-09-190-0036-0002
16874
06-09-500-0112-0001
01-50-56050192711
661-54
06-09-564-0555-0001
06-26200010633
661-89
06-09-671-0140-0001
16-62-09401231000
06-05-900-0327252
06-05-100-0167182
18042
661-92
06-05-900-9140178
03-08-08271405180
661-106
661-38
661-83
06-05-300-9002708
661-65
661-14
06-05-300-0326774
12-40520430000
662-06
16591
12305
664-07
661-15
03-01-01241117210
661-91
661-43
06-05-900-0888950
06-05-900-0080266
662-11
03-10-10257673950
06-05-300-0838652
06-02-B10117A007
661-19
06-10-00101000
661-42
01-50-04000082392
13-50-138
06-09-676-2101-0002
661-96
06-05-900-0045033
06-10-00101003
06-09-100-0088-0003
06-00059010413
07-04-6048443
12342
666-11
06-11-01-1105608
06-05-100-0888309
06-09-761-0026-0001
06-00453010412
12110
03-01-01010098080
06-05-500-0875741
06-11-01-1105502
03-01-01010959490
63

In [ ]:
#df['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [32]:
df

               produced_at  SEE904194792843
0      2015-01-01 00:00:00                0
1      2015-01-01 01:00:00                0
2      2015-01-01 02:00:00                0
3      2015-01-01 03:00:00                0
4      2015-01-01 04:00:00                0
...                    ...              ...
87667  2024-12-31 19:00:00                0
87668  2024-12-31 20:00:00                0
87669  2024-12-31 21:00:00                0
87670  2024-12-31 22:00:00                0
87671  2024-12-31 23:00:00                0

[87672 rows x 2 columns]

In [33]:
#columns_table = (inspect(engine).get_columns('power'))

NameError: name 'engine' is not defined

In [36]:
#for c in columns_table :
#    print(c['name'], c['type'])

In [37]:
df

               produced_at  SEE904194792843
0      2015-01-01 00:00:00                0
1      2015-01-01 01:00:00                0
2      2015-01-01 02:00:00                0
3      2015-01-01 03:00:00                0
4      2015-01-01 04:00:00                0
...                    ...              ...
87667  2024-12-31 19:00:00                0
87668  2024-12-31 20:00:00                0
87669  2024-12-31 21:00:00                0
87670  2024-12-31 22:00:00                0
87671  2024-12-31 23:00:00                0

[87672 rows x 2 columns]

In [38]:
CDF = pd.read_sql_table('power', engine2)

In [39]:
CDF.shape

(14377893, 3)

In [40]:
# , parse_dates={'produced_at': "%d.%m.%Y %H:%M"}

In [42]:
#CDF9 = CDF.drop(columns=['index'])
CDF9 = CDF.copy()

In [43]:
CDF9

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0439      0
1        2015-01-01 01:00:00          BNA0439      0
2        2015-01-01 02:00:00          BNA0439      0
3        2015-01-01 03:00:00          BNA0439      0
4        2015-01-01 04:00:00          BNA0439      0
...                      ...              ...    ...
14377888 2024-12-31 19:00:00  SEE904194792843      0
14377889 2024-12-31 20:00:00  SEE904194792843      0
14377890 2024-12-31 21:00:00  SEE904194792843      0
14377891 2024-12-31 22:00:00  SEE904194792843      0
14377892 2024-12-31 23:00:00  SEE904194792843      0

[14377893 rows x 3 columns]

In [44]:
#CDF9['produced_at'] =  pd.to_datetime(CDF9['produced_at'], format='%d.%m.%Y %H:%M', errors='coerce')
#CDF = CDF.set_index('produced_at')

In [45]:
CDF9.iloc[70128]

produced_at    2016-12-31 00:00:00
variable           SEE947816911833
value                           31
Name: 70128, dtype: object

In [46]:
CDF9.loc[CDF.variable=='SEE949509046600'].sort_values('produced_at')

Empty DataFrame
Columns: [produced_at, variable, value]
Index: []

In [47]:
CDF9.shape

(14377893, 3)

In [48]:
#CDF9.iloc[15219136]

In [49]:
CDF9.iloc[929304]

produced_at    2017-08-11 08:00:00
variable           SEE991817093418
value                          477
Name: 929304, dtype: object

In [50]:
#CDF9[CDF9.isnull().any(axis=1)].groupby("variable").count()

In [51]:
CDF9[CDF9.isnull().any(axis=1)].shape

(0, 3)

In [52]:
#CDF10 = CDF9.dropna()

In [53]:
CDF9["value"] = CDF9["value"].astype(int)

In [54]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [55]:
#CDF9['produced_at'] = CDF9['produced_at'].map(return_date)

In [56]:
CDF9

                  produced_at         variable  value
0         2015-01-01 00:00:00          BNA0439      0
1         2015-01-01 01:00:00          BNA0439      0
2         2015-01-01 02:00:00          BNA0439      0
3         2015-01-01 03:00:00          BNA0439      0
4         2015-01-01 04:00:00          BNA0439      0
...                       ...              ...    ...
14377888  2024-12-31 19:00:00  SEE904194792843      0
14377889  2024-12-31 20:00:00  SEE904194792843      0
14377890  2024-12-31 21:00:00  SEE904194792843      0
14377891  2024-12-31 22:00:00  SEE904194792843      0
14377892  2024-12-31 23:00:00  SEE904194792843      0

[14377893 rows x 3 columns]

In [57]:
#CDF_new = CDF.reset_index(drop=False)

In [58]:
#CDF_new['produced_at'] = CDF_new['produced_at'].to_datetime()
#CDF_new['produced_at'] = pd.to_datetime(df['produced_at'], format='%d.%m.%Y %H:%M')

In [59]:
#CDF_new[CDF_new.produced_at.isnull()]

In [60]:
#CDF_new

In [61]:
#CDF99 = CDF_new.drop(['index'], axis=1)

In [62]:
#CDF

In [63]:
#CDF99.set_index('produced_at')

In [64]:
#subC1 = CDF9.loc[CDF9.variable == 'SEE943690268513']

In [65]:
#subC1['produced_at'] = pd.to_datetime(subC1['produced_at'], errors='coerce')

In [66]:
#subC1

In [106]:
CDF10 = CDF9.copy()

In [107]:
CDF10['produced_at'] = pd.to_datetime(CDF10['produced_at']) #, errors='coerce'

In [108]:
CDF10

                 produced_at         variable  value
0        2015-01-01 00:00:00          BNA0439      0
1        2015-01-01 01:00:00          BNA0439      0
2        2015-01-01 02:00:00          BNA0439      0
3        2015-01-01 03:00:00          BNA0439      0
4        2015-01-01 04:00:00          BNA0439      0
...                      ...              ...    ...
14377888 2024-12-31 19:00:00  SEE904194792843      0
14377889 2024-12-31 20:00:00  SEE904194792843      0
14377890 2024-12-31 21:00:00  SEE904194792843      0
14377891 2024-12-31 22:00:00  SEE904194792843      0
14377892 2024-12-31 23:00:00  SEE904194792843      0

[14377893 rows x 3 columns]

In [109]:
CDF2 = CDF10.groupby('variable').resample('1ME', on='produced_at').sum()

# the inverse of groupby, reset_index
#CDF3 = CDF2.reset_index()

In [110]:
CDF2

                                                                      variable  \
variable        produced_at
BNA0140         2015-01-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-02-28   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-03-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-04-30   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
                2015-05-31   BNA0140BNA0140BNA0140BNA0140BNA0140BNA0140BNA0...
...                                                                        ...
SEE999117793854 2024-08-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-09-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-10-31   SEE999117793854SEE999117793854SEE999117793854S...
                2024-11-30   SEE999117793854SEE999117793854SEE999117793854S...
                2024-12-31   SEE999117793854SEE999117793854SEE999117793854S...

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[18960 rows x 2 columns]

In [111]:
CDF3 = CDF2.drop(columns="variable")

In [112]:
CDF3

                             value
variable        produced_at
BNA0140         2015-01-31       0
                2015-02-28       0
                2015-03-31       0
                2015-04-30       0
                2015-05-31       0
...                            ...
SEE999117793854 2024-08-31    5077
                2024-09-30    7186
                2024-10-31    6838
                2024-11-30   10273
                2024-12-31   14587

[18960 rows x 1 columns]

In [113]:
#gy = CDF.resample('1Y', on='produced_at').sum()
#gm = CDF.resample('1M', on='produced_at').sum()

In [114]:
gm2 = CDF3.reset_index()
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']

In [115]:
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)

In [116]:
#gm2

In [117]:
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')

In [118]:
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])

In [119]:
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [120]:
#gm5 = gm4.melt(id_vars=["year", "month"], var_name='blockid', value_name='power')
#gm5['power'] = gm5['power'].astype(int)

In [121]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
18955  2024     12  SEE995943794058   52543
18956  2024     12  SEE996720450723   51349
18957  2024     12  SEE997719859992   60650
18958  2024     12  SEE998383491525       0
18959  2024     12  SEE999117793854   14587

[18960 rows x 4 columns]

In [122]:
gm7

       year  month          blockid   power
0      2015      1          BNA0140       0
120    2015      1          BNA0143       0
240    2015      1          BNA0145       0
324    2015      1          BNA0146  129164
696    2015      1          BNA0215       0
...     ...    ...              ...     ...
18479  2024     12  SEE995943794058   52543
18599  2024     12  SEE996720450723   51349
18719  2024     12  SEE997719859992   60650
18839  2024     12  SEE998383491525       0
18959  2024     12  SEE999117793854   14587

[18960 rows x 4 columns]

In [123]:
bpm

                 plantid            sseid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
3      14-80-55047380000  SEE955310827123
4         12-30532000000  SEE939848582457
..                   ...              ...
936    06-05-300-9046797  SEE976489828827
937               664-07  SEE906830618081
938               664-02  SEE999977738880
939        07-05-8030815  SEE957723162266
940  06-09-661-0020-0001         BNA1337a

[941 rows x 2 columns]

In [124]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)

In [125]:
pm2

       year  month          blockid   power               plantid
0      2015      1          BNA0140       0  06-04-11_2001178_8_0
1      2015      1          BNA0145       0  06-04-11_2001178_8_1
2      2015      1          BNA0146  129164  06-04-11_2001178_8_1
3      2015      1          BNA0215       0     06-05-100-0365906
4      2015      1         BNA0221c   15020     06-05-100-0167182
...     ...    ...              ...     ...                   ...
17791  2024     12  SEE995943794058   52543        12-20730670000
17792  2024     12  SEE996720450723   51349   06-09-100-0088-0005
17793  2024     12  SEE997719859992   60650      06-11-01-1105501
17794  2024     12  SEE998383491525       0         06-08-1195689
17795  2024     12  SEE999117793854   14587     06-05-300-0877384

[17796 rows x 5 columns]

In [126]:
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')

In [127]:
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

In [128]:
ym1 = pm4.copy()
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [129]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

     year            plantid  yearpower
35   2015  06-05-100-0248923   15389371
97   2016  06-05-100-0248923   21816032
160  2017  06-05-100-0248923   22612324
221  2018  06-05-100-0248923   25510420
280  2019  06-05-100-0248923   17882517
335  2020  06-05-100-0248923   14625943
389  2021  06-05-100-0248923   16556991
440  2022  06-05-100-0248923   21859813
490  2023  06-05-100-0248923   15022471
540  2024  06-05-100-0248923   12631281

In [130]:
ym4.loc[ym4.plantid == "06-09-100-0001-0002"]

     year              plantid  yearpower
48   2015  06-09-100-0001-0002     560921
110  2016  06-09-100-0001-0002     204765
173  2017  06-09-100-0001-0002     133508
234  2018  06-09-100-0001-0002      24090
293  2019  06-09-100-0001-0002      37682
348  2020  06-09-100-0001-0002    1734818
402  2021  06-09-100-0001-0002    4187402
453  2022  06-09-100-0001-0002    2498555
503  2023  06-09-100-0001-0002    2856627
550  2024  06-09-100-0001-0002    3445940

In [131]:
ym4.to_csv("yearly.csv", index=False)
ym4.to_csv("yearly_pg.csv", header=False)

In [132]:
gm8.to_csv("monthly.csv", header=False)
#gm7.to_csv("yearly_pg.csv")

In [133]:
#invCDF = CDF.pivot(columns='variable')

In [134]:
gm8

       year  month          blockid   power
0      2015      1          BNA0140       0
1      2015      1          BNA0143       0
2      2015      1          BNA0145       0
3      2015      1          BNA0146  129164
4      2015      1          BNA0215       0
...     ...    ...              ...     ...
18955  2024     12  SEE995943794058   52543
18956  2024     12  SEE996720450723   51349
18957  2024     12  SEE997719859992   60650
18958  2024     12  SEE998383491525       0
18959  2024     12  SEE999117793854   14587

[18960 rows x 4 columns]

In [135]:
bpm

                 plantid            sseid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
3      14-80-55047380000  SEE955310827123
4         12-30532000000  SEE939848582457
..                   ...              ...
936    06-05-300-9046797  SEE976489828827
937               664-07  SEE906830618081
938               664-02  SEE999977738880
939        07-05-8030815  SEE957723162266
940  06-09-661-0020-0001         BNA1337a

[941 rows x 2 columns]