In [16]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re

In [17]:
plants = pd.read_csv("plants_2.csv")
power = pd.read_csv("../production/yearly.csv")

In [18]:
#power.melt(id_vars=['plantid'], value_vars=['yearpower', 'year'])

In [19]:
#power.loc[power.plantid == "06-05-100-0248923"]

In [20]:
power

     year        plantid  yearpower
0    2015  NW100-0365906    1501479
1    2015  NW100-0167182     115006
2    2015  NW500-0342658    2306293
3    2015     HE30001045    2528577
4    2015  NW900-0079017          0
..    ...            ...        ...
543  2024       BE166928    1171226
544  2024    SL0105352-G     137404
545  2024       BYS00044    1075551
546  2024  NW300-9002708    1403116
547  2024       BE169709     361995

[548 rows x 3 columns]

In [21]:
powers = power.pivot(index='plantid', columns='year')

In [22]:
powers

                    yearpower                                                  \
year                     2015        2016        2017        2018        2019
plantid
06-02-B10117A007    1108161.0   1306733.0   1249523.0    936518.0    790997.0
06-05-100-0431554   3725774.0   4348854.0   1140029.0         NaN         NaN
06-05-100-0853075   1014369.0    765838.0    262118.0         NaN         NaN
BB23020490          1652899.0   1527903.0   1575791.0   1460799.0   1352131.0
BB45025564         19612604.0  19947623.0  19621573.0  18910299.0  15104005.0
...                       ...         ...         ...         ...         ...
SL0105352-G           33579.0    156589.0    218460.0    205599.0    285545.0
SN70015796         17872558.0  16940828.0  17432468.0  17284829.0  16966904.0
SN80011256           298386.0    574814.0    441036.0    337447.0    421516.0
SN80011277         10815349.0  11455412.0  11905299.0  12054987.0   9284046.0
ST100125            4170448.0   4270624.0   4314039.0   4904878.0   2904120.0


year                     2020        2021        2022        2023        2024
plantid
06-02-B10117A007     798187.0    842285.0    952563.0    707521.0    637327.0
06-05-100-0431554         NaN         NaN         NaN         NaN         NaN
06-05-100-0853075         NaN         NaN         NaN         NaN         NaN
BB23020490          1391578.0   1272081.0   1356360.0   1182522.0   1386106.0
BB45025564         11684991.0  12948900.0  12505492.0  11628593.0   9538243.0
...                       ...         ...         ...         ...         ...
SL0105352-G          235451.0    252929.0    172319.0    141928.0    137404.0
SN70015796         13829348.0  14156333.0  17375485.0  11844322.0  12617201.0
SN80011256           516161.0    220020.0         NaN         NaN         NaN
SN80011277          8374593.0  11280826.0  12129746.0   7736932.0   5843144.0
ST100125            2083204.0   3265733.0   3184684.0   3064202.0   3312948.0

[61 rows x 10 columns]

In [23]:
df = powers.xs(('yearpower'), axis=1, drop_level=True)

In [24]:
df2 = df.reset_index()

In [25]:
df2

year,plantid,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,06-02-B10117A007,1108161.0,1306733.0,1249523.0,936518.0,790997.0,798187.0,842285.0,952563.0,707521.0,637327.0
1,06-05-100-0431554,3725774.0,4348854.0,1140029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06-05-100-0853075,1014369.0,765838.0,262118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BB23020490,1652899.0,1527903.0,1575791.0,1460799.0,1352131.0,1391578.0,1272081.0,1356360.0,1182522.0,1386106.0
4,BB45025564,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
...,...,...,...,...,...,...,...,...,...,...,...
56,SL0105352-G,33579.0,156589.0,218460.0,205599.0,285545.0,235451.0,252929.0,172319.0,141928.0,137404.0
57,SN70015796,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
58,SN80011256,298386.0,574814.0,441036.0,337447.0,421516.0,516161.0,220020.0,NaN,NaN,NaN
59,SN80011277,10815349.0,11455412.0,11905299.0,12054987.0,9284046.0,8374593.0,11280826.0,12129746.0,7736932.0,5843144.0
60,ST100125,4170448.0,4270624.0,4314039.0,4904878.0,2904120.0,2083204.0,3265733.0,3184684.0,3064202.0,3312948.0

In [26]:
#df

In [27]:
#powers.unstack('plantid')

In [28]:
np = pd.merge(plants, df2, how='left', on="plantid")

In [29]:
np

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NW100-0046639,0065 - STW - BHKW - KWK,Nordrhein-Westfalen,Erdgas,NaN,2024,2024,7.257,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SD662-98,bnBm GasKW BIB GT1,Hessen,Erdgas,NaN,2023,2023,378.400,bnBm,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SD662-99,bnBm Gaskraftwerk Leipheim,Bayern,Erdgas,NaN,2023,2023,310.000,bnBm,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NI04247180070,Nordland GuD-Anlage Gasturbine,Niedersachsen,Erdgas,NaN,2022,2022,85.286,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TH72012874,Gasmotor 1 Jena,Thüringen,Erdgas,NaN,2022,2022,60.875,in Betrieb,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
np.sort_values(by=[2019], ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
275,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
230,SN70015796,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
217,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
322,NW300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,13154280.0,15033694.0,19473733.0,18266049.0,12827830.0,8145901.0,12626436.0,15147355.0,11725739.0,10337723.0
106,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,NaN,1998,1997,1510.000,in Betrieb,2,...,10917280.0,10906473.0,10095854.0,11030178.0,9346499.0,9051706.0,10371571.0,8093328.0,8442791.0,7006971.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
#np

In [32]:
co2dict2 = {}
for j in range(2007, 2024):
    co2dict2[j] = 'co2_' + str(j)

In [33]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022',
 2023: 'co2_2023'}

In [34]:
rdict = {}
ddict = {}
co2dict = {}

for i in range(2015, 2025):
    rdict[('yearpower', i)] = 'energy_' + str(i)
    ddict[str(i)] = 0

for j in range(2007, 2024):
    co2dict[('amount', j)] = 'co2_' + str(j)

In [35]:
co2dict

{('amount', 2007): 'co2_2007',
 ('amount', 2008): 'co2_2008',
 ('amount', 2009): 'co2_2009',
 ('amount', 2010): 'co2_2010',
 ('amount', 2011): 'co2_2011',
 ('amount', 2012): 'co2_2012',
 ('amount', 2013): 'co2_2013',
 ('amount', 2014): 'co2_2014',
 ('amount', 2015): 'co2_2015',
 ('amount', 2016): 'co2_2016',
 ('amount', 2017): 'co2_2017',
 ('amount', 2018): 'co2_2018',
 ('amount', 2019): 'co2_2019',
 ('amount', 2020): 'co2_2020',
 ('amount', 2021): 'co2_2021',
 ('amount', 2022): 'co2_2022',
 ('amount', 2023): 'co2_2023'}

In [36]:
np2 = np.rename(columns=rdict)

In [37]:
np3 = np2.fillna(value=ddict)

In [38]:
np4 = np3.sort_values(2020, ascending=False)

In [39]:
np4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
275,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
230,SN70015796,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
217,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
106,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,NaN,1998,1997,1510.000,in Betrieb,2,...,10917280.0,10906473.0,10095854.0,11030178.0,9346499.0,9051706.0,10371571.0,8093328.0,8442791.0,7006971.0
344,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,7538467.0,11099158.0,13066618.0,10807558.0,8834396.0,8554457.0,9636584.0,12110914.0,7312086.0,8192538.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
#with pd.option_context('mode.use_inf_as_null', True):
np4 = np3.sort_values(2020, ascending=False)

In [41]:
#np4

In [42]:
#np3.sort_values("2015", ascending=False)

In [43]:
pols = pd.read_csv('../pollution/pollutants.csv')

In [44]:
pols

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
0,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
1,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
2,2023,BB16012651,NMVOC,Air,2580000.0,3,t,2580.000000,NMVOC [t]
3,2022,BB16012651,NO2,Air,671000.0,6,Tsd. t,0.671000,NO2 [Tsd. t]
4,2022,BB16012651,PM10,Air,88800.0,6,Tsd. t,0.088800,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
65140,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
65141,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
65142,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
65143,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]
65144,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [45]:
#pols2

In [46]:
pols1 = pols.loc[pols['releases_to'] == "Air"].loc[pols['pollutant'] == "CO2"]

In [47]:
#pols1

In [48]:
pols2 = pols1.drop(columns=['pollutant', 'releases_to', 'potency', 'unit_2', 'amount_2', 'pollutant2'])

In [49]:
pols2a = pols2.drop_duplicates(subset=['plantid', 'year'])

In [50]:
#pols2[pols2.duplicated(['plantid', 'year'], keep=False)].sort_values("year", ascending=False)

In [51]:
pols3 = pols2a.pivot(index='plantid', columns='year', values='amount')

In [52]:
pols2a

       year     plantid       amount
52     2023  BB16018798  285000000.0
55     2022  BB16018798  247000000.0
61     2021  BB16018798  247000000.0
67     2020  BB16018798  268000000.0
73     2019  BB16018798  298000000.0
...     ...         ...          ...
65127  2020  TH86012942  122000000.0
65129  2019  TH86012942  119000000.0
65131  2018  TH86012942  126000000.0
65133  2010  TH86012942  141000000.0
65141  2007  TH86012942  166000000.0

[2926 rows x 3 columns]

In [53]:
pols4 = pols3.reset_index()

In [54]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022',
 2023: 'co2_2023'}

In [55]:
pols5 = pols4.rename(columns=co2dict2)

In [56]:
pols5

year,plantid,co2_2007,co2_2008,co2_2009,co2_2010,co2_2011,co2_2012,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023
0,BB16018798,2.420000e+08,2.670000e+08,2.350000e+08,2.790000e+08,2.370000e+08,2.200000e+08,2.210000e+08,2.200000e+08,2.730000e+08,3.000000e+08,2.430000e+08,2.520000e+08,2.980000e+08,2.680000e+08,2.470000e+08,2.470000e+08,2.850000e+08
1,BB23020389,1.640000e+08,1.660000e+08,1.620000e+08,1.110000e+08,1.040000e+08,3.620000e+08,4.440000e+08,4.520000e+08,3.650000e+08,4.080000e+08,4.130000e+08,4.640000e+08,4.440000e+08,4.250000e+08,4.170000e+08,4.240000e+08,4.340000e+08
2,BB23020490,4.110000e+09,4.470000e+09,4.490000e+09,4.080000e+09,4.120000e+09,3.400000e+09,3.570000e+09,3.710000e+09,4.020000e+09,3.750000e+09,3.850000e+09,3.810000e+09,3.340000e+09,3.500000e+09,3.390000e+09,3.550000e+09,3.015000e+09
3,BB23022811,1.920000e+08,1.820000e+08,1.840000e+08,1.920000e+08,1.770000e+08,1.800000e+08,1.780000e+08,1.610000e+08,1.680000e+08,1.750000e+08,1.650000e+08,1.680000e+08,1.470000e+08,1.610000e+08,1.710000e+08,1.660000e+08,1.500000e+08
4,BB45025564,2.420000e+10,2.350000e+10,2.360000e+10,2.380000e+10,2.430000e+10,2.480000e+10,2.570000e+10,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10,1.413400e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,ST18046,NaN,1.680000e+08,1.720000e+08,2.270000e+08,2.400000e+08,2.390000e+08,2.420000e+08,2.370000e+08,2.550000e+08,2.570000e+08,2.500000e+08,2.500000e+08,2.440000e+08,2.500000e+08,2.290000e+08,2.250000e+08,2.210000e+08
217,TH30013152,NaN,2.710333e+08,2.490000e+08,2.650000e+08,2.570000e+08,2.450000e+08,2.500000e+08,2.560000e+08,2.600000e+08,2.960000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.980000e+08,2.930000e+08,2.620000e+08
218,TH62013494,1.770000e+08,1.807979e+08,1.030000e+08,1.510000e+08,1.700000e+08,1.630000e+08,1.350000e+08,1.500000e+08,1.420000e+08,1.210000e+08,1.500000e+08,1.420000e+08,1.440000e+08,1.470000e+08,1.420000e+08,1.310000e+08,1.290000e+08
219,TH72012874,3.430000e+08,3.454339e+08,3.670000e+08,3.850000e+08,3.530000e+08,3.010000e+08,2.230000e+08,1.880000e+08,1.880000e+08,2.250000e+08,2.430000e+08,2.620000e+08,2.100000e+08,2.230000e+08,2.640000e+08,1.790000e+08,1.770000e+08
220,TH86012942,1.660000e+08,NaN,NaN,1.410000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.260000e+08,1.190000e+08,1.220000e+08,1.210000e+08,1.170000e+08,1.110000e+08

In [57]:
#final

In [58]:
final = pd.merge(np4, pols5, how='left', on="plantid")

In [59]:
final.to_csv("test.csv")
final2 = final.copy()

In [60]:
#final2 = final.rename(columns=co2dict)

In [97]:
list(final4)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 'co2_2023']

In [62]:
final2[pd.isnull(final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022, co2_2023]
Index: []

[0 rows x 47 columns]

In [63]:
final3 = final2.dropna(subset=["plantid"])

In [64]:
final4 = final3.drop(["betreiber", "eigentuemer"], axis=1)

In [76]:
col_arr = list(final4)

In [88]:
len(col_arr)

45

In [77]:
#final4.rename(columns={"2023_x": 2023}, inplace=True)

In [78]:
#final4.drop(columns="2023_y", inplace=True)

In [79]:
#final3.sort_values('plantid').reset_index(drop=True)

In [84]:
def make_to_int(df, column):
    #df[column] = df[column]
    df[column] = df[column].round().astype('Int64')

In [98]:
for i in range(17, 45):
    make_to_int(final4, col_arr[i])

In [99]:
final4.to_csv('plants_new_nh.csv', header=False, index=False)

In [100]:
final4.loc[final4.plantid == "BE172654"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023
16,BE172654,HKW Mitte Dampfturbine,Berlin,Erdgas,NaN,1997,1997,444.0,in Betrieb,3,...,796000000,831000000,872000000,974000000,936000000,935000000,825000000,832000000,627000000,696000000

In [56]:
final3.loc[final3.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022, co2_2023]
Index: []

[0 rows x 47 columns]

In [57]:
a = int(2.990000e+10 )

In [58]:
a

29900000000

In [59]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 'co2_2023']

In [60]:
#final2.sort_values('endop')

In [61]:
final4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023
0,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,3.240000e+10,3.210000e+10,3.130000e+10,2.990000e+10,3.220000e+10,2.260000e+10,1.870000e+10,2.210000e+10,2.420000e+10,1.648500e+10
1,SN70015796,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,1.870000e+10,1.950000e+10,1.860000e+10,1.910000e+10,1.910000e+10,1.870000e+10,1.540000e+10,1.560000e+10,1.910000e+10,1.308800e+10
2,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10,1.413400e+10
3,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,NaN,1998,1997,1510.000,in Betrieb,2,...,1.170000e+10,1.230000e+10,1.230000e+10,1.150000e+10,1.250000e+10,1.060000e+10,1.040000e+10,1.190000e+10,9.640000e+09,9.713000e+09
4,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,1.880000e+10,1.830000e+10,1.890000e+10,1.910000e+10,1.690000e+10,1.340000e+10,1.160000e+10,1.460000e+10,1.500000e+10,9.336000e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,1.570000e+08,1.530000e+08,1.510000e+08,1.600000e+08,1.460000e+08,1.270000e+08,1.350000e+08,1.380000e+08,1.160000e+08,1.100000e+08
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,1.850000e+08,1.710000e+08,1.780000e+08,1.810000e+08,1.800000e+08,1.820000e+08,1.570000e+08,1.710000e+08,1.520000e+08,1.300000e+08
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,1.420000e+08,1.480000e+08,1.320000e+08,1.330000e+08,1.240000e+08,1.260000e+08,1.070000e+08,1.170000e+08,1.030000e+08,1.040000e+08

In [101]:
profit = pd.read_csv("../money/profit.csv")

In [105]:
final5 = final4.merge(profit, on="plantid", how="left")

In [106]:
final5.to_csv("plants_with_profit.csv", index=False, header=False)