In [1]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re

In [2]:
plants = pd.read_csv("plants_2.csv")
power = pd.read_csv("../production/yearly.csv")

In [3]:
#power.melt(id_vars=['plantid'], value_vars=['yearpower', 'year'])

In [4]:
#power.loc[power.plantid == "06-05-100-0248923"]

In [5]:
power

     year               plantid  yearpower
0    2015  06-04-11_2001178_8_0     761833
1    2015  06-04-11_2001178_8_1    1621311
2    2015     06-05-100-0365906    1501479
3    2015     06-05-100-0167182     115006
4    2015     06-05-500-0342658    2306293
..    ...                   ...        ...
639  2024      06-11-01-1105609    1171226
640  2024         06-10-0020157     137404
641  2024   06-09-100-0088-0005    1075551
642  2024     06-05-300-9002708    1403116
643  2024      06-11-01-1105501     361995

[644 rows x 3 columns]

In [6]:
powers = power.pivot(index='plantid', columns='year')

In [7]:
powers

                    yearpower                                                  \
year                     2015        2016        2017        2018        2019
plantid
01-50-02000283604   1370270.0   1121635.0   1047315.0   1159172.0    366425.0
03-01-01010098080   2858036.0   1988560.0   2187603.0   2607831.0    760756.0
03-01-01012110180   2102990.0   1710289.0         0.0         0.0         0.0
03-01-01241117210   1103769.0   1687429.0   1620072.0   1588253.0   1529038.0
03-06-06060316030   1658160.0   1564526.0   1463060.0   1517609.0   1056340.0
...                       ...         ...         ...         ...         ...
666-12             10359050.0   9701694.0   7384044.0  10321217.0   9954308.0
666-16             10381159.0  11334924.0  10900504.0  11475721.0  11382289.0
666-17              6929308.0   9211718.0  10743284.0  10913690.0  10235284.0
666-18             10205103.0  10619711.0   9788907.0   9034030.0   9690352.0
669-01               420405.0     35255.0     24431.0      7367.0     15109.0


year                     2020        2021        2022       2023      2024
plantid
01-50-02000283604         NaN         NaN         NaN        NaN       NaN
03-01-01010098080    919152.0    964026.0   1058804.0   609549.0  498280.0
03-01-01012110180         0.0         NaN         NaN        NaN       NaN
03-01-01241117210   1404615.0   1359363.0   1086121.0  1191623.0  467977.0
03-06-06060316030    891176.0   1177983.0   1550712.0  1136891.0  942371.0
...                       ...         ...         ...        ...       ...
666-12                    NaN         NaN         NaN        NaN       NaN
666-16             11028613.0  11349943.0  11610304.0  2831770.0       NaN
666-17             10832723.0  10731038.0  10715822.0  2103067.0       NaN
666-18             10345387.0  10319540.0  10364571.0  1778014.0       NaN
669-01                 3824.0     13613.0         NaN        NaN       NaN

[72 rows x 10 columns]

In [8]:
df = powers.xs(('yearpower'), axis=1, drop_level=True)

In [9]:
df2 = df.reset_index()

In [10]:
df2

year,plantid,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,01-50-02000283604,1370270.0,1121635.0,1047315.0,1159172.0,366425.0,NaN,NaN,NaN,NaN,NaN
1,03-01-01010098080,2858036.0,1988560.0,2187603.0,2607831.0,760756.0,919152.0,964026.0,1058804.0,609549.0,498280.0
2,03-01-01012110180,2102990.0,1710289.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,03-01-01241117210,1103769.0,1687429.0,1620072.0,1588253.0,1529038.0,1404615.0,1359363.0,1086121.0,1191623.0,467977.0
4,03-06-06060316030,1658160.0,1564526.0,1463060.0,1517609.0,1056340.0,891176.0,1177983.0,1550712.0,1136891.0,942371.0
...,...,...,...,...,...,...,...,...,...,...,...
67,666-12,10359050.0,9701694.0,7384044.0,10321217.0,9954308.0,NaN,NaN,NaN,NaN,NaN
68,666-16,10381159.0,11334924.0,10900504.0,11475721.0,11382289.0,11028613.0,11349943.0,11610304.0,2831770.0,NaN
69,666-17,6929308.0,9211718.0,10743284.0,10913690.0,10235284.0,10832723.0,10731038.0,10715822.0,2103067.0,NaN
70,666-18,10205103.0,10619711.0,9788907.0,9034030.0,9690352.0,10345387.0,10319540.0,10364571.0,1778014.0,NaN
71,669-01,420405.0,35255.0,24431.0,7367.0,15109.0,3824.0,13613.0,NaN,NaN,NaN

In [11]:
#df

In [12]:
#powers.unstack('plantid')

In [13]:
np = pd.merge(plants, df2, how='left', on="plantid")

In [14]:
np

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,06-05-100-0046639,0065 - STW - BHKW - KWK,Nordrhein-Westfalen,Erdgas,NaN,2024,2024,7.257,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06-09-700-9002-0001,bnBm Gaskraftwerk Leipheim,Bayern,Erdgas,NaN,2023,2023,310.000,bnBm,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14-70-52316707024,Gasmotoren-Heizkraftwerk Dresden-Reick - Aggre...,Sachsen,Erdgas,NaN,2022,2022,92.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16-72-73595430000,Gasmotor 1 Jena,Thüringen,Erdgas,NaN,2022,2022,60.875,in Betrieb,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,06-05-500-0875785,"Kraftwerk VI, Block 61, DT610",Nordrhein-Westfalen,Erdgas,NaN,2022,2022,273.994,in Betrieb,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,06-09-273-0317-0001,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,06-05-100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
np.sort_values(by=[2019], ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
276,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
229,14-70-46630660001,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
218,12-40710010000,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
324,06-05-300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,13154280.0,15033694.0,19473733.0,18266049.0,12827830.0,8145901.0,12626436.0,15147355.0,11725739.0,10337723.0
180,666-16,Isar 2,Bayern,Kernenergie,Nein,1988,1988,1410.000,stillgelegt,1,...,10381159.0,11334924.0,10900504.0,11475721.0,11382289.0,11028613.0,11349943.0,11610304.0,2831770.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,06-09-273-0317-0001,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,06-05-100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#np

In [17]:
co2dict2 = {}
for j in range(2007, 2023):
    co2dict2[j] = 'co2_' + str(j)

In [18]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022'}

In [19]:
rdict = {}
ddict = {}
co2dict = {}

for i in range(2015, 2025):
    rdict[('yearpower', i)] = 'energy_' + str(i)
    ddict[str(i)] = 0

for j in range(2007, 2023):
    co2dict[('amount', j)] = 'co2_' + str(j)

In [20]:
co2dict

{('amount', 2007): 'co2_2007',
 ('amount', 2008): 'co2_2008',
 ('amount', 2009): 'co2_2009',
 ('amount', 2010): 'co2_2010',
 ('amount', 2011): 'co2_2011',
 ('amount', 2012): 'co2_2012',
 ('amount', 2013): 'co2_2013',
 ('amount', 2014): 'co2_2014',
 ('amount', 2015): 'co2_2015',
 ('amount', 2016): 'co2_2016',
 ('amount', 2017): 'co2_2017',
 ('amount', 2018): 'co2_2018',
 ('amount', 2019): 'co2_2019',
 ('amount', 2020): 'co2_2020',
 ('amount', 2021): 'co2_2021',
 ('amount', 2022): 'co2_2022'}

In [21]:
np2 = np.rename(columns=rdict)

In [22]:
np3 = np2.fillna(value=ddict)

In [23]:
np4 = np3.sort_values(2020, ascending=False)

In [24]:
np4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
276,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
229,14-70-46630660001,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
218,12-40710010000,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
180,666-16,Isar 2,Bayern,Kernenergie,Nein,1988,1988,1410.000,stillgelegt,1,...,10381159.0,11334924.0,10900504.0,11475721.0,11382289.0,11028613.0,11349943.0,11610304.0,2831770.0,NaN
182,666-17,Emsland A,Niedersachsen,Kernenergie,Nein,1988,1988,1336.000,stillgelegt,1,...,6929308.0,9211718.0,10743284.0,10913690.0,10235284.0,10832723.0,10731038.0,10715822.0,2103067.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,06-09-273-0317-0001,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,06-05-100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#with pd.option_context('mode.use_inf_as_null', True):
np4 = np3.sort_values(2020, ascending=False)

In [26]:
#np4

In [27]:
#np3.sort_values("2015", ascending=False)

In [28]:
pols = pd.read_csv('../pollution/pollutants.csv')

In [29]:
#pols2

In [30]:
pols1 = pols.loc[pols['releases_to'] == "Air"].loc[pols['pollutant'] == "CO2"]

In [31]:
#pols1

In [32]:
pols2 = pols1.drop(columns=['pollutant', 'releases_to', 'potency', 'unit_2', 'amount_2', 'pollutant2'])

In [33]:
pols2a = pols2.drop_duplicates(subset=['plantid', 'year'])

In [34]:
#pols2[pols2.duplicated(['plantid', 'year'], keep=False)].sort_values("year", ascending=False)

In [35]:
pols3 = pols2a.pivot(index='plantid', columns='year', values='amount')

In [36]:
pols2a

       year            plantid       amount
0      2022  01-10-51011005501  203000000.0
2      2021  01-10-51011005501  214000000.0
4      2020  01-10-51011005501  182000000.0
6      2019  01-10-51011005501  207000000.0
8      2018  01-10-51011005501  212000000.0
...     ...                ...          ...
15482  2012              18042  239000000.0
15488  2011              18042  240000000.0
15494  2010              18042  227000000.0
15500  2009              18042  172000000.0
15505  2008              18042  168000000.0

[2869 rows x 3 columns]

In [37]:
pols4 = pols3.reset_index()

In [38]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022'}

In [39]:
pols5 = pols4.rename(columns=co2dict2)

In [40]:
pols5

year,plantid,co2_2007,co2_2008,co2_2009,co2_2010,co2_2011,co2_2012,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
0,01-10-51011005501,2.000000e+08,2.020000e+08,1.790000e+08,2.110000e+08,2.000000e+08,1.870000e+08,1.950000e+08,1.830000e+08,1.870000e+08,1.880000e+08,1.950000e+08,2.120000e+08,207000000.0,182000000.0,214000000.0,2.030000e+08
1,01-10-51048040567,1.140000e+09,1.100000e+09,1.080000e+09,1.060000e+09,1.020000e+09,1.010000e+09,9.870000e+08,9.550000e+08,9.730000e+08,9.500000e+08,9.850000e+08,9.300000e+08,957000000.0,915000000.0,944000000.0,1.000000e+09
2,01-50-01000004838,6.540000e+08,6.690000e+08,6.520000e+08,7.290000e+08,6.010000e+08,6.420000e+08,6.150000e+08,5.440000e+08,6.680000e+08,6.330000e+08,5.970000e+08,6.020000e+08,565000000.0,518000000.0,593000000.0,5.450000e+08
3,01-50-02000283604,1.430000e+09,1.890000e+09,1.910000e+09,1.830000e+09,1.170000e+09,1.850000e+09,1.750000e+09,1.580000e+09,1.440000e+09,1.210000e+09,1.120000e+09,1.250000e+09,416000000.0,NaN,NaN,NaN
4,01-50-04000082392,4.440000e+08,3.980000e+08,4.030000e+08,4.400000e+08,4.190000e+08,4.010000e+08,3.850000e+08,4.080000e+08,4.000000e+08,3.950000e+08,4.250000e+08,4.240000e+08,395000000.0,403000000.0,373000000.0,4.170000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,16874,NaN,3.660000e+08,3.960000e+08,3.840000e+08,4.050000e+08,4.060000e+08,4.150000e+08,4.070000e+08,3.790000e+08,4.330000e+08,4.380000e+08,4.380000e+08,407000000.0,407000000.0,NaN,NaN
226,18037,NaN,5.580000e+08,4.780000e+08,5.030000e+08,5.040000e+08,5.000000e+08,4.930000e+08,NaN,4.660000e+08,4.800000e+08,4.520000e+08,4.520000e+08,461000000.0,478000000.0,418000000.0,4.050000e+08
227,18038,NaN,8.680000e+08,8.370000e+08,9.180000e+08,9.310000e+08,9.060000e+08,4.610000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,18040,NaN,2.980000e+08,3.080000e+08,2.860000e+08,3.420000e+08,3.250000e+08,3.110000e+08,3.120000e+08,3.190000e+08,3.020000e+08,2.420000e+08,2.420000e+08,317000000.0,221000000.0,146000000.0,3.330000e+08
229,18042,NaN,1.680000e+08,1.720000e+08,2.270000e+08,2.400000e+08,2.390000e+08,2.420000e+08,2.370000e+08,2.550000e+08,2.570000e+08,2.500000e+08,2.500000e+08,244000000.0,250000000.0,229000000.0,2.250000e+08

In [41]:
final = pd.merge(np4, pols5, how='left', on="plantid")

In [42]:
final.to_csv("test.csv")
final2 = final.copy()

In [43]:
#final2 = final.rename(columns=co2dict)

In [44]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022']

In [45]:
final2[pd.isnull(final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022]
Index: []

[0 rows x 46 columns]

In [46]:
final3 = final2.dropna(subset=["plantid"])

In [47]:
final4 = final3.drop(["betreiber", "eigentuemer"], axis=1)

In [48]:
list(final4)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022']

In [49]:
final4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
0,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,3.330000e+10,3.240000e+10,3.210000e+10,3.130000e+10,2.990000e+10,3.220000e+10,2.260000e+10,1.870000e+10,2.210000e+10,2.420000e+10
1,14-70-46630660001,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,1.920000e+10,1.870000e+10,1.950000e+10,1.860000e+10,1.910000e+10,1.910000e+10,1.870000e+10,1.540000e+10,1.560000e+10,1.910000e+10
2,12-40710010000,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,2.570000e+10,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10
3,666-16,Isar 2,Bayern,Kernenergie,Nein,1988,1988,1410.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,666-17,Emsland A,Niedersachsen,Kernenergie,Nein,1988,1988,1336.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,06-09-273-0317-0001,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,1.590000e+08,1.570000e+08,1.530000e+08,1.510000e+08,1.600000e+08,1.460000e+08,1.270000e+08,1.350000e+08,1.380000e+08,1.160000e+08
353,06-05-100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,1.800000e+08,1.850000e+08,1.710000e+08,1.780000e+08,1.810000e+08,1.800000e+08,1.820000e+08,1.570000e+08,1.710000e+08,1.520000e+08
354,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,1.610000e+08,1.420000e+08,1.480000e+08,1.320000e+08,1.330000e+08,1.240000e+08,1.260000e+08,1.070000e+08,1.170000e+08,1.030000e+08

In [50]:
#final3.sort_values('plantid').reset_index(drop=True)

In [51]:
final4.to_csv('plants_new_nh.csv', header=False, index=False)

In [52]:
final4.loc[final4.plantid == "06-05-300-9046030"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
12,06-05-300-9046030,Knapsack I - Dampfturbine - DT 10,Nordrhein-Westfalen,Erdgas,NaN,2013,2007,1326.0,in Betrieb,4,...,198000000.0,NaN,NaN,376000000.0,327000000.0,162000000.0,895000000.0,957000000.0,426000000.0,256000000.0

In [53]:
final3.loc[final3.plantid == "06-05-100-0248923"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
0,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.0,in Betrieb,7,...,3.330000e+10,3.240000e+10,3.210000e+10,3.130000e+10,2.990000e+10,3.220000e+10,2.260000e+10,1.870000e+10,2.210000e+10,2.420000e+10

In [54]:
a = int(2.990000e+10 )

In [55]:
a

29900000000

In [56]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022']

In [57]:
#final2.sort_values('endop')