In [1]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re

In [2]:
plants = pd.read_csv("plants_2.csv")
power = pd.read_csv("../production-v2/yearly.csv")

In [3]:
power2 = pd.read_csv("../production-v2/yearly.csv")

In [4]:
#power.melt(id_vars=['plantid'], value_vars=['yearpower', 'year'])

In [5]:
#power.loc[power.plantid == "06-05-100-0248923"]

In [6]:
#power.to_csv("powertest.csv")
#power2.to_csv("powertest2.csv")

In [7]:
#power2.sort_values(by=["year", "plantid"], ascending=False)

In [8]:
power.sort_values(by=["year", "plantid"], ascending=False)

     year            plantid  yearpower
632  2025           ST100125    3014208
627  2025         SN70015796   11570184
629  2025          RP5000671    2014316
620  2025      NW900-0327252    2623808
617  2025      NW500-0915123    6143512
..    ...                ...        ...
42   2015         BB45025564   39082264
24   2015         BB23020490    3254272
12   2015  06-05-100-0853075    2028738
13   2015  06-05-100-0431554    7451548
32   2015   06-02-B10117A007    2216322

[639 rows x 3 columns]

In [9]:
powers = power.pivot(index='plantid', columns='year')

In [10]:
powers

                    yearpower                                                  \
year                     2015        2016        2017        2018        2019
plantid
06-02-B10117A007    2216322.0   2613466.0   2499046.0   1873036.0   1581994.0
06-05-100-0431554   7451548.0   8697708.0   2280058.0         NaN         NaN
06-05-100-0853075   2028738.0   1531676.0    524236.0         NaN         NaN
BB23020490          3254272.0   3008136.0   3098616.0   2872048.0   2659480.0
BB45025564         39082264.0  39746120.0  39095768.0  37681656.0  30096072.0
...                       ...         ...         ...         ...         ...
SL0101003-G         1091640.0   1179029.0    411538.0     17208.0     37646.0
SL0105352-G           33579.0    156589.0    218460.0    205599.0    285545.0
SN70015796         17824456.0  16892980.0  17385608.0  17238224.0  16920124.0
SN80011256           298386.0    574814.0    441036.0    337447.0    421516.0
ST100125            4149208.0   4249340.0   4293276.0   4881456.0   2887548.0

                                                                               \
year                     2020        2021        2022        2023        2024
plantid
06-02-B10117A007    1596374.0   1684570.0   1905126.0   1415042.0   1274654.0
06-05-100-0431554         NaN         NaN         NaN         NaN         NaN
06-05-100-0853075         NaN         NaN         NaN         NaN         NaN
BB23020490          2731032.0   2493232.0   2665944.0   2326248.0   2752368.0
BB45025564         23282592.0  25806688.0  24917528.0  23156456.0  19117560.0
...                       ...         ...         ...         ...         ...
SL0101003-G           63099.0     74852.0    328566.0    634532.0    160123.0
SL0105352-G          235451.0    252929.0    172319.0    141928.0    137404.0
SN70015796         13788512.0  14117384.0  17328260.0  11806900.0  12663172.0
SN80011256           516161.0    220020.0         NaN         NaN         NaN
ST100125            2068592.0   3247588.0   3166456.0   3047344.0   3308936.0


year                     2025
plantid
06-02-B10117A007          NaN
06-05-100-0431554         NaN
06-05-100-0853075         NaN
BB23020490          2020200.0
BB45025564         15391096.0
...                       ...
SL0101003-G               NaN
SL0105352-G               NaN
SN70015796         11570184.0
SN80011256                NaN
ST100125            3014208.0

[69 rows x 11 columns]

In [11]:
df = powers.xs(('yearpower'), axis=1, drop_level=True)

In [12]:
df2 = df.reset_index()

In [13]:
df2

year,plantid,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,06-02-B10117A007,2216322.0,2613466.0,2499046.0,1873036.0,1581994.0,1596374.0,1684570.0,1905126.0,1415042.0,1274654.0,NaN
1,06-05-100-0431554,7451548.0,8697708.0,2280058.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06-05-100-0853075,2028738.0,1531676.0,524236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BB23020490,3254272.0,3008136.0,3098616.0,2872048.0,2659480.0,2731032.0,2493232.0,2665944.0,2326248.0,2752368.0,2020200.0
4,BB45025564,39082264.0,39746120.0,39095768.0,37681656.0,30096072.0,23282592.0,25806688.0,24917528.0,23156456.0,19117560.0,15391096.0
...,...,...,...,...,...,...,...,...,...,...,...,...
64,SL0101003-G,1091640.0,1179029.0,411538.0,17208.0,37646.0,63099.0,74852.0,328566.0,634532.0,160123.0,NaN
65,SL0105352-G,33579.0,156589.0,218460.0,205599.0,285545.0,235451.0,252929.0,172319.0,141928.0,137404.0,NaN
66,SN70015796,17824456.0,16892980.0,17385608.0,17238224.0,16920124.0,13788512.0,14117384.0,17328260.0,11806900.0,12663172.0,11570184.0
67,SN80011256,298386.0,574814.0,441036.0,337447.0,421516.0,516161.0,220020.0,NaN,NaN,NaN,NaN
68,ST100125,4149208.0,4249340.0,4293276.0,4881456.0,2887548.0,2068592.0,3247588.0,3166456.0,3047344.0,3308936.0,3014208.0

In [14]:
#df

In [15]:
#powers.unstack('plantid')

In [16]:
np = pd.merge(plants, df2, how='left', on="plantid")

In [17]:
np

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,SN60018636,BHKW-G66-KWK-klein,Sachsen,Erdgas,Ja,43067,43067,3.736,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SD661-97,BHKW-G66-KWK-groß,Sachsen,Erdgas,Ja,41683,41683,12.747,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NW100-0046639,0065 - STW - BHKW - KWK,Nordrhein-Westfalen,Erdgas,Ja,2024,2024,7.257,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SD662-99,bnBm Gaskraftwerk Leipheim,Bayern,Erdgas,Nein,2023,2023,310.000,bnBm,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SD662-98,bnBm GasKW BIB GT1,Hessen,Erdgas,Nein,2023,2023,378.400,bnBm,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,Ja,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,60.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
np.sort_values(by=[2019], ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
275,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,50937196.0,54224752.0,58927450.0,41682712.0,34443638.0,40030664.0,44653794.0,30043984.0,25258404.0,NaN
217,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,39746120.0,39095768.0,37681656.0,30096072.0,23282592.0,25806688.0,24917528.0,23156456.0,19117560.0,15391096.0
322,NW300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,29978632.0,38834848.0,36431856.0,25598184.0,16253096.0,25197800.0,30220864.0,23387000.0,20812312.0,19822552.0
344,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,26653366.0,30451810.0,26428978.0,21383792.0,19483934.0,23037606.0,24221828.0,14624172.0,16385076.0,NaN
108,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,Ja,1998,1997,1510.000,in Betrieb,2,...,21812946.0,20191708.0,22060356.0,18692998.0,18103412.0,20743142.0,16186656.0,16885582.0,14013942.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,Ja,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,60.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#np

In [20]:
co2dict2 = {}
for j in range(2007, 2024):
    co2dict2[j] = 'co2_' + str(j)

In [21]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022',
 2023: 'co2_2023'}

In [22]:
rdict = {}
ddict = {}
co2dict = {}

for i in range(2015, 2025):
    rdict[('yearpower', i)] = 'energy_' + str(i)
    ddict[str(i)] = 0

for j in range(2007, 2024):
    co2dict[('amount', j)] = 'co2_' + str(j)

In [23]:
co2dict

{('amount', 2007): 'co2_2007',
 ('amount', 2008): 'co2_2008',
 ('amount', 2009): 'co2_2009',
 ('amount', 2010): 'co2_2010',
 ('amount', 2011): 'co2_2011',
 ('amount', 2012): 'co2_2012',
 ('amount', 2013): 'co2_2013',
 ('amount', 2014): 'co2_2014',
 ('amount', 2015): 'co2_2015',
 ('amount', 2016): 'co2_2016',
 ('amount', 2017): 'co2_2017',
 ('amount', 2018): 'co2_2018',
 ('amount', 2019): 'co2_2019',
 ('amount', 2020): 'co2_2020',
 ('amount', 2021): 'co2_2021',
 ('amount', 2022): 'co2_2022',
 ('amount', 2023): 'co2_2023'}

In [24]:
np2 = np.rename(columns=rdict)

In [25]:
np3 = np2.fillna(value=ddict)

In [26]:
np4 = np3.sort_values(2020, ascending=False)

In [27]:
np4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
275,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,50937196.0,54224752.0,58927450.0,41682712.0,34443638.0,40030664.0,44653794.0,30043984.0,25258404.0,NaN
217,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,39746120.0,39095768.0,37681656.0,30096072.0,23282592.0,25806688.0,24917528.0,23156456.0,19117560.0,15391096.0
344,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,26653366.0,30451810.0,26428978.0,21383792.0,19483934.0,23037606.0,24221828.0,14624172.0,16385076.0,NaN
108,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,Ja,1998,1997,1510.000,in Betrieb,2,...,21812946.0,20191708.0,22060356.0,18692998.0,18103412.0,20743142.0,16186656.0,16885582.0,14013942.0,NaN
322,NW300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,29978632.0,38834848.0,36431856.0,25598184.0,16253096.0,25197800.0,30220864.0,23387000.0,20812312.0,19822552.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,Ja,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,60.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#with pd.option_context('mode.use_inf_as_null', True):
np4 = np3.sort_values(2020, ascending=False)

In [29]:
#np4

In [30]:
#np3.sort_values("2015", ascending=False)

In [31]:
pols = pd.read_csv('../pollution/pollutants.csv')

In [32]:
pols

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
0,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
1,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
2,2023,BB16012651,NMVOC,Air,2580000.0,3,t,2580.000000,NMVOC [t]
3,2022,BB16012651,NO2,Air,671000.0,6,Tsd. t,0.671000,NO2 [Tsd. t]
4,2022,BB16012651,PM10,Air,88800.0,6,Tsd. t,0.088800,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
15606,2010,TH86012942,NO2,Air,104000.0,6,Tsd. t,0.104000,NO2 [Tsd. t]
15607,2009,TH86012942,NO2,Air,136000.0,6,Tsd. t,0.136000,NO2 [Tsd. t]
15608,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
15609,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
15610,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [33]:
#pols2

In [34]:
pols1 = pols.loc[pols['releases_to'] == "Air"].loc[pols['pollutant'] == "CO2"]

In [35]:
#pols1

In [36]:
pols2 = pols1.drop(columns=['pollutant', 'releases_to', 'potency', 'unit_2', 'amount_2', 'pollutant2'])

In [37]:
pols2a = pols2.drop_duplicates(subset=['plantid', 'year'])

In [38]:
#pols2[pols2.duplicated(['plantid', 'year'], keep=False)].sort_values("year", ascending=False)

In [39]:
pols3 = pols2a.pivot(index='plantid', columns='year', values='amount')

In [40]:
pols2a

       year     plantid       amount
52     2023  BB16018798  285000000.0
53     2022  BB16018798  247000000.0
55     2021  BB16018798  247000000.0
57     2020  BB16018798  268000000.0
59     2019  BB16018798  298000000.0
...     ...         ...          ...
15602  2020  TH86012942  122000000.0
15603  2019  TH86012942  119000000.0
15604  2018  TH86012942  126000000.0
15605  2010  TH86012942  141000000.0
15609  2007  TH86012942  166000000.0

[2909 rows x 3 columns]

In [41]:
pols4 = pols3.reset_index()

In [42]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022',
 2023: 'co2_2023'}

In [43]:
pols5 = pols4.rename(columns=co2dict2)

In [44]:
pols5

year,plantid,co2_2007,co2_2008,co2_2009,co2_2010,co2_2011,co2_2012,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023
0,BB16018798,2.420000e+08,2.670000e+08,2.350000e+08,2.790000e+08,2.370000e+08,2.200000e+08,2.210000e+08,2.200000e+08,2.730000e+08,3.000000e+08,2.430000e+08,2.520000e+08,2.980000e+08,2.680000e+08,2.470000e+08,2.470000e+08,2.850000e+08
1,BB23020389,1.640000e+08,1.660000e+08,1.620000e+08,1.110000e+08,1.040000e+08,3.620000e+08,4.440000e+08,4.520000e+08,3.650000e+08,4.080000e+08,4.130000e+08,4.640000e+08,4.440000e+08,4.250000e+08,4.170000e+08,4.240000e+08,4.340000e+08
2,BB23020490,4.110000e+09,4.470000e+09,4.490000e+09,4.080000e+09,4.120000e+09,3.400000e+09,3.570000e+09,3.710000e+09,4.020000e+09,3.750000e+09,3.850000e+09,3.810000e+09,3.340000e+09,3.500000e+09,3.390000e+09,3.550000e+09,3.015000e+09
3,BB23022811,1.920000e+08,1.820000e+08,1.840000e+08,1.920000e+08,1.770000e+08,1.800000e+08,1.780000e+08,1.610000e+08,1.680000e+08,1.750000e+08,1.650000e+08,1.680000e+08,1.470000e+08,1.610000e+08,1.710000e+08,1.660000e+08,1.500000e+08
4,BB45025564,2.420000e+10,2.350000e+10,2.360000e+10,2.380000e+10,2.430000e+10,2.480000e+10,2.570000e+10,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10,1.413400e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,ST18046,NaN,1.680000e+08,1.720000e+08,2.270000e+08,2.400000e+08,2.390000e+08,2.420000e+08,2.370000e+08,2.550000e+08,2.570000e+08,2.500000e+08,2.500000e+08,2.440000e+08,2.500000e+08,2.290000e+08,2.250000e+08,2.210000e+08
216,TH30013152,NaN,2.710333e+08,2.490000e+08,2.650000e+08,2.570000e+08,2.450000e+08,2.500000e+08,2.560000e+08,2.600000e+08,2.960000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.980000e+08,2.930000e+08,2.620000e+08
217,TH62013494,1.770000e+08,1.807979e+08,1.030000e+08,1.510000e+08,1.700000e+08,1.630000e+08,1.350000e+08,1.500000e+08,1.420000e+08,1.210000e+08,1.500000e+08,1.420000e+08,1.440000e+08,1.470000e+08,1.420000e+08,1.310000e+08,1.290000e+08
218,TH72012874,3.430000e+08,3.454339e+08,3.670000e+08,3.850000e+08,3.530000e+08,3.010000e+08,2.230000e+08,1.880000e+08,1.880000e+08,2.250000e+08,2.430000e+08,2.620000e+08,2.100000e+08,2.230000e+08,2.640000e+08,1.790000e+08,1.770000e+08
219,TH86012942,1.660000e+08,NaN,NaN,1.410000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.260000e+08,1.190000e+08,1.220000e+08,1.210000e+08,1.170000e+08,1.110000e+08

In [45]:
#final

In [46]:
final = pd.merge(np4, pols5, how='left', on="plantid")

In [47]:
final.to_csv("test.csv")
final2 = final.copy()

In [48]:
#final2 = final.rename(columns=co2dict)

In [49]:
#list(final4)

In [50]:
final2[pd.isnull(final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022, co2_2023]
Index: []

[0 rows x 48 columns]

In [51]:
final3 = final2.dropna(subset=["plantid"])

In [52]:
final4 = final3.drop(["betreiber", "eigentuemer"], axis=1)

In [53]:
col_arr = list(final4)

In [54]:
len(col_arr)

46

In [55]:
#final4.rename(columns={"2023_x": 2023}, inplace=True)

In [56]:
#final4.drop(columns="2023_y", inplace=True)

In [57]:
#final3.sort_values('plantid').reset_index(drop=True)

In [58]:
def make_to_int(df, column):
    #df[column] = df[column]
    df[column] = df[column].round().astype('Int64')

In [59]:
for i in range(17, 45):
    make_to_int(final4, col_arr[i])

In [60]:
final4.to_csv('plants_new_nh.csv', header=False, index=False)

In [61]:
final4.loc[final4.plantid == "BYS00041"][2024]

39    1516032
Name: 2024, dtype: Int64

In [62]:
final3.loc[final3.plantid == "BYS00041"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023
39,BYS00041,SWM HKW Nord 1 T10,Bayern,Erdgas,Ja,1991,1984,373.0,in Betrieb,3,...,2.370000e+09,2.570000e+09,2.520000e+09,2.380000e+09,2.040000e+09,2.040000e+09,1.580000e+09,1.640000e+09,1.810000e+09,2.090000e+09

In [63]:
a = int(2.990000e+10 )

In [64]:
a

29900000000

In [65]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 'co2_2023']

In [66]:
#final2.sort_values('endop')

In [67]:
final4.columns

Index([       'plantid',      'plantname',   'federalstate',   'energysource',
                  'chp', 'latestexpanded',      'initialop',     'totalpower',
                'state',     'blockcount',        'company',            'plz',
                  'ort',        'strasse',         'hausnr',  'geo_lat_wgs84',
       'geo_long_wgs84',    'activepower',             2015,             2016,
                   2017,             2018,             2019,             2020,
                   2021,             2022,             2023,             2024,
                   2025,       'co2_2007',       'co2_2008',       'co2_2009',
             'co2_2010',       'co2_2011',       'co2_2012',       'co2_2013',
             'co2_2014',       'co2_2015',       'co2_2016',       'co2_2017',
             'co2_2018',       'co2_2019',       'co2_2020',       'co2_2021',
             'co2_2022',       'co2_2023'],
      dtype='object')

In [68]:
profit = pd.read_csv("../money/profit.csv")

In [69]:
final5 = final4.merge(profit, on="plantid", how="left")

In [70]:
final6 = final5.drop(columns=['plantname_y'])

In [71]:
final6.to_csv("plants_with_profit.csv", index=False, header=False)

In [72]:
final6.columns

Index([       'plantid',    'plantname_x',   'federalstate',   'energysource',
                  'chp', 'latestexpanded',      'initialop',     'totalpower',
                'state',     'blockcount',        'company',            'plz',
                  'ort',        'strasse',         'hausnr',  'geo_lat_wgs84',
       'geo_long_wgs84',    'activepower',             2015,             2016,
                   2017,             2018,             2019,             2020,
                   2021,             2022,             2023,             2024,
                   2025,       'co2_2007',       'co2_2008',       'co2_2009',
             'co2_2010',       'co2_2011',       'co2_2012',       'co2_2013',
             'co2_2014',       'co2_2015',       'co2_2016',       'co2_2017',
             'co2_2018',       'co2_2019',       'co2_2020',       'co2_2021',
             'co2_2022',       'co2_2023',        'revenue',         'profit'],
      dtype='object')