In [119]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re

In [120]:
plants = pd.read_csv("plants_2.csv")
power = pd.read_csv("../production2/yearly.csv")

In [121]:
#power.melt(id_vars=['plantid'], value_vars=['yearpower', 'year'])

In [122]:
#power.loc[power.plantid == "06-05-100-0248923"]

In [123]:
power

    year              plantid  yearpower
0   2015    06-05-500-0342658    2306545
1   2015        06-08-2142201      24818
2   2015               661-18       2428
3   2015    06-05-900-0125939      18363
4   2015  06-09-100-0003-0003    2034876
5   2015    14-80-00009560000   10817069
6   2016    06-05-500-0342658    2886426
7   2016        06-08-2142201      17861
8   2016               661-18     190875
9   2016    06-05-900-0125939     425797
10  2016  06-09-100-0003-0003    1892349
11  2016    14-80-00009560000   11456750
12  2017    06-05-500-0342658    3224370
13  2017        06-08-2142201      30564
14  2017               661-18     243108
15  2017    06-05-900-0125939     490275
16  2017  06-09-100-0003-0003    1755619
17  2017    14-80-00009560000   11905637
18  2018    06-05-500-0342658    3113297
19  2018        06-08-2142201      23211
20  2018               661-18     275610
21  2018    06-05-900-0125939     461604
22  2018  06-09-100-0003-0003    1444906
23  2018    14-80-00009560000   12056399
24  2019    06-05-500-0342658    2862798
25  2019        06-08-2142201      15808
26  2019               661-18     346938
27  2019    06-05-900-0125939     991632
28  2019  06-09-100-0003-0003    1047310
29  2019    14-80-00009560000    9284477
30  2020    06-05-500-0342658    2257705
31  2020        06-08-2142201      15315
32  2020               661-18     310650
33  2020    06-05-900-0125939    1332487
34  2020  06-09-100-0003-0003     931434
35  2020    14-80-00009560000    8375104
36  2021    06-05-500-0342658    1899524
37  2021        06-08-2142201      32512
38  2021               661-18     256201
39  2021    06-05-900-0125939    1110705
40  2021  06-09-100-0003-0003    1621570
41  2021    14-80-00009560000   11282373
42  2022    06-05-500-0342658    1937659
43  2022        06-08-2142201      30997
44  2022               661-18     212181
45  2022    06-05-900-0125939     877719
46  2022  06-09-100-0003-0003    1613056
47  2022    14-80-00009560000   12131037
48  2023    06-05-500-0342658    1194155
49  2023        06-08-2142201      13595
50  2023               661-18     267126
51  2023    06-05-900-0125939     554024
52  2023  06-09-100-0003-0003    1272122
53  2023    14-80-00009560000    7701859
54  2024    06-05-500-0342658     353192
55  2024        06-08-2142201      21430
56  2024               661-18     300566
57  2024    06-05-900-0125939     782046
58  2024  06-09-100-0003-0003     996180
59  2024    14-80-00009560000    5843585

In [124]:
powers = power.pivot(index='plantid', columns='year')

In [125]:
powers

                    yearpower                                                  \
year                     2015      2016      2017      2018     2019     2020
plantid
06-05-500-0342658     2306545   2886426   3224370   3113297  2862798  2257705
06-05-900-0125939       18363    425797    490275    461604   991632  1332487
06-08-2142201           24818     17861     30564     23211    15808    15315
06-09-100-0003-0003   2034876   1892349   1755619   1444906  1047310   931434
14-80-00009560000    10817069  11456750  11905637  12056399  9284477  8375104
661-18                   2428    190875    243108    275610   346938   310650


year                     2021      2022     2023     2024
plantid
06-05-500-0342658     1899524   1937659  1194155   353192
06-05-900-0125939     1110705    877719   554024   782046
06-08-2142201           32512     30997    13595    21430
06-09-100-0003-0003   1621570   1613056  1272122   996180
14-80-00009560000    11282373  12131037  7701859  5843585
661-18                 256201    212181   267126   300566

In [126]:
df = powers.xs(('yearpower'), axis=1, drop_level=True)

In [127]:
df2 = df.reset_index()

In [128]:
df2

year,plantid,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,06-05-500-0342658,2306545,2886426,3224370,3113297,2862798,2257705,1899524,1937659,1194155,353192
1,06-05-900-0125939,18363,425797,490275,461604,991632,1332487,1110705,877719,554024,782046
2,06-08-2142201,24818,17861,30564,23211,15808,15315,32512,30997,13595,21430
3,06-09-100-0003-0003,2034876,1892349,1755619,1444906,1047310,931434,1621570,1613056,1272122,996180
4,14-80-00009560000,10817069,11456750,11905637,12056399,9284477,8375104,11282373,12131037,7701859,5843585
5,661-18,2428,190875,243108,275610,346938,310650,256201,212181,267126,300566

In [129]:
#df

In [130]:
#powers.unstack('plantid')

In [131]:
np = pd.merge(plants, df2, how='left', on="plantid")

In [132]:
np

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,06-11-01-1105502,GuD Marzahn Gasturbine,Berlin,Erdgas,NaN,2020,2020,258.800,in Betrieb,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06-09-162-0025-0001,Werk 1.5 KWK 2,Bayern,Erdgas,NaN,2019,2019,26.940,in Betrieb,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,661-106,70001314.01,Thüringen,Erdgas,NaN,2018,2018,17.548,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,661-111,Gasmotor Bad Salzungen,Thüringen,Erdgas,NaN,2018,2018,10.003,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,661-10,Küstenkraftwerk K.I.E.L Motor 13,Schleswig-Holstein,Erdgas,NaN,2018,2018,189.120,in Betrieb,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,06-05-300-9046797,LEV KWG G23,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
np.sort_values(by=[2019], ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
74,14-80-00009560000,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,NaN,2000,1999,1782.00,in Betrieb,2,...,10817069.0,11456750.0,11905637.0,12056399.0,9284477.0,8375104.0,11282373.0,12131037.0,7701859.0,5843585.0
273,06-05-500-0342658,Scholven,Nordrhein-Westfalen,Steinkohle,Ja,1985,1968,2126.00,Netzreserve,6,...,2306545.0,2886426.0,3224370.0,3113297.0,2862798.0,2257705.0,1899524.0,1937659.0,1194155.0,353192.0
222,06-09-100-0003-0003,Zolling GT1,Bayern,Steinkohle,NaN,1986,1976,521.00,in Betrieb,3,...,2034876.0,1892349.0,1755619.0,1444906.0,1047310.0,931434.0,1621570.0,1613056.0,1272122.0,996180.0
47,06-05-900-0125939,Cuno Heizkraftwerk Herdecke H6,Nordrhein-Westfalen,Erdgas,NaN,2007,2007,417.00,in Betrieb,1,...,18363.0,425797.0,490275.0,461604.0,991632.0,1332487.0,1110705.0,877719.0,554024.0,782046.0
202,661-18,Rheinfelden Dampfturbine,Baden-Württemberg,Erdgas,NaN,2006,1979,15.68,in Betrieb,2,...,2428.0,190875.0,243108.0,275610.0,346938.0,310650.0,256201.0,212181.0,267126.0,300566.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.00,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,06-05-300-9046797,LEV KWG G23,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.00,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.00,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.00,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.80,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
#np

In [135]:
co2dict2 = {}
for j in range(2007, 2023):
    co2dict2[j] = 'co2_' + str(j)

In [136]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022'}

In [137]:
rdict = {}
ddict = {}
co2dict = {}

for i in range(2015, 2024):
    rdict[('yearpower', i)] = 'energy_' + str(i)
    ddict[str(i)] = 0

for j in range(2007, 2023):
    co2dict[('amount', j)] = 'co2_' + str(j)

In [138]:
co2dict

{('amount', 2007): 'co2_2007',
 ('amount', 2008): 'co2_2008',
 ('amount', 2009): 'co2_2009',
 ('amount', 2010): 'co2_2010',
 ('amount', 2011): 'co2_2011',
 ('amount', 2012): 'co2_2012',
 ('amount', 2013): 'co2_2013',
 ('amount', 2014): 'co2_2014',
 ('amount', 2015): 'co2_2015',
 ('amount', 2016): 'co2_2016',
 ('amount', 2017): 'co2_2017',
 ('amount', 2018): 'co2_2018',
 ('amount', 2019): 'co2_2019',
 ('amount', 2020): 'co2_2020',
 ('amount', 2021): 'co2_2021',
 ('amount', 2022): 'co2_2022'}

In [139]:
np2 = np.rename(columns=rdict)

In [140]:
np3 = np2.fillna(value=ddict)

In [141]:
np4 = np3.sort_values(2020, ascending=False)

In [142]:
np4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
74,14-80-00009560000,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,NaN,2000,1999,1782.00,in Betrieb,2,...,10817069.0,11456750.0,11905637.0,12056399.0,9284477.0,8375104.0,11282373.0,12131037.0,7701859.0,5843585.0
273,06-05-500-0342658,Scholven,Nordrhein-Westfalen,Steinkohle,Ja,1985,1968,2126.00,Netzreserve,6,...,2306545.0,2886426.0,3224370.0,3113297.0,2862798.0,2257705.0,1899524.0,1937659.0,1194155.0,353192.0
47,06-05-900-0125939,Cuno Heizkraftwerk Herdecke H6,Nordrhein-Westfalen,Erdgas,NaN,2007,2007,417.00,in Betrieb,1,...,18363.0,425797.0,490275.0,461604.0,991632.0,1332487.0,1110705.0,877719.0,554024.0,782046.0
222,06-09-100-0003-0003,Zolling GT1,Bayern,Steinkohle,NaN,1986,1976,521.00,in Betrieb,3,...,2034876.0,1892349.0,1755619.0,1444906.0,1047310.0,931434.0,1621570.0,1613056.0,1272122.0,996180.0
202,661-18,Rheinfelden Dampfturbine,Baden-Württemberg,Erdgas,NaN,2006,1979,15.68,in Betrieb,2,...,2428.0,190875.0,243108.0,275610.0,346938.0,310650.0,256201.0,212181.0,267126.0,300566.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.00,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,06-05-300-9046797,LEV KWG G23,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.00,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.00,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.00,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.80,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
#with pd.option_context('mode.use_inf_as_null', True):
np4 = np3.sort_values(2020, ascending=False)

In [144]:
#np4

In [145]:
#np3.sort_values("2015", ascending=False)

In [146]:
pols = pd.read_csv('../pollution/pollutants.csv')

In [147]:
#pols2

In [148]:
pols1 = pols.loc[pols['releases_to'] == "Air"].loc[pols['pollutant'] == "CO2"]

In [149]:
#pols1

In [150]:
pols2 = pols1.drop(columns=['pollutant', 'releases_to', 'potency', 'unit_2', 'amount_2', 'pollutant2'])

In [151]:
pols2a = pols2.drop_duplicates(subset=['plantid', 'year'])

In [152]:
#pols2[pols2.duplicated(['plantid', 'year'], keep=False)].sort_values("year", ascending=False)

In [153]:
pols3 = pols2a.pivot(index='plantid', columns='year', values='amount')

In [154]:
pols2a

       year            plantid       amount
0      2022  01-50-01000004838  545000000.0
4      2021  01-50-01000004838  593000000.0
7      2020  01-50-01000004838  518000000.0
10     2019  01-50-01000004838  565000000.0
14     2018  01-50-01000004838  602000000.0
...     ...                ...          ...
13651  2012              18042  239000000.0
13657  2011              18042  240000000.0
13663  2010              18042  227000000.0
13669  2009              18042  172000000.0
13674  2008              18042  168000000.0

[2555 rows x 3 columns]

In [155]:
pols4 = pols3.reset_index()

In [156]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022'}

In [157]:
pols5 = pols4.rename(columns=co2dict2)

In [158]:
pols5

year,plantid,co2_2007,co2_2008,co2_2009,co2_2010,co2_2011,co2_2012,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
0,01-50-01000004838,6.540000e+08,6.690000e+08,6.520000e+08,7.290000e+08,6.010000e+08,6.420000e+08,6.150000e+08,5.440000e+08,6.680000e+08,6.330000e+08,5.970000e+08,6.020000e+08,5.650000e+08,5.180000e+08,5.930000e+08,5.450000e+08
1,01-50-02000283604,1.430000e+09,1.890000e+09,1.910000e+09,1.830000e+09,1.170000e+09,1.850000e+09,1.750000e+09,1.580000e+09,1.440000e+09,1.210000e+09,1.120000e+09,1.250000e+09,4.160000e+08,NaN,NaN,NaN
2,01-50-56050192711,NaN,NaN,NaN,1.480000e+09,1.150000e+09,1.370000e+09,1.280000e+09,1.330000e+09,1.400000e+09,1.320000e+09,1.140000e+09,1.170000e+09,1.110000e+09,1.090000e+09,1.040000e+09,1.270000e+09
3,03-01-01010098080,3.570000e+09,2.410000e+09,3.300000e+09,2.950000e+09,3.040000e+09,2.630000e+09,3.250000e+09,2.840000e+09,2.540000e+09,1.760000e+09,1.920000e+09,2.320000e+09,7.100000e+08,8.360000e+08,8.740000e+08,1.000000e+09
4,03-01-01010157480,4.870000e+08,4.260000e+08,4.080000e+08,4.130000e+08,4.610000e+08,6.940000e+08,4.820000e+08,3.870000e+08,4.220000e+08,4.610000e+08,4.680000e+08,4.210000e+08,4.350000e+08,3.730000e+08,4.520000e+08,5.270000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,16874,NaN,3.660000e+08,3.960000e+08,3.840000e+08,4.050000e+08,4.060000e+08,4.150000e+08,4.070000e+08,3.790000e+08,4.330000e+08,4.380000e+08,4.380000e+08,4.070000e+08,4.070000e+08,NaN,NaN
201,18037,NaN,5.580000e+08,4.780000e+08,5.030000e+08,5.040000e+08,5.000000e+08,4.930000e+08,NaN,4.660000e+08,4.800000e+08,4.520000e+08,4.520000e+08,4.610000e+08,4.780000e+08,4.180000e+08,4.050000e+08
202,18038,NaN,8.680000e+08,8.370000e+08,9.180000e+08,9.310000e+08,9.060000e+08,4.610000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,18040,NaN,2.980000e+08,3.080000e+08,2.860000e+08,3.420000e+08,3.250000e+08,3.110000e+08,3.120000e+08,3.190000e+08,3.020000e+08,2.420000e+08,2.420000e+08,3.170000e+08,2.210000e+08,1.460000e+08,3.330000e+08
204,18042,NaN,1.680000e+08,1.720000e+08,2.270000e+08,2.400000e+08,2.390000e+08,2.420000e+08,2.370000e+08,2.550000e+08,2.570000e+08,2.500000e+08,2.500000e+08,2.440000e+08,2.500000e+08,2.290000e+08,2.250000e+08

In [159]:
final = pd.merge(np4, pols5, how='left', on="plantid")

In [160]:
final.to_csv("test.csv")
final2 = final.copy()

In [161]:
#final2 = final.rename(columns=co2dict)

In [162]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022']

In [163]:
final2[pd.isnull(final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022]
Index: []

[0 rows x 46 columns]

In [164]:
final3 = final2.dropna(subset=["plantid"])

In [165]:
final4 = final3.drop(["betreiber", "eigentuemer"], axis=1)

In [166]:
list(final4)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022']

In [167]:
final4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
0,14-80-00009560000,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,NaN,2000,1999,1782.00,in Betrieb,2,...,1.180000e+10,1.190000e+10,1.030000e+10,1.080000e+10,1.140000e+10,1.170000e+10,8.980000e+09,8.300000e+09,1.110000e+10,1.190000e+10
1,06-05-500-0342658,Scholven,Nordrhein-Westfalen,Steinkohle,Ja,1985,1968,2126.00,Netzreserve,6,...,1.020000e+10,8.810000e+09,4.720000e+09,4.120000e+09,4.300000e+09,4.280000e+09,3.700000e+09,3.450000e+09,3.090000e+09,3.110000e+09
2,06-05-900-0125939,Cuno Heizkraftwerk Herdecke H6,Nordrhein-Westfalen,Erdgas,NaN,2007,2007,417.00,in Betrieb,1,...,1.160000e+08,NaN,NaN,1.880000e+08,1.920000e+08,1.820000e+08,3.750000e+08,5.320000e+08,4.100000e+08,3.570000e+08
3,06-09-100-0003-0003,Zolling GT1,Bayern,Steinkohle,NaN,1986,1976,521.00,in Betrieb,3,...,2.020000e+09,1.780000e+09,1.740000e+09,1.640000e+09,1.500000e+09,1.240000e+09,9.310000e+08,8.400000e+08,1.380000e+09,1.410000e+09
4,661-18,Rheinfelden Dampfturbine,Baden-Württemberg,Erdgas,NaN,2006,1979,15.68,in Betrieb,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.00,in Betrieb,8,...,1.880000e+10,1.880000e+10,1.830000e+10,1.890000e+10,1.910000e+10,1.690000e+10,1.340000e+10,1.160000e+10,1.460000e+10,1.500000e+10
316,06-05-300-9046797,LEV KWG G23,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.00,in Betrieb,8,...,8.930000e+08,8.360000e+08,8.260000e+08,8.030000e+08,7.930000e+08,7.320000e+08,7.430000e+08,6.750000e+08,8.230000e+08,7.950000e+08
317,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.00,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.00,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.80,in Betrieb,1,...,1.610000e+08,1.420000e+08,1.480000e+08,1.320000e+08,1.330000e+08,1.240000e+08,1.260000e+08,1.070000e+08,1.170000e+08,1.030000e+08

In [168]:
#final3.sort_values('plantid').reset_index(drop=True)

In [169]:
final4.to_csv('plants_new_nh.csv', header=False, index=False)

In [170]:
final4.loc[final4.plantid == "06-05-100-0248923"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
255,06-05-100-0248923,Neurath G,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.0,in Betrieb,7,...,3.330000e+10,3.240000e+10,3.210000e+10,3.130000e+10,2.990000e+10,3.220000e+10,2.260000e+10,1.870000e+10,2.210000e+10,2.420000e+10

In [171]:
final3.loc[final3.plantid == "06-05-100-0248923"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
255,06-05-100-0248923,Neurath G,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.0,in Betrieb,7,...,3.330000e+10,3.240000e+10,3.210000e+10,3.130000e+10,2.990000e+10,3.220000e+10,2.260000e+10,1.870000e+10,2.210000e+10,2.420000e+10

In [172]:
a = int(2.990000e+10 )

In [173]:
a

29900000000

In [174]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022']

In [175]:
#final2.sort_values('endop')