In [1]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re
from helpers import get_renamed_blocks, get_renamed_blocks3

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
prtr = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx")

In [5]:
#STATES = ['in Betrieb', 'Gesetzlich an Stilllegung gehindert', 'Netzreserve',  'Sicherheitsbereitschaft', 'Sonderfall', 'vorläufig stillgelegt', 'stillgelegt', 'Kohlestromvermarktungsverbot']
#STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'bnBm','stillgelegt', 'vorläufig stillgelegt']
ACTIVE_STATES = ['In Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'bnBm', 'vorläufig stillgelegt']
ENERGIES = ["Kernenergie", "Braunkohle", "Steinkohle", "Erdgas", "Mineralölprodukte", "Abfall", "Biomasse", ""]

In [6]:
plr = pd.read_excel("../data/Kraftwerksliste.xlsx", sheet_name=1, skiprows=10)

In [7]:
pl0 = pd.read_excel("../data/Kraftwerksliste.xlsx", skiprows=11)

In [8]:
#list(plr)

In [9]:
#list(pl0_bak)

In [10]:
pl0_bak = pl0.copy()
plr_bak = plr.copy()

In [11]:
list(pl0_bak)

['Unnamed: 0',
 'MaStR-Nr. der Stromerzeugungseinheit',
 'Anlagenbetreiber',
 'Anzeige-Name der Stromerzeugungseinheit',
 'PLZ der Einheit',
 'Ort der Einheit',
 'Straße der Einheit',
 'Hausnummer der Einheit',
 'Bundesland der Einheit',
 'Datum der erstmaligen Inbetriebnahme der Einheit',
 'Jahr der Inbetriebnahme der Einheit',
 'Kraftwerksstatus der Einheit',
 'Energieträger',
 'Hauptbrennstoff',
 'Auswertung Energieträger',
 'Wärmeauskopplung (KWK)\n(ja/nein)',
 'Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?',
 'Bruttoleistung in MW',
 'Nettonennleistung (elektrische Wirkleistung) in MW',
 'Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?: ja \nNettonennleistung der Einspeisung in ein deutsches Netz:',
 'Technologie der Stromerzeugung',
 'Volleinspeisung oder Teileinspeisung?',
 'Anschlussnetzbetreiber',
 'Spannungsebene']

In [12]:
list(plr_bak)

['Unnamed: 0',
 'MaStR-Nr. der Stromerzeugungseinheit',
 'Anzeige-Name der Stromerzeugungseinheit',
 'PLZ der Einheit',
 'Ort der Einheit',
 'Straße der Einheit',
 'Hausnummer der Einheit',
 'Bundesland der Einheit',
 'Datum der erstmaligen Inbetriebnahme der Einheit (Datum/Jahr)',
 'Datum der endgültigen Stilllegung der Einheit (Datum/Jahr)',
 'Kraftwerksstatus der Einheit',
 'Energieträger',
 'Hauptbrennstoff',
 'Auswertung Energieträger',
 'Wärmeauskopplung (KWK)\n(ja/nein)',
 'Bruttoleistung in MW',
 'Nettonennleistung (elektrische Wirkleistung) in MW',
 'Technologie der Stromerzeugung',
 'Volleinspeisung oder Teileinspeisung?',
 'Anschlussnetzbetreiber',
 'Spannungsebene',
 'Unnamed: 21']

In [13]:
cols = [0,12,15,16,17,20]
plt = get_renamed_blocks(pl0)
plq = plt.drop(plt.columns[cols],axis=1)

In [14]:
cols2 = [0, 10,11,17,20,21]
plr0a = get_renamed_blocks3(plr)
plr0b = plr0a.drop(plr0a.columns[cols2],axis=1)

In [15]:
list(plq)

['blockid',
 'company',
 'plantname',
 'plz',
 'place',
 'street',
 'streetnum',
 'federalstate',
 'initialop',
 'initialopYear',
 'state',
 'e2',
 'energysource',
 'power',
 'gerpower',
 'fullsupply',
 'TSO',
 'voltagelevel']

In [16]:
list(plr0b)

['blockid',
 'plantname',
 'plz',
 'place',
 'street',
 'streetnum',
 'federalstate',
 'initialop',
 'endop',
 'e2',
 'energysource',
 'chp',
 'grosspower',
 'power',
 'fullsupply',
 'TSO']

In [17]:
plq0a = plq[~plq['blockid'].isin(["SEE9-Dummy-nicht_EEG", "SEE9-Dummy-EEG"])]

In [18]:
plq0b = plq0a.sort_values(['power'], ascending=False)

In [19]:
#plq0b.groupby("energysource").count()

In [20]:
#plq0b.loc[pl0.energysource == "Abfall"]

In [21]:
#pl0 = pd.read_csv("../Kraftwerksliste_2020.csv", error_bad_lines=False, engine="python", encoding="latin1", sep=";", skiprows=9)
#prtr = pd.read_csv("../data/2019-11-25_PRTR-Deutschland_Freisetzungen.csv", error_bad_lines=False, engine="python", encoding="latin1", sep=";", skiprows=0)
#pl0 = pd.read_csv("Kraftwerksliste_CSV.csv", error_bad_lines=False, engine="python")
bm = pd.read_csv("../basic/plant_sse_mapper.csv", engine="python")

In [22]:
#bm

In [23]:
bm['plantid'] = bm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [24]:
bm.loc[bm.plantid.str.contains("_")]

                  plantid            sseid
141  06-04-11_2001178_8_2  SEE989202977269
259  06-04-11_2001178_8_1  SEE958310939391
565  06-04-11_2001178_8_0  SEE968950464368
686  06-04-11_2001178_8_1          BNA0146
722  06-04-11_2001178_8_2  SEE924172977710
852  06-04-11_2001178_8_0          BNA0140
855  06-04-11_2001178_8_1          BNA0145
880  06-04-11_2039669_2_0  SEE904968236689

In [25]:
#prtr.describe()

In [26]:
plq0a.insert(10, "endop", np.nan)
plr0b.insert(2, "company", np.nan)

In [27]:
plq0a.shape

(1842, 19)

In [28]:
plr0b.shape

(273, 17)

In [30]:
pl_combined = pd.concat([plq0a, plr0b])

In [31]:
pl_combined['energysource'] = pl_combined['energysource'].apply(lambda x: str(x).replace('Wärme', 'Erdgas'))

In [34]:
pl_combined.loc[pl_combined.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963,NaN,2012,NaN,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [35]:
pl_combined.shape

(2115, 21)

In [36]:
#list(plq0a)

In [37]:
#list(plr0b)

In [38]:
#list(pl_combined)

In [39]:
#list(plr0b)

In [40]:
#list(plq0a)

In [41]:
pl0 = pl_combined.copy()

In [42]:
pl0.loc[pl0["blockid"] == "BNA0645"]

Empty DataFrame
Columns: [blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [43]:
#pl0.groupby("energysource").count()

In [44]:
#pl0.groupby("state").count()

In [45]:
pl1 = pl0.loc[pl0["energysource"].isin(ENERGIES)]

In [46]:
#pl0.loc[pl0.energysource == "Wärme"]

In [47]:
pl_debug = pl0.copy()
pl_debug['initialop'] = pd.to_datetime(pl_debug['initialop'], errors='coerce')
pl_debug2 = pl_debug.copy()

In [48]:
pl_debug2.loc[pl_debug2.initialop == pd.NaT ]

Empty DataFrame
Columns: [blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [49]:
pl_debug2['initialop'] = pd.DatetimeIndex(pl_debug2.initialop).year
#pl_debug2['initialop'] = pl_debug.initialop.dt.year

In [50]:
#pl_debug2['initialop'] = pl_debug.initialop.dt.year

In [51]:
#pl_debug['initialop'] = pl_debug['initialop'].to_datetime()

In [52]:
pl_debug2.groupby("state").count()

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,
In Betrieb,1766,1766,1766,1766,1766,1675,1535,1766,1766,1766,0,1229,1766,1766,64,1734,1766,1766,0,0
Kapazitätsreserve aufgrund von § 13e EnWG,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve aufgrund von KVBG,4,4,4,4,4,4,4,4,4,4,0,4,4,4,0,4,4,4,0,0
Netzreserve aufgrund § 13b EnWG,23,23,23,23,23,23,22,23,23,23,0,21,23,23,0,23,23,23,0,0
besonderes netztechnisches Betriebsmittel,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
in Betrieb,2,2,2,2,2,2,2,2,2,2,0,2,2,2,0,2,2,2,0,0
vorläufig stillgelegt nach § 13b EnWG,8,8,8,8,8,8,7,8,8,8,0,8,8,8,0,8,8,8,0,0
vorläufig stillgelegt ohne § 13b EnWG,9,9,9,9,9,9,9,9,9,9,0,9,9,9,0,9,9,9,0,0

In [53]:
#pl_debug2.groupby("initialop").count()

In [54]:
#pl0.rename(columns={ pl0.columns[10]: "Energieträger_old", pl0.columns[13]: "Energieträger"}, inplace=True)

In [55]:
#pl0

In [56]:
#bm

In [57]:
#pl0.groupby("Energieträger").count()

In [58]:
#list(plt)

In [59]:
pl1['state'] = pl1['state'].fillna("stillgelegt")

In [60]:
pl1.loc[pl1.blockid == "SEE975094128629"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
266,SEE975094128629,NaN,HKW Mitte Kessel 12,38114.0,Braunschweig,Reiherstraße,3,Niedersachsen,1971-07-15 00:00:00,NaN,2024-06-26 00:00:00,stillgelegt,"Erdgas, Erdölgas",Erdgas,20.0,NaN,Volleinspeisung,NaN,NaN,Ja,22.4

In [61]:
pl1.loc[pl1.blockid == "BNA0221c"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
108,BNA0221c,NaN,Gasblock,40221.0,Düsseldorf,Auf der Lausward,75,Nordrhein-Westfalen,1977-03-28 00:00:00,NaN,2019,stillgelegt,NaN,Erdgas,293.0,NaN,NaN,Netzgesellschaft Düsseldorf mbH,NaN,Ja,NaN

In [62]:
plt.loc[plt.blockid == "BNA0711"]

Empty DataFrame
Columns: [Unnamed: 0, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, state, e1, e2, energysource, chp, border, grosspower, power, gerpower, tech, fullsupply, TSO, voltagelevel]
Index: []

In [63]:
plt = pl1.dropna(subset=["blockid"])

In [64]:
plt = plt.astype({"energysource": 'category'})

In [65]:
plt.loc[plt.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963,NaN,2012,stillgelegt,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [66]:
# remove duplicates blocks in berlin, TODO: remove, because BNetzA switched to SEE ids no longer neccessary
#idxs = plt.index[plt["blockid"].isin(["BNA0083", "BNA0085b"]) & ~plt["state"].isin(["in Betrieb"])].tolist()
#plt2 = plt.loc[~plt.index.isin(idxs)]

In [67]:
#plt.loc[plt.index.isin(idxs)]#

In [68]:
#plt["Energieträger"] = plt["Energieträger"].astype('category')
#plt["Energieträger"] = plt["Energieträger"].cat.set_categories(["Kernenergie", "Braunkohle", "Steinkohle", "Erdgas", "Mineralölprodukte"], ordered=True)

In [69]:
#plt["Energieträger"] = plt["Energieträger"].astype('category')

In [70]:
#plt.groupby('Energieträger').count()

In [71]:
pl2 = pl1.copy()

In [72]:
#pl2.groupby("Energieträger").count()

In [73]:
# plt.dtypes

In [74]:
#pl2 = plt.rename(columns={ pl1.columns[0]: "blockid", pl1.columns[3]: "PLZ", pl1.columns[4]: "Ort", pl1.columns[8]: "Inbetriebnahme", pl1.columns[9]: "Status", pl1.columns[15]: "KWK", pl1.columns[16]: "Nettoleistung"})
#pl3 = pl2.rename(columns={ pl1.columns[1]: "BlockID" })

In [75]:
'''
def to_year(x):
    if type(x) == type(4):
        return x
    elif type(x) == type(2.5):
        return 0 # handle nans
    return int(x[-4:])
'''

'\ndef to_year(x):\n    if type(x) == type(4):\n        return x\n    elif type(x) == type(2.5):\n        return 0 # handle nans\n    return int(x[-4:])\n'

In [76]:
def to_year(x):
    dt = pd.to_datetime(x)
    return dt.year

In [77]:
def to_year2(x):
    if pd.isna(x):
        return x
    elif isinstance(x, float):
        return x
    elif isinstance(x, int):
        return x
    else:
        ts = pd.Timestamp(ts_input=x)
        #print(ts)
        return int(ts.year)

In [78]:
#blocks.loc[blocks.Energieträger == "Kernenergie"]

In [79]:
#pl2

In [80]:
'''
pl2.loc[pl2.blockid == 'BNA0861a', 'initialop'] = 2012
pl2.loc[pl2.blockid == 'BNA1334', 'initialop'] = 2002
pl2.loc[pl2.blockid == 'BNA1141', 'initialop'] = 1970
pl2.loc[pl2.blockid == 'BNA0418', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1499', 'initialop'] = 1951
pl2.loc[pl2.blockid == 'BNA1502', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1500', 'initialop'] = 1990
pl2.loc[pl2.blockid == 'BNA1498', 'initialop'] = 1953
pl2.loc[pl2.blockid == 'BNA1260', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006
pl2.loc[pl2.blockid == 'BNA1114', 'initialop'] = 2012



pl2.loc[pl2.blockid == 'BNA0413b', 'initialop'] = 2014 # Westfalen D

pl2.loc[pl2.blockid == 'BNA0355', 'initialop'] = 1981 # Grafenrheinfeld
'''

#pl2['Nettoleistung'] = pl2['Nettoleistung'].str.replace('\n','')
#pl2['Nettoleistung'] = pl2[pd.to_numeric(pl2["Nettoleistung"])]
#pl2['Nettoleistung'] = pl2['Nettoleistung'].str.replace(';','.')

"\npl2.loc[pl2.blockid == 'BNA0861a', 'initialop'] = 2012\npl2.loc[pl2.blockid == 'BNA1334', 'initialop'] = 2002\npl2.loc[pl2.blockid == 'BNA1141', 'initialop'] = 1970\npl2.loc[pl2.blockid == 'BNA0418', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1499', 'initialop'] = 1951\npl2.loc[pl2.blockid == 'BNA1502', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1500', 'initialop'] = 1990\npl2.loc[pl2.blockid == 'BNA1498', 'initialop'] = 1953\npl2.loc[pl2.blockid == 'BNA1260', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006\npl2.loc[pl2.blockid == 'BNA1114', 'initialop'] = 2012\n\n\n\npl2.loc[pl2.blockid == 'BNA0413b', 'initialop'] = 2014 # Westfalen D\n\npl2.loc[pl2.blockid == 'BNA0355', 'initialop'] = 1981 # Grafenrheinfeld\n"

In [81]:
#pl2[] = pl2[pd.to_numeric(pl2["Nettoleistung"])]
pl2['initialop'] = pl2['initialop'].apply(to_year2)
#pl2['endop'] = pl2['endop'].apply(to_year2)
pl2['power'] = pl2['power'].apply(pd.to_numeric)

In [82]:
pl2.loc[pl2.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963.0,NaN,2012,stillgelegt,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [83]:
#bm[pl2.duplicated(['BlockID'], keep=False)].sort_values("BlockID", ascending=False)

In [84]:
#pl2[pl2.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

In [85]:
#cols = [10,11,12,14,17,18,19]
#pl3 = pl2.drop(pl2.columns[cols],axis=1)

In [86]:
#pl3.groupby('Unternehmen').max()

In [87]:
#pl3

In [88]:
def fix_company(company):
    #print(company)
    company_dict = {"RWE": "RWE AG", "Vattenfall": "Vattenfall GmbH", "Uniper": "Uniper SE", "EnBW": "EnBW AG", "Steag": "Steag GmbH", "Nordzucker": "Nordzucker AG", "Lausitz Energie": "LEAG"}
    for key, value in company_dict.items():
        if key in str(company):
            return value
    return company

In [89]:
def extract_still(x):
    match = re.findall("[0-9]{4}",x)
    return match[0] if match else np.nan

In [90]:
def fix_kwk(x):
    return "Nein" if x == "nein" else "Ja" if x == "ja" else x

In [91]:
pl4 = pl2.copy()

In [92]:
sq = 'Endgültig Stillgelegt 2013 (mit StA)'

In [93]:
list(pl2.groupby("state").count().reset_index()['state'])

['In Betrieb',
 'Kapazitätsreserve aufgrund von § 13e EnWG',
 'Netzreserve aufgrund von KVBG',
 'Netzreserve aufgrund § 13b EnWG',
 'besonderes netztechnisches Betriebsmittel',
 'in Betrieb',
 'stillgelegt',
 'vorläufig stillgelegt nach § 13b EnWG',
 'vorläufig stillgelegt ohne § 13b EnWG']

In [94]:
z = "endgültig stillgelegt 2022 (ohne § 13b EnWG oder KVBG)"

In [95]:
def extract_state(state):
    if state == "In Betrieb":
        return "in Betrieb"
    elif "Endgültig Stillgelegt" in state:
        return "stillgelegt"
    elif "Vorläufig Stillgelegt" in state:
        return "vorläufig stillgelegt"
    elif "an Stilllegung gehindert" in state:
        return "Gesetzlich an Stilllegung gehindert"
    else:
        return state

In [96]:
def extract_state2(state):
    
    states = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
    matches = ['In Betrieb', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve aufgrund § 13b EnWG', 'befristete Strommarktrückkehr', 'vorläufig stillgelegt', 'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', 'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', '[E|e]ndgültig [S|s]tillgelegt 20[0-9]{2} \([ohne]|[mit].']
    
    for s, m in list(zip(states, matches)):
        if re.search(m, state):
            return s
    
    return state

<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\('
/tmp/ipykernel_2553883/1872127742.py:4: SyntaxWarning: invalid escape sequence '\('
  matches = ['In Betrieb', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve aufgrund § 13b EnWG', 'befristete Strommarktrückkehr', 'vorläufig stillgelegt', 'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', 'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', '[E|e]ndgültig [S|s]tillgelegt 20[0-9]{2} \([ohne]|[mit].']
/tmp/ipykernel_2553883/1872127742.py:4: SyntaxWarning: invalid escape sequence '\('
  matches = ['In Betrieb', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve aufgrund § 13b EnWG', 'befristete Strommarktrückkehr', 'vorläufig stillgelegt', 'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', 'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', '[E|e]ndgültig [S|s]tillgelegt 20[0-9]{2} \([ohne]|[mit].']
/tmp/ipykernel_2553883/1872127742.py:4: SyntaxWarning: invalid escape sequence '\('
  matches = ['In Betrieb', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve aufgrund § 13b EnWG', 'befristete Strommarktrückkehr', 'vorläufig stillgelegt', 'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', 'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', '[E|e]ndgültig [S|s]tillgelegt 20[0-9]{2} \([ohne]|[mit].']

In [97]:
def extract_state3(state):
    
    states = ['in Betrieb', 'bnBm', 'Kapazitätsreserve', 'Netzreserve', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
    matches = ['In Betrieb', 'besonderes netztechnisches Betriebsmittel', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve',  r'vorläufig stillgelegt', r'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', r'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', r'stillgelegt']
    
    for s, m in list(zip(states, matches)):
        if re.search(m, state):
            return s
    
    return state

In [98]:
extract_state3(sq)

'Endgültig Stillgelegt 2013 (mit StA)'

In [99]:
pl4

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
0,SEE915851127786,STAWAG – Stadt- und Städteregionswerke Aachen AG,BHKW Schwarzer Weg,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023.0,2023.0,NaN,In Betrieb,"Erdgas, Erdölgas",Erdgas,21.5050,NaN,Volleinspeisung,Regionetz GmbH (SNB911641710114),Mittelspannung,NaN,NaN
1,SEE946736241334,Palm Power GmbH & Co. KG,HKW Aalen,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021.0,2021.0,NaN,In Betrieb,"Erdgas, Erdölgas",Erdgas,78.3020,NaN,Volleinspeisung,Netze BW GmbH (SNB948311994307),Hochspannung; Hochspannung,NaN,NaN
2,SEE930596800480,Lausitz Energie Kraftwerke AG,Gasturbinenkraftwerk Ahrensfelde GT A,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,1990.0,NaN,Kapazitätsreserve aufgrund von § 13e EnWG,"Erdgas, Erdölgas",Erdgas,37.1040,NaN,Volleinspeisung,50Hertz Transmission GmbH (SNB982046657236),Hochspannung,NaN,NaN
3,SEE929797382345,Lausitz Energie Kraftwerke AG,Gasturbinenkraftwerk Ahrensfelde GT B,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,1990.0,NaN,Kapazitätsreserve aufgrund von § 13e EnWG,"Erdgas, Erdölgas",Erdgas,37.1040,NaN,Volleinspeisung,50Hertz Transmission GmbH (SNB982046657236),Hochspannung,NaN,NaN
4,SEE988046628214,Lausitz Energie Kraftwerke AG,Gasturbinenkraftwerk Ahrensfelde GT C,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1991.0,1991.0,NaN,Kapazitätsreserve aufgrund von § 13e EnWG,"Erdgas, Erdölgas",Erdgas,37.1040,NaN,Volleinspeisung,50Hertz Transmission GmbH (SNB982046657236),Hochspannung,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,SEE975094128629,NaN,HKW Mitte Kessel 12,38114.0,Braunschweig,Reiherstraße,3,Niedersachsen,1971.0,NaN,2024-06-26 00:00:00,stillgelegt,"Erdgas, Erdölgas",Erdgas,20.0000,NaN,Volleinspeisung,NaN,NaN,Ja,22.400
269,SEE926418118239,NaN,GTS4,49479.0,Ibbenbüren,Groner Allee,76,Nordrhein-Westfalen,2013.0,NaN,2024-07-31 00:00:00,stillgelegt,"Erdgas, Erdölgas",Erdgas,1.8223,NaN,Teileinspeisung (einschließlich Eigenverbrauch),SWTE Netz GmbH & Co. KG (SNB950006175489),NaN,Ja,1.853
270,SEE937157344278,NaN,Kraftwerk Walheim Block 1,74399.0,Walheim,Mühlstraße,1,Baden-Württemberg,1964.0,NaN,2024-07-31 00:00:00,stillgelegt,Steinkohlen,Steinkohle,96.0000,NaN,Volleinspeisung,Netze BW GmbH (SNB948311994307),NaN,Nein,107.000
271,SEE981220191160,NaN,HKW Oberkirch,77704.0,Oberkirch,Hauptstraße,2,Baden-Württemberg,1987.0,NaN,2024-08-30 00:00:00,stillgelegt,Steinkohlen,Steinkohle,18.5000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),NaN,NaN,Ja,20.000
272,SEE937052769589,NaN,Heyden 4,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,1987.0,NaN,2024-09-30 00:00:00,stillgelegt,Steinkohlen,Steinkohle,875.0000,NaN,Volleinspeisung,NaN,NaN,Nein,920.000

In [100]:
pl4['company'] = pl4['company'].apply(lambda x: fix_company(x))
#pl4['endop'] = pl4['state'].apply(lambda x: extract_still(x))
pl4['state'] = pl4['state'].apply(lambda x: extract_state3(x))
pl4['chp'] = pl4['chp'].apply(lambda x: fix_kwk(x))

In [101]:
list(pl4.groupby("state").count().reset_index()['state'])

['Kapazitätsreserve',
 'Netzreserve',
 'bnBm',
 'in Betrieb',
 'stillgelegt',
 'vorläufig stillgelegt']

In [102]:
atest = pl4.groupby("state").count()

In [103]:
def myf():
    return 0 if "test" == "test" else 1

In [104]:
atest

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,
Kapazitätsreserve,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve,27,27,27,27,27,27,26,27,27,27,0,25,27,27,0,27,27,27,0,0
bnBm,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
in Betrieb,1215,1215,1215,1215,1215,1149,1126,1215,1215,1215,0,1194,1215,1215,0,1205,1215,1215,0,0
stillgelegt,249,0,246,248,249,183,164,249,248,0,249,150,249,249,0,126,168,0,248,135
vorläufig stillgelegt,17,17,17,17,17,17,16,17,17,17,0,17,17,17,0,17,17,17,0,0

In [105]:
newdf = pl4.copy()

In [106]:
#newdf.dtypes

In [107]:
newdf["state"] = newdf["state"].astype('category')
newdf["state"] = newdf["state"].cat.set_categories(STATES, ordered=True)

In [108]:
newdf["chp"] = newdf["chp"].astype('category')
newdf["chp"] = newdf["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)

In [109]:
#list(atest.reset_index()['state'])

In [110]:
#newdf.groupby("energysource").count()

In [111]:
atest

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,
Kapazitätsreserve,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve,27,27,27,27,27,27,26,27,27,27,0,25,27,27,0,27,27,27,0,0
bnBm,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
in Betrieb,1215,1215,1215,1215,1215,1149,1126,1215,1215,1215,0,1194,1215,1215,0,1205,1215,1215,0,0
stillgelegt,249,0,246,248,249,183,164,249,248,0,249,150,249,249,0,126,168,0,248,135
vorläufig stillgelegt,17,17,17,17,17,17,16,17,17,17,0,17,17,17,0,17,17,17,0,0

In [112]:
pl3 = newdf

In [113]:
atest = newdf.groupby(["power"]).count()
atest.sort_values("initialop", inplace=True, ascending=False)

In [114]:
#print(atest)

In [115]:
atest = pl3.groupby(["state"]).count()
# atest

/tmp/ipykernel_2553883/4069360528.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  atest = pl3.groupby(["state"]).count()

In [116]:
# pl3.rename(columns={ pl3.columns[10]: "Energieträger"}, inplace=True)

In [117]:
#bm[bm.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

In [118]:
#bm2 = bm.drop_duplicates()

In [119]:
#pl3

In [120]:
bm

                 plantid            sseid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
3      14-80-55047380000  SEE955310827123
4         12-30532000000  SEE939848582457
..                   ...              ...
936    06-05-300-9046797  SEE976489828827
937               664-07  SEE906830618081
938               664-02  SEE999977738880
939        07-05-8030815  SEE957723162266
940  06-09-661-0020-0001         BNA1337a

[941 rows x 2 columns]

In [121]:
pl4 = bm.merge(pl3, how="right", left_on="sseid", right_on="blockid")

In [122]:
pl4.sort_values(by=['plantid'])

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
1302,01-50-01000004838,BNA0269,BNA0269,NaN,HKW Flensburg,24939.0,Flensburg,Batteriestr.,48,Schleswig-Holstein,1974.0,NaN,2012,stillgelegt,NaN,Mineralölprodukte,30.0000,NaN,NaN,Stadtwerke Flensburg GmbH,NaN,Ja,NaN
309,01-50-01000004838,SEE966920434281,SEE966920434281,Stadtwerke Flensburg,Gasturbine 12,24939,Flensburg,Batteriestraße,48,Schleswig-Holstein,2016.0,2016.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,50.1000,NaN,Volleinspeisung,Stadtwerke Flensburg GmbH (SNB922220582657),Mittelspannung,NaN,NaN
1531,01-50-01000004838,SEE990438768378,SEE990438768378,NaN,Dampfturbine 8,24939.0,Flensburg,Batteriestraße,48,Schleswig-Holstein,1985.0,NaN,2024-04-30 00:00:00,stillgelegt,Steinkohlen,Steinkohle,32.9000,NaN,Volleinspeisung,NaN,NaN,Ja,35.900
308,01-50-01000004838,SEE957285549260,SEE957285549260,Stadtwerke Flensburg,Dampfturbine 9,24939,Flensburg,Batteriestraße,48,Schleswig-Holstein,1988.0,1988.0,NaN,in Betrieb,Steinkohlen,Steinkohle,32.9000,NaN,Volleinspeisung,Stadtwerke Flensburg GmbH (SNB922220582657),Mittelspannung,NaN,NaN
1350,01-50-01000004838,BNA0274,BNA0274,NaN,Heizkraftwerk FL,24939.0,Flensburg,Batteriestr.,48,Schleswig-Holstein,1978.0,NaN,2016,stillgelegt,NaN,Steinkohle,23.0000,NaN,NaN,Stadtwerke Flensburg GmbH,NaN,Nein,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1522,NaN,NaN,SEE952266131625,NaN,"Kraftwerk I, KT13",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1949.0,NaN,2024-04-01 00:00:00,stillgelegt,Steinkohlen,Steinkohle,20.5140,NaN,Volleinspeisung,CPM Netz GmbH (SNB956923775696),NaN,Ja,21.000
1523,NaN,NaN,SEE991559435767,NaN,"Kraftwerk I, KT5",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1940.0,NaN,2024-04-01 00:00:00,stillgelegt,Steinkohlen,Steinkohle,15.6380,NaN,Volleinspeisung,CPM Netz GmbH (SNB956923775696),NaN,Ja,16.000
1524,NaN,NaN,SEE993836152862,NaN,"Kraftwerk I, KT7",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1941.0,NaN,2024-04-01 00:00:00,stillgelegt,Steinkohlen,Steinkohle,17.5720,NaN,Volleinspeisung,CPM Netz GmbH (SNB956923775696),NaN,Ja,18.000
1529,NaN,NaN,SEE994543149961,NaN,ESA-BHKW,48155.0,Münster,Am Mittelhafen,11,Nordrhein-Westfalen,2009.0,NaN,2024-04-28 00:00:00,stillgelegt,"Erdgas, Erdölgas",Erdgas,3.7000,NaN,Volleinspeisung,NaN,NaN,Ja,3.900
1534,NaN,NaN,SEE926418118239,NaN,GTS4,49479.0,Ibbenbüren,Groner Allee,76,Nordrhein-Westfalen,2013.0,NaN,2024-07-31 00:00:00,stillgelegt,"Erdgas, Erdölgas",Erdgas,1.8223,NaN,Teileinspeisung (einschließlich Eigenverbrauch),SWTE Netz GmbH & Co. KG (SNB950006175489),NaN,Ja,1.853

In [123]:
#pl4.sort_values(by=['power'], ascending=False)

In [124]:
#pl4.sort_values(by=['power'], ascending=False)

In [125]:
#pl4[pl4.duplicated(['BlocID'], keep=False)].sort_values("BlockID", ascending=False)

In [126]:
pl5 = pl4[pd.notnull(pl4['blockid'])]
#pl5 = pl4
pl5a = pl5[pd.notnull(pl5['power'])]

In [127]:
#pl4[pl4['plantid'].isnull()].sort_values(by=["power"])

In [128]:
#pl6['plantid'] = pl6['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [129]:
# pl7 = pl6.replace("/", "_")

In [130]:
#pl7 = pl6.apply(str.replace("/", "_"))

In [131]:
#pl6.loc[pl6.Kraftwerksname == "KW Mittelsbüren"]

In [132]:
pl6 =  pl5a.copy() #[pd.notnull(pl5a['plantid'])]

In [133]:
pl6.dtypes

plantid            object
sseid              object
blockid            object
company            object
plantname          object
plz                object
place              object
street             object
streetnum          object
federalstate       object
initialop         float64
initialopYear     float64
endop              object
state            category
e2                 object
energysource       object
power             float64
gerpower          float64
fullsupply         object
TSO                object
voltagelevel       object
chp              category
grosspower        float64
dtype: object

In [134]:
pl6.loc[pl6.blockid == "BNA0711"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
1297,06-05-300-0326774,BNA0711,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963.0,NaN,2012,stillgelegt,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [135]:
pl6['initialop'] = pl6['initialop'].apply(pd.to_numeric)
pl6['endop'] = pl6['endop'].apply(lambda x: to_year2(x))

In [136]:
pl6.loc[pl6.blockid == "BNA0711"].dtypes

plantid            object
sseid              object
blockid            object
company            object
plantname          object
plz                object
place              object
street             object
streetnum          object
federalstate       object
initialop         float64
initialopYear     float64
endop             float64
state            category
e2                 object
energysource       object
power             float64
gerpower          float64
fullsupply         object
TSO                object
voltagelevel       object
chp              category
grosspower        float64
dtype: object

In [137]:
pl6.loc[pl6.blockid == "SEE999977738880"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
1419,664-02,SEE999977738880,SEE999977738880,NaN,IKW Deuben,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,1936.0,NaN,2021.0,stillgelegt,Rohbraunkohlen,Braunkohle,67.0,NaN,Teileinspeisung (einschließlich Eigenverbrauch),NaN,NaN,Ja,78.0

In [138]:
blocks = pl6.copy()
stammdaten = pl6.copy()

In [139]:
#TODO: fill based on endop and state

In [140]:
#blocks['state'] = blocks['state'].fillna(value='stillgelegt')

In [141]:
blocks.loc[blocks['state'].isnull()]

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [142]:
blocks.loc[blocks['state'] == 'in Betrieb'].sort_values(['endop'])

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
0,NaN,NaN,SEE915851127786,STAWAG – Stadt- und Städteregionswerke Aachen AG,BHKW Schwarzer Weg,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023.0,2023.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,21.505,NaN,Volleinspeisung,Regionetz GmbH (SNB911641710114),Mittelspannung,NaN,NaN
1,NaN,NaN,SEE946736241334,Palm Power GmbH & Co. KG,HKW Aalen,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021.0,2021.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,78.302,NaN,Volleinspeisung,Netze BW GmbH (SNB948311994307),Hochspannung; Hochspannung,NaN,NaN
6,661-59,SEE902796244388,SEE902796244388,Sappi Alfeld,Turbine 4,31061,Alfeld,Mühlenmasch,1,Niedersachsen,1970.0,1970.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,11.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Überlandwerk Leinetal GmbH (SNB910956210043),Mittelspannung,NaN,NaN
7,NaN,NaN,SEE973279238699,Sappi Alfeld,Turbine 5,31061,Alfeld,Mühlenmasch,1,Niedersachsen,2003.0,2003.0,NaN,in Betrieb,"Brennlauge, Schwarzlauge, Sulfitablauge",Biomasse,13.000,NaN,Volleinspeisung,Überlandwerk Leinetal GmbH (SNB910956210043),Mittelspannung,NaN,NaN
9,06-08-1741292,SEE971282697380,SEE971282697380,EnBW AG,Heizkraftwerk Altbach/Deizisau Block 4 GT A (s...,73776,Altbach,Industriestraße,11,Baden-Württemberg,1971.0,1971.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,45.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Netze BW GmbH (SNB948311994307),Hochspannung,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,06-05-300-0079450,SEE998356674993,SEE998356674993,Smurfit Kappa Zülpich Papier GmbH,GT1,53909,Zülpich,Zum Mühlengraben,1,Nordrhein-Westfalen,1996.0,1996.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,4.946,NaN,Volleinspeisung,Westnetz GmbH (SNB921897286493),Umspannebene Hochspannung/Mittelspannung,NaN,NaN
1285,06-05-300-0079450,SEE922579581844,SEE922579581844,Smurfit Kappa Zülpich Papier GmbH,GT2,53909,Zülpich,Zum Mühlengraben,1,Nordrhein-Westfalen,1996.0,1996.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,4.946,NaN,Volleinspeisung,Westnetz GmbH (SNB921897286493),Umspannebene Hochspannung/Mittelspannung,NaN,NaN
1286,06-05-300-0079450,SEE968206101610,SEE968206101610,Smurfit Kappa Zülpich Papier GmbH,GT3,53909,Zülpich,Zum Mühlengraben,1,Nordrhein-Westfalen,1997.0,1997.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,4.946,NaN,Volleinspeisung,Westnetz GmbH (SNB921897286493),Umspannebene Hochspannung/Mittelspannung,NaN,NaN
1287,661-97,SEE970806189455,SEE970806189455,Volkswagen Sachsen GmbH,BHKW-G66-KWK-groß,8058,Zwickau,Glauchauer Straße,40,Sachsen,2014.0,2014.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,12.747,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Umspannebene Hochspannung/Mittelspannung,NaN,NaN
1288,NaN,NaN,SEE937830141170,Volkswagen Sachsen GmbH,BHKW-G66-KWK-klein,8058,Zwickau,Glauchauer Straße,40,Sachsen,2017.0,2017.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,3.736,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Umspannebene Hochspannung/Mittelspannung,NaN,NaN

In [143]:
blocks.sort_values("initialop", inplace=True, ascending=False)
# blocks

In [144]:
plants = blocks.copy()
#plants = plants.dropna(subset=["plantid", "initialop"]) #TODO: remove initialop from here

In [145]:
#pl4[pl4.loc]
pl4.loc[pl4.plantid == "nan"]

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [146]:
plants.loc[plants['state'] == 'in Betrieb']

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
448,NaN,NaN,SEE976367618755,BEH Bioenergie Hannover GmbH,Biomethan BHKW 2 Hannover Stöcken,30419,Hannover,Stelinger Straße,19,Niedersachsen,2024.0,2024.0,NaN,in Betrieb,Biomethan (Bioerdgas),Biomasse,4.500,NaN,Volleinspeisung,enercity Netz GmbH (SNB971746988153),Mittelspannung,NaN,NaN
451,NaN,NaN,SEE998877345112,BEH Bioenergie Hannover GmbH,Biomethan BHKW 5 Hannover Stöcken,30419,Hannover,Stelinger Straße,19,Niedersachsen,2024.0,2024.0,NaN,in Betrieb,Biomethan (Bioerdgas),Biomasse,4.500,NaN,Volleinspeisung,enercity Netz GmbH (SNB971746988153),Mittelspannung,NaN,NaN
449,NaN,NaN,SEE958806714600,BEH Bioenergie Hannover GmbH,Biomethan BHKW 3 Hannover Stöcken,30419,Hannover,Stelinger Straße,19,Niedersachsen,2024.0,2024.0,NaN,in Betrieb,Biomethan (Bioerdgas),Biomasse,2.000,NaN,Volleinspeisung,enercity Netz GmbH (SNB971746988153),Mittelspannung,NaN,NaN
515,NaN,NaN,SEE984166693200,Boehringer Ingelheim Pharma GmbH&Co.KG,Boehringer Ingelheim - 6482 - PSI - KWK,55218,Ingelheim,Binger Strasse,173,Rheinland-Pfalz,2024.0,2024.0,NaN,in Betrieb,Industrieabfall,Abfall,12.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Rheinhessische Energie- und Wasserversorgungs-...,Mittelspannung,NaN,NaN
573,NaN,NaN,SEE938663790405,Stadtwerke Kempen GmbH,0066 - STW - BHKW - KWK,47906,Kempen,Otto-Schott-Straße,4,Nordrhein-Westfalen,2024.0,2024.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,2.419,NaN,Volleinspeisung,Stadtwerke Kempen GmbH (SNB943042904373),Mittelspannung,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,664-07,SEE906830618081,SEE906830618081,RWE AG,Fab Fortuna,50129,Bergheim,Auenheimer Straße,NaN,Nordrhein-Westfalen,1948.0,1948.0,NaN,in Betrieb,Rohbraunkohlen,Braunkohle,15.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Amprion GmbH (SNB976890256486),Höchstspannung,NaN,NaN
782,NaN,NaN,SEE996946209945,Caterpillar Energy Solutions,P12,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1939.0,1939.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,3.375,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
784,NaN,NaN,SEE936364054154,Caterpillar Energy Solutions,P18,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1939.0,1939.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,2.300,NaN,NaN,MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
783,NaN,NaN,SEE945811865984,Caterpillar Energy Solutions,P13,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1939.0,1939.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,1.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
538,07-05-8030815,SEE957723162266,SEE957723162266,SWK Stadtwerke Kaiserslautern Versorgungs-AG,HKW Karcherstraße,67655,Kaiserslautern,Karcherstraße,28,Rheinland-Pfalz,1900.0,1900.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,59.800,NaN,Teileinspeisung (einschließlich Eigenverbrauch),SWK Stadtwerke Kaiserslautern Versorgungs-AG (...,Mittelspannung; Mittelspannung,NaN,NaN

In [147]:
#plants

In [148]:
#plants_d = plants.loc[plants.duplicated("KraftwerkID", keep=False)]
# plants_d

In [149]:
#plants_c = plants_d.groupby(["KraftwerkID"]).sum()
#plants_count = plants_d.groupby(["KraftwerkID"]).count()

In [150]:
#plants_f = plants_c.reset_index()

In [151]:
#plants_count = plants_count.loc[:, ["blockid"]]

In [152]:
#plants_count = plants_count.reset_index()
# plants_count

In [153]:
#plants_f = plants_f.merge(plants_count, on="KraftwerkID", how="inner")
# plants_f

In [154]:
#plants[plants.duplicated(['KraftwerkID'], keep=False)].sort_values("BlockID", ascending=False)

In [155]:
plants["energysource"] = plants["energysource"].astype('category')
plants["energysource"] = plants["energysource"].cat.set_categories(ENERGIES, ordered=True)
plants["state"] = plants["state"].astype('category')
#plants["state"] = plants["state"].cat.set_categories(STATES, ordered=True)
plants["chp"] = plants["chp"].astype('category')
plants["chp"] = plants["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)
plants["federalstate"] = plants["federalstate"].astype('category')
plants["federalstate"] = plants["federalstate"].cat.set_categories(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'])

In [156]:
pl1 = pl0.loc[pl0["energysource"].isin(["Kernenergie", "Erdgas", "Steinkohle", "Braunkohle", "Steinkohle"])]

In [157]:
p_grp = plants.groupby("plantid")

In [158]:
#plants.groupby("Energip_subgrper").max()

In [159]:
plants.groupby("state").count()

/tmp/ipykernel_2553883/326027710.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  plants.groupby("state").count()

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,,,
in Betrieb,661,661,1215,1215,1215,1215,1215,1149,1126,1215,1215,1215,0,1194,1215,1215,0,1205,1215,1215,0,0
Kapazitätsreserve,16,16,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve,27,27,27,27,27,27,27,27,26,27,27,27,0,25,27,27,0,27,27,27,0,0
bnBm,0,0,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
stillgelegt,212,212,249,0,246,248,249,183,164,249,248,0,249,150,249,249,0,126,168,0,248,135
vorläufig stillgelegt,13,13,17,17,17,17,17,17,16,17,17,17,0,17,17,17,0,17,17,17,0,0

In [160]:
ACTIVE_STATES

['In Betrieb',
 'Kapazitätsreserve',
 'Netzreserve',
 'bnBm',
 'vorläufig stillgelegt']

In [161]:
plants.loc[plants['state'] == 'In Betrieb']

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [162]:
p_subgrp = plants.loc[plants['state'].isin(ACTIVE_STATES)].groupby('plantid') # TODO: add

In [163]:
plants_act = pd.DataFrame()
for plantid, group in p_subgrp:
    entry = {}
    entry["plantid"] = plantid
    entry["activepower"] = group["power"].sum()
    #plants_act = plants_act.append(entry, ignore_index=True)
    plants_act = pd.concat([plants_act, pd.DataFrame([entry])], ignore_index=True)

In [164]:
plants

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
448,NaN,NaN,SEE976367618755,BEH Bioenergie Hannover GmbH,Biomethan BHKW 2 Hannover Stöcken,30419,Hannover,Stelinger Straße,19,Niedersachsen,2024.0,2024.0,NaN,in Betrieb,Biomethan (Bioerdgas),Biomasse,4.500,NaN,Volleinspeisung,enercity Netz GmbH (SNB971746988153),Mittelspannung,NaN,NaN
451,NaN,NaN,SEE998877345112,BEH Bioenergie Hannover GmbH,Biomethan BHKW 5 Hannover Stöcken,30419,Hannover,Stelinger Straße,19,Niedersachsen,2024.0,2024.0,NaN,in Betrieb,Biomethan (Bioerdgas),Biomasse,4.500,NaN,Volleinspeisung,enercity Netz GmbH (SNB971746988153),Mittelspannung,NaN,NaN
449,NaN,NaN,SEE958806714600,BEH Bioenergie Hannover GmbH,Biomethan BHKW 3 Hannover Stöcken,30419,Hannover,Stelinger Straße,19,Niedersachsen,2024.0,2024.0,NaN,in Betrieb,Biomethan (Bioerdgas),Biomasse,2.000,NaN,Volleinspeisung,enercity Netz GmbH (SNB971746988153),Mittelspannung,NaN,NaN
515,NaN,NaN,SEE984166693200,Boehringer Ingelheim Pharma GmbH&Co.KG,Boehringer Ingelheim - 6482 - PSI - KWK,55218,Ingelheim,Binger Strasse,173,Rheinland-Pfalz,2024.0,2024.0,NaN,in Betrieb,Industrieabfall,Abfall,12.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),Rheinhessische Energie- und Wasserversorgungs-...,Mittelspannung,NaN,NaN
573,NaN,NaN,SEE938663790405,Stadtwerke Kempen GmbH,0066 - STW - BHKW - KWK,47906,Kempen,Otto-Schott-Straße,4,Nordrhein-Westfalen,2024.0,2024.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,2.419,NaN,Volleinspeisung,Stadtwerke Kempen GmbH (SNB943042904373),Mittelspannung,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784,NaN,NaN,SEE936364054154,Caterpillar Energy Solutions,P18,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1939.0,1939.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,2.300,NaN,NaN,MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
783,NaN,NaN,SEE945811865984,Caterpillar Energy Solutions,P13,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1939.0,1939.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,1.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
1419,664-02,SEE999977738880,SEE999977738880,NaN,IKW Deuben,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,1936.0,NaN,2021.0,stillgelegt,Rohbraunkohlen,Braunkohle,67.000,NaN,Teileinspeisung (einschließlich Eigenverbrauch),NaN,NaN,Ja,78.0
538,07-05-8030815,SEE957723162266,SEE957723162266,SWK Stadtwerke Kaiserslautern Versorgungs-AG,HKW Karcherstraße,67655,Kaiserslautern,Karcherstraße,28,Rheinland-Pfalz,1900.0,1900.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,59.800,NaN,Teileinspeisung (einschließlich Eigenverbrauch),SWK Stadtwerke Kaiserslautern Versorgungs-AG (...,Mittelspannung; Mittelspannung,NaN,NaN
1295,06-09-661-0020-0001,BNA1337a,BNA1337a,NaN,Heizkraftwerk,63741.0,Aschaffenburg,Weichertstr.,7,Bayern,NaN,NaN,2012.0,stillgelegt,NaN,Erdgas,27.000,NaN,NaN,Aschaffenburger Versorgungs GmbH,NaN,Ja,NaN

In [165]:
plants_act

                plantid  activepower
0     01-50-04000082392        9.545
1     03-04-04224004080      485.000
2     03-06-06254353820      487.000
3        06-00004310411       93.000
4        06-00176010435     1102.000
5     06-05-500-0342658      690.000
6     06-05-500-9981505       10.000
7     06-05-900-0045033      196.000
8     06-05-900-0080266      247.000
9     06-05-900-0205103      720.000
10    06-05-900-0327252      460.000
11    06-05-900-0865327     1287.000
12        06-08-1020129      250.000
13        06-08-1741292      433.000
14        06-08-2142201      148.000
15        06-08-2797933      870.000
16        06-08-2948214      860.000
17  06-09-190-0036-0002       64.000
18  06-09-273-0310-0001       25.400
19       06-10-00100999      726.000
20       06-10-00101000      390.000
21       06-10-00101003      655.600
22         07-01-126351       27.500
23        07-04-6021280      250.000
24       12-50724070000      186.756
25               661-07      148.416
26               661-44        6.000
27               661-77       14.050
28               662-03       85.000
29               669-01      772.000

In [166]:
#plants_act.sort_values('activepower', ascending=False)

In [167]:
#ap = plants.loc[plants.state == "in Betrieb" | plants.state == "Gesetzlich an Stilllegung gehindert"]

In [168]:
#plants_a.dtypes

In [169]:
plants_a = pd.DataFrame()
for plantid, group in p_grp:
    #if not plantid == "06-05-300-9046797":
    #    continue
    entry = {}
    #print(entry)
    entry["plantid"] = plantid
    # entry["BlockID"] = group
    try:
        entry["plantname"] = group["plantname"].value_counts().index[0]
    except IndexError:
        entry["plantname"] = np.nan
    entry["federalstate"] = group["federalstate"].value_counts().index[0]
    entry["energysource"] = group["energysource"].min()
    try:
        entry["chp"] = group["chp"].min()
    except TypeError:
        #print("aneror")
        #print(plantid)
        #print(group['KWK'].count())
        entry["chp"] = ""
    entry["latestexpanded"] = group["initialop"].max()
    entry["initialop"] = group["initialop"].min()
    entry["totalpower"] = group["power"].sum()
    entry["state"] = group["state"].min()
    entry["blockcount"] = group["blockid"].count()
    try:
        entry["company"] = group["company"].value_counts().index[0]
    except IndexError:
        ;
    #print(entry)
    #break
    plants_a = pd.concat([plants_a, pd.DataFrame([entry])], ignore_index=True)

In [170]:
#plants_a

In [171]:
#TODO: fix this

In [172]:
#plants_a[pd.isnull(plants_a)]

In [173]:
int_list = ['blockcount', 'initialop', 'latestexpanded']
for column in int_list:
    plants_a[column] = plants_a[column].astype(int)
#plant['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)

In [174]:
plants_a.dtypes

plantid            object
plantname          object
federalstate       object
energysource       object
chp                object
latestexpanded      int64
initialop           int64
totalpower        float64
state              object
blockcount          int64
company            object
dtype: object

In [175]:
plants_a["energysource"] = plants_a["energysource"].astype('category')
plants_a["energysource"] = plants_a["energysource"].cat.set_categories(ENERGIES, ordered=True)
plants_a["state"] = plants_a["state"].astype('category')
plants_a["state"] = plants_a["state"].cat.set_categories(STATES, ordered=True)
plants_a["chp"] = plants_a["chp"].astype('category')
plants_a["chp"] = plants_a["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)
plants_a["federalstate"] = plants_a["federalstate"].astype('category')
plants_a["federalstate"] = plants_a["federalstate"].cat.set_categories(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'])

In [176]:
plants_a.dtypes

plantid             object
plantname           object
federalstate      category
energysource      category
chp               category
latestexpanded       int64
initialop            int64
totalpower         float64
state             category
blockcount           int64
company             object
dtype: object

In [177]:
plants_a.loc[plants_a.plantid == "666-999"]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company]
Index: []

In [178]:
plants_a.loc[plants_a.plantid == "06-00176010435"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company
35,06-00176010435,Staudinger,Hessen,Steinkohle,Ja,1992,1965,1644.0,Netzreserve,4,Uniper SE

In [179]:
plants_a.loc[plants_a.plantid == "06-05-900-0865327"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company
106,06-05-900-0865327,Gersteinwerk,Nordrhein-Westfalen,Steinkohle,Nein,1984,1972,2011.0,in Betrieb,9,RWE AG

In [180]:
#plants_a = plants.drop_duplicates(subset="KraftwerkID")

In [181]:
column_titles = ['plantid', 'plantname', 'federalstate','energysource', 'chp', 'latestexpanded', 'initialop', 'totalpower', 'state', 'blockcount', 'company']
plants_b = plants_a.reindex(columns=column_titles)

In [182]:
#plants_b

In [183]:
list(blocks)

['plantid',
 'sseid',
 'blockid',
 'company',
 'plantname',
 'plz',
 'place',
 'street',
 'streetnum',
 'federalstate',
 'initialop',
 'initialopYear',
 'endop',
 'state',
 'e2',
 'energysource',
 'power',
 'gerpower',
 'fullsupply',
 'TSO',
 'voltagelevel',
 'chp',
 'grosspower']

In [184]:
#blocks.drop(['place', 'plz', 'street'], axis=1, inplace=True)

In [185]:
blocks[blocks.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
785,NaN,NaN,SEE988996320985,Caterpillar Energy Solutions,P31,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1994.0,1994.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,1.84,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
786,NaN,NaN,SEE988996320985,Caterpillar Energy Solutions,P31,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1994.0,1994.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,1.84,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN

In [186]:
#blocks

In [187]:
plants_b.sort_values("initialop", ascending=False, inplace=True)

In [188]:
#drop_list = ['Blockname', 'KWK', 'Nettoleistung', 'Stilllegung', 'Straße und Hausnummer (Standort Kraftwerk)', 'PLZ', 'Ort', 'Nettoleistung']
#plants_g = plants_f.drop(drop_list, axis=1)

In [189]:
#plants_h = plants_g.rename(columns={"KraftwerkID": "plantid", "Gesamtleistung": "totalpower", "Blockzahl": "blockcount", "BlockID": "blockid", "Bundesland": "federalstate", "Energieträger": "energysource", "Inbetriebnahme": "latestexpanded", "Kraftwerksname": "plantname", "Status": "state", "Unternehmen": "company"})

In [190]:
plants_final = plants_b.loc[:]

In [191]:
plants_final.dtypes

plantid             object
plantname           object
federalstate      category
energysource      category
chp               category
latestexpanded       int64
initialop            int64
totalpower         float64
state             category
blockcount           int64
company             object
dtype: object

In [192]:
# plants_final

In [193]:
# stammdaten

In [194]:
#stammdaten

In [195]:
# cols = [0,2,3,9,10,11,12]
stammdaten = pl6.copy()
drop_list = ['plantid', 'energysource', 'initialop', 'chp', 'plantname', 'power', 'state', 'endop', 'company', 'sseid', 'TSO', 'voltagelevel']
stammdaten_dafuq = stammdaten.drop(drop_list, axis=1)
stammdaten = stammdaten_dafuq.copy()

In [196]:
stammdaten_dafuq.sort_values(['blockid'])

,blockid,plz,place,street,streetnum,federalstate,initialopYear,e2,gerpower,fullsupply,grosspower
1294,BNA0011,79774.0,Albbruck,NaN,NaN,Baden-Württemberg,NaN,Steinkohle,NaN,NaN,NaN
1389,BNA0012d,31061.0,Alfeld,Mühlenmarsch,1,Niedersachsen,NaN,NaN,NaN,NaN,NaN
1316,BNA0059a,34225.0,Baunatal,NaN,NaN,Hessen,NaN,NaN,NaN,NaN,NaN
1392,BNA0075,12207.0,Berlin,Ostpreußendamm,61,Berlin,NaN,NaN,NaN,NaN,NaN
1375,BNA0076,12207.0,Berlin,Ostpreußendamm,61,Berlin,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
761,SEE999819576335,39126,Magdeburg,Kraftwerk-Privatweg,7,Sachsen-Anhalt,2006.0,"Abfall (Hausmüll, Siedl.abf.)",NaN,Volleinspeisung,NaN
254,SEE999839188105,40476,Düsseldorf,Rather Straße,51,Nordrhein-Westfalen,2012.0,"Erdgas, Erdölgas",NaN,Teileinspeisung (einschließlich Eigenverbrauch),NaN
1416,SEE999848168525,21079.0,Hamburg,Moorburger Schanze,2,Hamburg,NaN,Steinkohlen,NaN,Volleinspeisung,860.0
969,SEE999966551940,14478,Potsdam,Zum Heizwerk,20,Brandenburg,1996.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
1419,SEE999977738880,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,NaN,Rohbraunkohlen,NaN,Teileinspeisung (einschließlich Eigenverbrauch),78.0

In [197]:
stmp = pl6.copy()
stammdaten2 = stmp.merge(prtr, how="left", left_on="plantid", right_on="kennnummer")

In [198]:
#stammdaten2.loc[stammdaten2.blockid == "BNA0221c"]

In [199]:
#stammdaten.to_csv("stammdaten.csv", index=False)

In [200]:
#plants_final.to_csv("plants.csv", index=False)

In [201]:
#blocks.to_csv("blocks_3.csv", index=False)

In [202]:
stammdaten2

,plantid,sseid,blockid,company,plantname,plz_x,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower,jahr,kennnummer,betriebsname,betriebsname_2,betreiber,eigentuemer,plz_y,ort,strasse,hausnr,bundesland,flusseinzugsgebiet,geo_lat_wgs84,geo_long_wgs84,taet_nr,taetigkeit,activity,haupttaetigkeit,branche,sector,nace_id,nace_wirtschaftszweig,nace_sector,stoffgruppe,substances_group,schadstoff,pollutant,umweltkompartiment,releases_to,jahresfracht_freisetzung,versehentliche_freisetzung,schadstoff_schwellenwert,einheit,unit,bestimmungsmethode,determination_method,schutzgrund_fracht,confidential_reason_release,schutzgrund_betrieb,confidential_reason_facility
0,NaN,NaN,SEE915851127786,STAWAG – Stadt- und Städteregionswerke Aachen AG,BHKW Schwarzer Weg,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023.0,2023.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,21.505,NaN,Volleinspeisung,Regionetz GmbH (SNB911641710114),Mittelspannung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SEE946736241334,Palm Power GmbH & Co. KG,HKW Aalen,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021.0,2021.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,78.302,NaN,Volleinspeisung,Netze BW GmbH (SNB948311994307),Hochspannung; Hochspannung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,661-07,SEE930596800480,SEE930596800480,LEAG,Gasturbinenkraftwerk Ahrensfelde GT A,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,1990.0,NaN,Kapazitätsreserve,"Erdgas, Erdölgas",Erdgas,37.104,NaN,Volleinspeisung,50Hertz Transmission GmbH (SNB982046657236),Hochspannung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,661-07,SEE929797382345,SEE929797382345,LEAG,Gasturbinenkraftwerk Ahrensfelde GT B,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,1990.0,NaN,Kapazitätsreserve,"Erdgas, Erdölgas",Erdgas,37.104,NaN,Volleinspeisung,50Hertz Transmission GmbH (SNB982046657236),Hochspannung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,661-07,SEE988046628214,SEE988046628214,LEAG,Gasturbinenkraftwerk Ahrensfelde GT C,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1991.0,1991.0,NaN,Kapazitätsreserve,"Erdgas, Erdölgas",Erdgas,37.104,NaN,Volleinspeisung,50Hertz Transmission GmbH (SNB982046657236),Hochspannung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51261,06-05-700-0105516,SEE937052769589,SEE937052769589,NaN,Heyden 4,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,1987.0,NaN,2024.0,stillgelegt,Steinkohlen,Steinkohle,875.000,NaN,Volleinspeisung,NaN,NaN,Nein,920.0,2022.0,06-05-700-0105516,Uniper Kraftwerke GmbH,Kraftwerk Heyden,Uwe Knorr,Uniper Kraftwerke GmbH,32469,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,Weser,52.381589,8.998648,1.c,Verbrennungsanlagen > 50 MW,Thermal power stations and other combustion in...,1.0,Energiesektor,Energy sector,3511.0,Elektrizitätserzeugung,Production of electricity,Treibhausgase,Greenhouse gases,Kohlendioxid (CO2),Carbon dioxide (CO2),Luft,Air,1.380000e+09,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
51262,06-05-700-0105516,SEE937052769589,SEE937052769589,NaN,Heyden 4,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,1987.0,NaN,2024.0,stillgelegt,Steinkohlen,Steinkohle,875.000,NaN,Volleinspeisung,NaN,NaN,Nein,920.0,2022.0,06-05-700-0105516,Uniper Kraftwerke GmbH,Kraftwerk Heyden,Uwe Knorr,Uniper Kraftwerke GmbH,32469,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,Weser,52.381589,8.998648,1.c,Verbrennungsanlagen > 50 MW,Thermal power stations and other combustion in...,1.0,Energiesektor,Energy sector,3511.0,Elektrizitätserzeugung,Production of electricity,Andere Gase,Other gases,Stickoxide (NOx/NO2),Nitrogen oxides (NOx/NO2),Luft,Air,7.940000e+05,0.0,100000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
51263,06-05-700-0105516,SEE937052769589,SEE937052769589,NaN,Heyden 4,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,1987.0,NaN,2024.0,stillgelegt,Steinkohlen,Steinkohle,875.000,NaN,Volleinspeisung,NaN,NaN,Nein,920.0,2022.0,06-05-700-0105516,Uniper Kraftwerke GmbH,Kraftwerk Heyden,Uwe Knorr,Uniper Kraftwerke GmbH,32469,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,Weser,52.381589,8.998648,1.c,Verbrennungsanlagen > 50 MW,Thermal power stations and other combustion in...,1.0,Energiesektor,Energy sector,3511.0,Elektrizitätserzeugung,Production of electricity,Andere Gase,Other gases,Schwefeloxide (SOx/SO2),Sulphur oxides (SOx/SO2),Luft,Air,5.180000e+05,0.0,150000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
51264,06-05-700-0105516,SEE937052769589,SEE937052769589,NaN,Heyden 4,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,1987.0,NaN,2024.0,stillgelegt,Steinkohlen,Steinkohle,875.000,NaN,Volleinspeisung,NaN,NaN,Nein,920.0,2022.0,06-05-700-0105516,Uniper Kraftwerke GmbH,Kraftwerk Heyden,Uwe Knorr,Uniper Kraftwerke GmbH,32469,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,Weser,52.381589,8.998648,1.c,Verbrennungsanlagen > 50 MW,Thermal power stations and other combustion in...,1.0,Energiesektor,Energy sector,3511.0,Elektrizitätserzeugung,Production of electricity,Andere Gase,Other gases,Chlor und anorganische Verbindungen (als HCl),Chlorine and inorganic compounds (as HCl),Luft,Air,1.060000e+04,0.0,10000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
51265,06-05-700-0105516,SEE937052769589,SEE937052769589,NaN,Heyden 4,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,1987.0,NaN,2024.0,stillgelegt,Steinkohlen,Steinkohle,875.000,NaN,Volleinspeisung,NaN,NaN,Nein,920.0,2022.0,06-05-700-0105516,Uniper Kraftwerke GmbH,Kraftwerk Heyden,Uwe Knorr,Uniper Kraftwerke GmbH,32469,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,Weser,52.381589,8.998648,1.c,Verbrennungsanlagen > 50 MW,Thermal power stations and other combustion in...,1.0,Energiesektor,Energy sector,3511.0,Elektrizitätserzeugung,Production of electricity,Andere Gase,Other gases,Fluor und anorganische Verbindungen (als HF),Fluorine and inorganic compounds (as HF),Luft,Air,6.180000e+03,0.0,5000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN

In [203]:
DROP_ST = ['blockid', 'jahr', 'kennnummer','betriebsname','betriebsname_2','plz_x','ort','strasse','hausnr','bundesland','flusseinzugsgebiet','taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']
DROP_ST2 = ['jahr', 'kennnummer','betriebsname','betriebsname_2','plz','ort','strasse','hausnr','bundesland','flusseinzugsgebiet','taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']
DROP_ST3 = ['jahr', 'kennnummer', 'bundesland', 'flusseinzugsgebiet', "betriebsname", "betriebsname_2", 'taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']

In [204]:
#DROP_ST = ['jahr']

In [205]:
plants_d1 = plants_final.merge(prtr, how="left", left_on="plantid", right_on="kennnummer")

In [206]:
#plants_d1.dtypes

In [207]:
pld2 = plants_d1.drop_duplicates(['plantid'])

In [208]:
pld3 = pld2.drop(DROP_ST3, axis=1)
plants_final1 = pld3

In [209]:
plants_act

                plantid  activepower
0     01-50-04000082392        9.545
1     03-04-04224004080      485.000
2     03-06-06254353820      487.000
3        06-00004310411       93.000
4        06-00176010435     1102.000
5     06-05-500-0342658      690.000
6     06-05-500-9981505       10.000
7     06-05-900-0045033      196.000
8     06-05-900-0080266      247.000
9     06-05-900-0205103      720.000
10    06-05-900-0327252      460.000
11    06-05-900-0865327     1287.000
12        06-08-1020129      250.000
13        06-08-1741292      433.000
14        06-08-2142201      148.000
15        06-08-2797933      870.000
16        06-08-2948214      860.000
17  06-09-190-0036-0002       64.000
18  06-09-273-0310-0001       25.400
19       06-10-00100999      726.000
20       06-10-00101000      390.000
21       06-10-00101003      655.600
22         07-01-126351       27.500
23        07-04-6021280      250.000
24       12-50724070000      186.756
25               661-07      148.416
26               661-44        6.000
27               661-77       14.050
28               662-03       85.000
29               669-01      772.000

In [210]:
plants_final2 = plants_final1.merge(plants_act, on="plantid", how='left')

In [211]:
plants_final3 = plants_final2.dropna(subset=["plantid"])

In [212]:
plants_final3.groupby("energysource").count()

/tmp/ipykernel_2553883/2887887728.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  plants_final3.groupby("energysource").count()

,plantid,plantname,federalstate,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
energysource,,,,,,,,,,,,,,,,,,,
Kernenergie,8,8,8,8,8,8,8,8,8,0,0,0,0,0,0,0,0,0,0
Braunkohle,29,29,29,15,29,29,29,29,29,23,27,27,27,27,27,27,27,27,0
Steinkohle,68,68,68,43,68,68,68,68,68,43,65,65,65,65,65,65,65,65,15
Erdgas,195,193,195,44,195,195,195,195,195,172,127,127,127,127,127,127,127,127,13
Mineralölprodukte,19,19,19,8,19,19,19,19,19,12,6,6,6,6,6,6,6,6,2
Abfall,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Biomasse,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [213]:
plants_final2

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
0,06-11-01-1105502,GuD Marzahn Gasturbine,Berlin,Erdgas,NaN,2020,2020,258.800,in Betrieb,2,BEW Berliner Energie und Wärme AG,Vattenfall Europe Wärme AG,Vattenfall Europe Wärme AG,12681,Berlin,Rhinstr.,70,52.523389,13.522089,NaN
1,06-09-162-0025-0001,Werk 1.5 KWK 2,Bayern,Erdgas,NaN,2019,2019,26.940,in Betrieb,7,BMW AG,Bayerische Motorenwerke AG,Bayerische Motorenwerke AG,80788,München,Lerchenauer Str.,76,48.179175,11.561502,NaN
2,661-106,70001314.01,Thüringen,Erdgas,NaN,2018,2018,17.548,in Betrieb,4,ENGIE Deutschland GmbH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,661-111,Gasmotor Bad Salzungen,Thüringen,Erdgas,NaN,2018,2018,10.003,in Betrieb,1,TEAG Thüringer Energie AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,661-10,Küstenkraftwerk K.I.E.L Motor 13,Schleswig-Holstein,Erdgas,NaN,2018,2018,189.120,in Betrieb,20,Stadtwerke Kiel AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,RWE AG,-,-,52249,Eschweiler,Zum Hagelkreuz,20,50.833162,6.314578,NaN
316,06-05-300-9046797,LEV KWG G23,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.000,in Betrieb,8,Currenta GmbH & Co. OHG,-,-,51368,Leverkusen,CHEMPARK Leverkusen,Gebäude D 8,51.022209,6.985901,NaN
317,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,NaN,1948,1948,15.000,in Betrieb,1,RWE AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,SWK Stadtwerke Kaiserslautern Versorgungs-AG,-,-,67655,Kaiserslautern,Karcherstr.,28,49.434939,7.760927,NaN

In [214]:
plants_final2[pd.isnull(plants_final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower]
Index: []

In [215]:
stammdaten

,blockid,plz,place,street,streetnum,federalstate,initialopYear,e2,gerpower,fullsupply,grosspower
0,SEE915851127786,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
1,SEE946736241334,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
2,SEE930596800480,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
3,SEE929797382345,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
4,SEE988046628214,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1991.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1533,SEE975094128629,38114.0,Braunschweig,Reiherstraße,3,Niedersachsen,NaN,"Erdgas, Erdölgas",NaN,Volleinspeisung,22.400
1534,SEE926418118239,49479.0,Ibbenbüren,Groner Allee,76,Nordrhein-Westfalen,NaN,"Erdgas, Erdölgas",NaN,Teileinspeisung (einschließlich Eigenverbrauch),1.853
1535,SEE937157344278,74399.0,Walheim,Mühlstraße,1,Baden-Württemberg,NaN,Steinkohlen,NaN,Volleinspeisung,107.000
1536,SEE981220191160,77704.0,Oberkirch,Hauptstraße,2,Baden-Württemberg,NaN,Steinkohlen,NaN,Teileinspeisung (einschließlich Eigenverbrauch),20.000
1537,SEE937052769589,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,NaN,Steinkohlen,NaN,Volleinspeisung,920.000

In [216]:
#plants_final2.sort_values("activepower", ascending=False)

In [217]:
#stammdaten2.dtypes

In [218]:
#stammdaten3.sort_values(by=['plantid'], ascending=True)

In [219]:
#stammdaten3 = stammdaten2.drop(DROP_ST, axis=1)

In [220]:
#stammdaten4 = stammdaten3.drop_duplicates(['bnaid'])

In [221]:
#stammdaten4

In [222]:
#list(stammdaten2)

In [223]:
'''


"CREATE TABLE blocks(plantid TEXT, blockid TEXT NOT NULL PRIMARY KEY, blockdescription TEXT, federalstate TEXT, energysource TEXT, initialop INTEGER, chp TEXT,
blockname TEXT, netpower REAL, state TEXT, endop TEXT, company TEXT, FOREIGN KEY (blockid) REFERENCES addresses(blockid) ON DELETE CASCADE);"
662-01|BNA0164|Vattenfall GmbH|Brunsbüttel|Schleswig-Holstein|GT D|0.0|stillgelegt|Mineralölprodukte|Nein|63.5|201

'''

'\n\n\n"CREATE TABLE blocks(plantid TEXT, blockid TEXT NOT NULL PRIMARY KEY, blockdescription TEXT, federalstate TEXT, energysource TEXT, initialop INTEGER, chp TEXT,\nblockname TEXT, netpower REAL, state TEXT, endop TEXT, company TEXT, FOREIGN KEY (blockid) REFERENCES addresses(blockid) ON DELETE CASCADE);"\n662-01|BNA0164|Vattenfall GmbH|Brunsbüttel|Schleswig-Holstein|GT D|0.0|stillgelegt|Mineralölprodukte|Nein|63.5|201\n\n'

In [224]:
#|664-02|IKW

In [225]:
blocks2 = blocks[['blockid', 'plantid', 'plantname', 'federalstate', 'energysource', 'initialop', 'chp', 'power', 'state', 'endop', 'company']]

In [226]:
blocks2.loc[blocks2.blockid == "SEE999977738880"]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
1419,SEE999977738880,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,1936.0,Ja,67.0,stillgelegt,2021.0,NaN

In [227]:
blocks2.loc[blocks2.blockid == "SEE982928435068"]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
60,SEE982928435068,06-11-01-1105502,GuD Marzahn Dampfturbine,Berlin,Erdgas,2020.0,NaN,69.3,in Betrieb,NaN,BEW Berliner Energie und Wärme AG

In [228]:
list(blocks2)

['blockid',
 'plantid',
 'plantname',
 'federalstate',
 'energysource',
 'initialop',
 'chp',
 'power',
 'state',
 'endop',
 'company']

In [229]:
#blocks2.loc['C', 'x'] = "BNA1949"

In [230]:
stammdaten.to_csv("stammdaten_nh_new_2.csv", index=False, header=False)
blocks2.to_csv("blocks_nh_2.csv", index=False, header=False)
plants_final2.to_csv("plants_nh_2.csv", index=False, header=False)
stammdaten.to_csv("stammdaten_2.csv", index=False)
blocks2.to_csv("blocks_2.csv", index=False)
plants_final2.to_csv("plants_2.csv", index=False)

In [ ]:
#sqlite3 plantwatch.db  "CREATE TABLE plants(plantid TEXT NOT NULL PRIMARY KEY, plantname TEXT, federalstate TEXT, energysource TEXT, chp TEXT, latestexpanded INT, initialop INT, totalpower REAL, state TEXT, blockcount INT,  company TEXT, plz TEXT, place TEXT, street TEXT, number TEXT, latitude REAL, longitude REAL, activepower REAL, energy_2015 INTEGER,  energy_2016 INTEGER,  energy_2017 INTEGER,  energy_2018 INTEGER,  energy_2019 INTEGER, energy_2020 INTEGER, energy_2021 INTEGER, co2_2007 INTEGER,  co2_2008 INTEGER,  co2_2009 INTEGER,  co2_2010 INTEGER,  co2_2011 INTEGER,  co2_2012 INTEGER,  co2_2013 INTEGER,  co2_2014 INTEGER,  co2_2015 INTEGER,  co2_2016 INTEGER,  co2_2017 INTEGER,  co2_2018 INTEGER, co2_2019 INTEGER, co2_2020 INTEGER, FOREIGN KEY (plantid) REFERENCES blocks(plantid) ON DELETE CASCADE);"

In [ ]:
blocks2.dropna(subset=['plantid'])

In [ ]:
blocks2.shape

In [ ]:
blocks2.dropna(subset=['plantid']).shape

In [ ]:
stammdaten.dropna(subset=['sseid', 'bnaid']).sort_values(by=['sseid'], ascending=False)

In [ ]:
stammdaten

In [ ]:
blocks.loc[blocks["blockid"] == "BNA0645"]

In [ ]:
#bm2.to_csv("bpm.csv", index=False)

In [ ]:
#blocks

In [ ]:
#blocks.groupby('Energieträger').count()

In [ ]:
#pl4 = blocks.loc[blocks['Energieträger'] == "Mineralölprodukte"]

In [ ]:
#pl4

In [ ]:
#pd.set_option('display.max_rows', None)

In [ ]:
#pl4.loc[pl4['Energieträger'] == "Mineralölprodukte"].sort_values(["Bundesland", "Unternehmen", "Kraftwerksname"])

In [ ]:
#plants_final2

In [ ]:
blocks2.sort_values('power', ascending=False)[0:20]

In [ ]:
blocks2.sort_values('power', ascending=False)[0:20]