In [1]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re
from helpers import get_renamed_blocks, get_renamed_blocks3

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
#STATES = ['in Betrieb', 'Gesetzlich an Stilllegung gehindert', 'Netzreserve',  'Sicherheitsbereitschaft', 'Sonderfall', 'vorläufig stillgelegt', 'stillgelegt', 'Kohlestromvermarktungsverbot']
#STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'bnBm','stillgelegt', 'vorläufig stillgelegt']
ACTIVE_STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'bnBm', 'vorläufig stillgelegt']
ENERGIES = ["Kernenergie", "Braunkohle", "Steinkohle", "Erdgas", "Mineralölprodukte", "Abfall", "Biomasse", ""]

In [141]:
bm = pd.read_csv("../basic/plant_sse_mapper.csv", engine="python")
plr = pd.read_excel("../data/Kraftwerksliste.xlsx", sheet_name=1, skiprows=10)
pl0 = pd.read_excel("../data/Kraftwerksliste.xlsx", skiprows=11)
prtr = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx")

In [142]:
bm['plantid'] = bm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [143]:
bm.loc[bm.plantid.str.contains("_")]

                  plantid            sseid
141  06-04-11_2001178_8_2  SEE989202977269
259  06-04-11_2001178_8_1  SEE958310939391
566  06-04-11_2001178_8_0  SEE968950464368
687  06-04-11_2001178_8_1          BNA0146
723  06-04-11_2001178_8_2  SEE924172977710
853  06-04-11_2001178_8_0          BNA0140
856  06-04-11_2001178_8_1          BNA0145
881  06-04-11_2039669_2_0  SEE904968236689

In [144]:
pl0_bak = pl0.copy()
plr_bak = plr.copy()

In [145]:
#list(pl0_bak)
#list(plr_bak)

In [146]:
cols = [0,12,15,16,17,20]
plt = get_renamed_blocks(pl0)
plq = plt.drop(plt.columns[cols],axis=1)
cols2 = [0, 10,11,17,20,21]
plr0a = get_renamed_blocks3(plr)
plr0b = plr0a.drop(plr0a.columns[cols2],axis=1)

In [147]:
#list(plq)
#list(plr0b)

In [148]:
plq0a = plq[~plq['blockid'].isin(["SEE9-Dummy-nicht_EEG", "SEE9-Dummy-EEG"])] # remove non-conventional facilities
plq0b = plq0a.sort_values(['power'], ascending=False)

In [149]:
plq0a.insert(10, "endop", np.nan)
plr0b.insert(2, "company", np.nan)

In [150]:
plq0a.shape

(1842, 19)

In [151]:
plq0a.shape

(1842, 19)

In [152]:
plq0a.shape

(1842, 19)

In [153]:
plr0b.shape

(273, 17)

In [154]:
pl_combined = pd.concat([plq0a, plr0b])
pl_combined['energysource'] = pl_combined['energysource'].apply(lambda x: str(x).replace('Wärme', 'Erdgas'))

In [155]:
pl_combined.loc[pl_combined.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963,NaN,2012,NaN,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [156]:
pl_combined.shape

(2115, 21)

In [157]:
pl0 = pl_combined.copy()

In [158]:
pl_debug = pl0.copy()
pl_debug['initialop'] = pd.to_datetime(pl_debug['initialop'], errors='coerce')
pl_debug2 = pl_debug.copy()
pl1 = pl0.loc[pl0["energysource"].isin(ENERGIES)]
pl_debug = pl0.copy()
pl_debug['initialop'] = pd.to_datetime(pl_debug['initialop'], errors='coerce')
pl_debug2 = pl_debug.copy()

In [159]:
pl1 = pl0.loc[pl0["energysource"].isin(ENERGIES)]

In [160]:
pl0.loc[pl0["blockid"] == "BNA0645"]

Empty DataFrame
Columns: [blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [161]:
pl_debug2.groupby("state").count()

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,
In Betrieb,1766,1766,1766,1766,1766,1675,1535,1766,1766,1766,0,1229,1766,1766,64,1734,1766,1766,0,0
Kapazitätsreserve aufgrund von § 13e EnWG,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve aufgrund von KVBG,4,4,4,4,4,4,4,4,4,4,0,4,4,4,0,4,4,4,0,0
Netzreserve aufgrund § 13b EnWG,23,23,23,23,23,23,22,23,23,23,0,21,23,23,0,23,23,23,0,0
besonderes netztechnisches Betriebsmittel,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
in Betrieb,2,2,2,2,2,2,2,2,2,2,0,2,2,2,0,2,2,2,0,0
vorläufig stillgelegt nach § 13b EnWG,8,8,8,8,8,8,7,8,8,8,0,8,8,8,0,8,8,8,0,0
vorläufig stillgelegt ohne § 13b EnWG,9,9,9,9,9,9,9,9,9,9,0,9,9,9,0,9,9,9,0,0

In [162]:
#pl_debug2.groupby("initialop").count()

In [163]:
pl1['state'] = pl1['state'].fillna("stillgelegt")

/tmp/ipykernel_759070/293089823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pl1['state'] = pl1['state'].fillna("stillgelegt")

In [164]:
pl1.loc[pl1.blockid == "SEE975094128629"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
266,SEE975094128629,NaN,HKW Mitte Kessel 12,38114.0,Braunschweig,Reiherstraße,3,Niedersachsen,1971-07-15 00:00:00,NaN,2024-06-26 00:00:00,stillgelegt,"Erdgas, Erdölgas",Erdgas,20.0,NaN,Volleinspeisung,NaN,NaN,Ja,22.4

In [165]:
#pl_debug2['initialop'] = pl_debug.initialop.dt.year

In [166]:
#pl_debug['initialop'] = pl_debug['initialop'].to_datetime()

In [167]:
pl_debug2.groupby("state").count()

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,
In Betrieb,1766,1766,1766,1766,1766,1675,1535,1766,1766,1766,0,1229,1766,1766,64,1734,1766,1766,0,0
Kapazitätsreserve aufgrund von § 13e EnWG,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve aufgrund von KVBG,4,4,4,4,4,4,4,4,4,4,0,4,4,4,0,4,4,4,0,0
Netzreserve aufgrund § 13b EnWG,23,23,23,23,23,23,22,23,23,23,0,21,23,23,0,23,23,23,0,0
besonderes netztechnisches Betriebsmittel,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
in Betrieb,2,2,2,2,2,2,2,2,2,2,0,2,2,2,0,2,2,2,0,0
vorläufig stillgelegt nach § 13b EnWG,8,8,8,8,8,8,7,8,8,8,0,8,8,8,0,8,8,8,0,0
vorläufig stillgelegt ohne § 13b EnWG,9,9,9,9,9,9,9,9,9,9,0,9,9,9,0,9,9,9,0,0

In [168]:
#pl_debug2.groupby("initialop").count()

In [169]:
pl1['state'] = pl1['state'].fillna("stillgelegt")

/tmp/ipykernel_759070/293089823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pl1['state'] = pl1['state'].fillna("stillgelegt")

In [170]:
#pl0

In [171]:
#bm

In [172]:
#pl0.groupby("Energieträger").count()

In [173]:
#list(plt)

In [174]:
pl1['state'] = pl1['state'].fillna("stillgelegt")

/tmp/ipykernel_759070/293089823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pl1['state'] = pl1['state'].fillna("stillgelegt")

In [175]:
pl1.loc[pl1.blockid == "BNA0221c"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
108,BNA0221c,NaN,Gasblock,40221.0,Düsseldorf,Auf der Lausward,75,Nordrhein-Westfalen,1977-03-28 00:00:00,NaN,2019,stillgelegt,NaN,Erdgas,293.0,NaN,NaN,Netzgesellschaft Düsseldorf mbH,NaN,Ja,NaN

In [176]:
plt.loc[plt.blockid == "BNA0711"]

Empty DataFrame
Columns: [Unnamed: 0, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, state, e1, e2, energysource, chp, border, grosspower, power, gerpower, tech, fullsupply, TSO, voltagelevel]
Index: []

In [177]:
plt = pl1.dropna(subset=["blockid"])

In [178]:
plt = plt.astype({"energysource": 'category'})

In [179]:
plt.loc[plt.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963,NaN,2012,stillgelegt,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [180]:
pl2 = pl1.copy()

In [181]:
def to_year(x):
    dt = pd.to_datetime(x)
    return dt.year

In [182]:
def to_year2(x):
    if pd.isna(x):
        return x
    elif isinstance(x, float):
        return x
    elif isinstance(x, int):
        return x
    else:
        ts = pd.Timestamp(ts_input=x)
        #print(ts)
        return int(ts.year)

In [183]:
#blocks.loc[blocks.Energieträger == "Kernenergie"]

In [184]:
#pl2

In [185]:
'''
pl2.loc[pl2.blockid == 'BNA0861a', 'initialop'] = 2012
pl2.loc[pl2.blockid == 'BNA1334', 'initialop'] = 2002
pl2.loc[pl2.blockid == 'BNA1141', 'initialop'] = 1970
pl2.loc[pl2.blockid == 'BNA0418', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1499', 'initialop'] = 1951
pl2.loc[pl2.blockid == 'BNA1502', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1500', 'initialop'] = 1990
pl2.loc[pl2.blockid == 'BNA1498', 'initialop'] = 1953
pl2.loc[pl2.blockid == 'BNA1260', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006
pl2.loc[pl2.blockid == 'BNA1114', 'initialop'] = 2012



pl2.loc[pl2.blockid == 'BNA0413b', 'initialop'] = 2014 # Westfalen D

pl2.loc[pl2.blockid == 'BNA0355', 'initialop'] = 1981 # Grafenrheinfeld
'''

#pl2['Nettoleistung'] = pl2['Nettoleistung'].str.replace('\n','')
#pl2['Nettoleistung'] = pl2[pd.to_numeric(pl2["Nettoleistung"])]
#pl2['Nettoleistung'] = pl2['Nettoleistung'].str.replace(';','.')

"\npl2.loc[pl2.blockid == 'BNA0861a', 'initialop'] = 2012\npl2.loc[pl2.blockid == 'BNA1334', 'initialop'] = 2002\npl2.loc[pl2.blockid == 'BNA1141', 'initialop'] = 1970\npl2.loc[pl2.blockid == 'BNA0418', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1499', 'initialop'] = 1951\npl2.loc[pl2.blockid == 'BNA1502', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1500', 'initialop'] = 1990\npl2.loc[pl2.blockid == 'BNA1498', 'initialop'] = 1953\npl2.loc[pl2.blockid == 'BNA1260', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006\npl2.loc[pl2.blockid == 'BNA1114', 'initialop'] = 2012\n\n\n\npl2.loc[pl2.blockid == 'BNA0413b', 'initialop'] = 2014 # Westfalen D\n\npl2.loc[pl2.blockid == 'BNA0355', 'initialop'] = 1981 # Grafenrheinfeld\n"

In [186]:
#pl2[] = pl2[pd.to_numeric(pl2["Nettoleistung"])]
pl2['initialop'] = pl2['initialop'].apply(to_year2)
#pl2['endop'] = pl2['endop'].apply(to_year2)
pl2['power'] = pl2['power'].apply(pd.to_numeric)

In [187]:
pl2.loc[pl2.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963.0,NaN,2012,stillgelegt,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [188]:
#bm[pl2.duplicated(['BlockID'], keep=False)].sort_values("BlockID", ascending=False)

In [189]:
#pl2[pl2.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

In [190]:
#cols = [10,11,12,14,17,18,19]
#pl3 = pl2.drop(pl2.columns[cols],axis=1)

In [191]:
#pl3.groupby('Unternehmen').max()

In [192]:
#pl3

In [193]:
def fix_company(company):
    #print(company)
    company_dict = {"RWE": "RWE AG", "Vattenfall": "Vattenfall GmbH", "Uniper": "Uniper SE", "EnBW": "EnBW AG", "Steag": "Steag GmbH", "Nordzucker": "Nordzucker AG", "Lausitz Energie": "LEAG"}
    for key, value in company_dict.items():
        if key in str(company):
            return value
    return company

In [194]:
def extract_still(x):
    match = re.findall("[0-9]{4}",x)
    return match[0] if match else np.nan

In [195]:
def fix_kwk(x):
    return "Nein" if x == "nein" else "Ja" if x == "ja" else x

In [196]:
pl4 = pl2.copy()

In [197]:
sq = 'Endgültig Stillgelegt 2013 (mit StA)'

In [198]:
list(pl2.groupby("state").count().reset_index()['state'])

['In Betrieb',
 'Kapazitätsreserve aufgrund von § 13e EnWG',
 'Netzreserve aufgrund von KVBG',
 'Netzreserve aufgrund § 13b EnWG',
 'besonderes netztechnisches Betriebsmittel',
 'in Betrieb',
 'stillgelegt',
 'vorläufig stillgelegt nach § 13b EnWG',
 'vorläufig stillgelegt ohne § 13b EnWG']

In [199]:
z = "endgültig stillgelegt 2022 (ohne § 13b EnWG oder KVBG)"

In [200]:
def extract_state(state):
    if state == "In Betrieb":
        return "in Betrieb"
    elif "Endgültig Stillgelegt" in state:
        return "stillgelegt"
    elif "Vorläufig Stillgelegt" in state:
        return "vorläufig stillgelegt"
    elif "an Stilllegung gehindert" in state:
        return "Gesetzlich an Stilllegung gehindert"
    else:
        return state

In [201]:
def extract_state2(state):
    
    states = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
    matches = ['In Betrieb', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve aufgrund § 13b EnWG', 'befristete Strommarktrückkehr', 'vorläufig stillgelegt', r'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', r'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', r'[E|e]ndgültig [S|s]tillgelegt 20[0-9]{2} \([ohne]|[mit].']
    
    for s, m in list(zip(states, matches)):
        if re.search(m, state):
            return s
    
    return state

In [202]:
def extract_state3(state):
    
    states = ['in Betrieb', 'bnBm', 'Kapazitätsreserve', 'Netzreserve', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
    matches = ['In Betrieb', 'besonderes netztechnisches Betriebsmittel', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve',  r'vorläufig stillgelegt', r'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', r'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', r'stillgelegt']
    
    for s, m in list(zip(states, matches)):
        if re.search(m, state):
            return s
    
    return state

In [203]:
extract_state3(sq)

'Endgültig Stillgelegt 2013 (mit StA)'

In [204]:
#pl4

In [205]:
pl4['company'] = pl4['company'].apply(lambda x: fix_company(x))
#pl4['endop'] = pl4['state'].apply(lambda x: extract_still(x))
pl4['state'] = pl4['state'].apply(lambda x: extract_state3(x))
pl4['chp'] = pl4['chp'].apply(lambda x: fix_kwk(x))

In [206]:
list(pl4.groupby("state").count().reset_index()['state'])

['Kapazitätsreserve',
 'Netzreserve',
 'bnBm',
 'in Betrieb',
 'stillgelegt',
 'vorläufig stillgelegt']

In [207]:
atest = pl4.groupby("state").count()

In [208]:
#atest

In [209]:
newdf = pl4.copy()

In [210]:
#newdf.dtypes

In [211]:
newdf["state"] = newdf["state"].astype('category')
newdf["state"] = newdf["state"].cat.set_categories(STATES, ordered=True)

In [212]:
newdf["chp"] = newdf["chp"].astype('category')
newdf["chp"] = newdf["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)

In [213]:
pl3 = newdf

In [214]:
atest = newdf.groupby(["power"]).count()
atest.sort_values("initialop", inplace=True, ascending=False)

In [215]:
#print(atest)

In [216]:
atest = pl3.groupby(["state"]).count()
# atest

/tmp/ipykernel_759070/4069360528.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  atest = pl3.groupby(["state"]).count()

In [217]:
# pl3.rename(columns={ pl3.columns[10]: "Energieträger"}, inplace=True)

In [218]:
#bm[bm.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

In [219]:
#bm2 = bm.drop_duplicates()

In [220]:
#pl3

In [221]:
#bm

In [222]:
pl4 = bm.merge(pl3, how="right", left_on="sseid", right_on="blockid")

In [223]:
pl5 = pl4[pd.notnull(pl4['blockid'])]
#pl5 = pl4
pl5a = pl5[pd.notnull(pl5['power'])]
pl6 =  pl5a.copy() #[pd.notnull(pl5a['plantid'])]

In [224]:
#pl6.dtypes

In [225]:
pl6.loc[pl6.blockid == "BNA0711"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
1297,06-05-300-0326774,BNA0711,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963.0,NaN,2012,stillgelegt,NaN,Braunkohle,125.0,NaN,NaN,Amprion GmbH,NaN,Nein,NaN

In [226]:
pl6['initialop'] = pl6['initialop'].apply(pd.to_numeric)
pl6['endop'] = pl6['endop'].apply(lambda x: to_year2(x))

In [227]:
#pl6.loc[pl6.blockid == "BNA0711"].dtypes

In [228]:
pl6.loc[pl6.blockid == "SEE999977738880"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
1419,664-02,SEE999977738880,SEE999977738880,NaN,IKW Deuben,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,1936.0,NaN,2021.0,stillgelegt,Rohbraunkohlen,Braunkohle,67.0,NaN,Teileinspeisung (einschließlich Eigenverbrauch),NaN,NaN,Ja,78.0

In [229]:
blocks = pl6.copy()
stammdaten = pl6.copy()

In [230]:
plants = blocks.copy()
#plants = plants.dropna(subset=["plantid", "initialop"]) #TODO: remove initialop from here

In [231]:
plants["energysource"] = plants["energysource"].astype('category')
plants["energysource"] = plants["energysource"].cat.set_categories(ENERGIES, ordered=True)
plants["state"] = plants["state"].astype('category')
#plants["state"] = plants["state"].cat.set_categories(STATES, ordered=True)
plants["chp"] = plants["chp"].astype('category')
plants["chp"] = plants["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)
plants["federalstate"] = plants["federalstate"].astype('category')
plants["federalstate"] = plants["federalstate"].cat.set_categories(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'])

In [232]:
pl1 = pl0.loc[pl0["energysource"].isin(["Kernenergie", "Erdgas", "Steinkohle", "Braunkohle", "Steinkohle"])]

In [233]:
p_grp = plants.groupby("plantid")

In [234]:
#plants.groupby("Energip_subgrper").max()

In [235]:
plants.groupby("state").count()

/tmp/ipykernel_759070/326027710.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  plants.groupby("state").count()

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
state,,,,,,,,,,,,,,,,,,,,,,
in Betrieb,724,724,1215,1215,1215,1215,1215,1149,1126,1215,1215,1215,0,1194,1215,1215,0,1205,1215,1215,0,0
Kapazitätsreserve,16,16,16,16,16,16,16,16,15,16,16,16,0,16,16,16,0,16,16,16,0,0
Netzreserve,27,27,27,27,27,27,27,27,26,27,27,27,0,25,27,27,0,27,27,27,0,0
bnBm,3,3,14,14,14,14,14,14,14,14,14,14,0,13,14,14,0,14,14,14,0,0
stillgelegt,212,212,249,0,246,248,249,183,164,249,248,0,249,150,249,249,0,126,168,0,248,135
vorläufig stillgelegt,13,13,17,17,17,17,17,17,16,17,17,17,0,17,17,17,0,17,17,17,0,0

In [236]:
ACTIVE_STATES

['in Betrieb',
 'Kapazitätsreserve',
 'Netzreserve',
 'bnBm',
 'vorläufig stillgelegt']

In [237]:
#plants.loc[plants['state'] == 'in Betrieb']

In [238]:
#plants.loc[plants['state'].isin(ACTIVE_STATES)].sort_values('power', ascending=False)

In [239]:
p_subgrp = plants.loc[plants['state'].isin(ACTIVE_STATES)].groupby('plantid') # TODO: add

In [240]:
plants_act = pd.DataFrame()
for plantid, group in p_subgrp:
    entry = {}
    entry["plantid"] = plantid
    entry["activepower"] = group["power"].sum()
    #plants_act = plants_act.append(entry, ignore_index=True)
    plants_act = pd.concat([plants_act, pd.DataFrame([entry])], ignore_index=True)

In [317]:
#plants_act

In [246]:
plants_a = pd.DataFrame()
for plantid, group in p_grp:
    #if not plantid == "06-05-300-9046797":
    #    continue
    entry = {}
    #print(entry)
    entry["plantid"] = plantid
    # entry["BlockID"] = group
    try:
        entry["plantname"] = group["plantname"].value_counts().index[0]
    except IndexError:
        entry["plantname"] = np.nan
    entry["federalstate"] = group["federalstate"].value_counts().index[0]
    entry["energysource"] = group["energysource"].min()
    try:
        entry["chp"] = group["chp"].min()
    except TypeError:
        #print("aneror")
        #print(plantid)
        #print(group['KWK'].count())
        entry["chp"] = ""
    entry["latestexpanded"] = group["initialop"].max()
    entry["initialop"] = group["initialop"].min()
    entry["totalpower"] = group["power"].sum()
    entry["state"] = group["state"].min()
    entry["blockcount"] = group["blockid"].count()
    try:
        entry["company"] = group["company"].value_counts().index[0]
    except IndexError:
        ;
    #print(entry)
    #break
    plants_a = pd.concat([plants_a, pd.DataFrame([entry])], ignore_index=True)

In [250]:
int_list = ['blockcount', 'initialop', 'latestexpanded']
for column in int_list:
    plants_a[column] = plants_a[column].astype(int)
#plant['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)

In [313]:
#plants_a.dtypes

In [314]:
plants_a["energysource"] = plants_a["energysource"].astype('category')
plants_a["energysource"] = plants_a["energysource"].cat.set_categories(ENERGIES, ordered=True)
plants_a["state"] = plants_a["state"].astype('category')
plants_a["state"] = plants_a["state"].cat.set_categories(STATES, ordered=True)
plants_a["chp"] = plants_a["chp"].astype('category')
plants_a["chp"] = plants_a["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)
plants_a["federalstate"] = plants_a["federalstate"].astype('category')
plants_a["federalstate"] = plants_a["federalstate"].cat.set_categories(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'])

In [316]:
plants_a.loc[plants_a.plantid == "666-999"]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company]
Index: []

In [255]:
plants_a.loc[plants_a.plantid == "06-00176010435"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company
36,06-00176010435,Staudinger,Hessen,Steinkohle,Ja,1992,1965,1644.0,Netzreserve,4,Uniper SE

In [256]:
plants_a.loc[plants_a.plantid == "06-05-900-0865327"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company
108,06-05-900-0865327,Gersteinwerk,Nordrhein-Westfalen,Steinkohle,Nein,2022,1972,2057.0,in Betrieb,10,RWE AG

In [257]:
#plants_a = plants.drop_duplicates(subset="KraftwerkID")

In [258]:
blocks.loc[blocks.sseid == "SEE930982693153"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
504,06-05-300-9046030,SEE930982693153,SEE930982693153,Knapsack Power GmbH & Co. KG,Knapsack I - Gasturbine GT11,50354,Hürth,Industriestraße,300,Nordrhein-Westfalen,2007.0,2007.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,308.0,NaN,Volleinspeisung,Amprion GmbH (SNB976890256486),Höchstspannung,NaN,NaN

In [259]:
column_titles = ['plantid', 'plantname', 'federalstate','energysource', 'chp', 'latestexpanded', 'initialop', 'totalpower', 'state', 'blockcount', 'company']
plants_b = plants_a.reindex(columns=column_titles)

In [263]:
blocks[blocks.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,initialopYear,endop,state,e2,energysource,power,gerpower,fullsupply,TSO,voltagelevel,chp,grosspower
785,NaN,NaN,SEE988996320985,Caterpillar Energy Solutions,P31,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1994.0,1994.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,1.84,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN
786,NaN,NaN,SEE988996320985,Caterpillar Energy Solutions,P31,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1994.0,1994.0,NaN,in Betrieb,"Erdgas, Erdölgas",Erdgas,1.84,NaN,Teileinspeisung (einschließlich Eigenverbrauch),MVV Netze GmbH (SNB985472799266),Mittelspannung,NaN,NaN

In [265]:
plants_b.sort_values("initialop", ascending=False, inplace=True)

In [268]:
plants_final = plants_b.loc[:]

In [318]:
#plants_final.dtypes

In [319]:
# plants_final

In [320]:
# stammdaten

In [321]:
#stammdaten

In [273]:
# cols = [0,2,3,9,10,11,12]
stammdaten = pl6.copy()
drop_list = ['plantid', 'energysource', 'initialop', 'chp', 'plantname', 'power', 'state', 'endop', 'company', 'sseid', 'TSO', 'voltagelevel']
stammdaten_dafuq = stammdaten.drop(drop_list, axis=1)
stammdaten = stammdaten_dafuq.copy()

In [274]:
stammdaten_dafuq.sort_values(['blockid'])

,blockid,plz,place,street,streetnum,federalstate,initialopYear,e2,gerpower,fullsupply,grosspower
1294,BNA0011,79774.0,Albbruck,NaN,NaN,Baden-Württemberg,NaN,Steinkohle,NaN,NaN,NaN
1389,BNA0012d,31061.0,Alfeld,Mühlenmarsch,1,Niedersachsen,NaN,NaN,NaN,NaN,NaN
1316,BNA0059a,34225.0,Baunatal,NaN,NaN,Hessen,NaN,NaN,NaN,NaN,NaN
1392,BNA0075,12207.0,Berlin,Ostpreußendamm,61,Berlin,NaN,NaN,NaN,NaN,NaN
1375,BNA0076,12207.0,Berlin,Ostpreußendamm,61,Berlin,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
761,SEE999819576335,39126,Magdeburg,Kraftwerk-Privatweg,7,Sachsen-Anhalt,2006.0,"Abfall (Hausmüll, Siedl.abf.)",NaN,Volleinspeisung,NaN
254,SEE999839188105,40476,Düsseldorf,Rather Straße,51,Nordrhein-Westfalen,2012.0,"Erdgas, Erdölgas",NaN,Teileinspeisung (einschließlich Eigenverbrauch),NaN
1416,SEE999848168525,21079.0,Hamburg,Moorburger Schanze,2,Hamburg,NaN,Steinkohlen,NaN,Volleinspeisung,860.0
969,SEE999966551940,14478,Potsdam,Zum Heizwerk,20,Brandenburg,1996.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
1419,SEE999977738880,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,NaN,Rohbraunkohlen,NaN,Teileinspeisung (einschließlich Eigenverbrauch),78.0

In [275]:
stmp = pl6.copy()
stammdaten2 = stmp.merge(prtr, how="left", left_on="plantid", right_on="kennnummer")

In [322]:
#stammdaten2

In [323]:
DROP_ST = ['blockid', 'jahr', 'kennnummer','betriebsname','betriebsname_2','plz_x','ort','strasse','hausnr','bundesland','flusseinzugsgebiet','taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']
DROP_ST2 = ['jahr', 'kennnummer','betriebsname','betriebsname_2','plz','ort','strasse','hausnr','bundesland','flusseinzugsgebiet','taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']
DROP_ST3 = ['jahr', 'kennnummer', 'bundesland', 'flusseinzugsgebiet', "betriebsname", "betriebsname_2", 'taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']

In [324]:
#DROP_ST = ['jahr']

In [325]:
plants_d1 = plants_final.merge(prtr, how="left", left_on="plantid", right_on="kennnummer")

In [326]:
#plants_d1.dtypes

In [327]:
pld2 = plants_d1.drop_duplicates(['plantid'])

In [328]:
pld3 = pld2.drop(DROP_ST3, axis=1)
plants_final1 = pld3

In [329]:
#plants_act

In [330]:
plants_final2 = plants_final1.merge(plants_act, on="plantid", how='left')

In [331]:
plants_final3 = plants_final2.dropna(subset=["plantid"])

In [332]:
plants_final3.groupby("energysource").count()

/tmp/ipykernel_759070/2887887728.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  plants_final3.groupby("energysource").count()

,plantid,plantname,federalstate,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
energysource,,,,,,,,,,,,,,,,,,,
Kernenergie,8,8,8,8,8,8,8,8,8,0,0,0,0,0,0,0,0,0,0
Braunkohle,29,29,29,15,29,29,29,29,29,24,27,27,27,27,27,27,27,27,24
Steinkohle,68,68,68,43,68,68,68,68,68,45,65,65,65,65,65,65,65,65,45
Erdgas,198,196,198,44,198,198,198,198,198,175,131,131,131,131,131,131,131,131,175
Mineralölprodukte,19,19,19,8,19,19,19,19,19,12,6,6,6,6,6,6,6,6,12
Abfall,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Biomasse,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [333]:
plants_final2[pd.notnull(plants_final2['activepower'])].sort_values('activepower', ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
208,14-70-46630660001,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,LEAG,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,02943,Boxberg/O.L.,Kraftwerksstraße,-,51.418839,14.574320,2470.000
296,06-05-300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,RWE AG,-,-,50129,Bergheim,Werkstr.,-,50.970927,6.666582,2220.000
252,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,RWE AG,RWE Power Aktiengesellschaft,RWE Power Aktiengesellschaft,41517,Grevenbroich,Landstraße,375,51.037524,6.613850,2120.000
318,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,RWE AG,-,-,52249,Eschweiler,Zum Hagelkreuz,20,50.833162,6.314578,2040.000
194,12-40710010000,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,LEAG,Vattenfall Europe Generation AG & Co. KG,Vattenfall Europe Generation AG & Co. KG,03185,Peitz,Kraftwerkstraße,-,51.832472,14.453040,2000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,661-102,Dampfturbine V Südzucker Zeitz,Sachsen-Anhalt,Erdgas,NaN,2016,2016,5.641,in Betrieb,1,Südzucker AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.641
15,661-89,BHKW Ford Saarlouis Modul 1,Saarland,Erdgas,NaN,2016,2016,4.322,in Betrieb,1,Ford-Werke GmbH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.322
38,661-28,GM5,Bayern,Biomasse,NaN,2012,2012,4.311,in Betrieb,1,Stadtwerke Rosenheim GmbH & Co. KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.311
217,06-08-4666496,Turbinengenerator4-SiemensT5471,Baden-Württemberg,Erdgas,NaN,1977,1977,3.400,in Betrieb,1,Sappi Ehingen GmbH,-,-,89584,Ehingen,Biberacher Straße,73,48.267699,9.727059,3.400
51,661-80,0050 - STW - BHKW - KWK,Nordrhein-Westfalen,Erdgas,Ja,2017,2007,12.877,in Betrieb,5,Stadtwerke Kempen GmbH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.313

In [334]:
plants_final2.sort_values('activepower', ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
208,14-70-46630660001,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.0,in Betrieb,4,LEAG,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,02943,Boxberg/O.L.,Kraftwerksstraße,-,51.418839,14.574320,2470.0
296,06-05-300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.0,in Betrieb,8,RWE AG,-,-,50129,Bergheim,Werkstr.,-,50.970927,6.666582,2220.0
252,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.0,in Betrieb,7,RWE AG,RWE Power Aktiengesellschaft,RWE Power Aktiengesellschaft,41517,Grevenbroich,Landstraße,375,51.037524,6.613850,2120.0
318,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.0,in Betrieb,8,RWE AG,-,-,52249,Eschweiler,Zum Hagelkreuz,20,50.833162,6.314578,2040.0
194,12-40710010000,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.0,in Betrieb,6,LEAG,Vattenfall Europe Generation AG & Co. KG,Vattenfall Europe Generation AG & Co. KG,03185,Peitz,Kraftwerkstraße,-,51.832472,14.453040,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,06-05-900-0884101,KW Lünen,Nordrhein-Westfalen,Steinkohle,Ja,1970,1962,473.0,stillgelegt,2,NaN,-,-,44536,Lünen,Moltkestrasse,215,51.614079,7.481227,NaN
311,06-08-1479296,Bestandsanlage_HKW_Aalen,Baden-Württemberg,Erdgas,Ja,1960,1960,15.0,stillgelegt,1,NaN,-,-,73432,Aalen,Sutorstraße,-,48.823539,10.116731,NaN
315,06-05-900-0271161,Shamrock,Nordrhein-Westfalen,Steinkohle,Ja,1957,1957,132.0,stillgelegt,1,NaN,E.ON Kraftwerke GmbH,E.ON Kraftwerke GmbH,44652,Herne,Kastanienallee,1,51.528530,7.177758,NaN
316,06-05-100-0081105,Frimmersdorf,Nordrhein-Westfalen,Braunkohle,Nein,1970,1957,2008.0,stillgelegt,13,NaN,RWE Power Aktiengesellschaft,RWE Power Aktiengesellschaft,41517,Grevenbroich,Energiestrasse,-,51.057488,6.577031,NaN
321,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.0,stillgelegt,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [335]:
plants_final2[pd.isnull(plants_final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower]
Index: []

In [336]:
stammdaten

,blockid,plz,place,street,streetnum,federalstate,initialopYear,e2,gerpower,fullsupply,grosspower
0,SEE915851127786,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
1,SEE946736241334,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
2,SEE930596800480,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
3,SEE929797382345,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
4,SEE988046628214,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1991.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1533,SEE975094128629,38114.0,Braunschweig,Reiherstraße,3,Niedersachsen,NaN,"Erdgas, Erdölgas",NaN,Volleinspeisung,22.400
1534,SEE926418118239,49479.0,Ibbenbüren,Groner Allee,76,Nordrhein-Westfalen,NaN,"Erdgas, Erdölgas",NaN,Teileinspeisung (einschließlich Eigenverbrauch),1.853
1535,SEE937157344278,74399.0,Walheim,Mühlstraße,1,Baden-Württemberg,NaN,Steinkohlen,NaN,Volleinspeisung,107.000
1536,SEE981220191160,77704.0,Oberkirch,Hauptstraße,2,Baden-Württemberg,NaN,Steinkohlen,NaN,Teileinspeisung (einschließlich Eigenverbrauch),20.000
1537,SEE937052769589,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,NaN,Steinkohlen,NaN,Volleinspeisung,920.000

In [337]:
#plants_final2.sort_values("activepower", ascending=False)

In [338]:
#stammdaten2.dtypes

In [339]:
#stammdaten3.sort_values(by=['plantid'], ascending=True)

In [340]:
#stammdaten3 = stammdaten2.drop(DROP_ST, axis=1)

In [341]:
#stammdaten4 = stammdaten3.drop_duplicates(['bnaid'])

In [342]:
#stammdaten4

In [343]:
#list(stammdaten2)

In [344]:
'''


"CREATE TABLE blocks(plantid TEXT, blockid TEXT NOT NULL PRIMARY KEY, blockdescription TEXT, federalstate TEXT, energysource TEXT, initialop INTEGER, chp TEXT,
blockname TEXT, netpower REAL, state TEXT, endop TEXT, company TEXT, FOREIGN KEY (blockid) REFERENCES addresses(blockid) ON DELETE CASCADE);"
662-01|BNA0164|Vattenfall GmbH|Brunsbüttel|Schleswig-Holstein|GT D|0.0|stillgelegt|Mineralölprodukte|Nein|63.5|201

'''

'\n\n\n"CREATE TABLE blocks(plantid TEXT, blockid TEXT NOT NULL PRIMARY KEY, blockdescription TEXT, federalstate TEXT, energysource TEXT, initialop INTEGER, chp TEXT,\nblockname TEXT, netpower REAL, state TEXT, endop TEXT, company TEXT, FOREIGN KEY (blockid) REFERENCES addresses(blockid) ON DELETE CASCADE);"\n662-01|BNA0164|Vattenfall GmbH|Brunsbüttel|Schleswig-Holstein|GT D|0.0|stillgelegt|Mineralölprodukte|Nein|63.5|201\n\n'

In [345]:
#|664-02|IKW

In [346]:
blocks2 = blocks[['blockid', 'plantid', 'plantname', 'federalstate', 'energysource', 'initialop', 'chp', 'power', 'state', 'endop', 'company']]

In [347]:
blocks2.loc[blocks2.blockid == "SEE930982693153"]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
504,SEE930982693153,06-05-300-9046030,Knapsack I - Gasturbine GT11,Nordrhein-Westfalen,Erdgas,2007.0,NaN,308.0,in Betrieb,NaN,Knapsack Power GmbH & Co. KG

In [348]:
blocks2.loc[blocks2.blockid == "SEE982928435068"]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
60,SEE982928435068,06-11-01-1105502,GuD Marzahn Dampfturbine,Berlin,Erdgas,2020.0,NaN,69.3,in Betrieb,NaN,BEW Berliner Energie und Wärme AG

In [349]:
list(blocks2)

['blockid',
 'plantid',
 'plantname',
 'federalstate',
 'energysource',
 'initialop',
 'chp',
 'power',
 'state',
 'endop',
 'company']

In [350]:
#blocks2.loc['C', 'x'] = "BNA1949"

In [351]:
stammdaten.to_csv("stammdaten_nh_new_2.csv", index=False, header=False)
blocks2.to_csv("blocks_nh_2.csv", index=False, header=False)
blocks2.to_csv("blocks_new_nh.csv", index=False, header=False)
plants_final2.to_csv("plants_nh_2.csv", index=False, header=False)
stammdaten.to_csv("stammdaten_2.csv", index=False)
blocks2.to_csv("blocks_2.csv", index=False)
plants_final2.to_csv("plants_2.csv", index=False)

In [310]:
#sqlite3 plantwatch.db  "CREATE TABLE plants(plantid TEXT NOT NULL PRIMARY KEY, plantname TEXT, federalstate TEXT, energysource TEXT, chp TEXT, latestexpanded INT, initialop INT, totalpower REAL, state TEXT, blockcount INT,  company TEXT, plz TEXT, place TEXT, street TEXT, number TEXT, latitude REAL, longitude REAL, activepower REAL, energy_2015 INTEGER,  energy_2016 INTEGER,  energy_2017 INTEGER,  energy_2018 INTEGER,  energy_2019 INTEGER, energy_2020 INTEGER, energy_2021 INTEGER, co2_2007 INTEGER,  co2_2008 INTEGER,  co2_2009 INTEGER,  co2_2010 INTEGER,  co2_2011 INTEGER,  co2_2012 INTEGER,  co2_2013 INTEGER,  co2_2014 INTEGER,  co2_2015 INTEGER,  co2_2016 INTEGER,  co2_2017 INTEGER,  co2_2018 INTEGER, co2_2019 INTEGER, co2_2020 INTEGER, FOREIGN KEY (plantid) REFERENCES blocks(plantid) ON DELETE CASCADE);"

In [472]:
blocks2.dropna(subset=['plantid'])

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
804,SEE933361522259,662-03,Kraftwerk Marbach MAR 4,Baden-Württemberg,Mineralölprodukte,2024.0,NaN,310.000,bnBm,NaN,EnBW AG
137,SEE920992144554,03-01-01010157480,HKW Mitte GuD BMHKW,Niedersachsen,Erdgas,2023.0,NaN,98.100,in Betrieb,NaN,Braunschweiger Versorgungs-AG & Co. KG
1225,SEE987007882719,03-01-01241117210,GuD West 40 Gasturbine,Niedersachsen,Erdgas,2023.0,NaN,101.000,in Betrieb,NaN,Volkswagen AG
176,SEE955076814825,14-60-48821410003,"Motor-Heizkraftwerk Chemnitz-Nord, Motor 7",Sachsen,Erdgas,2023.0,NaN,12.538,in Betrieb,NaN,eins energie in sachsen GmbH & Co. KG
171,SEE944044057432,14-60-48821410003,"Motor-Heizkraftwerk Chemnitz-Nord, Motor 1",Sachsen,Erdgas,2023.0,NaN,12.538,in Betrieb,NaN,eins energie in sachsen GmbH & Co. KG
...,...,...,...,...,...,...,...,...,...,...,...
1300,BNA1021,06-05-300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,1955.0,Ja,123.000,stillgelegt,2012.0,NaN
50,SEE906830618081,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,1948.0,NaN,15.000,in Betrieb,NaN,RWE AG
1419,SEE999977738880,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,1936.0,Ja,67.000,stillgelegt,2021.0,NaN
538,SEE957723162266,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,1900.0,NaN,59.800,in Betrieb,NaN,SWK Stadtwerke Kaiserslautern Versorgungs-AG
1295,BNA1337a,06-09-661-0020-0001,Heizkraftwerk,Bayern,Erdgas,NaN,Ja,27.000,stillgelegt,2012.0,NaN

In [232]:
blocks2.shape

(1538, 11)

In [233]:
blocks2.dropna(subset=['plantid']).shape

(974, 11)

In [353]:
#stammdaten.dropna(subset=['sseid', 'bnaid']).sort_values(by=['sseid'], ascending=False)

In [354]:
stammdaten

,blockid,plz,place,street,streetnum,federalstate,initialopYear,e2,gerpower,fullsupply,grosspower
0,SEE915851127786,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
1,SEE946736241334,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
2,SEE930596800480,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
3,SEE929797382345,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
4,SEE988046628214,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1991.0,"Erdgas, Erdölgas",NaN,Volleinspeisung,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1533,SEE975094128629,38114.0,Braunschweig,Reiherstraße,3,Niedersachsen,NaN,"Erdgas, Erdölgas",NaN,Volleinspeisung,22.400
1534,SEE926418118239,49479.0,Ibbenbüren,Groner Allee,76,Nordrhein-Westfalen,NaN,"Erdgas, Erdölgas",NaN,Teileinspeisung (einschließlich Eigenverbrauch),1.853
1535,SEE937157344278,74399.0,Walheim,Mühlstraße,1,Baden-Württemberg,NaN,Steinkohlen,NaN,Volleinspeisung,107.000
1536,SEE981220191160,77704.0,Oberkirch,Hauptstraße,2,Baden-Württemberg,NaN,Steinkohlen,NaN,Teileinspeisung (einschließlich Eigenverbrauch),20.000
1537,SEE937052769589,32469.0,Petershagen,Kraftwerksiedlung,2,Nordrhein-Westfalen,NaN,Steinkohlen,NaN,Volleinspeisung,920.000

In [355]:
blocks.loc[blocks["blockid"] == "BNA0645"]

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, initialopYear, endop, state, e2, energysource, power, gerpower, fullsupply, TSO, voltagelevel, chp, grosspower]
Index: []

In [356]:
#bm2.to_csv("bpm.csv", index=False)

In [357]:
#blocks

In [358]:
#blocks.groupby('Energieträger').count()

In [359]:
#pl4 = blocks.loc[blocks['Energieträger'] == "Mineralölprodukte"]

In [360]:
#pl4

In [361]:
#pd.set_option('display.max_rows', None)

In [362]:
#pl4.loc[pl4['Energieträger'] == "Mineralölprodukte"].sort_values(["Bundesland", "Unternehmen", "Kraftwerksname"])

In [363]:
#plants_final2

In [364]:
blocks2.sort_values('power', ascending=False)[0:20]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
1482,SEE943690268513,666-16,Isar 2,Bayern,Kernenergie,1988.0,Nein,1410.0,stillgelegt,2023.0,NaN
1423,SEE951462745445,666-14,Brokdorf,Schleswig-Holstein,Kernenergie,1986.0,Nein,1410.0,stillgelegt,2021.0,NaN
1401,BNA0802,666-12,Kernkraftwerk Philippsburg 2,Baden-Württemberg,Kernenergie,1985.0,Nein,1402.0,stillgelegt,2019.0,NaN
1426,SEE930752846949,666-13,Grohnde,Niedersachsen,Kernenergie,1984.0,Nein,1360.0,stillgelegt,2021.0,NaN
1486,SEE944567587799,666-17,Emsland A,Niedersachsen,Kernenergie,1988.0,Nein,1336.0,stillgelegt,2023.0,NaN
1491,SEE985577062814,666-18,GKN II,Baden-Württemberg,Kernenergie,1989.0,Nein,1310.0,stillgelegt,2023.0,NaN
1432,SEE927528071629,666-11,Gundremmingen C,Bayern,Kernenergie,1984.0,Nein,1288.0,stillgelegt,2021.0,NaN
1374,BNA0381,666-11,Kernkraft Gundremmingen,Bayern,Kernenergie,1984.0,Nein,1284.0,stillgelegt,2017.0,NaN
1336,BNA0355,666-15,Grafenrheinfeld,Bayern,Kernenergie,1982.0,Nein,1275.0,stillgelegt,2015.0,NaN
393,SEE993592183001,06-05-100-0248923,Neurath G,Nordrhein-Westfalen,Braunkohle,2012.0,NaN,1060.0,in Betrieb,NaN,RWE AG
392,SEE925599434282,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,2012.0,NaN,1060.0,in Betrieb,NaN,RWE AG
196,SEE913516809497,06-05-500-0915123,Datteln 4,Nordrhein-Westfalen,Steinkohle,2020.0,NaN,1052.0,in Betrieb,NaN,Uniper SE
53,SEE983252937631,06-05-300-0326774,Niederaußem K,Nordrhein-Westfalen,Braunkohle,2003.0,NaN,944.0,in Betrieb,NaN,RWE AG
885,SEE966331411864,14-80-00009560000,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,2000.0,NaN,891.0,in Betrieb,NaN,LEAG
884,SEE998199911088,14-80-00009560000,Kraftwerk Lippendorf Block S,Sachsen,Braunkohle,1999.0,NaN,891.0,in Betrieb,NaN,EnBW AG
1537,SEE937052769589,06-05-700-0105516,Heyden 4,Nordrhein-Westfalen,Steinkohle,1987.0,Nein,875.0,stillgelegt,2024.0,NaN
797,SEE988477355802,06-08-2948214,GKM Block 9,Baden-Württemberg,Steinkohle,2015.0,NaN,868.0,in Betrieb,NaN,Grosskraftwerk Mannheim
130,SEE907389779292,14-70-46630660001,Boxberg Block Q,Sachsen,Braunkohle,2000.0,NaN,840.0,in Betrieb,NaN,LEAG
545,SEE980331579218,06-08-2797933,Rheinhafen-Dampfkraftwerk RDK 8,Baden-Württemberg,Steinkohle,2014.0,NaN,834.0,in Betrieb,NaN,EnBW AG
1415,SEE972471937317,06-02-BERZ003800,Moorburg Block A,Hamburg,Steinkohle,2015.0,Ja,800.0,stillgelegt,2021.0,NaN

In [365]:
blocks2.sort_values('power', ascending=False)[0:20]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
1482,SEE943690268513,666-16,Isar 2,Bayern,Kernenergie,1988.0,Nein,1410.0,stillgelegt,2023.0,NaN
1423,SEE951462745445,666-14,Brokdorf,Schleswig-Holstein,Kernenergie,1986.0,Nein,1410.0,stillgelegt,2021.0,NaN
1401,BNA0802,666-12,Kernkraftwerk Philippsburg 2,Baden-Württemberg,Kernenergie,1985.0,Nein,1402.0,stillgelegt,2019.0,NaN
1426,SEE930752846949,666-13,Grohnde,Niedersachsen,Kernenergie,1984.0,Nein,1360.0,stillgelegt,2021.0,NaN
1486,SEE944567587799,666-17,Emsland A,Niedersachsen,Kernenergie,1988.0,Nein,1336.0,stillgelegt,2023.0,NaN
1491,SEE985577062814,666-18,GKN II,Baden-Württemberg,Kernenergie,1989.0,Nein,1310.0,stillgelegt,2023.0,NaN
1432,SEE927528071629,666-11,Gundremmingen C,Bayern,Kernenergie,1984.0,Nein,1288.0,stillgelegt,2021.0,NaN
1374,BNA0381,666-11,Kernkraft Gundremmingen,Bayern,Kernenergie,1984.0,Nein,1284.0,stillgelegt,2017.0,NaN
1336,BNA0355,666-15,Grafenrheinfeld,Bayern,Kernenergie,1982.0,Nein,1275.0,stillgelegt,2015.0,NaN
393,SEE993592183001,06-05-100-0248923,Neurath G,Nordrhein-Westfalen,Braunkohle,2012.0,NaN,1060.0,in Betrieb,NaN,RWE AG
392,SEE925599434282,06-05-100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,2012.0,NaN,1060.0,in Betrieb,NaN,RWE AG
196,SEE913516809497,06-05-500-0915123,Datteln 4,Nordrhein-Westfalen,Steinkohle,2020.0,NaN,1052.0,in Betrieb,NaN,Uniper SE
53,SEE983252937631,06-05-300-0326774,Niederaußem K,Nordrhein-Westfalen,Braunkohle,2003.0,NaN,944.0,in Betrieb,NaN,RWE AG
885,SEE966331411864,14-80-00009560000,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,2000.0,NaN,891.0,in Betrieb,NaN,LEAG
884,SEE998199911088,14-80-00009560000,Kraftwerk Lippendorf Block S,Sachsen,Braunkohle,1999.0,NaN,891.0,in Betrieb,NaN,EnBW AG
1537,SEE937052769589,06-05-700-0105516,Heyden 4,Nordrhein-Westfalen,Steinkohle,1987.0,Nein,875.0,stillgelegt,2024.0,NaN
797,SEE988477355802,06-08-2948214,GKM Block 9,Baden-Württemberg,Steinkohle,2015.0,NaN,868.0,in Betrieb,NaN,Grosskraftwerk Mannheim
130,SEE907389779292,14-70-46630660001,Boxberg Block Q,Sachsen,Braunkohle,2000.0,NaN,840.0,in Betrieb,NaN,LEAG
545,SEE980331579218,06-08-2797933,Rheinhafen-Dampfkraftwerk RDK 8,Baden-Württemberg,Steinkohle,2014.0,NaN,834.0,in Betrieb,NaN,EnBW AG
1415,SEE972471937317,06-02-BERZ003800,Moorburg Block A,Hamburg,Steinkohle,2015.0,Ja,800.0,stillgelegt,2021.0,NaN