In [17]:
import pandas as pd
import os
from os import listdir, stat
import numpy as np

In [18]:
MIN_SIZE = 512

In [36]:
plantlist = ['Gro_kraftwerk_Mannheim', 'Knapsack_Gas_I']

In [20]:
YEARS = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [21]:
YEAR = 2023

In [22]:
files1 = [f for f in os.listdir('.') if os.path.isfile(f)]
files2 = [f for f in files1 if stat(f).st_size > MIN_SIZE]
FILES = list(filter(lambda x: True if x[-4:] == '.csv' else False, files2))

In [23]:
FILES

['Knapsack_Gas_I_202401010000_202412312359_Stunde.csv',
 'Knapsack_Gas_II_202401010000_202412312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_202101010000_202112312359_Stunde.csv',
 'Knapsack_Gas_I_202301010000_202312312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201801010000_201812312359_Stunde(2).csv',
 'Knapsack_Gas_II_201601010000_201612312359_Stunde.csv',
 'Knapsack_Gas_I_202001010000_202012312359_Stunde.csv',
 'Knapsack_Gas_II_202201010000_202212312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201501010000_201512312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201601010000_201612312359_Stunde(2).csv',
 'Gro_kraftwerk_Mannheim_202201010000_202212312359_Stunde(2).csv',
 'Gro_kraftwerk_Mannheim_201701010000_201712312359_Stunde(2).csv',
 'Gro_kraftwerk_Mannheim_202301010000_202312312359_Stunde(2).csv',
 'Gro_kraftwerk_Mannheim_202401010000_202412312359_Stunde(2).csv',
 'Knapsack_Gas_II_202301010000_202312312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_202401010000_202412312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201801010000_201812312359_Stunde.csv',
 'Knapsack_Gas_II_201501010000_201512312359_Stunde.csv',
 'Knapsack_Gas_II_202101010000_202112312359_Stunde.csv',
 'Knapsack_Gas_I_201701010000_201701312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201601010000_201612312359_Stunde.csv',
 'Knapsack_Gas_I_202101010000_202112312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_202301010000_202312312359_Stunde.csv',
 'Knapsack_Gas_I_202201010000_202212312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201501010000_201512312359_Stunde(2).csv',
 'Knapsack_Gas_II_201901010000_201912312359_Stunde.csv',
 'Knapsack_Gas_I_201901010000_201912312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_202201010000_202212312359_Stunde.csv',
 'Knapsack_Gas_II_201701010000_201701312359_Stunde.csv',
 'Knapsack_Gas_I_201601010000_201612312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_202101010000_202112312359_Stunde(2).csv',
 'Knapsack_Gas_I_201501010000_201512312359_Stunde.csv',
 'Knapsack_Gas_II_202001010000_202012312359_Stunde.csv',
 'Gro_kraftwerk_Mannheim_201701010000_201712312359_Stunde.csv',
 'Knapsack_Gas_II_201801010000_201812312359_Stunde.csv',
 'Knapsack_Gas_I_201801010000_201812312359_Stunde.csv']

In [24]:
def read_df(plantname, year):
    return pd.read_csv(plantname + "_" + str(year) + "01010000_" + str(year+1) + "12312359_Stunde.csv", sep=';')

def read_df(f):
    return pd.read_csv(f, sep=';')

In [25]:
dfdict = {}
for plant in plantlist:
    df = pd.DataFrame()
    dflist = []
    for year in YEARS:
        tmp = []
        for f in FILES:
            if plant in f.rsplit("_", 3)[0] and (str(year) in f.rsplit("_", 3)[1]):
                #print(f.rsplit("_", 3)[1])
                tmp.append(read_df(f).drop("Datum bis", axis=1))
        dflist.append(tmp)
        tmp = []
    dfdict[plant] = dflist

In [27]:
#dfdict['Knapsack_Gas_I']

In [12]:
#dflist

In [29]:
rename_dict = {"Datum von": "produced_at", "Generation_DE GKM Block 6 [MW] Originalauflösungen": "SEE909002940690", "Generation_DE GKM Block 9 [MW] Originalauflösungen": "SEE988477355802",
              "Generation_DE Knapsack I [MW] Originalauflösungen": "SEE905192478234","Generation_DE Kraftwerk Knapsack II [MW] Originalauflösungen": "SEE903983424590"}

In [37]:
plant_mapper = {"Gro_kraftwerk_Mannheim": "06-08-2948214", "Knapsack_Gas_I": "06-05-300-9046030"}

In [40]:
for plant in plantlist:
    combined_df = pd.DataFrame()
    anotherlist = []
    for dfs in dflist:
        if dfs == []:
            continue
        tmpdf = pd.concat(dfs, axis=1)
        anotherlist.append(tmpdf)
    nextlist = list(map(lambda x: x.iloc[:, np.setdiff1d(np.arange(len(x.columns)), 2)], anotherlist)) # reference: https://stackoverflow.com/a/68113529
    combined_df = pd.concat(nextlist, axis=0)
    final_df = combined_df.rename(columns=rename_dict)
    final_df = final_df.replace('-', 0)
    final_df.to_csv("../" + plant_mapper[plant] + ".csv", index=False)

In [15]:
combined_df = pd.DataFrame()
anotherlist = []
for dfs in dflist:
    if dfs == []:
        continue
    tmpdf = pd.concat(dfs, axis=1)
    anotherlist.append(tmpdf)
nextlist = list(map(lambda x: x.iloc[:, np.setdiff1d(np.arange(len(x.columns)), 2)], anotherlist)) # reference: https://stackoverflow.com/a/68113529
combined_df = pd.concat(nextlist, axis=0)
final_df = combined_df.rename(columns=rename_dict)
final_df.to_csv("../06-08-2948214.csv", index=False)

In [14]:
#anotherlist[0]

In [15]:
nextlist = list(map(lambda x: x.iloc[:, np.setdiff1d(np.arange(len(x.columns)), 2)], anotherlist)) # reference: https://stackoverflow.com/a/68113529

In [25]:
#nextlist[0]

In [17]:
combined_df = pd.concat(nextlist, axis=0)

In [30]:
#smardmapper = {"Gro_kraftwerk_Mannheim": ""}

In [21]:
list(combined_df)

['Datum von',
 'Generation_DE GKM Block 6 [MW] Originalauflösungen',
 'Generation_DE GKM Block 9 [MW] Originalauflösungen']

In [22]:
final_df = combined_df.rename(columns=rename_dict)

In [23]:
final_df = final_df.replace('-', 0)

In [24]:
final_df.to_csv("../06-08-2948214.csv", index=False)

In [322]:
final_df

           produced_at SEE909002940690 SEE988477355802
0     01.01.2015 00:00               0               0
1     01.01.2015 01:00               0               0
2     01.01.2015 02:00               0               0
3     01.01.2015 03:00               0               0
4     01.01.2015 04:00               0               0
...                ...             ...             ...
8779  31.12.2024 19:00           7,000           0,000
8780  31.12.2024 20:00           7,000         112,000
8781  31.12.2024 21:00           7,000         136,000
8782  31.12.2024 22:00           7,000         128,000
8783  31.12.2024 23:00           7,000         172,000

[70128 rows x 3 columns]

In [141]:
df1

,Datum von,Generation_DE GKM Block 9 [MW] Originalauflösungen
0,2023-01-01 00:00:00+00:00,"66,000"
1,2023-01-01 01:00:00+00:00,"70,000"
2,2023-01-01 02:00:00+00:00,"65,000"
3,2023-01-01 03:00:00+00:00,"70,000"
4,2023-01-01 04:00:00+00:00,"69,000"
...,...,...
17539,2024-12-31 19:00:00+00:00,"0,000"
17540,2024-12-31 20:00:00+00:00,"112,000"
17541,2024-12-31 21:00:00+00:00,"136,000"
17542,2024-12-31 22:00:00+00:00,"128,000"
17543,2024-12-31 23:00:00+00:00,"172,000"

In [120]:
df1 = dflist[0]
df2 = dflist[1]

In [121]:
df1['Datum von'] = pd.to_datetime(df1['Datum von'], format="%d.%m.%Y %H:%M", utc=True)
df2['Datum von'] = pd.to_datetime(df2['Datum von'], format="%d.%m.%Y %H:%M", utc=True)

In [122]:
df2

,Datum von,Generation_DE GKM Block 6 [MW] Originalauflösungen
0,2023-01-01 00:00:00+00:00,"13,000"
1,2023-01-01 01:00:00+00:00,"13,000"
2,2023-01-01 02:00:00+00:00,"13,000"
3,2023-01-01 03:00:00+00:00,"13,000"
4,2023-01-01 04:00:00+00:00,"13,000"
...,...,...
17539,2024-12-31 19:00:00+00:00,"7,000"
17540,2024-12-31 20:00:00+00:00,"7,000"
17541,2024-12-31 21:00:00+00:00,"7,000"
17542,2024-12-31 22:00:00+00:00,"7,000"
17543,2024-12-31 23:00:00+00:00,"7,000"

In [129]:
df3 = pd.concat([df1, df2], axis=1)

In [130]:
df3

,Datum von,Generation_DE GKM Block 9 [MW] Originalauflösungen,Datum von,Generation_DE GKM Block 6 [MW] Originalauflösungen
0,2023-01-01 00:00:00+00:00,"66,000",2023-01-01 00:00:00+00:00,"13,000"
1,2023-01-01 01:00:00+00:00,"70,000",2023-01-01 01:00:00+00:00,"13,000"
2,2023-01-01 02:00:00+00:00,"65,000",2023-01-01 02:00:00+00:00,"13,000"
3,2023-01-01 03:00:00+00:00,"70,000",2023-01-01 03:00:00+00:00,"13,000"
4,2023-01-01 04:00:00+00:00,"69,000",2023-01-01 04:00:00+00:00,"13,000"
...,...,...,...,...
17539,2024-12-31 19:00:00+00:00,"0,000",2024-12-31 19:00:00+00:00,"7,000"
17540,2024-12-31 20:00:00+00:00,"112,000",2024-12-31 20:00:00+00:00,"7,000"
17541,2024-12-31 21:00:00+00:00,"136,000",2024-12-31 21:00:00+00:00,"7,000"
17542,2024-12-31 22:00:00+00:00,"128,000",2024-12-31 22:00:00+00:00,"7,000"
17543,2024-12-31 23:00:00+00:00,"172,000",2024-12-31 23:00:00+00:00,"7,000"

In [133]:
df4 = df3.drop(df3.columns[2], axis=1)

In [134]:
df4

,Generation_DE GKM Block 9 [MW] Originalauflösungen,Generation_DE GKM Block 6 [MW] Originalauflösungen
0,"66,000","13,000"
1,"70,000","13,000"
2,"65,000","13,000"
3,"70,000","13,000"
4,"69,000","13,000"
...,...,...
17539,"0,000","7,000"
17540,"112,000","7,000"
17541,"136,000","7,000"
17542,"128,000","7,000"
17543,"172,000","7,000"

In [78]:
#dflist

In [139]:
tmp = FILES[0]
tmp.rsplit("_", 3)

['Gro_kraftwerk_Mannheim', '202301010000', '202412312359', 'Stunde(2).csv']

In [34]:
FILES

['Gro_kraftwerk_Mannheim_202301010000_202412312359_Stunde(2).csv',
 'Gro_kraftwerk_Mannheim_202301010000_202412312359_Stunde(1).csv',
 'Gro_kraftwerk_Mannheim_202301010000_202412312359_Stunde.csv']

In [14]:
df1 = read_df(plantlist[0], 2023)

In [5]:
df1 = pd.read_csv(plantname + "_" + year + "01010000_" + year+1 + "12312359_Stunde.csv", sep=';')
df2 = pd.read_csv("Gro_kraftwerk_Mannheim_202301010000_202412312359_Stunde(1).csv")
df3 = pd.read_csv("Gro_kraftwerk_Mannheim_202301010000_202412312359_Stunde(2).csv")

In [15]:
df1

,Datum von,Datum bis,Generation_DE GKM Block 6 [MW] Originalauflösungen
0,01.01.2023 00:00,01.01.2023 01:00,"13,000"
1,01.01.2023 01:00,01.01.2023 02:00,"13,000"
2,01.01.2023 02:00,01.01.2023 03:00,"13,000"
3,01.01.2023 03:00,01.01.2023 04:00,"13,000"
4,01.01.2023 04:00,01.01.2023 05:00,"13,000"
...,...,...,...
17539,31.12.2024 19:00,31.12.2024 20:00,"7,000"
17540,31.12.2024 20:00,31.12.2024 21:00,"7,000"
17541,31.12.2024 21:00,31.12.2024 22:00,"7,000"
17542,31.12.2024 22:00,31.12.2024 23:00,"7,000"
17543,31.12.2024 23:00,01.01.2025 00:00,"7,000"